import { did } from '../../seed-utils';

export const cambodiaPlaces = [
  // SIEM REAP
  {
    id: did('place-siemreap-lub-d-hostel'),
    city_id: did('city-siemreap'),
    city_area_id: did('area-siemreap-oldmarket'),
    slug: 'lub-d-hostel',
    name: 'Lub d Siem Reap',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 13.3622,
    lng: 103.8564,
    address: 'Sivatha Boulevard, Siem Reap',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '24/7 check-in',
    description: 'Modern hostel with female-only dorms, rooftop pool, and a great social vibe. Super clean and secure with lockers. Staff help arrange temple tours. Walking distance to Pub Street and Old Market.',
    is_active: true,
  },
  {
    id: did('place-siemreap-the-hive'),
    city_id: did('city-siemreap'),
    city_area_id: did('area-siemreap-oldmarket'),
    slug: 'the-hive-siem-reap',
    name: 'The Hive Siem Reap',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 13.3594,
    lng: 103.8541,
    address: 'Street 24, Wat Bo Village, Siem Reap',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '24/7 check-in',
    description: 'Beloved backpacker hostel with a pool and chill garden area. Female dorms available. Great place to meet other solo travelers heading to Angkor Wat. Free breakfast and friendly staff.',
    is_active: true,
  },
  {
    id: did('place-siemreap-chanrey-tree'),
    city_id: did('city-siemreap'),
    city_area_id: did('area-siemreap-oldmarket'),
    slug: 'chanrey-tree',
    name: 'Chanrey Tree',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 13.3583,
    lng: 103.8548,
    address: 'Wat Bo Road, Siem Reap',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '11am-11pm daily',
    description: 'Upscale Khmer restaurant in a beautiful wooden house. Solo diners are welcomed warmly. Try amok, beef lok lak, and fresh spring rolls. Portions are generous, and the setting is romantic without being awkward alone.',
    is_active: true,
  },
  {
    id: did('place-siemreap-brown-coffee'),
    city_id: did('city-siemreap'),
    city_area_id: did('area-siemreap-oldmarket'),
    slug: 'brown-coffee',
    name: 'Brown Coffee & Bakery',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 13.3611,
    lng: 103.8583,
    address: 'Sivatha Boulevard, Siem Reap',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '6:30am-9pm daily',
    description: 'Local chain cafe with air-con, strong WiFi, and good iced coffee. Perfect for solo work or cooling off between temple visits. Pastries are fresh, and the Vietnamese coffee is excellent.',
    is_active: true,
  },
  {
    id: did('place-siemreap-angkor-wat'),
    city_id: did('city-siemreap'),
    city_area_id: did('area-siemreap-angkor'),
    slug: 'angkor-wat',
    name: 'Angkor Wat Temple Complex',
    place_type: 'activity',
    primary_category_id: did('cat-landmark'),
    lat: 13.4125,
    lng: 103.8670,
    address: 'Angkor Archaeological Park, Siem Reap',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: '5am-5:30pm daily',
    description: 'Iconic UNESCO temple complex and must-see wonder. Solo women can easily join sunrise tours or hire a tuk-tuk for the day. Dress modestly (cover shoulders/knees). Bring water, sunscreen, and comfortable shoes.',
    is_active: true,
  },
  {
    id: did('place-siemreap-pub-street'),
    city_id: did('city-siemreap'),
    city_area_id: did('area-siemreap-pubst'),
    slug: 'pub-street',
    name: 'Pub Street',
    place_type: 'bar',
    primary_category_id: did('cat-nightlife'),
    lat: 13.3619,
    lng: 103.8575,
    address: 'Pub Street, Siem Reap',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '5pm-late daily',
    description: 'Famous backpacker nightlife strip with bars, clubs, and street food. Solo women can safely join the crowd here—it\'s touristy and well-lit. Try a $0.50 beer and make friends. Avoid overly drunk tuk-tuk drivers.',
    is_active: true,
  },
  {
    id: did('place-siemreap-phare-circus'),
    city_id: did('city-siemreap'),
    city_area_id: null,
    slug: 'phare-circus',
    name: 'Phare, The Cambodian Circus',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 13.3493,
    lng: 103.8351,
    address: 'Phare Circus Ring, Siem Reap',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Shows at 8pm Mon-Sat',
    description: 'Incredible acrobatic circus with storytelling and traditional music. Solo-friendly and inspiring—a social enterprise supporting local youth. Book tickets online or at the venue. Arrive early for good seats.',
    is_active: true,
  },

  // PHNOM PENH
  {
    id: did('place-phnompenh-mad-monkey'),
    city_id: did('city-phnompenh'),
    city_area_id: did('area-phnompenh-riverside'),
    slug: 'mad-monkey-hostel',
    name: 'Mad Monkey Hostel Phnom Penh',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 11.5689,
    lng: 104.9258,
    address: 'Street 302, Phnom Penh',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '24/7 check-in',
    description: 'Party hostel with a rooftop bar and pool. Female dorms available and secure. Great if you want to meet other backpackers. Pub crawls and events nightly. Close to riverside and nightlife.',
    is_active: true,
  },
  {
    id: did('place-phnompenh-malis'),
    city_id: did('city-phnompenh'),
    city_area_id: did('area-phnompenh-riverside'),
    slug: 'malis-restaurant',
    name: 'Malis Restaurant',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 11.5635,
    lng: 104.9246,
    address: '136 Norodom Blvd, Phnom Penh',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: '11am-2pm, 6pm-10pm daily',
    description: 'Elegant Khmer fine dining in a stunning pavilion setting. Solo diners are treated with care. Perfect for a treat-yourself meal. Try the amok, grilled fish, and Kampot pepper dishes. Reservations recommended.',
    is_active: true,
  },
  {
    id: did('place-phnompenh-brown-coffee-pp'),
    city_id: did('city-phnompenh'),
    city_area_id: did('area-phnompenh-bkk1'),
    slug: 'brown-coffee-pp',
    name: 'Brown Coffee BKK1',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 11.5556,
    lng: 104.9283,
    address: 'Street 302, BKK1, Phnom Penh',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '6:30am-9pm daily',
    description: 'Reliable local cafe chain with air-con and WiFi. Great for remote work or escaping the heat. Iced coffee is refreshing, and the croissants are decent. Solo-friendly and calm.',
    is_active: true,
  },
  {
    id: did('place-phnompenh-royal-palace'),
    city_id: did('city-phnompenh'),
    city_area_id: did('area-phnompenh-riverside'),
    slug: 'royal-palace',
    name: 'Royal Palace & Silver Pagoda',
    place_type: 'activity',
    primary_category_id: did('cat-landmark'),
    lat: 11.5640,
    lng: 104.9311,
    address: 'Sothearos Blvd, Phnom Penh',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '8am-11am, 2pm-5pm daily',
    description: 'Stunning royal complex with glittering architecture. Solo women can explore easily. Dress modestly—cover shoulders and knees. Hire a guide at the entrance or use an audio guide. Beautiful gardens to stroll.',
    is_active: true,
  },
  {
    id: did('place-phnompenh-russian-market'),
    city_id: did('city-phnompenh'),
    city_area_id: did('area-phnompenh-russianmarket'),
    slug: 'russian-market',
    name: 'Russian Market (Toul Tom Poung)',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 11.5456,
    lng: 104.9176,
    address: 'Street 163, Phnom Penh',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '7am-5pm daily',
    description: 'Bustling market for souvenirs, textiles, and street food. Solo women feel safe here during the day. Bargain gently and keep valuables secure. Great for picking up silk scarves and handicrafts.',
    is_active: true,
  },
  {
    id: did('place-phnompenh-sunset-cruise'),
    city_id: did('city-phnompenh'),
    city_area_id: did('area-phnompenh-riverside'),
    slug: 'mekong-sunset-cruise',
    name: 'Mekong River Sunset Cruise',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 11.5781,
    lng: 104.9297,
    address: 'Sisowath Quay, Phnom Penh',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Cruises around 5pm daily',
    description: 'Relaxing river cruise with sunset views over the Mekong and Tonle Sap rivers. Solo travelers can book easily. Most cruises include a drink. A peaceful way to end the day.',
    is_active: true,
  },

  // KAMPOT
  {
    id: did('place-kampot-banyan-tree'),
    city_id: did('city-kampot'),
    city_area_id: did('area-kampot-riverfront'),
    slug: 'banyan-tree-hostel',
    name: 'Banyan Tree Guesthouse',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 10.6113,
    lng: 104.1774,
    address: 'Riverside, Kampot',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '24/7 check-in',
    description: 'Laid-back riverside hostel with hammocks and river views. Female dorms available. Perfect for solo travelers looking to slow down. Rent a bike and explore pepper plantations and Bokor Mountain.',
    is_active: true,
  },
  {
    id: did('place-kampot-rikitikitavi'),
    city_id: did('city-kampot'),
    city_area_id: did('area-kampot-riverfront'),
    slug: 'rikitikitavi',
    name: 'Rikitikitavi',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 10.6106,
    lng: 104.1771,
    address: 'Riverside Road, Kampot',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '7am-10pm daily',
    description: 'Riverside restaurant with Western and Khmer dishes. Solo diners love the relaxed vibe and river views. Try the Kampot pepper crab and fresh fruit shakes. Great spot to watch the sunset.',
    is_active: true,
  },
  {
    id: did('place-kampot-karma-traders'),
    city_id: did('city-kampot'),
    city_area_id: did('area-kampot-oldtown'),
    slug: 'karma-traders',
    name: 'Karma Traders',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 10.6095,
    lng: 104.1789,
    address: 'Old Market Area, Kampot',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '7am-5pm daily',
    description: 'Cozy cafe with specialty coffee and healthy breakfast bowls. Solo-friendly with WiFi and a chill garden. Try the avocado toast and iced latte. Good vibes and traveler crowd.',
    is_active: true,
  },
  {
    id: did('place-kampot-pepper-farm'),
    city_id: did('city-kampot'),
    city_area_id: null,
    slug: 'kampot-pepper-farm',
    name: 'La Plantation Pepper Farm',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 10.5694,
    lng: 104.1381,
    address: 'Kampot Province',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '8am-5pm daily',
    description: 'Organic pepper farm offering free tours and tastings. Solo travelers can easily visit by tuk-tuk or motorbike. Learn about Kampot pepper\'s fame and buy some to take home. Beautiful countryside setting.',
    is_active: true,
  },
  {
    id: did('place-kampot-bokor-mountain'),
    city_id: did('city-kampot'),
    city_area_id: null,
    slug: 'bokor-mountain',
    name: 'Bokor National Park',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 10.6356,
    lng: 104.0378,
    address: 'Bokor Mountain, Kampot Province',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '7am-5pm daily',
    description: 'Misty mountain with abandoned French hill station and eerie casino ruins. Join a tour or rent a motorbike (experienced riders only). Solo women should go during the day. Views are otherworldly.',
    is_active: true,
  },

  // KOH RONG
  {
    id: did('place-kohrong-onederz'),
    city_id: did('city-kohrong'),
    city_area_id: did('area-kohrong-kohtouch'),
    slug: 'onederz-hostel',
    name: 'Onederz Koh Rong',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 10.6975,
    lng: 103.2986,
    address: 'Koh Touch Beach, Koh Rong',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '24/7 check-in',
    description: 'Beachfront party hostel with female dorms and beach access. Super social—great for solo travelers wanting to meet people. Nightly beach parties, fire shows, and bioluminescence swims. Bring earplugs.',
    is_active: true,
  },
  {
    id: did('place-kohrong-treehouse-bungalows'),
    city_id: did('city-kohrong'),
    city_area_id: did('area-kohrong-longset'),
    slug: 'treehouse-bungalows',
    name: 'Treehouse Bungalows',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 10.6822,
    lng: 103.2561,
    address: 'Long Set Beach, Koh Rong',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '24/7 check-in',
    description: 'Rustic jungle bungalows on quiet Long Set Beach. Perfect for solo women seeking peace and nature. No WiFi—disconnect and enjoy the stars. Hammocks, beach, and simple island life.',
    is_active: true,
  },
  {
    id: did('place-kohrong-the-island-bar'),
    city_id: did('city-kohrong'),
    city_area_id: did('area-kohrong-kohtouch'),
    slug: 'the-island-bar',
    name: 'The Island Bar',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 10.6982,
    lng: 103.2991,
    address: 'Koh Touch Beach, Koh Rong',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '8am-late daily',
    description: 'Beachfront bar and restaurant with fresh seafood and BBQ. Solo diners can grab a hammock seat and watch the sunset. Try the grilled fish and fruit shakes. Chill vibe during the day, livelier at night.',
    is_active: true,
  },
  {
    id: did('place-kohrong-bioluminescent-plankton'),
    city_id: did('city-kohrong'),
    city_area_id: did('area-kohrong-kohtouch'),
    slug: 'bioluminescent-plankton',
    name: 'Bioluminescent Plankton Night Swim',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 10.6975,
    lng: 103.2990,
    address: 'Koh Touch Beach, Koh Rong',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Best after dark, year-round',
    description: 'Magical experience swimming in glowing plankton at night. Solo women can join group swims organized by hostels. Totally safe and unforgettable. Best on moonless nights. Just wade in and watch the sparkle.',
    is_active: true,
  },
  {
    id: did('place-kohrong-snorkeling-tour'),
    city_id: did('city-kohrong'),
    city_area_id: did('area-kohrong-kohtouch'),
    slug: 'snorkeling-tour',
    name: 'Koh Rong Snorkeling Tour',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 10.6975,
    lng: 103.2986,
    address: 'Koh Touch Beach, Koh Rong',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Tours 9am-4pm daily',
    description: 'Half-day snorkeling trips to nearby reefs and islands. Solo travelers join group boats. Clear water, colorful fish, and often see sea turtles. Gear provided. Book at your hostel or beachfront tour desks.',
    is_active: true,
  },
];
