import { did } from '../../seed-utils';

export const indonesiaPlaces = [
  // UBUD
  {
    id: did('place-ubud-komaneka-bisma'),
    city_id: did('city-ubud'),
    city_area_id: did('area-ubud-central'),
    slug: 'komaneka-bisma',
    name: 'Komaneka at Bisma',
    place_type: 'hotel',
    primary_category_id: did('cat-stay'),
    lat: -8.5115,
    lng: 115.2611,
    address: 'Jl. Bisma, Ubud, Gianyar',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: '24 hours',
    description: 'Stunning boutique hotel with infinity pool overlooking rice terraces. Staff remembers solo travelers and the spa is a safe, rejuvenating haven after temple visits.',
    is_active: true,
  },
  {
    id: did('place-ubud-locavore'),
    city_id: did('city-ubud'),
    city_area_id: did('area-ubud-central'),
    slug: 'locavore',
    name: 'Locavore',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: -8.5069,
    lng: 115.2625,
    address: 'Jl. Dewi Sita, Ubud',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 4,
    hours_text: 'Tue-Sun 12pm-3pm, 6pm-10pm',
    description: 'World-renowned farm-to-table dining with a welcoming tasting menu counter. Solo diners get chatty staff attention and a front-row view of the culinary magic.',
    is_active: true,
  },
  {
    id: did('place-ubud-seniman'),
    city_id: did('city-ubud'),
    city_area_id: did('area-ubud-central'),
    slug: 'seniman-coffee',
    name: 'Seniman Coffee Studio',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: -8.5084,
    lng: 115.2631,
    address: 'Jl. Sriwedari No.5, Ubud',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 7am-9pm',
    description: 'Beloved coffee roastery with strong wifi and communal tables perfect for solo working. The baristas are friendly and the latte art is Instagram-worthy.',
    is_active: true,
  },
  {
    id: did('place-ubud-hubud'),
    city_id: did('city-ubud'),
    city_area_id: did('area-ubud-central'),
    slug: 'hubud',
    name: 'Hubud',
    place_type: 'coworking',
    primary_category_id: did('cat-coworking'),
    lat: -8.5101,
    lng: 115.2584,
    address: 'Jl. Monkey Forest, Ubud',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Mon-Fri 8am-6pm, Sat-Sun 9am-5pm',
    description: 'Iconic bamboo coworking space with a strong community of solo digital nomads. Regular networking events make it easy to find your tribe.',
    is_active: true,
  },
  {
    id: did('place-ubud-yoga-barn'),
    city_id: did('city-ubud'),
    city_area_id: did('area-ubud-central'),
    slug: 'yoga-barn',
    name: 'The Yoga Barn',
    place_type: 'wellness',
    primary_category_id: did('cat-wellness'),
    lat: -8.5234,
    lng: 115.2647,
    address: 'Jl. Raya Pengosekan, Ubud',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 6am-9pm',
    description: 'Jungle yoga sanctuary with drop-in classes and healing workshops. Solo women feel instantly welcomed in the supportive, judgment-free atmosphere.',
    is_active: true,
  },
  {
    id: did('place-ubud-tegallalang'),
    city_id: did('city-ubud'),
    city_area_id: did('area-ubud-tegallalang'),
    slug: 'tegallalang-rice-terraces',
    name: 'Tegallalang Rice Terraces',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: -8.4347,
    lng: 115.2775,
    address: 'Jl. Raya Tegallalang, Tegallalang',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 8am-6pm',
    description: 'Iconic emerald rice paddies with swing photo ops. Go early morning to avoid crowds and enjoy peaceful walks through the terraces—vendors are friendly but persistent.',
    is_active: true,
  },
  {
    id: did('place-ubud-karsa-kafe'),
    city_id: did('city-ubud'),
    city_area_id: did('area-ubud-campuhan'),
    slug: 'karsa-kafe',
    name: 'Karsa Kafe',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: -8.4989,
    lng: 115.2513,
    address: 'Jl. Raya Campuhan, Ubud',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 9am-9pm',
    description: 'Hidden garden cafe at the end of the Campuhan Ridge Walk with organic Indonesian food. Perfect solo lunch spot after your morning hike—peaceful and restorative.',
    is_active: true,
  },
  {
    id: did('place-ubud-campuhan-ridge'),
    city_id: did('city-ubud'),
    city_area_id: did('area-ubud-campuhan'),
    slug: 'campuhan-ridge-walk',
    name: 'Campuhan Ridge Walk',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: -8.4976,
    lng: 115.2501,
    address: 'Jl. Raya Campuhan, Ubud',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily sunrise-sunset',
    description: 'Scenic hillside trail through lush greenery, popular with solo walkers at sunrise. Well-trafficked and safe, with locals greeting you along the path.',
    is_active: true,
  },

  // CANGGU
  {
    id: did('place-canggu-thewave'),
    city_id: did('city-canggu'),
    city_area_id: did('area-canggu-berawa'),
    slug: 'thewave-canggu',
    name: 'Thewave Canggu',
    place_type: 'hotel',
    primary_category_id: did('cat-stay'),
    lat: -8.6485,
    lng: 115.1385,
    address: 'Jl. Pantai Berawa, Canggu',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '24 hours',
    description: 'Stylish beach hotel with a rooftop pool and social events. Solo travelers bond over sunset sessions and group dinners—easy to make friends here.',
    is_active: true,
  },
  {
    id: did('place-canggu-deus'),
    city_id: did('city-canggu'),
    city_area_id: did('area-canggu-batubolong'),
    slug: 'deus-temple',
    name: 'Deus Ex Machina Temple of Enthusiasm',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: -8.6512,
    lng: 115.1362,
    address: 'Jl. Batu Mejan, Canggu',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 7am-11pm',
    description: 'Surf-culture cafe with excellent coffee and live music. Great for solo laptop sessions during the day, then transforms into a laid-back evening hangout.',
    is_active: true,
  },
  {
    id: did('place-canggu-finns-beach-club'),
    city_id: did('city-canggu'),
    city_area_id: did('area-canggu-batubolong'),
    slug: 'finns-beach-club',
    name: "Finn\'s Beach Club",
    place_type: 'bar',
    primary_category_id: did('cat-nightlife'),
    lat: -8.6523,
    lng: 115.1347,
    address: 'Jl. Pantai Berawa, Canggu',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: 'Daily 9am-11pm',
    description: 'Iconic beach club with infinity pool and ocean views. Solo-friendly daybeds and a welcoming vibe—easy to chat with other travelers over cocktails.',
    is_active: true,
  },
  {
    id: did('place-canggu-motion'),
    city_id: did('city-canggu'),
    city_area_id: did('area-canggu-batubolong'),
    slug: 'motion-cafe',
    name: 'Motion Cafe',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: -8.6501,
    lng: 115.1371,
    address: 'Jl. Batu Mejan, Canggu',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 7am-6pm',
    description: 'Health-focused cafe with acai bowls and strong wifi. Popular with solo digital nomads—grab a communal table and you\'ll likely make a friend.',
    is_active: true,
  },
  {
    id: did('place-canggu-practice'),
    city_id: did('city-canggu'),
    city_area_id: did('area-canggu-berawa'),
    slug: 'the-practice',
    name: 'The Practice',
    place_type: 'wellness',
    primary_category_id: did('cat-wellness'),
    lat: -8.6467,
    lng: 115.1393,
    address: 'Jl. Pantai Berawa, Canggu',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 6am-9pm',
    description: 'Beautiful bamboo yoga studio with ocean breezes and world-class teachers. The community is warm and welcoming to solo practitioners of all levels.',
    is_active: true,
  },
  {
    id: did('place-canggu-tropical-nomad'),
    city_id: did('city-canggu'),
    city_area_id: did('area-canggu-batubolong'),
    slug: 'tropical-nomad',
    name: 'Tropical Nomad Coworking',
    place_type: 'coworking',
    primary_category_id: did('cat-coworking'),
    lat: -8.6495,
    lng: 115.1368,
    address: 'Jl. Batu Mejan, Canggu',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Mon-Fri 8am-6pm',
    description: 'Modern coworking space with fast wifi and a rooftop terrace. Regular social events make it easy for solo remote workers to connect.',
    is_active: true,
  },
  {
    id: did('place-canggu-mason'),
    city_id: did('city-canggu'),
    city_area_id: did('area-canggu-berawa'),
    slug: 'mason',
    name: 'Mason',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: -8.6479,
    lng: 115.1388,
    address: 'Jl. Pantai Berawa, Canggu',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: 'Daily 7am-11pm',
    description: 'Upscale restaurant with creative cocktails and sharing plates. The bar seating is perfect for solo dining, and the staff makes great conversation.',
    is_active: true,
  },
  {
    id: did('place-canggu-echo-beach'),
    city_id: did('city-canggu'),
    city_area_id: did('area-canggu-echobeach'),
    slug: 'echo-beach',
    name: 'Echo Beach',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: -8.6548,
    lng: 115.1311,
    address: 'Jl. Pura Batu Mejan, Canggu',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 24 hours',
    description: 'Popular surf beach with dramatic black sand and stunning sunsets. Safe for solo beach days—plenty of other travelers and local warungs nearby.',
    is_active: true,
  },

  // SEMINYAK
  {
    id: did('place-seminyak-potato-head'),
    city_id: did('city-seminyak'),
    city_area_id: did('area-seminyak-petitenget'),
    slug: 'potato-head-beach-club',
    name: 'Potato Head Beach Club',
    place_type: 'bar',
    primary_category_id: did('cat-nightlife'),
    lat: -8.6798,
    lng: 115.1538,
    address: 'Jl. Petitenget No.51B, Seminyak',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: 'Daily 9am-1am',
    description: 'Iconic beachfront club with infinity pool and world-class DJs. Solo women feel comfortable here—sophisticated crowd and attentive security staff.',
    is_active: true,
  },
  {
    id: did('place-seminyak-w-bali'),
    city_id: did('city-seminyak'),
    city_area_id: did('area-seminyak-petitenget'),
    slug: 'w-bali',
    name: 'W Bali - Seminyak',
    place_type: 'hotel',
    primary_category_id: did('cat-stay'),
    lat: -8.6812,
    lng: 115.1545,
    address: 'Jl. Petitenget, Seminyak',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 4,
    hours_text: '24 hours',
    description: 'Chic beachfront resort with vibrant pool scene and excellent service. Solo travelers appreciate the safe, social atmosphere and easy beach access.',
    is_active: true,
  },
  {
    id: did('place-seminyak-merah-putih'),
    city_id: did('city-seminyak'),
    city_area_id: did('area-seminyak-petitenget'),
    slug: 'merah-putih',
    name: 'Merah Putih',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: -8.6823,
    lng: 115.1601,
    address: 'Jl. Petitenget No.100X, Seminyak',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: 'Daily 11am-11pm',
    description: 'Stunning modern Indonesian restaurant with soaring bamboo architecture. The chef\'s table is ideal for solo diners who want to watch the kitchen in action.',
    is_active: true,
  },
  {
    id: did('place-seminyak-revolver'),
    city_id: did('city-seminyak'),
    city_area_id: did('area-seminyak-oberoi'),
    slug: 'revolver-espresso',
    name: 'Revolver Espresso',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: -8.6889,
    lng: 115.1623,
    address: 'Jl. Kayu Jati No.8, Seminyak',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 6:30am-6pm',
    description: 'Aussie-style breakfast spot known for epic brunch and strong coffee. Counter seating makes solo dining comfortable, and the vibe is always buzzing.',
    is_active: true,
  },
  {
    id: did('place-seminyak-motel-mexicola'),
    city_id: did('city-seminyak'),
    city_area_id: did('area-seminyak-oberoi'),
    slug: 'motel-mexicola',
    name: 'Motel Mexicola',
    place_type: 'bar',
    primary_category_id: did('cat-nightlife'),
    lat: -8.6901,
    lng: 115.1634,
    address: 'Jl. Kayu Jati No.9X, Seminyak',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 12pm-1am',
    description: 'Vibrant Mexican bar with colorful decor and killer margaritas. Fun, energetic crowd where solo travelers can easily join group tables and dance.',
    is_active: true,
  },
  {
    id: did('place-seminyak-seminyak-beach'),
    city_id: did('city-seminyak'),
    city_area_id: did('area-seminyak-doublesix'),
    slug: 'seminyak-beach',
    name: 'Seminyak Beach',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: -8.6945,
    lng: 115.1678,
    address: 'Jl. Arjuna (Double Six), Seminyak',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 24 hours',
    description: 'Wide sandy beach perfect for sunset strolls and people-watching. Well-populated with beachfront cafes—safe and social for solo beach days.',
    is_active: true,
  },
  {
    id: did('place-seminyak-kynd'),
    city_id: did('city-seminyak'),
    city_area_id: did('area-seminyak-oberoi'),
    slug: 'kynd-community',
    name: 'Kynd Community',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: -8.6878,
    lng: 115.1611,
    address: 'Jl. Oberoi, Seminyak',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 7am-10pm',
    description: 'Plant-based cafe with colorful smoothie bowls and a wellness vibe. Communal seating encourages solo travelers to connect over healthy eats.',
    is_active: true,
  },

  // YOGYAKARTA
  {
    id: did('place-yogya-phoenix-hotel'),
    city_id: did('city-yogya'),
    city_area_id: did('area-yogya-malioboro'),
    slug: 'phoenix-hotel',
    name: 'The Phoenix Hotel Yogyakarta',
    place_type: 'hotel',
    primary_category_id: did('cat-stay'),
    lat: -7.7923,
    lng: 110.3645,
    address: 'Jl. Jenderal Sudirman No.9, Yogyakarta',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '24 hours',
    description: 'Historic colonial hotel with old-world charm and a central location. Safe, well-staffed, and perfect for solo women exploring the city\'s cultural sites.',
    is_active: true,
  },
  {
    id: did('place-yogya-house-raminten'),
    city_id: did('city-yogya'),
    city_area_id: did('area-yogya-malioboro'),
    slug: 'house-of-raminten',
    name: 'House of Raminten',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: -7.7956,
    lng: 110.3689,
    address: 'Jl. FM Noto No.7, Yogyakarta',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 10am-10pm',
    description: 'Quirky Javanese restaurant with traditional decor and live music. Solo diners get warm service and a fascinating cultural dining experience.',
    is_active: true,
  },
  {
    id: did('place-yogya-kopi-klotok'),
    city_id: did('city-yogya'),
    city_area_id: did('area-yogya-prawirotaman'),
    slug: 'kopi-klotok',
    name: 'Kopi Klotok',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: -7.8134,
    lng: 110.3712,
    address: 'Jl. Prawirotaman, Yogyakarta',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 8am-10pm',
    description: 'Charming local coffee shop known for traditional Javanese coffee and snacks. Relaxed atmosphere perfect for solo journaling or reading.',
    is_active: true,
  },
  {
    id: did('place-yogya-borobudur'),
    city_id: did('city-yogya'),
    city_area_id: null,
    slug: 'borobudur-temple',
    name: 'Borobudur Temple',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: -7.6079,
    lng: 110.2038,
    address: 'Borobudur, Magelang, Central Java',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 6am-5pm',
    description: 'Magnificent 9th-century Buddhist temple and UNESCO site. Join a sunrise tour group for safety and shared wonder—an unforgettable solo travel moment.',
    is_active: true,
  },
  {
    id: did('place-yogya-prambanan'),
    city_id: did('city-yogya'),
    city_area_id: null,
    slug: 'prambanan-temple',
    name: 'Prambanan Temple',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: -7.7520,
    lng: 110.4915,
    address: 'Jl. Raya Solo-Yogyakarta, Prambanan',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 6am-5pm',
    description: 'Stunning Hindu temple complex with intricate stone carvings. Well-guarded and easy to explore solo—go late afternoon for golden light photography.',
    is_active: true,
  },
  {
    id: did('place-yogya-malioboro'),
    city_id: did('city-yogya'),
    city_area_id: did('area-yogya-malioboro'),
    slug: 'malioboro-street',
    name: 'Malioboro Street',
    place_type: 'shop',
    primary_category_id: did('cat-activity'),
    lat: -7.7928,
    lng: 110.3658,
    address: 'Jl. Malioboro, Yogyakarta',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 9am-9pm',
    description: 'Bustling shopping street with batik stalls and street food. Safe for solo wandering during the day—practice your bargaining skills and soak in the energy.',
    is_active: true,
  },

  // GILI ISLANDS
  {
    id: did('place-gili-villa-almarik'),
    city_id: did('city-gili'),
    city_area_id: did('area-gili-trawangan'),
    slug: 'villa-almarik',
    name: 'Villa Almarik',
    place_type: 'hotel',
    primary_category_id: did('cat-stay'),
    lat: -8.3512,
    lng: 116.0423,
    address: 'Gili Trawangan, Lombok',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '24 hours',
    description: 'Boutique resort with pool and beach access on the quieter side of the island. Solo travelers love the intimate vibe and helpful dive shop recommendations.',
    is_active: true,
  },
  {
    id: did('place-gili-scallywags'),
    city_id: did('city-gili'),
    city_area_id: did('area-gili-trawangan'),
    slug: 'scallywags',
    name: 'Scallywags Beach Club',
    place_type: 'bar',
    primary_category_id: did('cat-eat'),
    lat: -8.3489,
    lng: 116.0412,
    address: 'Gili Trawangan, Lombok',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 7am-11pm',
    description: 'Beachfront restaurant with seafood BBQ and sunset views. Easy to meet other travelers at the communal tables—great solo dinner spot.',
    is_active: true,
  },
  {
    id: did('place-gili-kayu-cafe'),
    city_id: did('city-gili'),
    city_area_id: did('area-gili-trawangan'),
    slug: 'kayu-cafe',
    name: 'Kayu Cafe',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: -8.3501,
    lng: 116.0419,
    address: 'Gili Trawangan, Lombok',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 7am-10pm',
    description: 'Stylish cafe with healthy bowls and strong coffee. Perfect for post-dive refueling or laptop work—the wifi is surprisingly good for island life.',
    is_active: true,
  },
  {
    id: did('place-gili-freedive-gili'),
    city_id: did('city-gili'),
    city_area_id: did('area-gili-trawangan'),
    slug: 'freedive-gili',
    name: 'Freedive Gili',
    place_type: 'shop',
    primary_category_id: did('cat-activity'),
    lat: -8.3495,
    lng: 116.0415,
    address: 'Gili Trawangan, Lombok',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 8am-6pm',
    description: 'Professional freediving school with patient instructors. Solo women feel safe and supported learning to dive—great community of ocean lovers.',
    is_active: true,
  },
  {
    id: did('place-gili-trawangan-night-market'),
    city_id: did('city-gili'),
    city_area_id: did('area-gili-trawangan'),
    slug: 'trawangan-night-market',
    name: 'Gili Trawangan Night Market',
    place_type: 'shop',
    primary_category_id: did('cat-eat'),
    lat: -8.3478,
    lng: 116.0408,
    address: 'Main strip, Gili Trawangan',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 6pm-11pm',
    description: 'Bustling night market with fresh seafood and local dishes. Safe and social for solo diners—grab a bench and chat with other island-hoppers.',
    is_active: true,
  },
  {
    id: did('place-gili-air-pemedal'),
    city_id: did('city-gili'),
    city_area_id: did('area-gili-air'),
    slug: 'gili-air-pemedal',
    name: 'Pemedal Beach',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: -8.3612,
    lng: 116.0845,
    address: 'Gili Air, Lombok',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 24 hours',
    description: 'Tranquil beach on Gili Air with excellent snorkeling right off the shore. Less crowded than Trawangan—perfect for peaceful solo beach days.',
    is_active: true,
  },
  {
    id: did('place-gili-sunset-point'),
    city_id: did('city-gili'),
    city_area_id: did('area-gili-trawangan'),
    slug: 'sunset-point',
    name: 'Sunset Point Gili T',
    place_type: 'landmark',
    primary_category_id: did('cat-activity'),
    lat: -8.3534,
    lng: 116.0398,
    address: 'West coast, Gili Trawangan',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily sunrise-sunset',
    description: 'Iconic sunset spot with swings in the water and beanbag lounges. Solo travelers gather here nightly to watch the sun sink behind Mount Agung—magical.',
    is_active: true,
  },
];
