import { did } from '../../seed-utils';

export const japanPlaces = [
  // TOKYO
  {
    id: did('place-tokyo-book-and-bed'),
    city_id: did('city-tokyo'),
    city_area_id: did('area-tokyo-shinjuku'),
    slug: 'book-and-bed',
    name: 'Book and Bed Tokyo',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 35.6938,
    lng: 139.7034,
    address: '1-17-7 Nishishinjuku, Shinjuku City, Tokyo 160-0023',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '24/7 check-in',
    description: 'Boutique hostel concept where you sleep surrounded by books. The capsule-style pods offer privacy and the common area is perfect for meeting other solo travelers. Staff speak English and the location in Shinjuku makes it easy to explore. Felt completely safe here as a solo woman—keycard access and women-only floors available.',
    is_active: true,
  },
  {
    id: did('place-tokyo-tsukiji-outer-market'),
    city_id: did('city-tokyo'),
    city_area_id: null,
    slug: 'tsukiji-outer-market',
    name: 'Tsukiji Outer Market',
    place_type: 'shop',
    primary_category_id: did('cat-eat'),
    lat: 35.6654,
    lng: 139.7707,
    address: '4 Chome Tsukiji, Chuo City, Tokyo 104-0045',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 5am-2pm',
    description: 'The outer market survived the main market relocation and it\'s perfect for solo food adventures. Grab fresh sushi for breakfast, sample street food, and chat with vendors. Go early morning to beat crowds. The atmosphere is buzzing but never felt overwhelming or unsafe—lots of other solo diners at the counter-style spots.',
    is_active: true,
  },
  {
    id: did('place-tokyo-streamer-coffee'),
    city_id: did('city-tokyo'),
    city_area_id: did('area-tokyo-shibuya'),
    slug: 'streamer-coffee',
    name: 'Streamer Coffee Company',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 35.6627,
    lng: 139.7006,
    address: '1-20-28 Shibuya, Shibuya City, Tokyo 150-0002',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Mon-Fri 8am-10pm, Weekends 9am-10pm',
    description: 'Cozy Shibuya cafe that feels like a warm hug after the chaos outside. Their latte art is Instagram-worthy and the vibe is calm enough to work or journal. Counter seating makes it easy to chat with baristas. A safe space to decompress—I\'ve spent many solo afternoons here with a book.',
    is_active: true,
  },
  {
    id: did('place-tokyo-teamlab-borderless'),
    city_id: did('city-tokyo'),
    city_area_id: null,
    slug: 'teamlab-borderless',
    name: 'teamLab Borderless',
    place_type: 'landmark',
    primary_category_id: did('cat-activity'),
    lat: 35.6246,
    lng: 139.7756,
    address: 'Azabudai Hills, 1-2-4 Azabudai, Minato City, Tokyo 106-0041',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: 'Daily 10am-8pm',
    description: 'Immersive digital art experience where you wander through interactive light installations. Book tickets online to skip lines. Perfect for solo exploration—lose yourself in the beauty without feeling self-conscious. The crowd is respectful and staff are helpful. Allocate 2-3 hours and wear comfortable shoes.',
    is_active: true,
  },
  {
    id: did('place-tokyo-senso-ji'),
    city_id: did('city-tokyo'),
    city_area_id: did('area-tokyo-asakusa'),
    slug: 'senso-ji-temple',
    name: 'Sensō-ji Temple',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 35.7148,
    lng: 139.7967,
    address: '2-3-1 Asakusa, Taito City, Tokyo 111-0032',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 6am-5pm',
    description: 'Tokyo\'s oldest temple with the iconic Kaminarimon gate and Nakamise shopping street. Go early morning for a peaceful experience or evening when it\'s beautifully lit. The atmosphere is spiritual yet welcoming. As a solo woman, I felt comfortable exploring—families and tourists everywhere, very safe area.',
    is_active: true,
  },
  {
    id: did('place-tokyo-omoide-yokocho'),
    city_id: did('city-tokyo'),
    city_area_id: did('area-tokyo-shinjuku'),
    slug: 'omoide-yokocho',
    name: 'Omoide Yokocho',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 35.6938,
    lng: 139.7007,
    address: '1 Chome Nishishinjuku, Shinjuku City, Tokyo 160-0023',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 5pm-1am',
    description: 'Narrow alleyway packed with tiny yakitori joints and izakayas. The atmosphere is authentically local but welcoming to foreigners. Counter seating makes it easy to dine solo—just point at what looks good. Best visited early evening before the salarymen get too drunk. Felt safe but skip if late-night chaos isn\'t your vibe.',
    is_active: true,
  },
  {
    id: did('place-tokyo-bunka-hostel'),
    city_id: did('city-tokyo'),
    city_area_id: did('area-tokyo-asakusa'),
    slug: 'bunka-hostel',
    name: 'Bunka Hostel Tokyo',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 35.7119,
    lng: 139.7965,
    address: '1-10-5 Asakusa, Taito City, Tokyo 111-0032',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '24/7',
    description: 'Design-forward hostel in a renovated building with cafe on ground floor. Mix of dorms and private rooms. The communal areas foster connection without being pushy. Great for solo travelers who want community. Female dorms available and the neighborhood (Asakusa) is quiet and safe at night.',
    is_active: true,
  },
  {
    id: did('place-tokyo-harajuku-gyoza'),
    city_id: did('city-tokyo'),
    city_area_id: did('area-tokyo-shibuya'),
    slug: 'harajuku-gyoza-lou',
    name: 'Harajuku Gyoza Lou',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 35.6702,
    lng: 139.7026,
    address: '6-2-4 Jingumae, Shibuya City, Tokyo 150-0001',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 11:30am-4am',
    description: 'Cult-favorite gyoza spot with just a few menu items—all delicious. Counter seating wraps around the open kitchen where you watch them cook. Perfect for solo dining, fast, satisfying, and affordable. The queue moves quickly. Open late if you need a post-karaoke bite. Casual and safe.',
    is_active: true,
  },

  // KYOTO
  {
    id: did('place-kyoto-len-hostel'),
    city_id: did('city-kyoto'),
    city_area_id: did('area-kyoto-gion'),
    slug: 'len-kyoto-kawaramachi',
    name: 'Len Kyoto Kawaramachi',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 35.0042,
    lng: 135.7689,
    address: '457 Nishinocho, Nakagyo Ward, Kyoto 604-8042',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '24/7',
    description: 'Modern hostel with traditional Japanese aesthetics. Tatami-style dorms and a beautiful common space with city views. The staff curate events like tea ceremonies and walking tours—great for meeting other solo travelers. Women-only dorms, lockers, and a safe, central location near Gion.',
    is_active: true,
  },
  {
    id: did('place-kyoto-nishiki-market'),
    city_id: did('city-kyoto'),
    city_area_id: null,
    slug: 'nishiki-market',
    name: 'Nishiki Market',
    place_type: 'shop',
    primary_category_id: did('cat-eat'),
    lat: 35.0050,
    lng: 135.7661,
    address: 'Nishikikoji-dori, Nakagyo Ward, Kyoto 604-8054',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 9am-6pm',
    description: 'Kyoto\'s 400-year-old food market stretching five blocks. Sample everything from pickles to fresh mochi to grilled seafood. The vendors are friendly and used to tourists. Easy to navigate solo—just wander and graze. Crowded but never felt unsafe. Go mid-morning for the best energy.',
    is_active: true,
  },
  {
    id: did('place-kyoto-weekenders-coffee'),
    city_id: did('city-kyoto'),
    city_area_id: did('area-kyoto-higashiyama'),
    slug: 'weekenders-coffee',
    name: 'Weekenders Coffee',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 35.0033,
    lng: 135.7806,
    address: '566-6 Komatsucho, Higashiyama Ward, Kyoto 605-0811',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Wed-Mon 10am-6pm, Closed Tue',
    description: 'Minimalist corner cafe with excellent pour-over coffee and pastries. Large windows, natural light, perfect for people-watching or journaling. The baristas are warm and it attracts a creative crowd. Solo-friendly vibes—bring a book and stay awhile. Located in a quiet residential area near temples.',
    is_active: true,
  },
  {
    id: did('place-kyoto-fushimi-inari'),
    city_id: did('city-kyoto'),
    city_area_id: null,
    slug: 'fushimi-inari-shrine',
    name: 'Fushimi Inari Shrine',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 34.9671,
    lng: 135.7727,
    address: '68 Fukakusa Yabunouchicho, Fushimi Ward, Kyoto 612-0882',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Open 24/7',
    description: 'Iconic shrine with thousands of vermillion torii gates winding up the mountain. The hike takes 2-3 hours round trip. Go early morning or late afternoon to avoid tour groups. As a solo hiker, I felt safe—lots of people around and the path is well-maintained. Bring water and wear good shoes.',
    is_active: true,
  },
  {
    id: did('place-kyoto-arashiyama-bamboo'),
    city_id: did('city-kyoto'),
    city_area_id: did('area-kyoto-arashiyama'),
    slug: 'arashiyama-bamboo-grove',
    name: 'Arashiyama Bamboo Grove',
    place_type: 'landmark',
    primary_category_id: did('cat-activity'),
    lat: 35.0170,
    lng: 135.6722,
    address: 'Sagatenryuji Susukinobabacho, Ukyo Ward, Kyoto 616-8385',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Open 24/7',
    description: 'Walk through towering bamboo stalks—it\'s as magical as photos suggest. Visit at sunrise for a mystical, crowd-free experience. The area is well-trafficked and safe. Combine with nearby temples and the monkey park. Rental kimono shops nearby if you want that Instagram moment.',
    is_active: true,
  },
  {
    id: did('place-kyoto-ippudo-ramen'),
    city_id: did('city-kyoto'),
    city_area_id: null,
    slug: 'ippudo-kyoto',
    name: 'Ippudo Ramen Kyoto',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 35.0116,
    lng: 135.7681,
    address: '143-2 Zaimokucho, Sanjo-dori Kawaramachi Higashi-iru, Nakagyo Ward, Kyoto',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 11am-11pm',
    description: 'Famous ramen chain that\'s consistently excellent. Counter seating is perfect for solo diners—order from a vending machine, no Japanese needed. The tonkotsu broth is rich and creamy. Quick service, casual atmosphere. Safe and comfortable even dining alone at night.',
    is_active: true,
  },
  {
    id: did('place-kyoto-kurasu-coffee'),
    city_id: did('city-kyoto'),
    city_area_id: null,
    slug: 'kurasu-kyoto',
    name: 'Kurasu Kyoto',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 35.0055,
    lng: 135.7698,
    address: '566 Kiyamotocho, Nakagyo Ward, Kyoto 604-8801',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 8am-6pm',
    description: 'Specialty coffee roastery with a gorgeous two-story space. Excellent beans, knowledgeable staff, and great wifi. The second floor has communal tables perfect for working solo. Regulars include freelancers and travelers. Very welcoming environment—easy to strike up conversations or keep to yourself.',
    is_active: true,
  },
  {
    id: did('place-kyoto-gion-district'),
    city_id: did('city-kyoto'),
    city_area_id: did('area-kyoto-gion'),
    slug: 'gion-district',
    name: 'Gion District',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 35.0034,
    lng: 135.7751,
    address: 'Gion, Higashiyama Ward, Kyoto 605-0001',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Open 24/7',
    description: 'Kyoto\'s most famous geisha district with traditional wooden machiya houses. Stroll the atmospheric streets, especially Hanamikoji. If you\'re lucky, you might spot a geiko or maiko. Best visited at dusk when lanterns light up. Perfectly safe to explore solo—very touristy but magical nonetheless.',
    is_active: true,
  },

  // OSAKA
  {
    id: did('place-osaka-hostel-64'),
    city_id: did('city-osaka'),
    city_area_id: did('area-osaka-namba'),
    slug: 'hostel-64-osaka',
    name: 'Hostel 64 Osaka',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 34.6665,
    lng: 135.5016,
    address: '1-12-20 Nipponbashi, Chuo Ward, Osaka 542-0073',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '24/7',
    description: 'Budget-friendly hostel with a rooftop terrace and lively common area. The staff organize bar crawls and food tours—great for solo travelers wanting to make friends. Clean dorms, good security, female-only options. Located in Namba, walking distance to Dotonbori. The social vibe is infectious but never pushy.',
    is_active: true,
  },
  {
    id: did('place-osaka-dotonbori-street'),
    city_id: did('city-osaka'),
    city_area_id: did('area-osaka-dotonbori'),
    slug: 'dotonbori-street',
    name: 'Dotonbori Street',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 34.6686,
    lng: 135.5010,
    address: 'Dotonbori, Chuo Ward, Osaka 542-0071',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Most shops 11am-11pm',
    description: 'Osaka\'s neon-lit food paradise along the canal. Try takoyaki, okonomiyaki, kushikatsu—all the hits. The energy is electric and slightly frantic but thrilling. Lots of solo diners at counter-style spots. Felt safe even at night with the crowds. The giant signs (Glico Man!) are pure Osaka energy.',
    is_active: true,
  },
  {
    id: did('place-osaka-mel-coffee-roasters'),
    city_id: did('city-osaka'),
    city_area_id: null,
    slug: 'mel-coffee-roasters',
    name: 'Mel Coffee Roasters',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 34.6937,
    lng: 135.4969,
    address: '2-2-14 Edobori, Nishi Ward, Osaka 550-0002',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Mon-Sat 9am-6pm, Sun 10am-6pm',
    description: 'Industrial-chic cafe in a quiet neighborhood away from tourist chaos. Exceptional coffee and a calm workspace vibe. The owner is friendly and speaks English. Great spot to reset between sightseeing—locals and expats frequent it. Solo-friendly with counter seating and communal tables.',
    is_active: true,
  },
  {
    id: did('place-osaka-castle'),
    city_id: did('city-osaka'),
    city_area_id: null,
    slug: 'osaka-castle',
    name: 'Osaka Castle',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 34.6873,
    lng: 135.5262,
    address: '1-1 Osakajo, Chuo Ward, Osaka 540-0002',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 9am-5pm',
    description: 'Iconic castle surrounded by park and moats. The interior is a museum with exhibits on samurai history. The top floor offers panoramic city views. The park is lovely for a solo stroll, especially during cherry blossom season. Totally safe and easy to navigate—audio guides available.',
    is_active: true,
  },
  {
    id: did('place-osaka-kuromon-market'),
    city_id: did('city-osaka'),
    city_area_id: did('area-osaka-namba'),
    slug: 'kuromon-market',
    name: 'Kuromon Ichiba Market',
    place_type: 'shop',
    primary_category_id: did('cat-eat'),
    lat: 34.6662,
    lng: 135.5053,
    address: '2-4-1 Nipponbashi, Chuo Ward, Osaka 542-0073',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 8am-6pm',
    description: 'Covered market known as "Osaka\'s kitchen." Sample fresh seafood, wagyu skewers, tropical fruit. The vendors are welcoming and used to solo diners. Grab a beer and oysters at 10am—it\'s allowed and encouraged. Touristy but fun. Safe and easy to navigate alone.',
    is_active: true,
  },
  {
    id: did('place-osaka-shinsekai'),
    city_id: did('city-osaka'),
    city_area_id: did('area-osaka-shinsekai'),
    slug: 'shinsekai-district',
    name: 'Shinsekai District',
    place_type: 'landmark',
    primary_category_id: did('cat-activity'),
    lat: 34.6523,
    lng: 135.5061,
    address: 'Ebisuhigashi, Naniwa Ward, Osaka 556-0002',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Most shops 10am-10pm',
    description: 'Retro neighborhood with the iconic Tsutenkaku Tower and countless kushikatsu (fried skewers) joints. The area has an old-school, working-class charm. Visit during the day for sightseeing and early evening for food. Solo-friendly but can feel a bit rough late at night—stick to main streets.',
    is_active: true,
  },
  {
    id: did('place-osaka-brooklyn-roasting'),
    city_id: did('city-osaka'),
    city_area_id: null,
    slug: 'brooklyn-roasting-osaka',
    name: 'Brooklyn Roasting Company Osaka',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 34.6759,
    lng: 135.4944,
    address: '1-3-27 Kitahorie, Nishi Ward, Osaka 550-0014',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 9am-8pm',
    description: 'Spacious cafe in the trendy Kitahorie area. Brooklyn vibes transplanted to Osaka with great coffee and all-day breakfast. Wifi, outlets, and a chill crowd of freelancers and creatives. Perfect for solo work sessions or lazy Sunday mornings. English-speaking staff.',
    is_active: true,
  },
  {
    id: did('place-osaka-sumiyoshi-taisha'),
    city_id: did('city-osaka'),
    city_area_id: null,
    slug: 'sumiyoshi-taisha',
    name: 'Sumiyoshi Taisha Shrine',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 34.6098,
    lng: 135.4928,
    address: '2-9-89 Sumiyoshi, Sumiyoshi Ward, Osaka 558-0045',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 6am-5pm',
    description: 'One of Japan\'s oldest shrines with unique architectural style and a famous arched bridge. Less touristy than other Osaka attractions, offering a peaceful escape. The grounds are beautiful and great for solo contemplation. Easy train access. Completely safe and welcoming.',
    is_active: true,
  },
];
