import { did } from '../../seed-utils';

export const laosPlaces = [
  // LUANG PRABANG
  {
    id: did('place-luangprabang-spicylao-backpackers'),
    city_id: did('city-luangprabang'),
    city_area_id: did('area-luangprabang-oldtown'),
    slug: 'spicylao-backpackers',
    name: 'SpicyLao Backpackers',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 19.8876,
    lng: 102.1350,
    address: 'Kingkitsarath Road, Luang Prabang',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '24/7 check-in',
    description: 'Social hostel with female dorms, a garden bar, and nightly hangouts. Great for meeting other solo travelers. Staff organize waterfall tours and alms-giving ceremonies. Central location near night market.',
    is_active: true,
  },
  {
    id: did('place-luangprabang-tamarind'),
    city_id: did('city-luangprabang'),
    city_area_id: did('area-luangprabang-oldtown'),
    slug: 'tamarind-restaurant',
    name: 'Tamarind Restaurant',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 19.8930,
    lng: 102.1409,
    address: 'Kingkitsarath Road, Luang Prabang',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '11am-10pm daily',
    description: 'Elevated Lao cuisine in a beautiful garden setting. Solo diners are welcomed. Try the tasting platter to sample multiple dishes. They also offer cooking classes—great way to meet people. Reservations recommended.',
    is_active: true,
  },
  {
    id: did('place-luangprabang-joma-bakery'),
    city_id: did('city-luangprabang'),
    city_area_id: did('area-luangprabang-oldtown'),
    slug: 'joma-bakery-cafe',
    name: 'Joma Bakery Cafe',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 19.8907,
    lng: 102.1387,
    address: 'Chao Fa Ngum Road, Luang Prabang',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '7am-9pm daily',
    description: 'Popular cafe chain with excellent coffee, pastries, and sandwiches. Solo-friendly with WiFi and air-con. Perfect for breakfast or remote work. The iced lattes and chocolate croissants are top-notch.',
    is_active: true,
  },
  {
    id: did('place-luangprabang-kuang-si-falls'),
    city_id: did('city-luangprabang'),
    city_area_id: null,
    slug: 'kuang-si-falls',
    name: 'Kuang Si Waterfalls',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 19.7493,
    lng: 101.9905,
    address: '30km south of Luang Prabang',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '8am-5:30pm daily',
    description: 'Stunning turquoise waterfalls with swimming pools. Solo women can join group tours or rent a motorbike. Arrive early to beat crowds. Bring a swimsuit and waterproof bag. There\'s also a bear rescue center.',
    is_active: true,
  },
  {
    id: did('place-luangprabang-alms-giving'),
    city_id: did('city-luangprabang'),
    city_area_id: did('area-luangprabang-oldtown'),
    slug: 'alms-giving-ceremony',
    name: 'Tak Bat (Alms Giving Ceremony)',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 19.8916,
    lng: 102.1355,
    address: 'Main streets, Luang Prabang Old Town',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '5:30am-6:30am daily',
    description: 'Sacred Buddhist ritual where monks collect alms at sunrise. Solo women can observe respectfully from a distance. Wear modest clothing, don\'t touch monks, and be silent. A peaceful, spiritual experience.',
    is_active: true,
  },
  {
    id: did('place-luangprabang-night-market'),
    city_id: did('city-luangprabang'),
    city_area_id: did('area-luangprabang-nightmarket'),
    slug: 'luang-prabang-night-market',
    name: 'Luang Prabang Night Market',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 19.8899,
    lng: 102.1366,
    address: 'Sisavangvong Road, Luang Prabang',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '5pm-10pm daily',
    description: 'Handicraft night market with textiles, lanterns, and souvenirs. Safe for solo women—well-lit and family-friendly. Fixed prices, no haggling needed. Perfect for picking up silk scarves and handmade gifts.',
    is_active: true,
  },
  {
    id: did('place-luangprabang-mount-phousi'),
    city_id: did('city-luangprabang'),
    city_area_id: did('area-luangprabang-oldtown'),
    slug: 'mount-phousi',
    name: 'Mount Phousi',
    place_type: 'activity',
    primary_category_id: did('cat-landmark'),
    lat: 19.8945,
    lng: 102.1398,
    address: 'Phousi Hill, Luang Prabang',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '6am-6pm daily',
    description: 'Sacred hill with 360-degree views over Luang Prabang. Climb 328 steps for sunset—crowded but worth it. Solo women feel safe here during the day. Bring water and a sarong for the temple at the top.',
    is_active: true,
  },

  // VIENTIANE
  {
    id: did('place-vientiane-mixok-hostel'),
    city_id: did('city-vientiane'),
    city_area_id: did('area-vientiane-mekong'),
    slug: 'mixok-hostel',
    name: 'Mixok Hostel',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 17.9631,
    lng: 102.6140,
    address: 'Fa Ngum Road, Vientiane',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '24/7 check-in',
    description: 'Riverside hostel with female dorms and a rooftop terrace. Clean, chill, and social. Great base for exploring Vientiane\'s temples and cafes. Staff can arrange bus tickets to other cities.',
    is_active: true,
  },
  {
    id: did('place-vientiane-kualao-restaurant'),
    city_id: did('city-vientiane'),
    city_area_id: did('area-vientiane-mekong'),
    slug: 'kualao-restaurant',
    name: 'Kualao Restaurant',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 17.9658,
    lng: 102.6141,
    address: '111 Quai Fa Ngoum, Vientiane',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '11am-2pm, 6pm-10pm daily',
    description: 'Riverfront restaurant serving traditional Lao dishes. Solo diners can enjoy sunset views over the Mekong. Try laap, tam mak hoong (papaya salad), and sticky rice. Live traditional music some evenings.',
    is_active: true,
  },
  {
    id: did('place-vientiane-joma-vientiane'),
    city_id: did('city-vientiane'),
    city_area_id: did('area-vientiane-mekong'),
    slug: 'joma-cafe-vientiane',
    name: 'Joma Bakery Cafe Vientiane',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 17.9606,
    lng: 102.6136,
    address: 'Setthathirath Road, Vientiane',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '7am-9pm daily',
    description: 'Reliable cafe with WiFi, air-con, and great coffee. Solo-friendly spot for breakfast or remote work. Same quality as the Luang Prabang branch. Try the breakfast burrito and iced latte.',
    is_active: true,
  },
  {
    id: did('place-vientiane-pha-that-luang'),
    city_id: did('city-vientiane'),
    city_area_id: did('area-vientiane-thatluang'),
    slug: 'pha-that-luang',
    name: 'Pha That Luang (Great Stupa)',
    place_type: 'activity',
    primary_category_id: did('cat-landmark'),
    lat: 17.9775,
    lng: 102.6342,
    address: 'That Luang Road, Vientiane',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '8am-12pm, 1pm-4pm Tue-Sun, closed Mon',
    description: 'National symbol of Laos—a stunning golden stupa and Buddhist temple. Solo women can easily visit. Dress modestly (cover shoulders and knees). Peaceful grounds perfect for a quiet stroll.',
    is_active: true,
  },
  {
    id: did('place-vientiane-buddha-park'),
    city_id: did('city-vientiane'),
    city_area_id: null,
    slug: 'buddha-park',
    name: 'Buddha Park (Xieng Khuan)',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 17.9204,
    lng: 102.7631,
    address: '25km southeast of Vientiane',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '8am-5pm daily',
    description: 'Surreal sculpture park with over 200 Buddhist and Hindu statues. Easy to reach by tuk-tuk or local bus. Solo women feel safe here. Quirky, fun, and great for photos. Climb inside the giant pumpkin structure.',
    is_active: true,
  },

  // VANG VIENG
  {
    id: did('place-vangvieng-nana-backpackers'),
    city_id: did('city-vangvieng'),
    city_area_id: did('area-vangvieng-center'),
    slug: 'nana-backpackers',
    name: 'Nana Backpackers Hostel',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 18.9285,
    lng: 102.4476,
    address: 'Main Road, Vang Vieng',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '24/7 check-in',
    description: 'Party hostel with female dorms, a bar, and pool table. Great for solo travelers wanting to socialize. They organize tubing, caving, and kayaking trips. Lively atmosphere and central location.',
    is_active: true,
  },
  {
    id: did('place-vangvieng-smile-beach-bar'),
    city_id: did('city-vangvieng'),
    city_area_id: did('area-vangvieng-center'),
    slug: 'smile-beach-bar',
    name: 'Smile Beach Bar',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 18.9240,
    lng: 102.4463,
    address: 'Riverside, Vang Vieng',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '10am-11pm daily',
    description: 'Riverside bar and restaurant with stunning karst views. Solo diners can grab a hammock or swing seat. Western and Lao food, plus cold Beer Lao. Perfect for sunset. Chill backpacker vibe.',
    is_active: true,
  },
  {
    id: did('place-vangvieng-gary-cafe'),
    city_id: did('city-vangvieng'),
    city_area_id: did('area-vangvieng-center'),
    slug: 'gary-cafe',
    name: 'Gary\'s Irish Bar & Cafe',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 18.9272,
    lng: 102.4480,
    address: 'Main Road, Vang Vieng',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '7am-11pm daily',
    description: 'Popular cafe-bar with WiFi and comfort food. Good for solo breakfast or working during the day. Full Irish breakfast, pancakes, and smoothie bowls. Turns into a bar at night with live sports.',
    is_active: true,
  },
  {
    id: did('place-vangvieng-blue-lagoon'),
    city_id: did('city-vangvieng'),
    city_area_id: did('area-vangvieng-bluelagoon'),
    slug: 'blue-lagoon',
    name: 'Blue Lagoon & Tham Phu Kham Cave',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 18.9835,
    lng: 102.4142,
    address: '7km west of Vang Vieng',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '8am-6pm daily',
    description: 'Natural swimming hole with turquoise water and rope swings. Solo women can easily join group tours or rent a motorbike. Climb to the cave above for a reclining Buddha. Bring a swimsuit and small bills.',
    is_active: true,
  },
  {
    id: did('place-vangvieng-tubing'),
    city_id: did('city-vangvieng'),
    city_area_id: did('area-vangvieng-center'),
    slug: 'tubing-nam-song-river',
    name: 'Nam Song River Tubing',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 18.9285,
    lng: 102.4456,
    address: 'Tubing rental shops, Main Road, Vang Vieng',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '9am-4pm daily',
    description: 'Famous tubing experience down the Nam Song River. Solo travelers join others easily. It\'s calmer now than it used to be—still fun but safer. Rent a tube, float, and stop at riverside bars. Bring waterproof gear.',
    is_active: true,
  },
  {
    id: did('place-vangvieng-hot-air-balloon'),
    city_id: did('city-vangvieng'),
    city_area_id: null,
    slug: 'hot-air-balloon',
    name: 'Vang Vieng Hot Air Balloon',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 18.9300,
    lng: 102.4500,
    address: 'Launch sites near Vang Vieng',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: 'Sunrise and sunset flights daily',
    description: 'Tethered hot air balloon ride with 360-degree views of karst mountains and rice paddies. Solo-friendly—you\'ll share the basket. Sunrise is magical. Book through your hostel or tour agencies in town.',
    is_active: true,
  },
];
