import { did } from '../../seed-utils';

export const lesothoPlaces = [
  // MASERU
  {
    id: did('place-maseru-thaba-bosiu'),
    city_id: did('city-maseru'),
    city_area_id: did('area-maseru-center'),
    slug: 'thaba-bosiu-cultural-village',
    name: 'Thaba Bosiu Cultural Village',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: -29.3703,
    lng: 27.5842,
    address: 'Thaba Bosiu, Maseru District',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 8am-5pm',
    description: 'The mountain fortress where King Moshoeshoe I unified the Basotho nation — a place of deep historical weight. The guided walk to the summit passes royal graves and stone ruins, with panoramic views of the surrounding lowlands. Hire a local guide for the full story.',
    is_active: true,
  },
  {
    id: did('place-maseru-avani-hotel'),
    city_id: did('city-maseru'),
    city_area_id: did('area-maseru-center'),
    slug: 'avani-maseru-hotel',
    name: 'Avani Maseru Hotel',
    place_type: 'hotel',
    primary_category_id: did('cat-stay'),
    lat: -29.3170,
    lng: 27.4810,
    address: '12 Open Road, Maseru 100',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '24/7',
    description: 'Maseru\'s most established international hotel, set along the Caledon River with views across to South Africa. The rooms are clean and functional, the restaurant is dependable, and the location makes it a practical base for exploring the capital and day trips into the highlands.',
    is_active: true,
  },
  {
    id: did('place-maseru-pioneer-mall'),
    city_id: did('city-maseru'),
    city_area_id: did('area-maseru-center'),
    slug: 'pioneer-mall-maseru',
    name: 'Pioneer Mall',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: -29.3150,
    lng: 27.4900,
    address: 'Kingsway Road, Maseru',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 9am-6pm',
    description: 'The largest shopping centre in Lesotho, useful for stocking up on supplies before heading into the mountains. The food court and supermarket are practical stops, and the craft vendors outside sell Basotho blankets and woven goods at reasonable prices.',
    is_active: true,
  },

  // SEMONKONG
  {
    id: did('place-semonkong-maletsunyane-falls'),
    city_id: did('city-semonkong'),
    city_area_id: did('area-semonkong-village'),
    slug: 'maletsunyane-falls',
    name: 'Maletsunyane Falls',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: -29.8350,
    lng: 28.9700,
    address: 'Semonkong, Maseru District',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daylight hours',
    description: 'One of the highest single-drop waterfalls in Southern Africa, plunging 192 meters into a mossy gorge. The walk from the lodge takes about 45 minutes through open grassland and the viewpoint is unfenced and dramatic. In winter, the falls sometimes freeze entirely.',
    is_active: true,
  },
  {
    id: did('place-semonkong-lodge'),
    city_id: did('city-semonkong'),
    city_area_id: did('area-semonkong-village'),
    slug: 'semonkong-lodge',
    name: 'Semonkong Lodge',
    place_type: 'hotel',
    primary_category_id: did('cat-stay'),
    lat: -29.8400,
    lng: 28.9730,
    address: 'Semonkong Village, Maseru District',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '24/7',
    description: 'The only formal accommodation in Semonkong, with options ranging from dorms to stone rondavels with fireplaces. The lodge organises pony treks, abseiling, and guided hikes. Evenings are quiet — wood fires, mountain air, and a genuinely remote sense of place.',
    is_active: true,
  },
  {
    id: did('place-semonkong-pony-trekking'),
    city_id: did('city-semonkong'),
    city_area_id: did('area-semonkong-village'),
    slug: 'pony-trekking-adventure',
    name: 'Pony Trekking Adventure',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: -29.8380,
    lng: 28.9710,
    address: 'Semonkong Village, Maseru District',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Morning departures, typically 8am-9am',
    description: 'Basotho ponies have navigated these highlands for generations, and a half-day or multi-day trek through remote villages and mountain passes is the most authentic way to experience rural Lesotho. No riding experience required — the ponies know the terrain better than anyone.',
    is_active: true,
  },
  {
    id: did('place-semonkong-abseiling'),
    city_id: did('city-semonkong'),
    city_area_id: did('area-semonkong-village'),
    slug: 'abseiling-maletsunyane',
    name: 'Abseiling Maletsunyane',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: -29.8355,
    lng: 28.9705,
    address: 'Maletsunyane Falls, Semonkong',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'By arrangement, weather dependent',
    description: 'A commercial abseil down the full 192-meter face of Maletsunyane Falls — considered the longest single-drop abseil in the world. The operation is run by the lodge with proper safety equipment. Not for the faint-hearted, but the bragging rights are legitimate.',
    is_active: true,
  },
];
