import { did } from '../../seed-utils';

export const malaysiaPlaces = [
  // KUALA LUMPUR
  {
    id: did('place-kl-capsule-transit'),
    city_id: did('city-kl'),
    city_area_id: did('area-kl-klcc'),
    slug: 'capsule-transit',
    name: 'Capsule Transit KLIA2',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 2.7456,
    lng: 101.7072,
    address: 'Gateway@KLIA2, Level 2, KLIA2 Airport, Sepang',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '24/7',
    description: 'Affordable capsule hotel right in KLIA2 airport, perfect for solo women travelers with layovers. Clean, safe, and convenient with keycard access. Great if you have an early flight or arrive late.',
    is_active: true,
  },
  {
    id: did('place-kl-reggae-mansion'),
    city_id: did('city-kl'),
    city_area_id: did('area-kl-chinatown'),
    slug: 'reggae-mansion',
    name: 'Reggae Mansion',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 3.1438,
    lng: 101.6964,
    address: '158 Jalan Tun H S Lee, Chinatown, Kuala Lumpur',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '24/7 check-in',
    description: 'Vibrant social hostel in the heart of Chinatown, beloved by solo female travelers. Rooftop bar, female-only dorms, lockers, and a super social atmosphere. Great for meeting other travelers.',
    is_active: true,
  },
  {
    id: did('place-kl-jalan-alor'),
    city_id: did('city-kl'),
    city_area_id: did('area-kl-bukitbintang'),
    slug: 'jalan-alor',
    name: 'Jalan Alor Food Street',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 3.1469,
    lng: 101.7034,
    address: 'Jalan Alor, Bukit Bintang, Kuala Lumpur',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '5pm-4am daily',
    description: 'Iconic street food haven bustling with energy. Solo women feel safe here even at night—it\'s crowded, well-lit, and full of families. Try the BBQ seafood, satay, and Hokkien mee. Arrive hungry.',
    is_active: true,
  },
  {
    id: did('place-kl-vcr'),
    city_id: did('city-kl'),
    city_area_id: did('area-kl-bukitbintang'),
    slug: 'vcr-cafe',
    name: 'VCR',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 3.1516,
    lng: 101.7123,
    address: '2 Jalan Galloway, Bukit Bintang, Kuala Lumpur',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '8am-6pm Mon-Fri, 9am-6pm Sat-Sun',
    description: 'Specialty coffee pioneer in KL with excellent WiFi and a calm vibe. Popular with digital nomads and solo workers. The flat white is spot-on, and the brunch menu is solid. Arrive early for a seat.',
    is_active: true,
  },
  {
    id: did('place-kl-batu-caves'),
    city_id: did('city-kl'),
    city_area_id: null,
    slug: 'batu-caves',
    name: 'Batu Caves',
    place_type: 'activity',
    primary_category_id: did('cat-landmark'),
    lat: 3.2379,
    lng: 101.6840,
    address: 'Gombak, Selangor',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '6am-9pm daily',
    description: 'Stunning Hindu temple inside limestone caves, reached by 272 rainbow steps. Solo women feel safe here—it\'s touristy but respectful. Wear modest clothing (cover shoulders and knees). Watch out for cheeky monkeys.',
    is_active: true,
  },
  {
    id: did('place-kl-petronas-towers'),
    city_id: did('city-kl'),
    city_area_id: did('area-kl-klcc'),
    slug: 'petronas-towers',
    name: 'Petronas Twin Towers Skybridge',
    place_type: 'activity',
    primary_category_id: did('cat-landmark'),
    lat: 3.1578,
    lng: 101.7117,
    address: 'Concourse Level, Tower 2, KLCC, Kuala Lumpur',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '9am-9pm Tue-Sun, closed Mon',
    description: 'Iconic twin towers with skybridge access. Book tickets online in advance—they sell out. Solo women can easily join group tours. The view is breathtaking, and KLCC park below is great for an evening stroll.',
    is_active: true,
  },
  {
    id: did('place-kl-central-market'),
    city_id: did('city-kl'),
    city_area_id: did('area-kl-chinatown'),
    slug: 'central-market',
    name: 'Central Market',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 3.1463,
    lng: 101.6958,
    address: 'Jalan Hang Kasturi, Kuala Lumpur',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '10am-9:30pm daily',
    description: 'Cultural hub for Malaysian crafts, batik, and souvenirs. Clean, air-conditioned, and hassle-free shopping. Solo women can browse comfortably without aggressive vendors. Try a batik painting workshop upstairs.',
    is_active: true,
  },

  // PENANG
  {
    id: did('place-penang-Frame-Guest-House'),
    city_id: did('city-penang'),
    city_area_id: did('area-penang-georgetown'),
    slug: 'frame-guest-house',
    name: 'Frame Guest House',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 5.4164,
    lng: 100.3327,
    address: '212 Chulia Street, George Town, Penang',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '24/7 check-in',
    description: 'Cozy boutique hostel in the heart of George Town with female-only dorms. Super clean, friendly staff, and a great rooftop area. Walking distance to street art and food. Perfect base for solo explorers.',
    is_active: true,
  },
  {
    id: did('place-penang-tek-sen'),
    city_id: did('city-penang'),
    city_area_id: did('area-penang-georgetown'),
    slug: 'tek-sen',
    name: 'Tek Sen Restaurant',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 5.4175,
    lng: 100.3354,
    address: '18 Lebuh Carnarvon, George Town, Penang',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '5:30pm-10pm Tue-Sun, closed Mon',
    description: 'No-frills Chinese restaurant serving some of the best comfort food in Penang. Popular with solo diners and families. The steamed fish, prawns, and tofu dishes are legendary. Expect a wait, but it\'s worth it.',
    is_active: true,
  },
  {
    id: did('place-penang-china-house'),
    city_id: did('city-penang'),
    city_area_id: did('area-penang-georgetown'),
    slug: 'china-house',
    name: 'China House',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 5.4183,
    lng: 100.3359,
    address: '153 & 155 Beach Street, George Town, Penang',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '9am-11pm daily',
    description: 'Sprawling heritage cafe with art gallery vibes. Multiple rooms to explore, each with its own character. Great for solo work sessions with WiFi. The cakes are divine, and there\'s live music some nights.',
    is_active: true,
  },
  {
    id: did('place-penang-street-art-tour'),
    city_id: did('city-penang'),
    city_area_id: did('area-penang-georgetown'),
    slug: 'georgetown-street-art',
    name: 'George Town Street Art Trail',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 5.4141,
    lng: 100.3292,
    address: 'Armenian Street and surrounding areas, George Town, Penang',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Open 24/7',
    description: 'Famous murals by Ernest Zacharevic scattered across George Town. Completely free and solo-friendly—just walk around with a map. Safe during the day, and you\'ll meet tons of other travelers hunting for art.',
    is_active: true,
  },
  {
    id: did('place-penang-yoga-district'),
    city_id: did('city-penang'),
    city_area_id: did('area-penang-georgetown'),
    slug: 'yoga-district',
    name: 'The Yoga District',
    place_type: 'wellness',
    primary_category_id: did('cat-wellness'),
    lat: 5.4190,
    lng: 100.3302,
    address: '80A Lebuh Armenian, George Town, Penang',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Schedule varies, check website',
    description: 'Welcoming yoga studio in a restored shophouse. Drop-in classes available, and the community is friendly to newcomers. Great way for solo women to meet locals and travelers. Mats provided.',
    is_active: true,
  },
  {
    id: did('place-penang-gurney-drive'),
    city_id: did('city-penang'),
    city_area_id: null,
    slug: 'gurney-drive-hawker',
    name: 'Gurney Drive Hawker Centre',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 5.4378,
    lng: 100.3103,
    address: 'Persiaran Gurney, George Town, Penang',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '6pm-2am daily',
    description: 'Legendary seafront hawker center with endless food options. Solo women feel comfortable here—grab a table, order from multiple stalls, and enjoy the sea breeze. Try char kway teow and cendol.',
    is_active: true,
  },

  // LANGKAWI
  {
    id: did('place-langkawi-tubotel'),
    city_id: did('city-langkawi'),
    city_area_id: did('area-langkawi-pantaicenang'),
    slug: 'tubotel',
    name: 'Tubotel',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 6.2888,
    lng: 99.7233,
    address: 'Lot 1221, Jalan Pantai Cenang, Langkawi',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '24/7 check-in',
    description: 'Quirky capsule hotel made from concrete pipes. Clean, modern, and budget-friendly. Solo women appreciate the privacy and security of individual pods. Right near the beach and walking distance to restaurants.',
    is_active: true,
  },
  {
    id: did('place-langkawi-wonderland'),
    city_id: did('city-langkawi'),
    city_area_id: did('area-langkawi-pantaicenang'),
    slug: 'wonderland-food-store',
    name: 'Wonderland Food Store',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 6.2920,
    lng: 99.7246,
    address: 'Jalan Pantai Cenang, Langkawi',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '12pm-10pm daily',
    description: 'Hipster open-air restaurant with Western and Asian fusion. Great for solo dining with communal tables and friendly staff. The burgers are juicy, and the nasi lemak burger is a fun twist. Relaxed vibe.',
    is_active: true,
  },
  {
    id: did('place-langkawi-nest'),
    city_id: did('city-langkawi'),
    city_area_id: did('area-langkawi-pantaicenang'),
    slug: 'nest-rooftop',
    name: 'Nest Rooftop Bar',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 6.2905,
    lng: 99.7241,
    address: 'Jalan Pantai Cenang, Langkawi',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '8am-11pm daily',
    description: 'Beachfront cafe with sunset views and excellent coffee. Solo-friendly atmosphere—grab a book and chill. WiFi is decent for light work. Smoothie bowls and pancakes are Instagram-worthy and delicious.',
    is_active: true,
  },
  {
    id: did('place-langkawi-skycab'),
    city_id: did('city-langkawi'),
    city_area_id: null,
    slug: 'langkawi-skycab',
    name: 'Langkawi SkyCab Cable Car',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 6.3823,
    lng: 99.6634,
    address: 'Oriental Village, Burau Bay, Langkawi',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: '9:30am-6pm daily',
    description: 'Stunning cable car ride to the top of Mount Mat Cincang. Solo women can easily join shared cabins. The views are incredible, and the SkyBridge is thrilling. Go early to beat crowds and heat.',
    is_active: true,
  },
  {
    id: did('place-langkawi-mangrove-tour'),
    city_id: did('city-langkawi'),
    city_area_id: did('area-langkawi-kuah'),
    slug: 'kilim-geopark-mangrove',
    name: 'Kilim Geoforest Park Mangrove Tour',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 6.3964,
    lng: 99.8417,
    address: 'Kilim Jetty, Langkawi',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Tours 9am-5pm daily',
    description: 'Half-day boat tour through mangroves, limestone caves, and eagle feeding. Easy to join as a solo traveler—you\'ll be grouped with others. Guides are friendly and respectful. Don\'t forget sunscreen.',
    is_active: true,
  },

  // MALACCA
  {
    id: did('place-malacca-rucksack-caratel'),
    city_id: did('city-malacca'),
    city_area_id: did('area-malacca-jonkerst'),
    slug: 'rucksack-caratel',
    name: 'Rucksack Caratel',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 2.1953,
    lng: 102.2500,
    address: '108A Jalan Tun Tan Cheng Lock, Melaka',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '24/7 check-in',
    description: 'Charming hostel on heritage Jonker Street. Female dorms available, and the common areas are great for meeting travelers. The location is unbeatable—walk to everything. Staff are super helpful with tips.',
    is_active: true,
  },
  {
    id: did('place-malacca-nancy-kitchen'),
    city_id: did('city-malacca'),
    city_area_id: did('area-malacca-jonkerst'),
    slug: 'nancy-kitchen',
    name: 'Nancy\'s Kitchen',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 2.1989,
    lng: 102.2492,
    address: '13 Jalan KL 3/8, Taman Kota Laksamana, Melaka',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '11am-3pm, 5pm-9pm daily',
    description: 'Famous for authentic Nyonya cuisine in a homey setting. Solo diners are warmly welcomed. Try the ayam pongteh, otak-otak, and cendol. Portions are generous, so order conservatively or share.',
    is_active: true,
  },
  {
    id: did('place-malacca-calanthe-art-cafe'),
    city_id: did('city-malacca'),
    city_area_id: did('area-malacca-jonkerst'),
    slug: 'calanthe-art-cafe',
    name: 'Calanthe Art Cafe',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 2.1965,
    lng: 102.2492,
    address: '93 Jalan Hang Kasturi, Melaka',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '9am-6pm daily',
    description: 'Heritage cafe known for 13 States Coffee—each blend represents a Malaysian state. Cozy, solo-friendly vibe with local art on the walls. Perfect spot to journal and people-watch. Try the kaya toast.',
    is_active: true,
  },
  {
    id: did('place-malacca-dutch-square'),
    city_id: did('city-malacca'),
    city_area_id: did('area-malacca-dutchsquare'),
    slug: 'dutch-square',
    name: 'Dutch Square (Red Square)',
    place_type: 'activity',
    primary_category_id: did('cat-landmark'),
    lat: 2.1945,
    lng: 102.2486,
    address: 'Jalan Gereja, Melaka',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Open 24/7',
    description: 'Iconic red buildings and Christ Church at the heart of Malacca. Solo women can safely explore during the day. Grab a trishaw ride (negotiate price first), visit museums, and enjoy the colonial architecture.',
    is_active: true,
  },
  {
    id: did('place-malacca-river-cruise'),
    city_id: did('city-malacca'),
    city_area_id: did('area-malacca-jonkerst'),
    slug: 'melaka-river-cruise',
    name: 'Melaka River Cruise',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 2.1974,
    lng: 102.2501,
    address: 'Jalan Laksamana, Melaka',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '9am-11pm daily',
    description: '45-minute boat ride along the Melaka River with street art and murals lining the banks. Safe and easy for solo travelers. Evening cruises are magical when the lights come on. Buy tickets at the jetty.',
    is_active: true,
  },
  {
    id: did('place-malacca-jonker-walk'),
    city_id: did('city-malacca'),
    city_area_id: did('area-malacca-jonkerst'),
    slug: 'jonker-walk-night-market',
    name: 'Jonker Walk Night Market',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 2.1965,
    lng: 102.2497,
    address: 'Jalan Hang Jebat, Melaka',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Fri-Sun 6pm-midnight',
    description: 'Weekend street market buzzing with food, crafts, and antiques. Solo women feel safe here—it\'s crowded and lively. Try local snacks like chicken rice balls and durian puffs. Bargain gently for souvenirs.',
    is_active: true,
  },

  // KOTA KINABALU
  {
    id: did('place-kk-akinabalu-youth-hostel'),
    city_id: did('city-kk'),
    city_area_id: did('area-kk-citycenter'),
    slug: 'akinabalu-youth-hostel',
    name: 'Akinabalu Youth Hostel',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 5.9763,
    lng: 116.0750,
    address: '11 Lorong Dewan, Kota Kinabalu',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '24/7 check-in',
    description: 'Clean, modern hostel with female dorms and a social rooftop area. Great base for solo travelers planning Mount Kinabalu treks. Staff can help arrange tours. Walking distance to night market and waterfront.',
    is_active: true,
  },
  {
    id: did('place-kk-welcome-seafood'),
    city_id: did('city-kk'),
    city_area_id: did('area-kk-citycenter'),
    slug: 'welcome-seafood',
    name: 'Welcome Seafood Restaurant',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 5.9788,
    lng: 116.0728,
    address: 'Lot 18, Jalan Tun Fuad Stephens, Sinsuran, Kota Kinabalu',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '12pm-2:30pm, 5pm-10pm daily',
    description: 'Famous for butter prawns and fresh seafood. Solo diners are welcome, though portions are big—consider ordering one dish and rice. Family-friendly atmosphere. Ask for recommendations from the friendly staff.',
    is_active: true,
  },
  {
    id: did('place-kk-kawa-kawa-cafe'),
    city_id: did('city-kk'),
    city_area_id: did('area-kk-gayast'),
    slug: 'kawa-kawa-cafe',
    name: 'Kawa Kawa Cafe',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 5.9803,
    lng: 116.0755,
    address: '29 Jalan Haji Saman, Kota Kinabalu',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '8am-6pm Tue-Sun, closed Mon',
    description: 'Cozy neighborhood cafe with specialty coffee and homemade pastries. Perfect for solo work or reading. WiFi is strong. Try the local Sabah coffee and any of the cakes. Quiet and welcoming vibe.',
    is_active: true,
  },
  {
    id: did('place-kk-tunku-abdul-rahman-park'),
    city_id: did('city-kk'),
    city_area_id: null,
    slug: 'tunku-abdul-rahman-marine-park',
    name: 'Tunku Abdul Rahman Marine Park',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 6.0000,
    lng: 116.0067,
    address: 'Jesselton Point Ferry Terminal, Kota Kinabalu',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Ferries 8am-4pm daily',
    description: 'Five islands perfect for snorkeling and beach lounging, just 15 minutes by boat. Easy to join island-hopping tours as a solo traveler. Manukan and Sapi islands are the most popular. Bring sunscreen.',
    is_active: true,
  },
  {
    id: did('place-kk-filipino-market'),
    city_id: did('city-kk'),
    city_area_id: did('area-kk-citycenter'),
    slug: 'filipino-night-market',
    name: 'Filipino Market (Pasar Malam)',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 5.9806,
    lng: 116.0730,
    address: 'Jalan Tun Fuad Stephens, Kota Kinabalu',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '5pm-11pm daily',
    description: 'Vibrant night market with endless BBQ seafood stalls. Solo women feel safe here—it\'s busy and family-oriented. Bargain for seafood, pick your stall, and they\'ll cook it for you. Try the grilled fish.',
    is_active: true,
  },
  {
    id: did('place-kk-signal-hill'),
    city_id: did('city-kk'),
    city_area_id: did('area-kk-citycenter'),
    slug: 'signal-hill-observatory',
    name: 'Signal Hill Observatory Platform',
    place_type: 'activity',
    primary_category_id: did('cat-landmark'),
    lat: 5.9951,
    lng: 116.0868,
    address: 'Signal Hill, Kota Kinabalu',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Open 24/7',
    description: 'Panoramic viewpoint overlooking KK city and the South China Sea. Safe to visit during the day—it\'s a short drive or Grab ride up. Sunset views are stunning. Bring water and a camera.',
    is_active: true,
  },
];
