import { did } from '../../seed-utils';

export const moroccoPlaces = [
  // MARRAKECH
  {
    id: did('place-marrakech-riad-dar-anika'),
    city_id: did('city-marrakech'),
    city_area_id: did('area-marrakech-medina'),
    slug: 'riad-dar-anika',
    name: 'Riad Dar Anika',
    place_type: 'homestay',
    primary_category_id: did('cat-stay'),
    lat: 31.6295,
    lng: -7.9811,
    address: 'Derb Lalla Aouda 63, Rue Riad Zitoun el-Jdid, Marrakech 40000',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '24/7',
    description: 'Beautiful traditional riad in the medina with a rooftop terrace overlooking the city. The owners are a French-Moroccan couple who make solo travelers feel like family. Breakfast on the terrace is included and they help arrange guides and tours. The location is central but the thick walls keep it peaceful. Felt very safe here as a solo woman—the staff are protective in the best way.',
    is_active: true,
  },
  {
    id: did('place-marrakech-jemaa-el-fnaa'),
    city_id: did('city-marrakech'),
    city_area_id: did('area-marrakech-medina'),
    slug: 'jemaa-el-fnaa',
    name: 'Jemaa el-Fnaa Square',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 31.6259,
    lng: -7.9892,
    address: 'Jemaa el-Fna, Marrakech 40000',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Open 24/7, busiest 5pm-11pm',
    description: 'The beating heart of Marrakech—a UNESCO-recognized square filled with storytellers, snake charmers, orange juice stands, and food stalls at night. It\'s chaotic, loud, and exhilarating. Go during the day first to get oriented, then return at sunset when it transforms. As a solo woman, I stayed aware but felt safe in the crowds. Rooftop cafes around the square offer great views if you need a breather.',
    is_active: true,
  },
  {
    id: did('place-marrakech-nomad-restaurant'),
    city_id: did('city-marrakech'),
    city_area_id: did('area-marrakech-medina'),
    slug: 'nomad-marrakech',
    name: 'Nomad',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 31.6307,
    lng: -7.9874,
    address: '1 Derb Aarjane, Rahba Lakdima, Marrakech 40000',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: 'Daily 12pm-11pm',
    description: 'Modern Moroccan cuisine in a stunning three-story space with a rooftop terrace. The menu is creative—try the cauliflower taktouka or lamb tagine. Solo dining is comfortable here, staff are welcoming and the atmosphere is relaxed. Book ahead for rooftop seating at sunset. A nice break from street food with cocktails and a sophisticated vibe.',
    is_active: true,
  },
  {
    id: did('place-marrakech-cafe-clock'),
    city_id: did('city-marrakech'),
    city_area_id: did('area-marrakech-kasbah'),
    slug: 'cafe-clock-marrakech',
    name: 'Café Clock',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 31.6215,
    lng: -7.9903,
    address: '224 Derb Chtouka, Kasbah, Marrakech 40000',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 9am-10pm',
    description: 'Cultural cafe near Bahia Palace known for its camel burger (yes, really) and storytelling nights. The vibe is backpacker-friendly and social—great for solo travelers. They host Arabic lessons, cooking classes, and live music. WiFi, good coffee, and a shaded courtyard. Friendly staff and a welcoming space to meet other travelers.',
    is_active: true,
  },
  {
    id: did('place-marrakech-jardin-majorelle'),
    city_id: did('city-marrakech'),
    city_area_id: did('area-marrakech-gueliz'),
    slug: 'jardin-majorelle',
    name: 'Jardin Majorelle',
    place_type: 'landmark',
    primary_category_id: did('cat-activity'),
    lat: 31.6411,
    lng: -8.0034,
    address: 'Rue Yves Saint Laurent, Marrakech 40000',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 8am-6pm',
    description: 'Stunning garden created by French painter Jacques Majorelle and later owned by Yves Saint Laurent. The vibrant blue buildings and exotic plants are incredibly photogenic. Book tickets online to skip lines—go early morning for fewer crowds. A peaceful escape from the medina. Solo visit is lovely, though watch your belongings. The on-site cafe is overpriced but the garden is worth it.',
    is_active: true,
  },
  {
    id: did('place-marrakech-souk-semmarine'),
    city_id: did('city-marrakech'),
    city_area_id: did('area-marrakech-medina'),
    slug: 'souk-semmarine',
    name: 'Souk Semmarine',
    place_type: 'shop',
    primary_category_id: did('cat-activity'),
    lat: 31.6276,
    lng: -7.9893,
    address: 'Souk Semmarine, Medina, Marrakech 40000',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 9am-8pm',
    description: 'The main covered market in the medina with endless stalls selling leather, textiles, lanterns, spices, and more. Haggling is expected—start at 50% of asking price. It\'s overwhelming at first but thrilling. As a solo woman, I dressed modestly and walked with purpose. Vendors can be pushy but a firm "no thank you" works. Hire a guide your first time if you\'re nervous.',
    is_active: true,
  },
  {
    id: did('place-marrakech-koutoubia-mosque'),
    city_id: did('city-marrakech'),
    city_area_id: did('area-marrakech-medina'),
    slug: 'koutoubia-mosque',
    name: 'Koutoubia Mosque',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 31.6249,
    lng: -7.9933,
    address: 'Rue el Ksour, Marrakech 40000',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Exterior viewable 24/7, not open to non-Muslims',
    description: 'Marrakech\'s largest mosque with an iconic 77-meter minaret visible across the city. Non-Muslims cannot enter, but the exterior and surrounding gardens are beautiful. Visit at sunset when the call to prayer echoes. The area is safe and peaceful—great for a solo stroll. The gardens are a nice spot to rest and take photos.',
    is_active: true,
  },
  {
    id: did('place-marrakech-le-jardin'),
    city_id: did('city-marrakech'),
    city_area_id: did('area-marrakech-medina'),
    slug: 'le-jardin-marrakech',
    name: 'Le Jardin',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 31.6324,
    lng: -7.9890,
    address: '32 Souk Jeld Sidi Abdelaziz, Medina, Marrakech 40000',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 9am-11pm',
    description: 'Hidden oasis in the medina with a lush garden, koi pond, and modern Moroccan menu. The setting is peaceful and romantic, even for solo diners. Try the chicken pastilla or vegetable tagine. Great spot for lunch after souk shopping. WiFi available and English-speaking staff. A calm refuge with reasonable prices for the quality.',
    is_active: true,
  },

  // FES
  {
    id: did('place-fes-riad-rcif'),
    city_id: did('city-fes'),
    city_area_id: did('area-fes-fesbali'),
    slug: 'riad-rcif',
    name: 'Riad Rcif',
    place_type: 'homestay',
    primary_category_id: did('cat-stay'),
    lat: 34.0639,
    lng: -4.9748,
    address: '36-37 Derb Bechara, Douh, Fes 30000',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '24/7',
    description: 'Charming family-run riad in the heart of the Fes medina. The rooftop terrace has sweeping views and the hospitality is exceptional. Hicham (the owner) is incredibly helpful arranging guides and giving recommendations. Solo travelers get personal attention here. Rooms are simple but clean. The location means you\'re close to everything but can also get lost in the maze—they\'ll walk you out the first time.',
    is_active: true,
  },
  {
    id: did('place-fes-chouara-tannery'),
    city_id: did('city-fes'),
    city_area_id: did('area-fes-fesbali'),
    slug: 'chouara-tannery',
    name: 'Chouara Tannery',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 34.0655,
    lng: -4.9732,
    address: 'Hay Lablida Chouara, Fes 30110',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 9am-6pm',
    description: 'The famous leather tanneries where hides are dyed in colorful stone wells—a centuries-old process. View from surrounding leather shop terraces (they\'ll offer you mint to mask the smell). It\'s a tourist magnet but genuinely fascinating. Shop owners can be pushy about buying, but a polite decline works. Go mid-morning for best light. As a solo woman, having a guide helps navigate the attention.',
    is_active: true,
  },
  {
    id: did('place-fes-cafe-clock-fes'),
    city_id: did('city-fes'),
    city_area_id: did('area-fes-fesbali'),
    slug: 'cafe-clock-fes',
    name: 'Café Clock Fes',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 34.0612,
    lng: -4.9788,
    address: '7 Derb el Magana, Talaa Kebira, Fes 30110',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 9am-10pm',
    description: 'Sister location to Marrakech\'s Café Clock with the same welcoming vibe. Famous for camel burger, Moroccan fusion dishes, and cultural events like storytelling nights and cooking classes. The courtyard is beautiful and WiFi is solid. Solo travelers gather here—easy to meet people or enjoy solo time. Staff are lovely and it feels like a safe haven in the medina.',
    is_active: true,
  },
  {
    id: did('place-fes-bou-inania-madrasa'),
    city_id: did('city-fes'),
    city_area_id: did('area-fes-fesbali'),
    slug: 'bou-inania-madrasa',
    name: 'Bou Inania Madrasa',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 34.0631,
    lng: -4.9764,
    address: 'Rue Talaa Kebira, Fes 30110',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 9am-5pm',
    description: 'Stunning 14th-century Islamic school with intricate tilework, carved cedar, and marble. It\'s one of the few religious sites in Fes open to non-Muslims. The architecture is breathtaking. Entry fee is small. Visit in the morning for softer light and fewer crowds. Easy solo visit—peaceful and contemplative. Dress modestly out of respect.',
    is_active: true,
  },
  {
    id: did('place-fes-nejjarine-museum'),
    city_id: did('city-fes'),
    city_area_id: did('area-fes-fesbali'),
    slug: 'nejjarine-museum',
    name: 'Nejjarine Museum of Wood Arts & Crafts',
    place_type: 'landmark',
    primary_category_id: did('cat-activity'),
    lat: 34.0641,
    lng: -4.9757,
    address: 'Pl. Nejjarine, Fes 30110',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 10am-5pm',
    description: 'Beautiful museum in a restored funduq (caravanserai) showcasing Moroccan woodworking. The building itself is the main attraction—intricate tilework and a stunning courtyard. The rooftop cafe offers medina views. Small but well-curated. Perfect solo activity—quiet, educational, and a nice escape from the medina hustle. Entry includes tea on the roof.',
    is_active: true,
  },
  {
    id: did('place-fes-ruined-garden'),
    city_id: did('city-fes'),
    city_area_id: did('area-fes-fesbali'),
    slug: 'ruined-garden',
    name: 'The Ruined Garden',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 34.0647,
    lng: -4.9741,
    address: '15 Derb Idrissy, Sidi Ahmed Chaoui, Fes 30000',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 10am-10pm',
    description: 'Enchanting garden restaurant in a restored riad with lush plants, fairy lights, and Moroccan-Mediterranean fusion food. The atmosphere is magical, especially at night. Solo diners are common and welcomed. Try the mezze platter or tagine. Reservations recommended for dinner. A romantic spot even when you\'re alone—bring a book and linger over mint tea.',
    is_active: true,
  },
  {
    id: did('place-fes-fes-cooking-class'),
    city_id: did('city-fes'),
    city_area_id: did('area-fes-villenovelle'),
    slug: 'fes-cooking-class',
    name: 'Fes Cooking Workshop',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 34.0331,
    lng: -5.0003,
    address: 'Various locations, book via Cafe Clock or riads',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: 'Classes typically 10am-2pm',
    description: 'Half-day cooking classes where you shop at the souk with a chef, then cook traditional Moroccan dishes. Learn to make tagine, couscous, and pastries. Classes are small and interactive—perfect for solo travelers. You eat what you cook and take recipes home. Book through Café Clock or your riad. A highlight of my Fes trip and a great way to meet people.',
    is_active: true,
  },
  {
    id: did('place-fes-jnan-sbil-gardens'),
    city_id: did('city-fes'),
    city_area_id: did('area-fes-villenovelle'),
    slug: 'jnan-sbil-gardens',
    name: 'Jnan Sbil Gardens',
    place_type: 'landmark',
    primary_category_id: did('cat-activity'),
    lat: 34.0583,
    lng: -4.9889,
    address: 'Avenue Moulay Hassan, Fes 30000',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 8am-6pm',
    description: 'Peaceful public gardens between the old and new cities with fountains, walking paths, and shaded benches. Free entry. A lovely spot to decompress after the intensity of the medina. Popular with local families, especially on weekends. Safe for solo strolling—bring a book and find a quiet corner. The greenery is a welcome contrast to the city\'s ochre tones.',
    is_active: true,
  },

  // CHEFCHAOUEN
  {
    id: did('place-chefchaouen-dar-echchaouen'),
    city_id: did('city-chefchaouen'),
    city_area_id: did('area-chefchaouen-medina'),
    slug: 'dar-echchaouen',
    name: 'Dar Echchaouen',
    place_type: 'homestay',
    primary_category_id: did('cat-stay'),
    lat: 35.1711,
    lng: -5.2686,
    address: '28 Targui, Chefchaouen 91000',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '24/7',
    description: 'Charming guesthouse with blue walls (of course) and a rooftop terrace overlooking the medina and mountains. The owner is welcoming and gives great hiking recommendations. Breakfast is homemade and delicious. Perfect for solo travelers—small, intimate, and safe. The medina is tiny so you can\'t get lost. Chefchaouen is Morocco\'s most relaxed city—perfect if Marrakech or Fes felt overwhelming.',
    is_active: true,
  },
  {
    id: did('place-chefchaouen-plaza-uta-el-hammam'),
    city_id: did('city-chefchaouen'),
    city_area_id: did('area-chefchaouen-plaza'),
    slug: 'plaza-uta-el-hammam',
    name: 'Plaza Uta el-Hammam',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 35.1698,
    lng: -5.2688,
    address: 'Place Outa el Hammam, Chefchaouen 91000',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Open 24/7',
    description: 'The heart of Chefchaouen with cafes, orange trees, and the kasbah. It\'s the perfect spot to people-watch with a fresh orange juice or mint tea. The vibe is laid-back and friendly. Solo travelers gather here naturally. Evenings are magical when locals and tourists mix. Felt incredibly safe—Chefchaouen is known for being welcoming to solo women.',
    is_active: true,
  },
  {
    id: did('place-chefchaouen-cafe-clock-chef'),
    city_id: did('city-chefchaouen'),
    city_area_id: did('area-chefchaouen-medina'),
    slug: 'cafe-clock-chefchaouen',
    name: 'Café Clock Chefchaouen',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 35.1705,
    lng: -5.2679,
    address: 'Derb Ben Seffaj 7, Chefchaouen 91000',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 9am-10pm',
    description: 'Third outpost of the beloved Café Clock brand. Same great vibe—cultural events, good food (camel burger!), and a social atmosphere perfect for solo travelers. The terrace overlooks the blue streets. WiFi works well. Locals and travelers mix easily here. Try the Moroccan breakfast or linger over coffee and plan your day.',
    is_active: true,
  },
  {
    id: did('place-chefchaouen-ras-el-maa'),
    city_id: did('city-chefchaouen'),
    city_area_id: did('area-chefchaouen-medina'),
    slug: 'ras-el-maa-waterfall',
    name: 'Ras el-Maa Waterfall',
    place_type: 'landmark',
    primary_category_id: did('cat-activity'),
    lat: 35.1724,
    lng: -5.2651,
    address: 'Ras el-Maa, Chefchaouen 91000',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Open 24/7',
    description: 'Small waterfall at the edge of the medina where locals wash clothes and rugs. It\'s not dramatic, but the setting is picturesque—rushing water, blue buildings, and mountain views. Walk the path uphill for even better vistas. Great for a solo morning walk. Locals are friendly and used to tourists. Continue up for a hike to the Spanish Mosque for sunset.',
    is_active: true,
  },
  {
    id: did('place-chefchaouen-spanish-mosque'),
    city_id: did('city-chefchaouen'),
    city_area_id: null,
    slug: 'spanish-mosque',
    name: 'Spanish Mosque Viewpoint',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 35.1755,
    lng: -5.2657,
    address: 'Hill southeast of medina, Chefchaouen 91000',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Open 24/7',
    description: 'Abandoned mosque on a hill with panoramic views of Chefchaouen\'s blue medina and the Rif Mountains. The 30-minute hike from town is moderate—wear good shoes. Sunset is the best time (though it gets crowded). Solo hiking felt safe during the day—lots of other tourists and locals. The views are stunning and worth the climb. Bring water.',
    is_active: true,
  },
  {
    id: did('place-chefchaouen-restaurant-beldi-bab-ssour'),
    city_id: did('city-chefchaouen'),
    city_area_id: did('area-chefchaouen-medina'),
    slug: 'restaurant-beldi-bab-ssour',
    name: 'Restaurant Beldi Bab Ssour',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 35.1689,
    lng: -5.2694,
    address: 'Rue Bab Ssour, Chefchaouen 91000',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 12pm-10pm',
    description: 'Traditional Moroccan restaurant with a rooftop terrace and mountain views. The tagines are excellent and portions are generous. Solo diners are welcome—grab a rooftop table and enjoy the breeze. Service is warm and unhurried. Prices are reasonable. A great spot for a relaxed solo dinner after a day of exploring and photographing blue streets.',
    is_active: true,
  },
  {
    id: did('place-chefchaouen-akchour-waterfalls'),
    city_id: did('city-chefchaouen'),
    city_area_id: null,
    slug: 'akchour-waterfalls',
    name: 'Akchour Waterfalls',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 35.1253,
    lng: -5.1689,
    address: 'Akchour, 30km from Chefchaouen',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daylight hours',
    description: 'Stunning waterfall hike in the Rif Mountains, 30km from Chefchaouen. Most visitors do a day trip—hire a taxi (negotiate price) or join a group tour. The hike to the small falls is easy (45 min), to God\'s Bridge is moderate (2-3 hours). Solo hikers should go with a guide or group for safety. The scenery is spectacular and a nice contrast to city exploring.',
    is_active: true,
  },
  {
    id: did('place-chefchaouen-sophia-cafe'),
    city_id: did('city-chefchaouen'),
    city_area_id: did('area-chefchaouen-plaza'),
    slug: 'cafe-restaurant-sophia',
    name: 'Café Restaurant Sophia',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 35.1701,
    lng: -5.2683,
    address: 'Avenue Hassan II, Chefchaouen 91000',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 8am-11pm',
    description: 'Simple cafe on the main plaza with outdoor seating perfect for people-watching. Great fresh orange juice, coffee, and Moroccan breakfast. The staff are friendly and used to solo travelers. WiFi is decent. It\'s a good spot to journal, plan your day, or just soak in the mellow Chefchaouen vibe. Very affordable and no pressure to order much.',
    is_active: true,
  },
];
