import { did } from '../../seed-utils';

export const mozambiquePlaces = [
  // MAPUTO
  {
    id: did('place-maputo-mercado-central'),
    city_id: did('city-maputo'),
    city_area_id: did('area-maputo-baixa'),
    slug: 'mercado-central-maputo',
    name: 'Mercado Central',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: -25.9690,
    lng: 32.5720,
    address: 'Avenida 25 de Setembro, Baixa, Maputo',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Mon-Sat 6am-5pm, Sun 6am-12pm',
    description: 'Maputo\'s central market is a sprawling, sensory experience — spices, cashews, capulana fabric, and fresh produce packed under a Portuguese-era iron roof. Vendors are friendly and prices are low. Keep belongings close in the crowds and go early for the best energy.',
    is_active: true,
  },
  {
    id: did('place-maputo-cafe-acacia'),
    city_id: did('city-maputo'),
    city_area_id: did('area-maputo-polana'),
    slug: 'cafe-acacia-maputo',
    name: 'Cafe Acacia',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: -25.9650,
    lng: 32.5750,
    address: 'Polana District, Maputo',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 7am-6pm',
    description: 'A calm, leafy cafe in the Polana neighbourhood with strong espresso, fresh pastries, and reliable WiFi. The shaded terrace draws Maputo\'s creative crowd and remote workers. A welcome pause from the city\'s heat and pace.',
    is_active: true,
  },
  {
    id: did('place-maputo-special-reserve'),
    city_id: did('city-maputo'),
    city_area_id: did('area-maputo-baixa'),
    slug: 'maputo-special-reserve',
    name: 'Maputo Special Reserve',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: -26.3900,
    lng: 32.6500,
    address: 'Maputo Special Reserve, Maputo Province',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 6am-6pm',
    description: 'A coastal reserve south of the city with elephants, flamingos, and pristine beaches accessible by 4x4. The park is undergoing steady rehabilitation and wildlife sightings are improving each year. Day trips from Maputo are feasible with an early start.',
    is_active: true,
  },
  {
    id: did('place-maputo-polana-serena'),
    city_id: did('city-maputo'),
    city_area_id: did('area-maputo-polana'),
    slug: 'polana-serena-hotel',
    name: 'Polana Serena Hotel',
    place_type: 'hotel',
    primary_category_id: did('cat-stay'),
    lat: -25.9620,
    lng: 32.5840,
    address: 'Avenida Julius Nyerere 1380, Maputo',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: '24/7',
    description: 'Maputo\'s grand dame — a 1922 heritage hotel with high ceilings, ocean views, and impeccable service. The pool terrace overlooks the Indian Ocean and the bar draws diplomats and locals alike. A refined anchor point for solo travelers in a city that rewards slow exploration.',
    is_active: true,
  },

  // TOFO
  {
    id: did('place-tofo-fatimas-nest'),
    city_id: did('city-tofo'),
    city_area_id: did('area-tofo-beachfront'),
    slug: 'fatimas-nest-tofo',
    name: 'Fatima\'s Nest',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: -23.7540,
    lng: 35.5400,
    address: 'Praia do Tofo, Inhambane Province',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '24/7',
    description: 'A backpacker institution right on Tofo beach with dorms, en-suite cabanas, and a social bar that fills up nightly. The dive shop on-site makes ocean excursions effortless. Solo travelers meet each other here within the first hour.',
    is_active: true,
  },
  {
    id: did('place-tofo-whale-shark-dive'),
    city_id: did('city-tofo'),
    city_area_id: did('area-tofo-beachfront'),
    slug: 'tofo-whale-shark-dive',
    name: 'Tofo Whale Shark Dive',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: -23.7550,
    lng: 35.5420,
    address: 'Praia do Tofo, Inhambane Province',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Morning departures, typically 7am',
    description: 'Tofo is one of the world\'s most reliable spots to swim with whale sharks year-round. Local dive operators run morning ocean safaris — snorkelling with these gentle giants is a life-list experience. Mantas and dolphins are frequent bonuses.',
    is_active: true,
  },
  {
    id: did('place-tofo-dinos-beach-bar'),
    city_id: did('city-tofo'),
    city_area_id: did('area-tofo-beachfront'),
    slug: 'dinos-beach-bar',
    name: 'Dino\'s Beach Bar',
    place_type: 'bar',
    primary_category_id: did('cat-nightlife'),
    lat: -23.7535,
    lng: 35.5410,
    address: 'Praia do Tofo, Inhambane Province',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 10am-late',
    description: 'A barefoot beach bar with plastic chairs in the sand, cold 2M beers, and a playlist that matches the pace of the tides. The crowd is a mix of surfers, divers, and long-term travelers. Unpretentious in the best possible way.',
    is_active: true,
  },
  {
    id: did('place-tofo-casa-barry'),
    city_id: did('city-tofo'),
    city_area_id: did('area-tofo-beachfront'),
    slug: 'casa-barry-lodge',
    name: 'Casa Barry Lodge',
    place_type: 'hotel',
    primary_category_id: did('cat-stay'),
    lat: -23.7545,
    lng: 35.5405,
    address: 'Praia do Tofo, Inhambane Province',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '24/7',
    description: 'A well-run mid-range lodge steps from the beach with clean rooms, a pool, and an on-site restaurant serving fresh seafood. The atmosphere is quieter than the backpacker spots but still sociable. A solid choice for solo travelers who want comfort without isolation.',
    is_active: true,
  },

  // BAZARUTO
  {
    id: did('place-bazaruto-snorkeling'),
    city_id: did('city-bazaruto'),
    city_area_id: did('area-bazaruto-island'),
    slug: 'bazaruto-island-snorkeling',
    name: 'Bazaruto Island Snorkeling',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: -21.6500,
    lng: 35.4830,
    address: 'Bazaruto Archipelago, Inhambane Province',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Morning departures by arrangement',
    description: 'The archipelago\'s coral reefs are among the best-preserved in the western Indian Ocean, with visibility regularly exceeding 20 meters. Dugongs, sea turtles, and tropical reef fish are common. Excursions are typically arranged through island lodges.',
    is_active: true,
  },
  {
    id: did('place-bazaruto-anantara'),
    city_id: did('city-bazaruto'),
    city_area_id: did('area-bazaruto-island'),
    slug: 'anantara-bazaruto',
    name: 'Anantara Bazaruto',
    place_type: 'hotel',
    primary_category_id: did('cat-stay'),
    lat: -21.5390,
    lng: 35.4710,
    address: 'Bazaruto Island, Inhambane Province',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: '24/7',
    description: 'A luxury island resort with private villas, a spa, and direct beach access on one of Mozambique\'s most pristine islands. The remoteness is the point — no roads, no crowds, just turquoise water and sand dunes. Transfers are by helicopter or boat from Vilankulo.',
    is_active: true,
  },
];
