import { did } from '../../seed-utils';

export const myanmarPlaces = [
  // BAGAN
  {
    id: did('place-bagan-ostello-bello'),
    city_id: did('city-bagan'),
    city_area_id: did('area-bagan-nyaungu'),
    slug: 'ostello-bello-bagan',
    name: 'Ostello Bello Bagan',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 21.1729,
    lng: 94.9065,
    address: 'Nyaung U, Bagan',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '24/7 check-in',
    description: 'Social hostel with pool, rooftop bar, and female dorms. Great for solo travelers wanting to meet people. Staff organize e-bike rentals and sunrise temple tours. Free pasta dinners and happy hour.',
    is_active: true,
  },
  {
    id: did('place-bagan-star-beam'),
    city_id: did('city-bagan'),
    city_area_id: did('area-bagan-nyaungu'),
    slug: 'star-beam-restaurant',
    name: 'Star Beam Rooftop Restaurant',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 21.1735,
    lng: 94.9071,
    address: 'Main Road, Nyaung U, Bagan',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '6am-10pm daily',
    description: 'Rooftop restaurant with temple views and traditional Burmese food. Solo diners are welcomed warmly. Try the tea leaf salad, curry sets, and fresh lime juice. Sunset views are stunning.',
    is_active: true,
  },
  {
    id: did('place-bagan-moon-vegetarian'),
    city_id: did('city-bagan'),
    city_area_id: did('area-bagan-oldbagan'),
    slug: 'moon-vegetarian',
    name: 'Moon Vegetarian Restaurant',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 21.1695,
    lng: 94.8589,
    address: 'Old Bagan',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '7am-9pm daily',
    description: 'Simple vegetarian spot with fresh Burmese dishes. Solo-friendly and affordable. Try the vegetable curry, noodle soup, and sweet tea. Perfect for a quick, healthy meal after temple hopping.',
    is_active: true,
  },
  {
    id: did('place-bagan-weather-spoon'),
    city_id: did('city-bagan'),
    city_area_id: did('area-bagan-nyaungu'),
    slug: 'weather-spoon-cafe',
    name: 'The Moon Be Kind Cafe',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 21.1740,
    lng: 94.9068,
    address: 'Nyaung U, Bagan',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '7am-8pm daily',
    description: 'Cozy cafe with WiFi, iced coffee, and smoothie bowls. Popular with digital nomads and solo travelers. Great for a midday break. The avocado toast and banana pancakes are delicious.',
    is_active: true,
  },
  {
    id: did('place-bagan-temples'),
    city_id: did('city-bagan'),
    city_area_id: did('area-bagan-oldbagan'),
    slug: 'bagan-temples',
    name: 'Bagan Archaeological Zone',
    place_type: 'activity',
    primary_category_id: did('cat-landmark'),
    lat: 21.1717,
    lng: 94.8578,
    address: 'Bagan',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: '6am-6pm daily',
    description: 'Over 2,000 ancient Buddhist temples scattered across the plains. Solo women can easily rent an e-bike and explore independently. Sunrise and sunset are magical. Bring sun protection and water.',
    is_active: true,
  },
  {
    id: did('place-bagan-hot-air-balloon'),
    city_id: did('city-bagan'),
    city_area_id: null,
    slug: 'bagan-balloon',
    name: 'Balloons Over Bagan',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 21.1700,
    lng: 94.8600,
    address: 'Bagan',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 4,
    hours_text: 'Sunrise flights daily (seasonal)',
    description: 'Iconic sunrise hot air balloon ride over the temples. Expensive but unforgettable. Solo travelers are grouped with others. Book well in advance—this is a bucket-list experience. Operates Oct-March.',
    is_active: true,
  },
  {
    id: did('place-bagan-cooking-class'),
    city_id: did('city-bagan'),
    city_area_id: did('area-bagan-nyaungu'),
    slug: 'bagan-cooking-class',
    name: 'Bagan Cooking Class',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 21.1728,
    lng: 94.9070,
    address: 'Nyaung U, Bagan',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Classes 9am and 3pm daily',
    description: 'Half-day cooking class learning to make traditional Burmese dishes. Solo travelers join small groups. Visit a local market, then cook and eat together. Fun, social, and delicious.',
    is_active: true,
  },

  // YANGON
  {
    id: did('place-yangon-little-yangon-hostel'),
    city_id: did('city-yangon'),
    city_area_id: did('area-yangon-downtown'),
    slug: 'little-yangon-hostel',
    name: 'Little Yangon Hostel',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 16.7794,
    lng: 96.1496,
    address: '67 Sule Pagoda Road, Yangon',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '24/7 check-in',
    description: 'Centrally located hostel with female dorms and a rooftop bar. Clean, safe, and social. Walking distance to Sule Pagoda and downtown markets. Staff help arrange tours and transport.',
    is_active: true,
  },
  {
    id: did('place-yangon-rangoon-tea-house'),
    city_id: did('city-yangon'),
    city_area_id: did('area-yangon-downtown'),
    slug: 'rangoon-tea-house',
    name: 'Rangoon Tea House',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 16.7888,
    lng: 96.1535,
    address: '77-79 Pansodan Street, Yangon',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '7am-10pm daily',
    description: 'Modern take on traditional Burmese tea house culture. Solo diners love the contemporary vibe and delicious food. Try the tea leaf salad, mohinga, and sweet tea. Reservations recommended for dinner.',
    is_active: true,
  },
  {
    id: did('place-yangon-999-shan-noodle'),
    city_id: did('city-yangon'),
    city_area_id: did('area-yangon-downtown'),
    slug: '999-shan-noodle',
    name: '999 Shan Noodle House',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 16.7855,
    lng: 96.1521,
    address: '130B 34th Street, Yangon',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '6am-3pm daily',
    description: 'Famous for Shan-style noodles in a no-frills setting. Solo diners fit right in at communal tables. Order the noodle soup or dry noodles with chicken. Filling and authentic.',
    is_active: true,
  },
  {
    id: did('place-yangon-cafe-unlock'),
    city_id: did('city-yangon'),
    city_area_id: did('area-yangon-downtown'),
    slug: 'cafe-unlock',
    name: 'Unlock Cafe & Bar',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 16.7879,
    lng: 96.1528,
    address: '41 Pansodan Street, Yangon',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '8am-10pm daily',
    description: 'Hip cafe in a colonial building with strong WiFi and specialty coffee. Perfect for solo work or reading. The brunch menu is excellent. Turns into a bar at night with craft cocktails.',
    is_active: true,
  },
  {
    id: did('place-yangon-shwedagon-pagoda'),
    city_id: did('city-yangon'),
    city_area_id: did('area-yangon-shwedagon'),
    slug: 'shwedagon-pagoda',
    name: 'Shwedagon Pagoda',
    place_type: 'activity',
    primary_category_id: did('cat-landmark'),
    lat: 16.7982,
    lng: 96.1498,
    address: 'Yangon',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '4am-10pm daily',
    description: 'Myanmar\'s most sacred Buddhist site—a stunning golden pagoda. Solo women can explore safely. Dress modestly and remove shoes. Sunset is the best time to visit when the gold glows. Peaceful and awe-inspiring.',
    is_active: true,
  },
  {
    id: did('place-yangon-bogyoke-market'),
    city_id: did('city-yangon'),
    city_area_id: did('area-yangon-downtown'),
    slug: 'bogyoke-aung-san-market',
    name: 'Bogyoke Aung San Market',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 16.7788,
    lng: 96.1525,
    address: 'Bogyoke Aung San Road, Yangon',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '9am-5pm Tue-Sun, closed Mon',
    description: 'Colonial-era covered market selling gems, textiles, handicrafts, and souvenirs. Safe for solo women during the day. Bargain gently. Great for picking up longyi (traditional skirts) and jade jewelry.',
    is_active: true,
  },
  {
    id: did('place-yangon-chinatown-night-market'),
    city_id: did('city-yangon'),
    city_area_id: did('area-yangon-chinatown'),
    slug: 'yangon-chinatown',
    name: 'Chinatown Night Market',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 16.7758,
    lng: 96.1448,
    address: '19th Street, Yangon',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '6pm-11pm daily',
    description: 'Bustling street food scene with BBQ, noodles, and seafood. Solo women feel safe here—it\'s crowded and lively. Grab a plastic stool and order from multiple stalls. Try the grilled squid and Myanmar beer.',
    is_active: true,
  },

  // INLE LAKE
  {
    id: did('place-inlelake-ostello-bello-inle'),
    city_id: did('city-inlelake'),
    city_area_id: did('area-inlelake-nyaungshwe'),
    slug: 'ostello-bello-inle',
    name: 'Ostello Bello Inle Lake',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 20.5479,
    lng: 96.9090,
    address: 'Yone Gyi Road, Nyaung Shwe',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '24/7 check-in',
    description: 'Lakefront hostel with female dorms, pool, and free dinners. Social atmosphere perfect for solo travelers. Bike rentals available to explore Nyaung Shwe. Staff organize boat tours of Inle Lake.',
    is_active: true,
  },
  {
    id: did('place-inlelake-viewpoint-lodge'),
    city_id: did('city-inlelake'),
    city_area_id: did('area-inlelake-nyaungshwe'),
    slug: 'viewpoint-lodge-restaurant',
    name: 'Viewpoint Lodge & Restaurant',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 20.5515,
    lng: 96.9087,
    address: 'Phaung Daw Pyan Road, Nyaung Shwe',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '7am-10pm daily',
    description: 'Rooftop restaurant with lake views and Shan cuisine. Solo diners enjoy the peaceful setting. Try Shan noodles, tofu dishes, and fresh fish from the lake. Sunset views are beautiful.',
    is_active: true,
  },
  {
    id: did('place-inlelake-unique-superb-food'),
    city_id: did('city-inlelake'),
    city_area_id: did('area-inlelake-nyaungshwe'),
    slug: 'unique-superb-food',
    name: 'Unique Superb Food House',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 20.5482,
    lng: 96.9092,
    address: 'Yone Gyi Road, Nyaung Shwe',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '7am-10pm daily',
    description: 'Local favorite with massive portions and friendly service. Solo travelers love the communal vibe. Try the Shan-style rice, stir-fried veggies, and avocado salad. Filling and satisfying.',
    is_active: true,
  },
  {
    id: did('place-inlelake-kayah-cafe'),
    city_id: did('city-inlelake'),
    city_area_id: did('area-inlelake-nyaungshwe'),
    slug: 'kayah-cafe',
    name: 'Kayah Cafe',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 20.5490,
    lng: 96.9095,
    address: 'Yone Gyi Road, Nyaung Shwe',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '7am-8pm daily',
    description: 'Charming cafe with local coffee, smoothies, and breakfast. Solo-friendly with WiFi and a garden. Great for a quiet morning before boat tours. The pancakes and fruit salads are fresh.',
    is_active: true,
  },
  {
    id: did('place-inlelake-boat-tour'),
    city_id: did('city-inlelake'),
    city_area_id: did('area-inlelake-lake'),
    slug: 'inle-lake-boat-tour',
    name: 'Inle Lake Boat Tour',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 20.5500,
    lng: 96.9100,
    address: 'Inle Lake',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Tours 8am-5pm daily',
    description: 'Full-day boat tour visiting floating gardens, leg-rowing fishermen, and stilt-house villages. Solo travelers join group boats or hire private. See Phaung Daw Oo Pagoda and traditional workshops. Unforgettable.',
    is_active: true,
  },
  {
    id: did('place-inlelake-red-mountain-vineyard'),
    city_id: did('city-inlelake'),
    city_area_id: null,
    slug: 'red-mountain-vineyard',
    name: 'Red Mountain Estate Vineyards & Winery',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 20.5800,
    lng: 96.9000,
    address: 'Red Mountain, Inle Lake',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: '10am-6pm daily',
    description: 'Hillside vineyard with wine tasting and stunning valley views. Solo women can easily visit by bike or taxi. Try the Sauvignon Blanc and cheese platter. A unique Myanmar experience.',
    is_active: true,
  },
  {
    id: did('place-inlelake-indein-pagodas'),
    city_id: did('city-inlelake'),
    city_area_id: did('area-inlelake-lake'),
    slug: 'indein-pagodas',
    name: 'Indein Village & Pagodas',
    place_type: 'activity',
    primary_category_id: did('cat-landmark'),
    lat: 20.4833,
    lng: 96.7833,
    address: 'Indein Village, Inle Lake',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '8am-5pm daily',
    description: 'Ancient ruins of hundreds of overgrown stupas on a hilltop. Reach by boat from Nyaung Shwe. Solo women feel safe exploring. Climb the covered stairway for panoramic views. Mystical and peaceful.',
    is_active: true,
  },
];
