import { did } from '../../seed-utils';

export const namibiaPlaces = [
  // WINDHOEK
  {
    id: did('place-windhoek-joes-beerhouse'),
    city_id: did('city-windhoek'),
    city_area_id: did('area-windhoek-center'),
    slug: 'joes-beerhouse',
    name: 'Joe\'s Beerhouse',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: -22.5697,
    lng: 17.0795,
    address: '160 Nelson Mandela Avenue, Windhoek',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Mon-Sat 11am-11pm, Sun 11am-3pm',
    description: 'A Windhoek institution with eclectic outdoor seating under a canopy of trees and salvaged decor. The game meat platter is the move — oryx, kudu, and springbok grilled over open flame. Solo diners are common and the atmosphere is convivial without being rowdy.',
    is_active: true,
  },
  {
    id: did('place-windhoek-christuskirche'),
    city_id: did('city-windhoek'),
    city_area_id: did('area-windhoek-center'),
    slug: 'christuskirche',
    name: 'Christuskirche',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: -22.5715,
    lng: 17.0843,
    address: 'Robert Mugabe Avenue, Windhoek',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Exterior viewable 24/7',
    description: 'A striking neo-Gothic church built in 1910 that stands as Windhoek\'s most recognizable landmark. The stained glass interior is worth a look if the doors are open, and the hilltop position offers wide views over the parliamentary gardens and city center.',
    is_active: true,
  },
  {
    id: did('place-windhoek-craft-centre'),
    city_id: did('city-windhoek'),
    city_area_id: did('area-windhoek-center'),
    slug: 'craft-centre-namibia',
    name: 'Craft Centre Namibia',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: -22.5700,
    lng: 17.0850,
    address: '40 Tal Street, Windhoek',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Mon-Fri 9am-5:30pm, Sat 9am-1pm',
    description: 'A curated cooperative of Namibian artisans selling handwoven baskets, Herero dolls, and San-inspired jewellery. Quality is high, prices are fair, and the artists are often on-site — a far better souvenir stop than the tourist shops near the airport.',
    is_active: true,
  },
  {
    id: did('place-windhoek-hilton'),
    city_id: did('city-windhoek'),
    city_area_id: did('area-windhoek-kleinwindhoek'),
    slug: 'hilton-windhoek',
    name: 'Hilton Windhoek',
    place_type: 'hotel',
    primary_category_id: did('cat-stay'),
    lat: -22.5650,
    lng: 17.0810,
    address: 'Rev. Michael Scott Street, Windhoek',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: '24/7',
    description: 'The city\'s most reliable upscale hotel with a rooftop pool, solid restaurant, and central location. Rooms are modern and well-maintained. A dependable base for solo travelers arriving late or departing early for Sossusvlei or Etosha.',
    is_active: true,
  },

  // SOSSUSVLEI
  {
    id: did('place-sossusvlei-dune45'),
    city_id: did('city-sossusvlei'),
    city_area_id: did('area-sossusvlei-dunearea'),
    slug: 'dune-45-sunrise-climb',
    name: 'Dune 45 Sunrise Climb',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: -24.7330,
    lng: 15.4750,
    address: 'Dune 45, Namib-Naukluft National Park',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Gates open at sunrise',
    description: 'The most accessible of the great dunes — a 170-meter climb rewarded with sweeping views of apricot-colored sand ridges at first light. Leave before dawn to catch the gates opening and reach the crest as the sun breaks. The descent is half the time and twice the fun.',
    is_active: true,
  },
  {
    id: did('place-sossusvlei-deadvlei'),
    city_id: did('city-sossusvlei'),
    city_area_id: did('area-sossusvlei-dunearea'),
    slug: 'deadvlei',
    name: 'Deadvlei',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: -24.7592,
    lng: 15.2936,
    address: 'Deadvlei, Namib-Naukluft National Park',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Gates open at sunrise, last entry varies',
    description: 'A surreal white clay pan ringed by 300-meter dunes and scattered with 900-year-old skeleton trees. The contrast of bleached earth, black trunks, and orange sand is one of the most photographed landscapes on the continent. Arrive early to beat the midday heat.',
    is_active: true,
  },
  {
    id: did('place-sossusvlei-lodge'),
    city_id: did('city-sossusvlei'),
    city_area_id: did('area-sossusvlei-dunearea'),
    slug: 'sossusvlei-lodge',
    name: 'Sossusvlei Lodge',
    place_type: 'hotel',
    primary_category_id: did('cat-stay'),
    lat: -24.7510,
    lng: 15.8790,
    address: 'C19, Sesriem, Namib-Naukluft Park',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: '24/7',
    description: 'Located just outside the park gates with air-conditioned rooms, a pool, and desert views in every direction. The proximity to Sesriem means early access to the dunes. Stargazing from the terrace is extraordinary — minimal light pollution for hundreds of kilometres.',
    is_active: true,
  },
  {
    id: did('place-sossusvlei-sesriem-canyon'),
    city_id: did('city-sossusvlei'),
    city_area_id: did('area-sossusvlei-dunearea'),
    slug: 'sesriem-canyon',
    name: 'Sesriem Canyon',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: -24.4848,
    lng: 15.8196,
    address: 'Sesriem, Namib-Naukluft National Park',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daylight hours',
    description: 'A narrow slot canyon carved over millions of years by the Tsauchab River, reaching 30 meters deep in places. The short walk to the canyon floor is manageable in sturdy shoes. Best visited in late afternoon when the light angles into the rock walls.',
    is_active: true,
  },

  // SWAKOPMUND
  {
    id: did('place-swakopmund-tug-restaurant'),
    city_id: did('city-swakopmund'),
    city_area_id: did('area-swakopmund-waterfront'),
    slug: 'the-tug-restaurant',
    name: 'The Tug Restaurant',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: -22.6783,
    lng: 14.5273,
    address: 'Strand Street, Waterfront, Swakopmund',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 12pm-10pm',
    description: 'Built around a beached tugboat on the Swakopmund waterfront, this is the town\'s go-to for fresh Atlantic seafood. The oysters are sourced from Walvis Bay and the setting — waves breaking against the glass — is hard to match. Solo bar seating is comfortable.',
    is_active: true,
  },
  {
    id: did('place-swakopmund-sandboarding'),
    city_id: did('city-swakopmund'),
    city_area_id: did('area-swakopmund-center'),
    slug: 'sandboarding-namib-desert',
    name: 'Sandboarding Namib Desert',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: -22.6500,
    lng: 14.5000,
    address: 'Namib dunes, outside Swakopmund',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Morning departures, typically 8am',
    description: 'Half-day tours take you to the dune fields outside town for stand-up or lie-down sandboarding. Speeds on the lie-down boards reach 80 km/h — genuinely exhilarating. Operators provide all equipment and transport. Solo bookings are easy and groups are small.',
    is_active: true,
  },
  {
    id: did('place-swakopmund-jetty'),
    city_id: did('city-swakopmund'),
    city_area_id: did('area-swakopmund-waterfront'),
    slug: 'swakopmund-jetty',
    name: 'Swakopmund Jetty',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: -22.6780,
    lng: 14.5260,
    address: 'Strand Street, Swakopmund',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Open 24/7',
    description: 'A restored 1905 iron jetty stretching into the Atlantic, now one of Swakopmund\'s most recognizable silhouettes. The walk to the end is meditative, especially at dusk when the fog rolls in and the town\'s German colonial architecture fades into mist.',
    is_active: true,
  },
  {
    id: did('place-swakopmund-desert-breeze'),
    city_id: did('city-swakopmund'),
    city_area_id: did('area-swakopmund-center'),
    slug: 'desert-breeze-lodge',
    name: 'Desert Breeze Lodge',
    place_type: 'hotel',
    primary_category_id: did('cat-stay'),
    lat: -22.6890,
    lng: 14.5490,
    address: 'Corner of Nordring & Anton Lubowski Avenue, Swakopmund',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '24/7',
    description: 'A boutique guesthouse on the edge of town with individually designed rooms and a courtyard garden sheltered from the coastal wind. The breakfast spread is generous and the owners are a reliable source of local recommendations.',
    is_active: true,
  },
];
