import { did } from '../../seed-utils';

export const philippinesPlaces = [
  // EL NIDO
  {
    id: did('place-elnido-spin-designer'),
    city_id: did('city-elnido'),
    city_area_id: did('area-elnido-town'),
    slug: 'spin-designer-hostel',
    name: 'Spin Designer Hostel',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 11.1918,
    lng: 119.4012,
    address: 'Calle Hama, El Nido, Palawan',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '24 hours',
    description: 'Social hostel with rooftop bar and nightly events. Solo female travelers rave about the friendly vibe and easy-to-join island hopping tours.',
    is_active: true,
  },
  {
    id: did('place-elnido-artcafe'),
    city_id: did('city-elnido'),
    city_area_id: did('area-elnido-town'),
    slug: 'artcafe',
    name: 'ARTCAFE',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 11.1934,
    lng: 119.4023,
    address: 'Serena St, El Nido',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 6am-11pm',
    description: 'Beloved beachfront restaurant with Mediterranean-Filipino fusion. Perfect for solo dinner—grab a table with sunset views and excellent people-watching.',
    is_active: true,
  },
  {
    id: did('place-elnido-trattoria-altrove'),
    city_id: did('city-elnido'),
    city_area_id: did('area-elnido-town'),
    slug: 'trattoria-altrove',
    name: 'Trattoria Altrove',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 11.1925,
    lng: 119.4018,
    address: 'Hama St, El Nido',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 11am-11pm',
    description: 'Authentic Italian pizza in a cozy garden setting. Counter seating makes solo dining comfortable, and the wood-fired pizzas are worth the wait.',
    is_active: true,
  },
  {
    id: did('place-elnido-happiness-beach'),
    city_id: did('city-elnido'),
    city_area_id: did('area-elnido-town'),
    slug: 'happiness-beach-bar',
    name: 'Happiness Beach Bar',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 11.1928,
    lng: 119.4025,
    address: 'Calle Real, El Nido',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 7am-10pm',
    description: 'Beachfront cafe with strong coffee and healthy breakfast bowls. Solo-friendly communal tables and a chill reggae soundtrack.',
    is_active: true,
  },
  {
    id: did('place-elnido-tour-a'),
    city_id: did('city-elnido'),
    city_area_id: did('area-elnido-town'),
    slug: 'island-hopping-tour-a',
    name: 'El Nido Island Hopping Tour A',
    place_type: 'tour',
    primary_category_id: did('cat-activity'),
    lat: 11.1932,
    lng: 119.4020,
    address: 'El Nido tourism office, El Nido',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 9am-5pm',
    description: 'Classic lagoon tour including Big Lagoon and Secret Lagoon. Solo travelers easily join group boats—shared kayaking and swimming make fast friends.',
    is_active: true,
  },
  {
    id: did('place-elnido-nacpan-beach'),
    city_id: did('city-elnido'),
    city_area_id: did('area-elnido-nacpan'),
    slug: 'nacpan-beach',
    name: 'Nacpan Beach',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 11.2512,
    lng: 119.4523,
    address: 'Bucana, El Nido, Palawan',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 24 hours',
    description: 'Four-kilometer pristine white sand beach backed by palm trees. Rent a scooter to get here solo—safe, stunning, and far from the crowds.',
    is_active: true,
  },
  {
    id: did('place-elnido-corong-corong'),
    city_id: did('city-elnido'),
    city_area_id: did('area-elnido-corong'),
    slug: 'corong-corong-beach',
    name: 'Corong Corong Beach',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 11.1856,
    lng: 119.3989,
    address: 'Corong-Corong, El Nido',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 24 hours',
    description: 'Quieter alternative to the main beach with shallow turquoise water. Perfect for solo sunset walks and peaceful swimming.',
    is_active: true,
  },

  // SIARGAO
  {
    id: did('place-siargao-nay-palad'),
    city_id: did('city-siargao'),
    city_area_id: did('area-siargao-generalluna'),
    slug: 'nay-palad-hideaway',
    name: 'Nay Palad Hideaway',
    place_type: 'hotel',
    primary_category_id: did('cat-stay'),
    lat: 9.8123,
    lng: 126.1534,
    address: 'Union, General Luna, Siargao',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: '24 hours',
    description: 'Boutique jungle resort with wellness focus and gorgeous pool. Solo travelers find community through yoga classes and shared dinners.',
    is_active: true,
  },
  {
    id: did('place-siargao-bravo'),
    city_id: did('city-siargao'),
    city_area_id: did('area-siargao-generalluna'),
    slug: 'bravo-beach-resort',
    name: 'Bravo Beach Resort',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 9.8089,
    lng: 126.1512,
    address: 'Tourism Rd, General Luna',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 7am-10pm',
    description: 'Beachfront restaurant with fresh seafood and Filipino favorites. Solo-friendly atmosphere where surfers swap stories over sunset beers.',
    is_active: true,
  },
  {
    id: did('place-siargao-kermit'),
    city_id: did('city-siargao'),
    city_area_id: did('area-siargao-generalluna'),
    slug: 'kermit-siargao',
    name: 'Kermit Siargao',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 9.8078,
    lng: 126.1489,
    address: 'General Luna, Siargao',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 11am-11pm',
    description: 'Famous wood-fired pizza and gelato spot with a lively garden atmosphere. Easy to share a table and make friends—Siargao\'s social hub.',
    is_active: true,
  },
  {
    id: did('place-siargao-shaka'),
    city_id: did('city-siargao'),
    city_area_id: did('area-siargao-generalluna'),
    slug: 'shaka-cafe',
    name: 'Shaka Cafe',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 9.8067,
    lng: 126.1478,
    address: 'Tourism Rd, General Luna',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 6am-10pm',
    description: 'Iconic siargao cafe with smoothie bowls and coconut lattes. The long communal table is where solo travelers meet their island crew.',
    is_active: true,
  },
  {
    id: did('place-siargao-cloud9'),
    city_id: did('city-siargao'),
    city_area_id: did('area-siargao-cloud9'),
    slug: 'cloud-9-boardwalk',
    name: 'Cloud 9 Boardwalk',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 9.8345,
    lng: 126.1756,
    address: 'Cloud 9, General Luna',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 24 hours',
    description: 'World-famous surf break with a wooden pier for watching surfers. Safe solo spot to soak in the surf culture—grab a coconut and enjoy the show.',
    is_active: true,
  },
  {
    id: did('place-siargao-sugba-lagoon'),
    city_id: did('city-siargao'),
    city_area_id: null,
    slug: 'sugba-lagoon',
    name: 'Sugba Lagoon',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 9.9123,
    lng: 126.0834,
    address: 'Del Carmen, Siargao',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 8am-4pm',
    description: 'Crystal-clear lagoon with paddleboarding and cliff jumping. Join a group tour as a solo traveler—shared boat rides make it easy to connect.',
    is_active: true,
  },
  {
    id: did('place-siargao-naked-island'),
    city_id: did('city-siargao'),
    city_area_id: null,
    slug: 'naked-island',
    name: 'Naked Island',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 9.7623,
    lng: 126.1123,
    address: 'Pilar, Siargao',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 9am-4pm',
    description: 'Tiny sandbar island on the island hopping tour circuit. Pure white sand, turquoise water, and nothing else—an unforgettable solo adventure moment.',
    is_active: true,
  },
  {
    id: did('place-siargao-jungle'),
    city_id: did('city-siargao'),
    city_area_id: did('area-siargao-generalluna'),
    slug: 'jungle-party-hostel',
    name: 'Jungle Party Hostel',
    place_type: 'hostel',
    primary_category_id: did('cat-nightlife'),
    lat: 9.8056,
    lng: 126.1467,
    address: 'General Luna, Siargao',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 24 hours',
    description: 'Legendary party hostel with Wednesday night raves and pool parties. Solo travelers bond over epic nights—safe, social, and unforgettable.',
    is_active: true,
  },

  // CEBU
  {
    id: did('place-cebu-radisson-blu'),
    city_id: did('city-cebu'),
    city_area_id: did('area-cebu-city'),
    slug: 'radisson-blu-cebu',
    name: 'Radisson Blu Cebu',
    place_type: 'hotel',
    primary_category_id: did('cat-stay'),
    lat: 10.3156,
    lng: 123.8934,
    address: 'Serging Osmena Blvd, Cebu City',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: '24 hours',
    description: 'Modern business hotel with rooftop pool and excellent security. Solo women appreciate the central location and professional service.',
    is_active: true,
  },
  {
    id: did('place-cebu-anzani'),
    city_id: did('city-cebu'),
    city_area_id: did('area-cebu-city'),
    slug: 'anzani',
    name: 'Anzani New Mediterranean Cuisine',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 10.3401,
    lng: 123.9123,
    address: 'Nivel Hills, Lahug, Cebu City',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: 'Daily 11am-2pm, 6pm-10pm',
    description: 'Upscale Mediterranean restaurant with stunning hilltop views. The bar seating is perfect for solo fine dining with a view of the city lights.',
    is_active: true,
  },
  {
    id: did('place-cebu-bo-coffee'),
    city_id: did('city-cebu'),
    city_area_id: did('area-cebu-city'),
    slug: 'bo-s-coffee',
    name: "Bo\'s Coffee",
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 10.3178,
    lng: 123.8945,
    address: 'IT Park, Cebu City',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 7am-10pm',
    description: 'Filipino coffee chain with reliable wifi and comfortable seating. IT Park branch is popular with solo digital nomads working remote.',
    is_active: true,
  },
  {
    id: did('place-cebu-oslob-whale-sharks'),
    city_id: did('city-cebu'),
    city_area_id: did('area-cebu-oslob'),
    slug: 'oslob-whale-sharks',
    name: 'Oslob Whale Shark Watching',
    place_type: 'tour',
    primary_category_id: did('cat-activity'),
    lat: 9.4789,
    lng: 123.3912,
    address: 'Tan-awan, Oslob, Cebu',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 6am-12pm',
    description: 'Swim with gentle whale sharks in crystal water. Book a solo tour package from Cebu City—guides ensure safety and it\'s a bucket-list experience.',
    is_active: true,
  },
  {
    id: did('place-cebu-kawasan-falls'),
    city_id: did('city-cebu'),
    city_area_id: null,
    slug: 'kawasan-falls',
    name: 'Kawasan Falls',
    place_type: 'landmark',
    primary_category_id: did('cat-activity'),
    lat: 9.8234,
    lng: 123.3745,
    address: 'Badian, Cebu',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 6am-5pm',
    description: 'Turquoise waterfall paradise with bamboo rafting and cliff jumping. Join a guided canyoneering tour for safety—thrilling solo adventure.',
    is_active: true,
  },
  {
    id: did('place-cebu-tops-lookout'),
    city_id: did('city-cebu'),
    city_area_id: did('area-cebu-city'),
    slug: 'tops-lookout',
    name: 'Tops Lookout',
    place_type: 'landmark',
    primary_category_id: did('cat-activity'),
    lat: 10.3523,
    lng: 123.9234,
    address: 'Busay Hills, Cebu City',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 24 hours',
    description: 'Mountain viewpoint with panoramic city and ocean views. Take a Grab up for sunset as a solo traveler—safe and absolutely worth the ride.',
    is_active: true,
  },
  {
    id: did('place-cebu-malapascua'),
    city_id: did('city-cebu'),
    city_area_id: null,
    slug: 'malapascua-island',
    name: 'Malapascua Island',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 11.3345,
    lng: 124.1123,
    address: 'Daanbantayan, Cebu',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 24 hours',
    description: 'Small diving island famous for thresher sharks. Solo divers find a tight-knit community and safe, professional dive operators.',
    is_active: true,
  },

  // MANILA
  {
    id: did('place-manila-peninsula'),
    city_id: did('city-manila'),
    city_area_id: did('area-manila-makati'),
    slug: 'peninsula-manila',
    name: 'The Peninsula Manila',
    place_type: 'hotel',
    primary_category_id: did('cat-stay'),
    lat: 14.5567,
    lng: 121.0234,
    address: 'Ayala Ave, Makati, Manila',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 4,
    hours_text: '24 hours',
    description: 'Luxury hotel with impeccable service and central Makati location. Solo women travelers appreciate the top-tier security and professional staff.',
    is_active: true,
  },
  {
    id: did('place-manila-toyo-eatery'),
    city_id: did('city-manila'),
    city_area_id: did('area-manila-makati'),
    slug: 'toyo-eatery',
    name: 'Toyo Eatery',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 14.5589,
    lng: 121.0289,
    address: 'The Alley at Karrivin, Makati',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: 'Tue-Sun 12pm-3pm, 6pm-10pm',
    description: 'Acclaimed Filipino restaurant with innovative tasting menus. Counter seating puts solo diners in conversation with the passionate kitchen team.',
    is_active: true,
  },
  {
    id: did('place-manila-comune'),
    city_id: did('city-manila'),
    city_area_id: did('area-manila-bgc'),
    slug: 'comune',
    name: 'Comune',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 14.5512,
    lng: 121.0467,
    address: 'Bonifacio High Street, BGC',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 7am-11pm',
    description: 'Italian cafe with excellent coffee and pasta. BGC location is safe and walkable—perfect for solo work sessions or people-watching.',
    is_active: true,
  },
  {
    id: did('place-manila-intramuros'),
    city_id: did('city-manila'),
    city_area_id: did('area-manila-intramuros'),
    slug: 'intramuros-walled-city',
    name: 'Intramuros Walled City',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 14.5898,
    lng: 120.9745,
    address: 'Intramuros, Manila',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 8am-6pm',
    description: 'Spanish colonial walled city with cobblestone streets and churches. Join a walking tour as a solo traveler—safe, fascinating history lesson.',
    is_active: true,
  },
  {
    id: did('place-manila-poblacion'),
    city_id: did('city-manila'),
    city_area_id: did('area-manila-poblacion'),
    slug: 'poblacion-nightlife',
    name: 'Poblacion Nightlife District',
    place_type: 'landmark',
    primary_category_id: did('cat-nightlife'),
    lat: 14.5634,
    lng: 121.0178,
    address: 'Poblacion, Makati',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 6pm-3am',
    description: 'Hip neighborhood with craft cocktail bars and late-night eats. Solo women feel comfortable bar-hopping here—lively but safe, stick to main streets.',
    is_active: true,
  },
  {
    id: did('place-manila-bgc-art-walk'),
    city_id: did('city-manila'),
    city_area_id: did('area-manila-bgc'),
    slug: 'bgc-art-walk',
    name: 'BGC Arts Center',
    place_type: 'landmark',
    primary_category_id: did('cat-activity'),
    lat: 14.5489,
    lng: 121.0512,
    address: '8th Ave, Bonifacio Global City',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 10am-8pm',
    description: 'Modern arts district with galleries and outdoor installations. Safe solo wandering through BGC\'s most creative corner—great for afternoon exploration.',
    is_active: true,
  },

  // BOHOL
  {
    id: did('place-bohol-amorita'),
    city_id: did('city-bohol'),
    city_area_id: did('area-bohol-panglao'),
    slug: 'amorita-resort',
    name: 'Amorita Resort',
    place_type: 'hotel',
    primary_category_id: did('cat-stay'),
    lat: 9.5789,
    lng: 123.7912,
    address: 'Panglao Island, Bohol',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: '24 hours',
    description: 'Cliffside resort with infinity pool overlooking the ocean. Solo travelers love the intimate vibe and easy access to dive shops.',
    is_active: true,
  },
  {
    id: did('place-bohol-bohol-bee-farm'),
    city_id: did('city-bohol'),
    city_area_id: did('area-bohol-panglao'),
    slug: 'bohol-bee-farm',
    name: 'Bohol Bee Farm',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 9.5456,
    lng: 123.7823,
    address: 'Panglao Island, Bohol',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 7am-8pm',
    description: 'Organic farm-to-table restaurant with ocean views and homemade ice cream. Solo diners enjoy the peaceful garden setting and healthy Filipino cuisine.',
    is_active: true,
  },
  {
    id: did('place-bohol-chocolate-hills'),
    city_id: did('city-bohol'),
    city_area_id: null,
    slug: 'chocolate-hills',
    name: 'Chocolate Hills',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 9.7951,
    lng: 124.1693,
    address: 'Carmen, Bohol',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 6am-6pm',
    description: 'Iconic geological formations with over 1,000 cone-shaped hills. Join a countryside tour as a solo traveler—safe, scenic, and utterly unique.',
    is_active: true,
  },
  {
    id: did('place-bohol-tarsier-sanctuary'),
    city_id: did('city-bohol'),
    city_area_id: null,
    slug: 'tarsier-sanctuary',
    name: 'Philippine Tarsier Sanctuary',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 9.6834,
    lng: 124.0512,
    address: 'Corella, Bohol',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 9am-4pm',
    description: 'Conservation area protecting tiny, bug-eyed tarsiers. Peaceful self-guided trails make it easy for solo nature lovers—adorable and educational.',
    is_active: true,
  },
  {
    id: did('place-bohol-balicasag'),
    city_id: did('city-bohol'),
    city_area_id: did('area-bohol-panglao'),
    slug: 'balicasag-island',
    name: 'Balicasag Island',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 9.5145,
    lng: 123.6834,
    address: 'Panglao, Bohol',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 8am-4pm',
    description: 'World-class diving and snorkeling with sea turtles and vibrant reefs. Join an island hopping tour—solo travelers bond over underwater magic.',
    is_active: true,
  },
  {
    id: did('place-bohol-loboc-river'),
    city_id: did('city-bohol'),
    city_area_id: null,
    slug: 'loboc-river-cruise',
    name: 'Loboc River Cruise',
    place_type: 'tour',
    primary_category_id: did('cat-activity'),
    lat: 9.6389,
    lng: 124.0312,
    address: 'Loboc, Bohol',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 10am-3pm',
    description: 'Floating restaurant cruise through lush jungle scenery with live music. Solo travelers enjoy the buffet and sing-alongs—quintessential Bohol experience.',
    is_active: true,
  },
  {
    id: did('place-bohol-alona-beach'),
    city_id: did('city-bohol'),
    city_area_id: did('area-bohol-panglao'),
    slug: 'alona-beach',
    name: 'Alona Beach',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 9.5234,
    lng: 123.7456,
    address: 'Panglao Island, Bohol',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 24 hours',
    description: 'White sand beach lined with dive shops and restaurants. Solo-friendly vibe with easy access to island hopping and nightlife—Bohol\'s social hub.',
    is_active: true,
  },
  {
    id: did('place-bohol-anda-beach'),
    city_id: did('city-bohol'),
    city_area_id: null,
    slug: 'anda-beach',
    name: 'Anda Beach',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 9.7389,
    lng: 124.5623,
    address: 'Anda, Bohol',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 24 hours',
    description: 'Remote white sand beach away from tourist crowds. Peaceful solo escape with excellent snorkeling and a handful of quiet resorts.',
    is_active: true,
  },
];
