import { did } from '../../seed-utils';

export const portugalPlaces = [
  // LISBON
  {
    id: did('place-lisbon-the-independente'),
    city_id: did('city-lisbon'),
    city_area_id: did('area-lisbon-bairroalto'),
    slug: 'the-independente-hostel',
    name: 'The Independente Hostel & Suites',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 38.7169,
    lng: -9.1467,
    address: 'R. de São Pedro de Alcântara 81, 1250-238 Lisboa',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '24/7',
    description: 'Gorgeous hostel in a 19th-century building with a rooftop bar offering stunning sunset views over Lisbon. The social atmosphere is perfect for solo travelers—daily events, communal dinners, and a welcoming international crowd. Female dorms available. Located in Bairro Alto, you\'re in the heart of the action but the hostel itself feels like a calm retreat.',
    is_active: true,
  },
  {
    id: did('place-lisbon-timeout-market'),
    city_id: did('city-lisbon'),
    city_area_id: null,
    slug: 'timeout-market',
    name: 'Time Out Market Lisboa',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 38.7067,
    lng: -9.1459,
    address: 'Av. 24 de Julho 49, 1200-479 Lisboa',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Sun-Wed 10am-12am, Thu-Sat 10am-2am',
    description: 'Curated food hall featuring Lisbon\'s top chefs and restaurants all under one roof. Perfect for solo diners—grab what you want, find communal seating, people-watch. Try the pastel de nata, seafood rice, or bifana. Lively but safe atmosphere. Great spot to meet other travelers or just enjoy quality food without the pressure of a formal restaurant.',
    is_active: true,
  },
  {
    id: did('place-lisbon-fabrica-coffee'),
    city_id: did('city-lisbon'),
    city_area_id: did('area-lisbon-baixa'),
    slug: 'fabrica-coffee-roasters',
    name: 'Fábrica Coffee Roasters',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 38.7115,
    lng: -9.1392,
    address: 'R. das Portas de Santo Antão 136, 1150-269 Lisboa',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Mon-Fri 8:30am-6pm, Sat-Sun 9:30am-6pm',
    description: 'Industrial-chic cafe with exposed brick, long communal tables, and some of the best coffee in Lisbon. The vibe is relaxed and laptop-friendly. Baristas are passionate about their craft and happy to chat. Solo-friendly with a mix of locals and digital nomads. The avocado toast is excellent if you need more than caffeine.',
    is_active: true,
  },
  {
    id: did('place-lisbon-tram-28'),
    city_id: did('city-lisbon'),
    city_area_id: null,
    slug: 'tram-28-ride',
    name: 'Tram 28 Ride',
    place_type: 'landmark',
    primary_category_id: did('cat-activity'),
    lat: 38.7145,
    lng: -9.1334,
    address: 'Various stops across Alfama, Graça, Baixa, Estrela',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 6am-9pm',
    description: 'Iconic yellow tram that winds through Lisbon\'s historic neighborhoods. It\'s touristy but genuinely fun and practical. Board early morning to avoid crowds and actually get a seat. Watch for pickpockets in high season—keep your bag close. As a solo rider, sit on the right side for best views. The route covers Alfama, Graça, and more—a scenic way to get oriented.',
    is_active: true,
  },
  {
    id: did('place-lisbon-alfama-district'),
    city_id: did('city-lisbon'),
    city_area_id: did('area-lisbon-alfama'),
    slug: 'alfama-district',
    name: 'Alfama District',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 38.7135,
    lng: -9.1288,
    address: 'Alfama, Lisboa',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Open 24/7',
    description: 'Lisbon\'s oldest neighborhood with narrow cobblestone streets, colorful tiles, and fado music drifting from restaurants. Get lost wandering—that\'s the point. Visit during the day to explore churches and viewpoints, evening for fado. Solo exploration feels safe, locals are friendly, and there\'s always someone around. Wear comfortable shoes for the hills.',
    is_active: true,
  },
  {
    id: did('place-lisbon-cervejaria-ramiro'),
    city_id: did('city-lisbon'),
    city_area_id: null,
    slug: 'cervejaria-ramiro',
    name: 'Cervejaria Ramiro',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 38.7359,
    lng: -9.1334,
    address: 'Av. Almirante Reis 1 H, 1150-007 Lisboa',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: 'Tue-Sun 12pm-12am, Closed Mon',
    description: 'Legendary seafood spot famous for giant prawns, clams, and lobster. Yes, there\'s a queue, but it moves. Counter seating works well for solo diners—order the garlic prawns and a beer. The atmosphere is buzzing and communal. Staff are efficient and used to tourists. A bit pricey but worth the splurge for the freshest seafood in Lisbon.',
    is_active: true,
  },
  {
    id: did('place-lisbon-lx-factory'),
    city_id: did('city-lisbon'),
    city_area_id: null,
    slug: 'lx-factory',
    name: 'LX Factory',
    place_type: 'coworking',
    primary_category_id: did('cat-activity'),
    lat: 38.7028,
    lng: -9.1772,
    address: 'R. Rodrigues de Faria 103, 1300-501 Lisboa',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Mon-Sat 10am-11pm, Sun 10am-8pm',
    description: 'Former industrial complex turned creative village with bookstores, boutiques, street art, cafes, and coworking spaces. Perfect for a solo afternoon of exploring—very Instagrammable. Ler Devagar bookstore is a must-see. The Sunday market has vintage finds. Safe, artsy, and filled with other solo wanderers and digital nomads.',
    is_active: true,
  },
  {
    id: did('place-lisbon-belem-tower'),
    city_id: did('city-lisbon'),
    city_area_id: did('area-lisbon-belem'),
    slug: 'belem-tower',
    name: 'Belém Tower',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 38.6916,
    lng: -9.2160,
    address: 'Av. Brasília, 1400-038 Lisboa',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Tue-Sun 10am-5:30pm, Closed Mon',
    description: 'Iconic 16th-century fortress on the Tagus River, a UNESCO World Heritage Site. Book tickets online to skip the line. The interior is small but the views from the top are worth it. Combine with nearby Jerónimos Monastery and the famous pastel de nata at Pastéis de Belém. Easy solo visit—well-organized and safe.',
    is_active: true,
  },

  // PORTO
  {
    id: did('place-porto-selina-hostel'),
    city_id: did('city-porto'),
    city_area_id: did('area-porto-ribeira'),
    slug: 'selina-porto',
    name: 'Selina Porto',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 41.1419,
    lng: -8.6149,
    address: 'Praça da Ribeira 6, 4050-513 Porto',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '24/7',
    description: 'Modern hostel right on the Ribeira waterfront with coworking, yoga classes, and a lively bar. The community vibe is strong—easy to meet other solo travelers at events or communal meals. Mix of dorms and private rooms. Female dorms available. The location is unbeatable, though it can get loud on weekends.',
    is_active: true,
  },
  {
    id: did('place-porto-mercado-do-bolhao'),
    city_id: did('city-porto'),
    city_area_id: null,
    slug: 'mercado-do-bolhao',
    name: 'Mercado do Bolhão',
    place_type: 'shop',
    primary_category_id: did('cat-eat'),
    lat: 41.1477,
    lng: -8.6066,
    address: 'R. Formosa, 4000-214 Porto',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Mon-Sat 8am-8pm, Closed Sun',
    description: 'Beautifully renovated two-story market with fresh produce, flowers, and food stalls. Grab lunch upstairs at one of the traditional Portuguese spots—try francesinha or grilled sardines. The vendors are chatty and proud of their products. Great for solo exploring and grazing. Authentic local atmosphere without being intimidating.',
    is_active: true,
  },
  {
    id: did('place-porto-claus-coffee'),
    city_id: did('city-porto'),
    city_area_id: did('area-porto-cedofeita'),
    slug: 'claus-porto-coffee',
    name: 'Claus Porto Coffee',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 41.1524,
    lng: -8.6269,
    address: 'R. do Rosário 277, 4050-521 Porto',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Mon-Fri 9am-7pm, Sat-Sun 10am-7pm',
    description: 'Cozy cafe in the Cedofeita neighborhood with specialty coffee and homemade cakes. The vibe is warm and welcoming—part coffee shop, part community hub. Great wifi and a quiet upstairs area for working. Solo-friendly with regulars who\'ll chat if you\'re open to it. A peaceful contrast to the tourist bustle of Ribeira.',
    is_active: true,
  },
  {
    id: did('place-porto-livraria-lello'),
    city_id: did('city-porto'),
    city_area_id: null,
    slug: 'livraria-lello',
    name: 'Livraria Lello',
    place_type: 'shop',
    primary_category_id: did('cat-landmark'),
    lat: 41.1469,
    lng: -8.6147,
    address: 'R. das Carmelitas 144, 4050-161 Porto',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 9:30am-7pm',
    description: 'One of the world\'s most beautiful bookstores with a stunning red staircase (said to inspire Harry Potter). You need a timed ticket—book online. It\'s touristy and crowded, but the architecture is breathtaking. Go early for fewer people. Solo visit is easy—just wander, take photos, maybe buy a book. The €5 ticket is redeemable against purchases.',
    is_active: true,
  },
  {
    id: did('place-porto-douro-river-cruise'),
    city_id: did('city-porto'),
    city_area_id: did('area-porto-ribeira'),
    slug: 'douro-river-cruise',
    name: 'Douro River Cruise',
    place_type: 'tour',
    primary_category_id: did('cat-activity'),
    lat: 41.1404,
    lng: -8.6139,
    address: 'Departing from Ribeira docks, 4050 Porto',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily departures 10am-6pm',
    description: 'Scenic boat ride under Porto\'s iconic bridges and along the Douro Valley. The 50-minute "Six Bridges" cruise is perfect for solo travelers—affordable, no awkward group dynamics, just relax and enjoy the views. Book directly at the docks or online. Sunset cruises are romantic even solo. Felt totally comfortable as a solo woman.',
    is_active: true,
  },
  {
    id: did('place-porto-cantina-32'),
    city_id: did('city-porto'),
    city_area_id: null,
    slug: 'cantina-32',
    name: 'Cantina 32',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 41.1459,
    lng: -8.6089,
    address: 'Rua das Flores 32, 4050-262 Porto',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 12pm-11pm',
    description: 'Modern Portuguese cuisine in a casual, buzzing space on Rua das Flores. The octopus and duck rice are standouts. Counter seating available for solo diners. Staff are friendly and the atmosphere is laid-back. Reservations recommended for dinner. Great wine selection if you want to treat yourself to a nice solo meal.',
    is_active: true,
  },
  {
    id: did('place-porto-cafe-candelabro'),
    city_id: did('city-porto'),
    city_area_id: null,
    slug: 'cafe-candelabro',
    name: 'Café Candelabro',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 41.1557,
    lng: -8.6298,
    address: 'Rua da Conceição 95, 4050-200 Porto',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Mon-Thu 10am-12am, Fri-Sat 10am-2am, Sun 10am-10pm',
    description: 'Quirky cafe-bar with vintage decor, plants everywhere, and a bohemian vibe. Great coffee by day, cocktails and craft beer by night. The crowd is artsy and international. Perfect for solo hangs—bring a book or journal, or chat with the bartender. Live music some nights. Located in a quieter neighborhood away from tourist hordes.',
    is_active: true,
  },
  {
    id: did('place-porto-clerigos-tower'),
    city_id: did('city-porto'),
    city_area_id: null,
    slug: 'clerigos-tower',
    name: 'Clérigos Tower',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 41.1456,
    lng: -8.6142,
    address: 'R. de São Filipe de Nery, 4050-546 Porto',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 9am-7pm',
    description: 'Baroque bell tower with 225 steps leading to panoramic views of Porto. The climb is steep but manageable—take breaks. Buy tickets online to skip the line. The church itself is beautiful too. Easy solo visit and the views from the top are the best in the city. Go late afternoon for golden hour light.',
    is_active: true,
  },
];
