import { did } from '../../seed-utils';

export const singaporePlaces = [
  {
    id: did('place-sg-capsule-pod-boutique'),
    city_id: did('city-sg'),
    city_area_id: did('area-sg-chinatown'),
    slug: 'capsule-pod-boutique',
    name: 'The Pod Boutique Capsule Hotel',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 1.2823,
    lng: 103.8435,
    address: '289 Beach Road, Singapore',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '24/7 check-in',
    description: 'Modern capsule hotel near Bugis MRT with female-only pods. Clean, safe, and perfect for solo budget travelers. Lockers, WiFi, and a small common area. Central location makes exploring easy.',
    is_active: true,
  },
  {
    id: did('place-sg-five-stones-hostel'),
    city_id: did('city-sg'),
    city_area_id: did('area-sg-kampongglam'),
    slug: 'five-stones-hostel',
    name: 'Five Stones Hostel',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 1.3021,
    lng: 103.8584,
    address: '286 Joo Chiat Road, Singapore',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '24/7 check-in',
    description: 'Boutique heritage hostel in colorful Joo Chiat with female dorms. Beautiful Peranakan architecture, super clean, and social vibe. Great for meeting other solo travelers. Near MRT and local eateries.',
    is_active: true,
  },
  {
    id: did('place-sg-lau-pa-sat'),
    city_id: did('city-sg'),
    city_area_id: did('area-sg-marinabay'),
    slug: 'lau-pa-sat',
    name: 'Lau Pa Sat',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 1.2804,
    lng: 103.8504,
    address: '18 Raffles Quay, Singapore',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '24/7',
    description: 'Iconic Victorian-era hawker center in the financial district. Safe and easy for solo diners—grab a seat and order from various stalls. Try satay, laksa, and chicken rice. Buzzing at lunch and dinner.',
    is_active: true,
  },
  {
    id: did('place-sg-tiong-bahru-market'),
    city_id: did('city-sg'),
    city_area_id: did('area-sg-tiongbahru'),
    slug: 'tiong-bahru-market',
    name: 'Tiong Bahru Market & Food Centre',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 1.2863,
    lng: 103.8278,
    address: '30 Seng Poh Road, Singapore',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '6am-9pm daily',
    description: 'Local hawker gem in hip Tiong Bahru neighborhood. Solo women feel right at home here. Try Jian Bo Shui Kueh, chwee kueh, and lor mee. Second floor has fresh produce and traditional snacks.',
    is_active: true,
  },
  {
    id: did('place-sg-common-man-coffee'),
    city_id: did('city-sg'),
    city_area_id: did('area-sg-marinabay'),
    slug: 'common-man-coffee-roasters',
    name: 'Common Man Coffee Roasters',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 1.3014,
    lng: 103.8383,
    address: '22 Martin Road, Singapore',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '8am-6pm Mon-Fri, 9am-6pm Sat-Sun',
    description: 'Specialty coffee roastery with industrial-chic vibes. Popular with remote workers and solo coffee lovers. Excellent flat whites, strong WiFi, and all-day brunch. Can get crowded on weekends.',
    is_active: true,
  },
  {
    id: did('place-sg-tiong-bahru-bakery'),
    city_id: did('city-sg'),
    city_area_id: did('area-sg-tiongbahru'),
    slug: 'tiong-bahru-bakery',
    name: 'Tiong Bahru Bakery',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 1.2864,
    lng: 103.8309,
    address: '56 Eng Hoon Street, Singapore',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '8am-8pm daily',
    description: 'French bakery in a charming Art Deco neighborhood. Perfect for solo breakfast or laptop work. The croissants are flaky perfection, and the coffee is solid. Grab a window seat and watch the world go by.',
    is_active: true,
  },
  {
    id: did('place-sg-gardens-by-the-bay'),
    city_id: did('city-sg'),
    city_area_id: did('area-sg-marinabay'),
    slug: 'gardens-by-the-bay',
    name: 'Gardens by the Bay',
    place_type: 'activity',
    primary_category_id: did('cat-landmark'),
    lat: 1.2816,
    lng: 103.8636,
    address: '18 Marina Gardens Drive, Singapore',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '5am-2am daily (outdoor gardens)',
    description: 'Futuristic garden with iconic Supertrees and climate-controlled domes. Solo-friendly and safe to explore anytime. Free light show at 7:45pm and 8:45pm nightly. Cloud Forest and Flower Dome require tickets.',
    is_active: true,
  },
  {
    id: did('place-sg-arab-street'),
    city_id: did('city-sg'),
    city_area_id: did('area-sg-kampongglam'),
    slug: 'arab-street-kampong-glam',
    name: 'Kampong Glam & Sultan Mosque',
    place_type: 'activity',
    primary_category_id: did('cat-landmark'),
    lat: 1.3027,
    lng: 103.8589,
    address: 'Arab Street, Singapore',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Open daily',
    description: 'Historic Malay-Muslim quarter with colorful shophouses, indie boutiques, and the stunning Sultan Mosque. Solo women feel welcome—just dress modestly if entering the mosque. Great for photos and exploration.',
    is_active: true,
  },
  {
    id: did('place-sg-sentosa-island'),
    city_id: did('city-sg'),
    city_area_id: null,
    slug: 'sentosa-beach',
    name: 'Sentosa Island Beaches',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 1.2494,
    lng: 103.8303,
    address: 'Sentosa Island, Singapore',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Open 24/7',
    description: 'Resort island with three beaches—Siloso, Palawan, and Tanjong. Safe for solo women to lounge, swim, or walk. Free entry to beaches. Take the Sentosa Express from VivoCity. Rent a bike to explore.',
    is_active: true,
  },
  {
    id: did('place-sg-pulau-ubin'),
    city_id: did('city-sg'),
    city_area_id: null,
    slug: 'pulau-ubin',
    name: 'Pulau Ubin Island',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 1.4042,
    lng: 103.9601,
    address: 'Pulau Ubin, Singapore',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Bumboat 6am-7pm daily',
    description: 'Rustic island escape with jungle trails and bike paths. Take a bumboat from Changi Point Ferry Terminal (S$4). Rent a bike and explore Chek Jawa Wetlands. Solo women feel safe during the day.',
    is_active: true,
  },
  {
    id: did('place-sg-chinatown-complex'),
    city_id: did('city-sg'),
    city_area_id: did('area-sg-chinatown'),
    slug: 'chinatown-complex',
    name: 'Chinatown Complex Food Centre',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 1.2827,
    lng: 103.8435,
    address: '335 Smith Street, Singapore',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '6am-10pm daily',
    description: 'Massive hawker center with over 260 stalls. Solo diners can easily find a seat and sample everything. Try Lian Xing Zhou porridge, Tian Tian chicken rice, and Liang Zhao ji fried kway teow. Cash only.',
    is_active: true,
  },
  {
    id: did('place-sg-yoga-movement'),
    city_id: did('city-sg'),
    city_area_id: did('area-sg-tiongbahru'),
    slug: 'yoga-movement-tiong-bahru',
    name: 'Yoga Movement Tiong Bahru',
    place_type: 'wellness',
    primary_category_id: did('cat-wellness'),
    lat: 1.2847,
    lng: 103.8259,
    address: '78A Guan Chuan Street, Singapore',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: 'Schedule varies, check website',
    description: 'Welcoming yoga studio with drop-in classes for all levels. Solo travelers can easily join without booking long-term. Friendly community and experienced instructors. Mats and props provided.',
    is_active: true,
  },
];
