import { did } from '../../seed-utils';

export const southAfricaPlaces = [
  // CAPE TOWN
  {
    id: did('place-capetown-neverland'),
    city_id: did('city-capetown'),
    city_area_id: did('area-capetown-seapoint'),
    slug: 'never-never-land',
    name: 'Never Never Land',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: -33.9173,
    lng: 18.3946,
    address: '226 Main Road, Green Point',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '24/7',
    description: 'Colorful backpacker hostel with a rooftop pool and views of Signal Hill. The social atmosphere makes it easy to find hiking and wine tour partners within hours of checking in.',
    is_active: true,
  },
  {
    id: did('place-capetown-tablemountain'),
    city_id: did('city-capetown'),
    city_area_id: did('area-capetown-gardens'),
    slug: 'table-mountain',
    name: 'Table Mountain',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: -33.9625,
    lng: 18.4039,
    address: 'Table Mountain National Park',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Cable car 8am-6pm, weather dependent',
    description: 'Cape Town\'s defining landmark with multiple hiking routes and a cable car. Check weather before heading up — the mountain creates its own clouds and conditions change fast.',
    is_active: true,
  },
  {
    id: did('place-capetown-lionshead'),
    city_id: did('city-capetown'),
    city_area_id: did('area-capetown-seapoint'),
    slug: 'lions-head-hike',
    name: 'Lion\'s Head Sunrise Hike',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: -33.9361,
    lng: 18.3897,
    address: 'Signal Hill Road, Lion\'s Head',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Best at sunrise or full moon',
    description: 'The full moon hike is a Cape Town rite of passage. Join hundreds of locals for the sunset ascent — the combination of Atlantic and city views from the top is genuinely moving.',
    is_active: true,
  },
  {
    id: did('place-capetown-kirstenbosch'),
    city_id: did('city-capetown'),
    city_area_id: did('area-capetown-gardens'),
    slug: 'kirstenbosch',
    name: 'Kirstenbosch National Botanical Garden',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: -33.9881,
    lng: 18.4327,
    address: 'Rhodes Drive, Newlands',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '8am-6pm daily (7pm in summer)',
    description: 'World-class botanical garden on Table Mountain\'s eastern slopes. The tree canopy walkway (Boomslang) is worth the hype, and Sunday sunset concerts in summer are a local institution.',
    is_active: true,
  },
  {
    id: did('place-capetown-bokaaptour'),
    city_id: did('city-capetown'),
    city_area_id: did('area-capetown-bokaap'),
    slug: 'bo-kaap-cooking-class',
    name: 'Bo-Kaap Cooking Experience',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: -33.9207,
    lng: 18.4178,
    address: 'Wale Street, Bo-Kaap',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '10am-2pm, book in advance',
    description: 'Learn Cape Malay cooking in the colorful Bo-Kaap neighborhood from local women who have been making samoosas and bobotie for generations. This is a living neighborhood — book through a local operator, not just a walk-in.',
    is_active: true,
  },
  {
    id: did('place-capetown-oldbiscuitmill'),
    city_id: did('city-capetown'),
    city_area_id: did('area-capetown-woodstock'),
    slug: 'old-biscuit-mill',
    name: 'The Old Biscuit Mill',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: -33.9279,
    lng: 18.4564,
    address: '375 Albert Road, Woodstock',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Neighbourgoods Market: Sat 9am-2pm',
    description: 'Saturday\'s Neighbourgoods Market is the best food market in the city. Artisan stalls, craft beer, and a design-conscious crowd make this Woodstock\'s cultural anchor.',
    is_active: true,
  },
  {
    id: did('place-capetown-campsbaystrip'),
    city_id: did('city-capetown'),
    city_area_id: did('area-capetown-campsbay'),
    slug: 'camps-bay-strip',
    name: 'Camps Bay Beach & Strip',
    place_type: 'bar',
    primary_category_id: did('cat-nightlife'),
    lat: -33.9510,
    lng: 18.3778,
    address: 'Victoria Road, Camps Bay',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: '11am-late',
    description: 'Palm-lined sunset strip with the Twelve Apostles as backdrop. Grab a sundowner at Chinchilla or Cafe Caprice — the views are earned by enduring the see-and-be-seen crowd.',
    is_active: true,
  },
  {
    id: did('place-capetown-vawaterfront'),
    city_id: did('city-capetown'),
    city_area_id: did('area-capetown-seapoint'),
    slug: 'va-waterfront',
    name: 'V&A Waterfront',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: -33.9036,
    lng: 18.4210,
    address: '19 Dock Road, V&A Waterfront',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '9am-9pm daily',
    description: 'Working harbor turned shopping and dining complex with Zeitz MOCAA museum anchoring the cultural end. The Watershed craft market has genuinely good South African design.',
    is_active: true,
  },
  {
    id: did('place-capetown-kloof'),
    city_id: did('city-capetown'),
    city_area_id: did('area-capetown-gardens'),
    slug: 'kloof-street',
    name: 'Kloof Street Restaurants',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: -33.9315,
    lng: 18.4100,
    address: 'Kloof Street, Gardens',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '11am-11pm varies',
    description: 'Cape Town\'s most walkable dining strip runs from Gardens up toward Tamboerskloof. Start at Manna Epicure for breakfast and work your way to Yours Truly for dinner.',
    is_active: true,
  },
  {
    id: did('place-capetown-seapointprom'),
    city_id: did('city-capetown'),
    city_area_id: did('area-capetown-seapoint'),
    slug: 'sea-point-promenade',
    name: 'Sea Point Promenade',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: -33.9175,
    lng: 18.3830,
    address: 'Beach Road, Sea Point',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Open 24/7, best mornings and late afternoon',
    description: 'Safe, well-patrolled coastal walkway that every local uses for running, walking, and sunset watching. The stretch from Mouille Point lighthouse to Bantry Bay is perfect for a solo morning run.',
    is_active: true,
  },

  // JOHANNESBURG
  {
    id: did('place-joburg-apartheid'),
    city_id: did('city-joburg'),
    city_area_id: did('area-joburg-sandton'),
    slug: 'apartheid-museum',
    name: 'Apartheid Museum',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: -26.2381,
    lng: 28.0101,
    address: 'Northern Parkway & Gold Reef Road, Ormonde',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '9am-5pm, closed Mondays',
    description: 'Essential and emotionally demanding. Budget 3 hours minimum. The exhibition design is world-class, and the experience reframes everything else you see in Johannesburg.',
    is_active: true,
  },
  {
    id: did('place-joburg-constitutionhill'),
    city_id: did('city-joburg'),
    city_area_id: did('area-joburg-maboneng'),
    slug: 'constitution-hill',
    name: 'Constitution Hill',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: -26.1888,
    lng: 28.0419,
    address: '11 Kotze Street, Braamfontein',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '9am-5pm daily',
    description: 'Former prison complex where Mandela and Gandhi were both held, now home to South Africa\'s Constitutional Court. The contrast between the old prison and the new court building tells the country\'s story.',
    is_active: true,
  },
  {
    id: did('place-joburg-44stanley'),
    city_id: did('city-joburg'),
    city_area_id: did('area-joburg-rosebank'),
    slug: '44-stanley',
    name: '44 Stanley',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: -26.1803,
    lng: 28.0399,
    address: '44 Stanley Avenue, Milpark',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '9am-5pm daily',
    description: 'Converted industrial precinct with independent boutiques, galleries, and some of Joburg\'s best cafes. The kind of place where you come for coffee and stay for three hours browsing local design.',
    is_active: true,
  },
  {
    id: did('place-joburg-artsonmain'),
    city_id: did('city-joburg'),
    city_area_id: did('area-joburg-maboneng'),
    slug: 'arts-on-main',
    name: 'Arts on Main',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: -26.2048,
    lng: 28.0553,
    address: '264 Fox Street, Maboneng',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Sun market 10am-3pm, galleries vary',
    description: 'Maboneng\'s creative anchor with artist studios, galleries, and a Sunday market. Visit during the day and pair with a walk through the surrounding street art — Uber in and out.',
    is_active: true,
  },
  {
    id: did('place-joburg-sowetotour'),
    city_id: did('city-joburg'),
    city_area_id: did('area-joburg-sandton'),
    slug: 'soweto-guided-tour',
    name: 'Soweto Guided Tour',
    place_type: 'tour',
    primary_category_id: did('cat-activity'),
    lat: -26.2673,
    lng: 27.8598,
    address: 'Soweto, Johannesburg',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Tours typically 9am-1pm',
    description: 'A guided tour of Soweto is the single best thing you can do in Johannesburg. Visit the Hector Pieterson Memorial, Mandela House on Vilakazi Street, and eat at a local shisa nyama.',
    is_active: true,
  },
  {
    id: did('place-joburg-melvillecafe'),
    city_id: did('city-joburg'),
    city_area_id: did('area-joburg-melville'),
    slug: 'melville-7th-street',
    name: '7th Street Melville',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: -26.1755,
    lng: 28.0053,
    address: '7th Street, Melville',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '8am-late',
    description: 'Melville\'s strip of restaurants, cafes, and bars draws a young, creative crowd. Lucky Bean for brunch and Ant Cafe for afternoon coffee are the reliable picks.',
    is_active: true,
  },

  // DURBAN
  {
    id: did('place-durban-ushaka'),
    city_id: did('city-durban'),
    city_area_id: did('area-durban-beachfront'),
    slug: 'ushaka-marine-world',
    name: 'uShaka Marine World',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: -29.8682,
    lng: 31.0447,
    address: '1 King Shaka Avenue, Point Waterfront',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '9am-5pm daily',
    description: 'Built into an old ship hull, the aquarium here is genuinely impressive. The beach alongside it is one of the safer swimming options on the Durban beachfront.',
    is_active: true,
  },
  {
    id: did('place-durban-floridaroad'),
    city_id: did('city-durban'),
    city_area_id: did('area-durban-floridaroad'),
    slug: 'florida-road-dining',
    name: 'Florida Road',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: -29.8458,
    lng: 31.0149,
    address: 'Florida Road, Morningside',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '11am-late',
    description: 'Durban\'s best dining strip with Victorian houses converted into restaurants and bars. Start at Freedom Cafe for bunny chow — Durban\'s signature curry-in-a-loaf that is better than it sounds.',
    is_active: true,
  },
  {
    id: did('place-durban-umhlangaprom'),
    city_id: did('city-durban'),
    city_area_id: did('area-durban-umhlanga'),
    slug: 'umhlanga-promenade',
    name: 'Umhlanga Promenade',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: -29.7272,
    lng: 31.0859,
    address: 'Lagoon Drive, Umhlanga Rocks',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Open all day',
    description: 'The whale-bone pier and coastal walkway in Umhlanga is the safest, most comfortable beach area near Durban. Dolphins are common, and the Gateway Theatre of Shopping is a 5-minute drive.',
    is_active: true,
  },
  {
    id: did('place-durban-bunnychow'),
    city_id: did('city-durban'),
    city_area_id: did('area-durban-beachfront'),
    slug: 'durban-curry-tour',
    name: 'Durban Curry Trail',
    place_type: 'tour',
    primary_category_id: did('cat-activity'),
    lat: -29.8570,
    lng: 31.0290,
    address: 'Various locations, Durban',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Tours 10am-2pm',
    description: 'Durban has the largest Indian diaspora in Africa, and the curry here is legitimately world-class. A guided food tour through the Indian quarter covers bunny chow, roti, and biryani with context.',
    is_active: true,
  },
  {
    id: did('place-durban-gatewaybeach'),
    city_id: did('city-durban'),
    city_area_id: did('area-durban-umhlanga'),
    slug: 'oyster-box-hotel',
    name: 'The Oyster Box',
    place_type: 'hotel',
    primary_category_id: did('cat-stay'),
    lat: -29.7285,
    lng: 31.0870,
    address: '2 Lighthouse Road, Umhlanga Rocks',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: '24/7',
    description: 'Umhlanga\'s iconic red-and-white hotel next to the lighthouse. Even if you don\'t stay, high tea on the terrace with Indian Ocean views is worth the splurge.',
    is_active: true,
  },

  // KRUGER NATIONAL PARK
  {
    id: did('place-kruger-selfdrive'),
    city_id: did('city-kruger'),
    city_area_id: did('area-kruger-south'),
    slug: 'kruger-self-drive-safari',
    name: 'Kruger Self-Drive Safari',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: -24.9947,
    lng: 31.5926,
    address: 'Various gates, Kruger National Park',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Gates open sunrise to sunset',
    description: 'Driving yourself through Kruger is one of the most rewarding solo experiences in Southern Africa. A normal sedan handles the tar roads, and the southern section (Lower Sabie to Skukuza) has the highest game density.',
    is_active: true,
  },
  {
    id: did('place-kruger-skukuza'),
    city_id: did('city-kruger'),
    city_area_id: did('area-kruger-south'),
    slug: 'skukuza-rest-camp',
    name: 'Skukuza Rest Camp',
    place_type: 'hotel',
    primary_category_id: did('cat-stay'),
    lat: -24.9975,
    lng: 31.5926,
    address: 'Skukuza, Kruger National Park',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Check-in 2pm, gates close at sunset',
    description: 'Kruger\'s largest rest camp with bungalows, a restaurant, and a shop on the Sabie River. Book months ahead for dry season. The camp is fenced, and watching hippos from the river deck at sunset is the nightly ritual.',
    is_active: true,
  },
  {
    id: did('place-kruger-sunrisedrive'),
    city_id: did('city-kruger'),
    city_area_id: did('area-kruger-central'),
    slug: 'kruger-sunrise-drive',
    name: 'Guided Sunrise Game Drive',
    place_type: 'tour',
    primary_category_id: did('cat-activity'),
    lat: -24.0174,
    lng: 31.4917,
    address: 'Bookable at any rest camp',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Depart pre-dawn, return 8-9am',
    description: 'SANParks runs guided dawn drives in open vehicles with experienced rangers. You leave before the gates open to the public, which means better wildlife sightings and expert eyes spotting things you would miss alone.',
    is_active: true,
  },
  {
    id: did('place-kruger-lowersabie'),
    city_id: did('city-kruger'),
    city_area_id: did('area-kruger-south'),
    slug: 'lower-sabie-rest-camp',
    name: 'Lower Sabie Rest Camp',
    place_type: 'hotel',
    primary_category_id: did('cat-stay'),
    lat: -25.1192,
    lng: 31.9133,
    address: 'Lower Sabie, Kruger National Park',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Check-in 2pm',
    description: 'Smaller and quieter than Skukuza with prime river frontage. The sunset deck overlooking the Sabie River delivers reliable elephant and hippo sightings without leaving camp.',
    is_active: true,
  },
];
