import { did } from '../../seed-utils';

export const thailandPlaces = [
  // BANGKOK
  {
    id: did('place-bkk-lub-d-silom'),
    city_id: did('city-bkk'),
    city_area_id: did('area-bkk-silom'),
    slug: 'lub-d-silom',
    name: 'Lub d Bangkok Silom',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 13.7274,
    lng: 100.5340,
    address: '4 Decho Road, Silom, Bang Rak',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '24/7',
    description: 'Modern design hostel with women-only dorms that actually feel safe and clean. The rooftop bar is perfect for meeting other solo travelers without the rowdy hostel party vibe.',
    is_active: true,
  },
  {
    id: did('place-bkk-somtam-nua'),
    city_id: did('city-bkk'),
    city_area_id: did('area-bkk-silom'),
    slug: 'somtam-nua',
    name: 'Som Tam Nua',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 13.7440,
    lng: 100.5510,
    address: '392/14 Siam Square Soi 5, Pathum Wan',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '10:30am - 9:30pm daily',
    description: 'Iconic papaya salad spot that\'s always packed with locals and tourists alike. Sit at the communal tables and don\'t skip the grilled chicken.',
    is_active: true,
  },
  {
    id: did('place-bkk-roast'),
    city_id: did('city-bkk'),
    city_area_id: did('area-bkk-sukhumvit'),
    slug: 'roast-coffee',
    name: 'Roast',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 13.7307,
    lng: 100.5418,
    address: '8 Sukhumvit 26, Khlong Tan, Khlong Toei',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '7am - 7pm daily',
    description: 'Minimalist cafe with excellent wifi and strong coffee, perfect for remote work. The staff respects your space and the vibe is calm enough to actually get things done.',
    is_active: true,
  },
  {
    id: did('place-bkk-grand-palace'),
    city_id: did('city-bkk'),
    city_area_id: did('area-bkk-oldtown'),
    slug: 'grand-palace',
    name: 'The Grand Palace',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 13.7500,
    lng: 100.4915,
    address: 'Na Phra Lan Road, Phra Borom Maha Ratchawang',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '8:30am - 3:30pm daily',
    description: 'Bangkok\'s most famous temple complex is stunning but can feel overwhelming. Go early to beat the crowds and wear covered shoulders and knees to avoid the rental scarf vendors.',
    is_active: true,
  },
  {
    id: did('place-bkk-khaosan-market'),
    city_id: did('city-bkk'),
    city_area_id: did('area-bkk-khaosan'),
    slug: 'khaosan-market',
    name: 'Khao San Road Night Market',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 13.7588,
    lng: 100.4976,
    address: 'Khao San Road, Phra Nakhon',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '6pm - midnight daily',
    description: 'Classic backpacker street with pad thai stalls and questionable buckets. It\'s touristy but fun for people-watching, just keep your valuables close and trust your gut.',
    is_active: true,
  },
  {
    id: did('place-bkk-health-land'),
    city_id: did('city-bkk'),
    city_area_id: did('area-bkk-sukhumvit'),
    slug: 'health-land-asoke',
    name: 'Health Land Spa & Massage Asoke',
    place_type: 'wellness',
    primary_category_id: did('cat-wellness'),
    lat: 13.7365,
    lng: 100.5603,
    address: '120/1 North Sathorn Road, Silom',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '9am - 11pm daily',
    description: 'Legitimate spa chain with professional therapists and no pressure. Book the traditional Thai massage and prepare to be stretched like never before.',
    is_active: true,
  },

  // CHIANG MAI
  {
    id: did('place-cnx-stamps-hostel'),
    city_id: did('city-cnx'),
    city_area_id: did('area-cnx-oldcity'),
    slug: 'stamps-hostel',
    name: 'Stamps Backpackers',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 18.7883,
    lng: 98.9853,
    address: '7 Moon Muang Soi 9, Sri Phum',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '24/7',
    description: 'Social hostel where it\'s easy to meet people for temple-hopping or motorbike adventures. The common areas buzz without being overwhelming, and the beds actually have good curtains.',
    is_active: true,
  },
  {
    id: did('place-cnx-khao-soi-khun-yai'),
    city_id: did('city-cnx'),
    city_area_id: did('area-cnx-oldcity'),
    slug: 'khao-soi-khun-yai',
    name: 'Khao Soi Khun Yai',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 18.7860,
    lng: 98.9930,
    address: 'Sri Phum Road, Chang Moi',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '9am - 4pm daily',
    description: 'Tiny local spot serving the best khao soi in town, no contest. The auntie running it is sweet and the coconut curry will ruin you for all other versions.',
    is_active: true,
  },
  {
    id: did('place-cnx-ristr8to'),
    city_id: did('city-cnx'),
    city_area_id: did('area-cnx-nimman'),
    slug: 'ristr8to',
    name: 'Ristr8to',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 18.8020,
    lng: 98.9670,
    address: '15/3 Nimmanhaemin Road Soi 3',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '8am - 6pm daily',
    description: 'Award-winning coffee with latte art that belongs in a museum. The baristas are serious about their craft but friendly, and it\'s a great spot to work or journal.',
    is_active: true,
  },
  {
    id: did('place-cnx-doi-suthep'),
    city_id: did('city-cnx'),
    city_area_id: null,
    slug: 'doi-suthep',
    name: 'Wat Phra That Doi Suthep',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 18.8047,
    lng: 98.9217,
    address: 'Mueang Chiang Mai District',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '6am - 6pm daily',
    description: 'Stunning mountaintop temple with panoramic city views worth the 309 steps. Go at sunrise to beat the tour groups and experience it in peaceful silence.',
    is_active: true,
  },
  {
    id: did('place-cnx-elephant-nature-park'),
    city_id: did('city-cnx'),
    city_area_id: null,
    slug: 'elephant-nature-park',
    name: 'Elephant Nature Park',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 19.0333,
    lng: 98.9833,
    address: 'Mae Taeng District',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: 'Tours 9am - 5pm daily',
    description: 'Ethical elephant sanctuary where you observe and feed rescued elephants in their natural habitat. No riding, no tricks, just incredible animals being treated with respect.',
    is_active: true,
  },
  {
    id: did('place-cnx-punspace-nimman'),
    city_id: did('city-cnx'),
    city_area_id: did('area-cnx-nimman'),
    slug: 'punspace-nimman',
    name: 'PUNSPACE Nimman',
    place_type: 'coworking',
    primary_category_id: did('cat-coworking'),
    lat: 18.7970,
    lng: 98.9680,
    address: 'Soi Nimmanhemin 9, Su Thep',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '8am - 8pm Mon-Fri, 9am - 6pm Sat-Sun',
    description: 'Digital nomad hub with fast wifi and AC that actually works. The community is welcoming and it\'s easy to make friends without forced networking events.',
    is_active: true,
  },
  {
    id: did('place-cnx-night-bazaar'),
    city_id: did('city-cnx'),
    city_area_id: did('area-cnx-nightbazaar'),
    slug: 'chiang-mai-night-bazaar',
    name: 'Chiang Mai Night Bazaar',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 18.7880,
    lng: 99.0010,
    address: 'Chang Khlan Road, Chang Khlan',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '6pm - midnight daily',
    description: 'Massive night market with everything from knock-off bags to beautiful handicrafts. Bargain hard but fairly, and the food stalls in the back are where locals actually eat.',
    is_active: true,
  },

  // KRABI
  {
    id: did('place-krabi-slumber-party'),
    city_id: did('city-krabi'),
    city_area_id: did('area-krabi-aonang'),
    slug: 'slumber-party-hostel',
    name: 'Slumber Party Hostel',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 8.0365,
    lng: 98.8290,
    address: '329/1 Moo 2, Ao Nang, Muang',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '24/7',
    description: 'Chill hostel with a pool and female-only dorms that feel secure. Perfect base for island hopping, and the staff can arrange boat tours that aren\'t tourist traps.',
    is_active: true,
  },
  {
    id: did('place-krabi-krua-thara'),
    city_id: did('city-krabi'),
    city_area_id: did('area-krabi-aonang'),
    slug: 'krua-thara',
    name: 'Krua Thara Seafood',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 8.0320,
    lng: 98.8250,
    address: 'Ao Nang Beach Road',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '11am - 10pm daily',
    description: 'Beachfront seafood with your toes in the sand and prices that won\'t shock you. The grilled fish is incredible, and dining alone here feels natural.',
    is_active: true,
  },
  {
    id: did('place-krabi-railay-beach'),
    city_id: did('city-krabi'),
    city_area_id: did('area-krabi-railay'),
    slug: 'railay-beach',
    name: 'Railay Beach',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 8.0108,
    lng: 98.8406,
    address: 'Railay Beach, Ao Nang, Muang',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Open 24/7',
    description: 'Stunning limestone cliffs and crystal-clear water accessible only by boat. The west side is perfect for sunset, and the beach is safe for solo women day and night.',
    is_active: true,
  },
  {
    id: did('place-krabi-rock-climbing'),
    city_id: did('city-krabi'),
    city_area_id: did('area-krabi-railay'),
    slug: 'railay-rock-climbing',
    name: 'Basecamp Tonsai Climbing School',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 8.0095,
    lng: 98.8380,
    address: 'Railay Beach, Ao Nang, Muang',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '8am - 6pm daily',
    description: 'World-class rock climbing with instructors who take safety seriously. Perfect for solo travelers since you\'ll quickly bond with your climbing partners.',
    is_active: true,
  },
  {
    id: did('place-krabi-four-islands'),
    city_id: did('city-krabi'),
    city_area_id: did('area-krabi-aonang'),
    slug: 'four-islands-tour',
    name: 'Four Islands Tour',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 8.0340,
    lng: 98.8270,
    address: 'Departing from Ao Nang Beach',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Tours 9am - 5pm daily',
    description: 'Classic island-hopping tour to Phra Nang Cave, Chicken Island, and more. Join a group tour to split costs and meet other travelers, just book from your hostel to avoid beach scams.',
    is_active: true,
  },

  // PAI
  {
    id: did('place-pai-common-grounds'),
    city_id: did('city-pai'),
    city_area_id: did('area-pai-walkingst'),
    slug: 'common-grounds',
    name: 'Common Grounds Pai',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 19.3600,
    lng: 98.4380,
    address: 'Walking Street, Wiang Tai',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '24/7',
    description: 'Hippie-chic hostel where solo travelers become instant friends over sunset sessions. The communal vibe is genuine, and the female dorms are cozy and secure.',
    is_active: true,
  },
  {
    id: did('place-pai-nong-beer'),
    city_id: did('city-pai'),
    city_area_id: did('area-pai-walkingst'),
    slug: 'nong-beer',
    name: 'Nong Beer Restaurant',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 19.3595,
    lng: 98.4385,
    address: 'Ratchadamnoen Road, Wiang Tai',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '8am - 11pm daily',
    description: 'Local favorite with massive portions and tiny prices. The mango sticky rice is legendary, and the family running it treats solo diners like regulars.',
    is_active: true,
  },
  {
    id: did('place-pai-canyon'),
    city_id: did('city-pai'),
    city_area_id: did('area-pai-canyon'),
    slug: 'pai-canyon',
    name: 'Pai Canyon',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 19.3870,
    lng: 98.4120,
    address: 'Ban Tham, Mae Hi',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Open 24/7',
    description: 'Dramatic red-rock formations with narrow ridges and sunset views that justify the windy motorbike ride. Go in daylight first to scope the paths before attempting sunset.',
    is_active: true,
  },
  {
    id: did('place-pai-hot-springs'),
    city_id: did('city-pai'),
    city_area_id: null,
    slug: 'pai-hot-springs',
    name: 'Tha Pai Hot Springs',
    place_type: 'wellness',
    primary_category_id: did('cat-wellness'),
    lat: 19.4180,
    lng: 98.5020,
    address: 'Mae Hi, Pai District',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '7am - 6pm daily',
    description: 'Natural hot springs in the jungle where you can soak in mineral pools. Go early morning for a peaceful soak before the tour groups arrive.',
    is_active: true,
  },
  {
    id: did('place-pai-walking-street'),
    city_id: did('city-pai'),
    city_area_id: did('area-pai-walkingst'),
    slug: 'pai-walking-street-market',
    name: 'Pai Walking Street Market',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 19.3600,
    lng: 98.4375,
    address: 'Ratchadamnoen Road, Wiang Tai',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '5pm - 10pm daily',
    description: 'Nightly street market with artisan crafts, street food, and live music. The vibe is relaxed and safe, perfect for wandering solo with a mango smoothie.',
    is_active: true,
  },

  // KOH PHANGAN
  {
    id: did('place-kpg-beachlove'),
    city_id: did('city-kpg'),
    city_area_id: did('area-kpg-srithanu'),
    slug: 'beachlove-hostel',
    name: 'Beachlove Hostel',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 9.7750,
    lng: 100.0180,
    address: 'Sri Thanu Beach, Koh Phangan',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '24/7',
    description: 'Beachfront hostel with yoga vibes and female dorms that open to garden views. Skip the full moon chaos and stay here for the island\'s chill wellness scene.',
    is_active: true,
  },
  {
    id: did('place-kpg-fishermans-restaurant'),
    city_id: did('city-kpg'),
    city_area_id: did('area-kpg-haadrin'),
    slug: 'fishermans-restaurant',
    name: 'Fisherman\'s Restaurant',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 9.6705,
    lng: 100.0380,
    address: 'Haad Rin, Koh Phangan',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '11am - 10pm daily',
    description: 'Beachside restaurant with fresh seafood and no pressure to party. Great for a quiet dinner watching fire dancers without the full moon madness.',
    is_active: true,
  },
  {
    id: did('place-kpg-pantip-market'),
    city_id: did('city-kpg'),
    city_area_id: did('area-kpg-thongsala'),
    slug: 'pantip-market',
    name: 'Pantip Night Market',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 9.7420,
    lng: 100.0210,
    address: 'Thong Sala, Koh Phangan',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '6pm - 11pm Sat only',
    description: 'Saturday night market with local food stalls and artisan goods. Safer and more authentic than the full moon party scene, and the pad thai is top-tier.',
    is_active: true,
  },
  {
    id: did('place-kpg-bottle-beach'),
    city_id: did('city-kpg'),
    city_area_id: null,
    slug: 'bottle-beach',
    name: 'Bottle Beach (Haad Khuat)',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 9.8080,
    lng: 100.0520,
    address: 'Northern Koh Phangan',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Open 24/7',
    description: 'Secluded beach accessible by boat or jungle trek with calm waters perfect for swimming. Take the boat taxi for safety and go midweek to have it almost to yourself.',
    is_active: true,
  },
  {
    id: did('place-kpg-orion-healing'),
    city_id: did('city-kpg'),
    city_area_id: did('area-kpg-srithanu'),
    slug: 'orion-healing-center',
    name: 'Orion Healing Center',
    place_type: 'wellness',
    primary_category_id: did('cat-wellness'),
    lat: 9.7760,
    lng: 100.0170,
    address: 'Sri Thanu, Koh Phangan',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: '8am - 7pm daily',
    description: 'Holistic wellness center offering yoga, detox programs, and Thai massage. The community is welcoming to solo women, and the sunset yoga sessions are transformative.',
    is_active: true,
  },
];
