import { did } from '../../seed-utils';

export const vietnamPlaces = [
  // HO CHI MINH CITY
  {
    id: did('place-sgn-hideout-hostel'),
    city_id: did('city-sgn'),
    city_area_id: did('area-sgn-district1'),
    slug: 'hideout-hostel',
    name: 'The Hideout Hostel',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 10.7720,
    lng: 106.6990,
    address: '177/23 Pham Ngu Lao, District 1',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '24/7',
    description: 'Rooftop bar hostel with female-only dorms and lockers that actually work. The social scene is buzzing but not obnoxious, and staff help coordinate group trips to the Cu Chi tunnels.',
    is_active: true,
  },
  {
    id: did('place-sgn-pho-2000'),
    city_id: did('city-sgn'),
    city_area_id: did('area-sgn-district1'),
    slug: 'pho-2000',
    name: 'Pho 2000',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 10.7692,
    lng: 106.6994,
    address: '1-3 Phan Chu Trinh, District 1',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '6am - 2am daily',
    description: 'Famous pho spot where Bill Clinton ate back in 2000, but don\'t let the tourist hype fool you, the broth is genuinely incredible. Solo diners fit right in at the communal tables.',
    is_active: true,
  },
  {
    id: did('place-sgn-workshop-coffee'),
    city_id: did('city-sgn'),
    city_area_id: did('area-sgn-district3'),
    slug: 'the-workshop-coffee',
    name: 'The Workshop Coffee',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 10.7850,
    lng: 106.6950,
    address: '27 Ngo Duc Ke, District 1',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '7:30am - 10pm daily',
    description: 'Industrial-chic cafe with Vietnamese specialty coffee and reliable wifi for digital nomads. The iced coconut coffee is addictive, and the atmosphere is focused but friendly.',
    is_active: true,
  },
  {
    id: did('place-sgn-war-museum'),
    city_id: did('city-sgn'),
    city_area_id: did('area-sgn-district3'),
    slug: 'war-remnants-museum',
    name: 'War Remnants Museum',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 10.7797,
    lng: 106.6918,
    address: '28 Vo Van Tan, District 3',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '7:30am - 6pm daily',
    description: 'Powerful and sobering museum documenting the Vietnam War from the Vietnamese perspective. Go early to process it all without crowds, and expect to feel emotional.',
    is_active: true,
  },
  {
    id: did('place-sgn-ben-thanh-market'),
    city_id: did('city-sgn'),
    city_area_id: did('area-sgn-district1'),
    slug: 'ben-thanh-market',
    name: 'Ben Thanh Market',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 10.7722,
    lng: 106.6980,
    address: 'Le Loi Boulevard, District 1',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '6am - 6pm daily',
    description: 'Iconic covered market where vendors will chase you down but the food stalls are legit. Bargain hard and watch your bag, but the energy is electric and the souvenirs are plentiful.',
    is_active: true,
  },
  {
    id: did('place-sgn-bui-vien-walking'),
    city_id: did('city-sgn'),
    city_area_id: did('area-sgn-buivien'),
    slug: 'bui-vien-walking-street',
    name: 'Bui Vien Walking Street',
    place_type: 'bar',
    primary_category_id: did('cat-nightlife'),
    lat: 10.7675,
    lng: 106.6925,
    address: 'Bui Vien Street, District 1',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '6pm - 2am daily',
    description: 'Backpacker party street with cheap beer and rooftop bars. Stick to well-lit spots, keep your phone close, and grab a banh mi from the street vendors at midnight.',
    is_active: true,
  },
  {
    id: did('place-sgn-mekong-delta'),
    city_id: did('city-sgn'),
    city_area_id: null,
    slug: 'mekong-delta-tour',
    name: 'Mekong Delta Day Tour',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 10.0333,
    lng: 105.7833,
    address: 'Departing from District 1',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Tours 7am - 5pm daily',
    description: 'Classic day trip to floating markets and coconut candy workshops. Book through a reputable hostel to avoid scammy operators, and bring motion sickness meds for the boat rides.',
    is_active: true,
  },

  // HANOI
  {
    id: did('place-han-nexy-hostel'),
    city_id: did('city-han'),
    city_area_id: did('area-han-oldquarter'),
    slug: 'nexy-hostel',
    name: 'Nexy Hostel',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 21.0330,
    lng: 105.8520,
    address: '2 Ma May, Hoan Kiem',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '24/7',
    description: 'Modern hostel in the heart of the Old Quarter with female dorms and a rooftop terrace perfect for meeting travel buddies. Staff organize free walking tours that are actually worth waking up for.',
    is_active: true,
  },
  {
    id: did('place-han-bun-cha-dac-kim'),
    city_id: did('city-han'),
    city_area_id: did('area-han-oldquarter'),
    slug: 'bun-cha-dac-kim',
    name: 'Bun Cha Dac Kim',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 21.0320,
    lng: 105.8485,
    address: '1 Hang Manh, Hoan Kiem',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '10am - 8pm daily',
    description: 'Hole-in-the-wall serving Hanoi\'s signature bun cha with charcoal-grilled pork and herbs. Point at what others are eating if you\'re overwhelmed, and prepare for the best meal of your trip.',
    is_active: true,
  },
  {
    id: did('place-han-cong-caphe'),
    city_id: did('city-han'),
    city_area_id: did('area-han-oldquarter'),
    slug: 'cong-caphe',
    name: 'Cong Caphe',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 21.0285,
    lng: 105.8520,
    address: '152 Trieu Viet Vuong, Hai Ba Trung',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '7am - 11pm daily',
    description: 'Communist propaganda-themed cafe chain with coconut coffee that\'s dangerously good. Crowded but cozy, and a great spot to rest your feet between temple visits.',
    is_active: true,
  },
  {
    id: did('place-han-hoan-kiem-lake'),
    city_id: did('city-han'),
    city_area_id: did('area-han-oldquarter'),
    slug: 'hoan-kiem-lake',
    name: 'Hoan Kiem Lake',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 21.0285,
    lng: 105.8522,
    address: 'Hoan Kiem District',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Open 24/7',
    description: 'Central lake surrounded by locals doing tai chi at sunrise and couples on evening strolls. It\'s the safest place to wander alone at night, and the energy is magical.',
    is_active: true,
  },
  {
    id: did('place-han-temple-of-literature'),
    city_id: did('city-han'),
    city_area_id: did('area-han-frenchquarter'),
    slug: 'temple-of-literature',
    name: 'Temple of Literature',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 21.0277,
    lng: 105.8356,
    address: '58 Quoc Tu Giam, Dong Da',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '8am - 5pm Tue-Sun',
    description: 'Vietnam\'s first university, now a peaceful temple complex with ancient trees and tranquil courtyards. Go midweek to avoid school groups and actually enjoy the serenity.',
    is_active: true,
  },
  {
    id: did('place-han-halong-bay'),
    city_id: did('city-han'),
    city_area_id: null,
    slug: 'halong-bay-cruise',
    name: 'Ha Long Bay Overnight Cruise',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 20.9101,
    lng: 107.1839,
    address: 'Departing from Hanoi',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: 'Tours depart daily',
    description: 'UNESCO World Heritage site with limestone karsts rising from emerald waters. Book a mid-range cruise to avoid party boats, and the kayaking through caves is unforgettable.',
    is_active: true,
  },
  {
    id: did('place-han-west-lake'),
    city_id: did('city-han'),
    city_area_id: did('area-han-westlake'),
    slug: 'west-lake',
    name: 'West Lake (Ho Tay)',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 21.0583,
    lng: 105.8192,
    address: 'Tay Ho District',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Open 24/7',
    description: 'Hanoi\'s largest lake surrounded by cafes and temples, perfect for an afternoon bike ride. The expat neighborhood feels safe and has great brunch spots when you need a pho break.',
    is_active: true,
  },

  // HOI AN
  {
    id: did('place-hoi-tribee-bana'),
    city_id: did('city-hoi'),
    city_area_id: did('area-hoi-ancient'),
    slug: 'tribee-bana-hostel',
    name: 'Tribee Bana Hostel',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 15.8783,
    lng: 108.3280,
    address: '39 Phan Chau Trinh, Minh An',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '24/7',
    description: 'Pool party hostel with a chill side, offering female dorms and free bikes to explore the ancient town. The breakfast spreads are generous, and you\'ll make instant friends.',
    is_active: true,
  },
  {
    id: did('place-hoi-morning-glory'),
    city_id: did('city-hoi'),
    city_area_id: did('area-hoi-ancient'),
    slug: 'morning-glory',
    name: 'Morning Glory Restaurant',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 15.8794,
    lng: 108.3270,
    address: '106 Nguyen Thai Hoc, Minh An',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '8am - 10pm daily',
    description: 'Celebrity chef Ms. Vy\'s restaurant serving elevated Vietnamese classics with cooking classes upstairs. Book the morning class to learn cao lau and fresh spring rolls from the pros.',
    is_active: true,
  },
  {
    id: did('place-hoi-reaching-out'),
    city_id: did('city-hoi'),
    city_area_id: did('area-hoi-ancient'),
    slug: 'reaching-out-tea-house',
    name: 'Reaching Out Tea House',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 15.8780,
    lng: 108.3265,
    address: '131 Tran Phu, Minh An',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '9am - 9pm daily',
    description: 'Silent tea house staffed by deaf artisans where you communicate via notes. The peaceful vibe is meditative, and the lotus tea is served with intention and grace.',
    is_active: true,
  },
  {
    id: did('place-hoi-ancient-town'),
    city_id: did('city-hoi'),
    city_area_id: did('area-hoi-ancient'),
    slug: 'hoi-an-ancient-town',
    name: 'Hoi An Ancient Town',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 15.8801,
    lng: 108.3380,
    address: 'Minh An, Hoi An',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Open 24/7',
    description: 'UNESCO Old Town with lantern-lit streets and tailor shops on every corner. Go at sunrise to explore without the crowds, and yes, get a custom dress made but negotiate hard.',
    is_active: true,
  },
  {
    id: did('place-hoi-an-bang-beach'),
    city_id: did('city-hoi'),
    city_area_id: did('area-hoi-anbang'),
    slug: 'an-bang-beach',
    name: 'An Bang Beach',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 15.9150,
    lng: 108.3567,
    address: 'Cam An, Hoi An',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Open 24/7',
    description: 'Quieter alternative to Cua Dai with beach clubs offering lounge chairs for the price of a drink. Safe for solo swimmers, and the seafood shacks are phenomenal.',
    is_active: true,
  },
  {
    id: did('place-hoi-basket-boat'),
    city_id: did('city-hoi'),
    city_area_id: did('area-hoi-camthanh'),
    slug: 'basket-boat-tour',
    name: 'Cam Thanh Coconut Basket Boat Tour',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 15.9167,
    lng: 108.3833,
    address: 'Cam Thanh Village, Hoi An',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Tours 8am - 5pm daily',
    description: 'Traditional basket boat ride through coconut palm waterways where fishermen teach you to spin the boat. Touristy but charming, and the village lunch afterward is home-cooked perfection.',
    is_active: true,
  },
  {
    id: did('place-hoi-cooking-class'),
    city_id: did('city-hoi'),
    city_area_id: did('area-hoi-ancient'),
    slug: 'hoi-an-cooking-class',
    name: 'Hoi An Eco Cooking Class',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 15.8650,
    lng: 108.3100,
    address: 'Tra Que Village, Cam Ha',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Classes 8:30am - 1pm daily',
    description: 'Organic farm cooking class starting with a market tour and ending with a feast you made yourself. Perfect for solo travelers since you\'ll bond over chopping herbs and rolling spring rolls.',
    is_active: true,
  },

  // DA NANG
  {
    id: did('place-dad-memory-hostel'),
    city_id: did('city-dad'),
    city_area_id: did('area-dad-mykhe'),
    slug: 'memory-hostel',
    name: 'Memory Hostel & Cafe',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 16.0544,
    lng: 108.2430,
    address: '5 Le Tan Toan, Phuoc My',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '24/7',
    description: 'Beachside hostel with female dorms and a cafe downstairs serving killer smoothie bowls. The sunset sessions on the roof are low-key but social, and the beach is steps away.',
    is_active: true,
  },
  {
    id: did('place-dad-bun-cha-ca'),
    city_id: did('city-dad'),
    city_area_id: did('area-dad-hanriver'),
    slug: 'bun-cha-ca-93',
    name: 'Bun Cha Ca 93',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: 16.0544,
    lng: 108.2220,
    address: '93 Nguyen Chi Thanh, Hai Chau',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '10am - 9pm daily',
    description: 'Local spot for fish cake noodle soup that Da Nang is famous for. No English menu but the auntie will guide you, and it\'s cheap enough to order extra spring rolls.',
    is_active: true,
  },
  {
    id: did('place-dad-my-khe-beach'),
    city_id: did('city-dad'),
    city_area_id: did('area-dad-mykhe'),
    slug: 'my-khe-beach',
    name: 'My Khe Beach',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 16.0411,
    lng: 108.2472,
    address: 'Son Tra District',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Open 24/7',
    description: 'Pristine white-sand beach that Forbes called one of the world\'s most beautiful. Safe for solo swimming with lifeguards, and the sunrise is worth setting an alarm for.',
    is_active: true,
  },
  {
    id: did('place-dad-marble-mountains'),
    city_id: did('city-dad'),
    city_area_id: null,
    slug: 'marble-mountains',
    name: 'Marble Mountains',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 16.0055,
    lng: 108.2631,
    address: 'Hoa Hai, Ngu Hanh Son',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '7am - 5:30pm daily',
    description: 'Five marble and limestone hills with hidden caves, temples, and panoramic views. Wear good shoes for the stairs, and skip the elevator to earn the vista.',
    is_active: true,
  },
  {
    id: did('place-dad-dragon-bridge'),
    city_id: did('city-dad'),
    city_area_id: did('area-dad-hanriver'),
    slug: 'dragon-bridge',
    name: 'Dragon Bridge',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 16.0544,
    lng: 108.2272,
    address: 'Nguyen Van Linh, Hai Chau',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Bridge lighting 9pm Sat-Sun',
    description: 'Massive dragon-shaped bridge that breathes fire and sprays water on weekends at 9pm. It\'s touristy but spectacular, and the riverfront is safe for evening strolls.',
    is_active: true,
  },
  {
    id: did('place-dad-son-tra'),
    city_id: did('city-dad'),
    city_area_id: did('area-dad-sontra'),
    slug: 'son-tra-peninsula',
    name: 'Son Tra Peninsula',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 16.1067,
    lng: 108.2756,
    address: 'Son Tra District',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Open 24/7',
    description: 'Jungle-covered peninsula with secluded beaches and endangered monkeys. Rent a motorbike or hire a GrabBike for safety, and the Lady Buddha statue offers sweeping ocean views.',
    is_active: true,
  },

  // DA LAT
  {
    id: did('place-dlat-dalat-family-hostel'),
    city_id: did('city-dlat'),
    city_area_id: did('area-dlat-center'),
    slug: 'dalat-family-hostel',
    name: 'Dalat Family Hostel',
    place_type: 'hostel',
    primary_category_id: did('cat-stay'),
    lat: 11.9404,
    lng: 108.4382,
    address: '5B Ly Tu Trong, Phuong 2',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '24/7',
    description: 'Cozy family-run hostel with homemade breakfasts and female dorms in Vietnam\'s mountain retreat. The owner arranges canyoning trips and the fireplace is lit on chilly nights.',
    is_active: true,
  },
  {
    id: did('place-dlat-one-more-cafe'),
    city_id: did('city-dlat'),
    city_area_id: did('area-dlat-center'),
    slug: 'one-more-cafe',
    name: 'One More Cafe',
    place_type: 'cafe',
    primary_category_id: did('cat-cafe'),
    lat: 11.9415,
    lng: 108.4350,
    address: '2 Nguyen Du, Phuong 1',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: '7am - 10pm daily',
    description: 'Indie cafe with live music and Vietnamese specialty coffee grown in the surrounding hills. The avocado coffee sounds weird but trust the process, and the vibe is effortlessly cool.',
    is_active: true,
  },
  {
    id: did('place-dlat-crazy-house'),
    city_id: did('city-dlat'),
    city_area_id: did('area-dlat-center'),
    slug: 'crazy-house',
    name: 'Crazy House (Hang Nga Guesthouse)',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 11.9447,
    lng: 108.4203,
    address: '03 Huynh Thuc Khang, Phuong 4',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '8:30am - 7pm daily',
    description: 'Surreal Gaudi-inspired guesthouse that looks like a fairy tale nightmare. The architecture is bonkers in the best way, and it\'s actually safe to wander the twisted staircases alone.',
    is_active: true,
  },
  {
    id: did('place-dlat-dalat-market'),
    city_id: did('city-dlat'),
    city_area_id: did('area-dlat-center'),
    slug: 'dalat-market',
    name: 'Dalat Night Market',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 11.9365,
    lng: 108.4420,
    address: 'Nguyen Thi Minh Khai, Phuong 1',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '5pm - 11pm daily',
    description: 'Night market with grilled corn, strawberries, and local snacks perfect for a solo dinner crawl. The atmosphere is lively but not chaotic, and vendors are friendlier than in bigger cities.',
    is_active: true,
  },
  {
    id: did('place-dlat-tuyen-lam'),
    city_id: did('city-dlat'),
    city_area_id: did('area-dlat-tuyenlam'),
    slug: 'tuyen-lam-lake',
    name: 'Tuyen Lam Lake',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 11.8917,
    lng: 108.4233,
    address: 'Ward 4, Da Lat',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Open 24/7',
    description: 'Serene pine-surrounded lake perfect for renting a swan paddleboat or just sitting with a book. The cable car ride over offers misty mountain views that feel like another world.',
    is_active: true,
  },
  {
    id: did('place-dlat-canyoning'),
    city_id: did('city-dlat'),
    city_area_id: null,
    slug: 'dalat-canyoning',
    name: 'Dalat Canyoning Adventures',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: 11.9750,
    lng: 108.4167,
    address: 'Various locations around Da Lat',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: 'Tours 7am - 3pm daily',
    description: 'Rappel down waterfalls and jump into natural pools with professional guides who prioritize safety. Join a group tour to meet adventurous solo travelers, and prepare to feel like a badass.',
    is_active: true,
  },
  {
    id: did('place-dlat-linh-phuoc'),
    city_id: did('city-dlat'),
    city_area_id: did('area-dlat-tuyenlam'),
    slug: 'linh-phuoc-pagoda',
    name: 'Linh Phuoc Pagoda',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: 11.9042,
    lng: 108.4711,
    address: '120 Tu Phuoc, Trai Mat',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: '7am - 6pm daily',
    description: 'Mosaic temple covered in intricate broken glass and ceramic art depicting dragons and Buddhist scenes. It\'s a short ride from town, and the craftsmanship is mesmerizing.',
    is_active: true,
  },
];
