import { did } from '../../seed-utils';

export const zimbabwePlaces = [
  // VICTORIA FALLS
  {
    id: did('place-vicfalls-rainforest'),
    city_id: did('city-vicfalls'),
    city_area_id: did('area-vicfalls-town'),
    slug: 'victoria-falls-rainforest',
    name: 'Victoria Falls Rainforest',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: -17.9253,
    lng: 25.8567,
    address: 'Victoria Falls National Park, Livingstone Way, Victoria Falls',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 6am-6pm',
    description: 'A network of paved paths winds through lush rainforest directly opposite the falls, offering unobstructed views of the main curtain and the gorge below. Bring a waterproof layer during high water season — the spray is relentless and spectacular.',
    is_active: true,
  },
  {
    id: did('place-vicfalls-lookout-cafe'),
    city_id: did('city-vicfalls'),
    city_area_id: did('area-vicfalls-town'),
    slug: 'lookout-cafe',
    name: 'Lookout Cafe',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: -17.9215,
    lng: 25.8545,
    address: 'Batoka Gorge, Victoria Falls',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 9am-6pm',
    description: 'Cantilevered over the Batoka Gorge with uninterrupted views of the Zambezi bridge and spray from the falls. The menu is straightforward but the setting does the heavy lifting — ideal for a solo lunch where the scenery is the company.',
    is_active: true,
  },
  {
    id: did('place-vicfalls-bungee-bridge'),
    city_id: did('city-vicfalls'),
    city_area_id: did('area-vicfalls-town'),
    slug: 'bungee-bridge-tour',
    name: 'Bungee Bridge Tour',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: -17.9275,
    lng: 25.8610,
    address: 'Victoria Falls Bridge, Zimbabwe-Zambia Border',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: 'Daily 8am-5pm',
    description: 'A 111-meter freefall from the historic bridge spanning the gorge between Zimbabwe and Zambia. Operators are experienced and safety standards are high. Even if you skip the jump, a guided bridge walk offers vertigo-inducing views.',
    is_active: true,
  },
  {
    id: did('place-vicfalls-victoria-falls-hotel'),
    city_id: did('city-vicfalls'),
    city_area_id: did('area-vicfalls-town'),
    slug: 'the-victoria-falls-hotel',
    name: 'The Victoria Falls Hotel',
    place_type: 'hotel',
    primary_category_id: did('cat-stay'),
    lat: -17.9282,
    lng: 25.8522,
    address: '1 Mallet Drive, Victoria Falls',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 3,
    hours_text: '24/7',
    description: 'Colonial-era luxury hotel with sprawling gardens, a pool overlooking the gorge, and direct views of the bridge. The afternoon tea on the terrace is a polished ritual, and the staff are attentive without hovering.',
    is_active: true,
  },
  {
    id: did('place-vicfalls-zambezi-sunset-cruise'),
    city_id: did('city-vicfalls'),
    city_area_id: did('area-vicfalls-zambezi'),
    slug: 'zambezi-river-sunset-cruise',
    name: 'Zambezi River Sunset Cruise',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: -17.9200,
    lng: 25.8500,
    address: 'Zambezi Waterfront, Victoria Falls',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily, departures 4pm-4:30pm (seasonal)',
    description: 'A two-hour drift along the upper Zambezi with drinks, canapes, and a reliable golden-hour light show. Hippos surface nearby, birdlife is constant, and solo travelers blend easily into the relaxed atmosphere on board.',
    is_active: true,
  },

  // HARARE
  {
    id: did('place-harare-national-gallery'),
    city_id: did('city-harare'),
    city_area_id: did('area-harare-avondale'),
    slug: 'national-gallery-of-zimbabwe',
    name: 'National Gallery of Zimbabwe',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: -17.8247,
    lng: 31.0489,
    address: '20 Julius Nyerere Way, Harare',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Tue-Sun 9am-5pm, Closed Mon',
    description: 'One of Southern Africa\'s most important art institutions, with a permanent collection spanning Shona sculpture and contemporary Zimbabwean photography. The rotating exhibitions are consistently strong and the building itself is a quiet retreat from the city.',
    is_active: true,
  },
  {
    id: did('place-harare-sam-levys-village'),
    city_id: did('city-harare'),
    city_area_id: did('area-harare-borrowdale'),
    slug: 'sam-levys-village',
    name: 'Sam Levy\'s Village',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: -17.7776,
    lng: 31.0533,
    address: 'Borrowdale Road, Borrowdale, Harare',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 9am-6pm',
    description: 'Harare\'s most polished open-air shopping village with boutiques, cafes, and a weekend craft market. The Borrowdale crowd is cosmopolitan and the pace is unhurried — a useful base for coffee, SIM cards, and getting oriented.',
    is_active: true,
  },
  {
    id: did('place-harare-amanzi-restaurant'),
    city_id: did('city-harare'),
    city_area_id: did('area-harare-avondale'),
    slug: 'amanzi-restaurant',
    name: 'Amanzi Restaurant',
    place_type: 'restaurant',
    primary_category_id: did('cat-eat'),
    lat: -17.7990,
    lng: 31.0400,
    address: 'Avondale, Harare',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 11am-10pm',
    description: 'A garden-set restaurant in Avondale with a seasonal menu drawing from local produce and pan-African influences. Solo diners fit right in at the bar counter, and the wine list highlights Zimbabwean and South African labels worth exploring.',
    is_active: true,
  },

  // MASVINGO
  {
    id: did('place-masvingo-great-zimbabwe'),
    city_id: did('city-masvingo'),
    city_area_id: did('area-masvingo-center'),
    slug: 'great-zimbabwe-ruins',
    name: 'Great Zimbabwe Ruins',
    place_type: 'landmark',
    primary_category_id: did('cat-landmark'),
    lat: -20.2697,
    lng: 30.9334,
    address: 'Great Zimbabwe National Monument, Masvingo',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 2,
    hours_text: 'Daily 8am-5pm',
    description: 'The largest stone ruins in sub-Saharan Africa and a UNESCO World Heritage Site — the towering granite walls of this medieval city are deeply impressive. Hire a local guide to understand the history; walking the Great Enclosure alone takes roughly an hour.',
    is_active: true,
  },
  {
    id: did('place-masvingo-lake-mutirikwi'),
    city_id: did('city-masvingo'),
    city_area_id: did('area-masvingo-center'),
    slug: 'lake-mutirikwi',
    name: 'Lake Mutirikwi',
    place_type: 'activity',
    primary_category_id: did('cat-activity'),
    lat: -20.1833,
    lng: 30.8333,
    address: 'Lake Mutirikwi Recreational Park, Masvingo',
    google_place_id: null,
    phone: null,
    website: null,
    price_level: 1,
    hours_text: 'Daily 6am-6pm',
    description: 'A vast reservoir surrounded by granite hills and dry bushveld, with boat trips, fishing, and game drives through the surrounding park. The birdlife is exceptional and the landscape feels remote despite being just 30 minutes from town.',
    is_active: true,
  },
];
