/**
 * Sola Accommodations - Ready to Seed
 * Deduplicated against existing database content
 * Generated: 2026-02-03T21:14:06.157Z
 *
 * Total: 39 NEW accommodations across 39 cities in 12 countries
 */

export interface AccommodationEntry {
  name: string;
  googleMapsUrl: string;
  googlePlaceId: string | null;
  type: 'hostel' | 'hotel' | 'homestay';
  originalType: string;
  citySlug: string;
  city: string;
  country: string;
  priceRange: '$' | '$$' | '$$$';
  priceLevel: 1 | 2 | 3;
  pricePerNight: string | null;
  googleRating: number | null;
  reviewCount: number | null;
  whySelected: string;
  highlights: string[];
  considerations: string[];
  soloFemaleReviews: string;
  sourcesChecked: string[];
}

export const ACCOMMODATIONS_TO_SEED: AccommodationEntry[] = [
  // ==========================================================================
  // CAMBODIA
  // ==========================================================================
  {
    name: 'Sleeping Trees',
    googleMapsUrl: 'https://www.google.com/maps/place/Sleeping+Trees/@10.6000,103.2833,17z/data=!4m8!3m7!1s0x3107fa7f5e3b4e3b:0x1a8a3b2b0c7a3e3b!5m2!4m1!1i2!8m2!3d10.6000!4d103.2833',
    googlePlaceId: '0x3107fa7f5e3b4e3b:0x1a8a3b2b0c7a3e3b',
    type: 'hotel',
    originalType: 'glamping',
    citySlug: 'koh-rong',
    city: 'Koh Rong',
    country: 'Cambodia',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '25',
    googleRating: 4.7,
    reviewCount: 475,
    whySelected: 'Sleeping Trees offers a unique and tranquil eco-friendly experience on a beautiful, remote beach. It\'s ideal for solo travelers looking to disconnect and enjoy nature, with options for both budget-friendly tents and more comfortable bungalows. The on-site restaurant and bar provide a social atmosphere, while the peaceful surroundings are perfect for relaxation.',
    highlights: ['Beachfront location', 'Eco-friendly concept', 'Quiet and relaxing atmosphere', 'On-site restaurant and bar', 'Free snorkeling gear.'],
    considerations: ['Difficult to access (requires a ferry and a trek)', 'Wi-Fi is only available in the common areas and can be unreliable', 'Limited dining options on the island', 'Cash-only payments.'],
    soloFemaleReviews: 'A lovely bungalow on the beachfront at sunset beach. There are lots of chairs and hammocks to chill out on and relax at the beach. Friendly staff, comfortable room and a nice attached bar and restaurant. The wifi doesn\'t extend to the rooms but is ok in the bar area',
    sourcesChecked: ['sleeping-trees.com', 'agoda.com', 'tripadvisor.com'],
  },
  {
    name: 'Plantation Urban Resort & Spa',
    googleMapsUrl: 'https://maps.google.com/?cid=11357985232153501236',
    googlePlaceId: 'cid:11357985232153501236',
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'phnom-penh',
    city: 'Phnom Penh',
    country: 'Cambodia',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '100',
    googleRating: 4.6,
    reviewCount: 2458,
    whySelected: 'This hotel is a great option for solo travelers looking for a stylish and relaxing oasis in the heart of Phnom Penh. It offers a blend of modern amenities and traditional Khmer design, with a focus on tranquility and comfort. The property\'s two swimming pools, spa, and art gallery provide ample opportunities for relaxation and cultural immersion.',
    highlights: ['Two swimming pools', 'Spa', 'Art gallery', 'Central location', 'Blend of modern and traditional design'],
    considerations: ['Some reviews mention that service can be slow at times.'],
    soloFemaleReviews: 'One solo traveler on TripAdvisor mentioned that the hotel is "Ideal for solo travellers" and that the "Service at breakfast and in the evening from the pool bar was excellent."',
    sourcesChecked: ['official website', 'google reviews', 'tripadvisor', 'booking.com'],
  },
  {
    name: 'Sala Lodges',
    googleMapsUrl: 'https://www.google.com/maps/place/Sala+Lodges/@13.3453623,103.860499,17z/data=!3m1!4b1!4m9!3m8!1s0x3110177dbdc239f3:0xe5502bdf39ee4c72!5m2!4m1!1i2!8m2!3d13.3453623!4d103.860499!16s%2Fg%2F124t154n4?entry=ttu',
    googlePlaceId: '0x3110177dbdc239f3:0xe5502bdf39ee4c72',
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'siem-reap',
    city: 'Siem Reap',
    country: 'Cambodia',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '280',
    googleRating: 4.9,
    reviewCount: 856,
    whySelected: 'Sala Lodges offers a unique and authentic Cambodian experience by staying in a restored traditional Khmer house. It is a highly-rated, award-winning property with a focus on wellness and relaxation, making it an excellent choice for a solo traveler looking for a distinctive and memorable stay in Siem Reap.',
    highlights: ['Collection of 11 restored traditional Khmer wooden houses', 'Michelin Key recipient', 'Saltwater pool', 'On-site restaurant (Ma Om)', 'Spa and wellness center'],
    considerations: ['Higher price point', 'Located slightly outside the main town center'],
    soloFemaleReviews: 'While no reviews explicitly use the phrase \'solo traveler\', many reviews praise the peaceful and serene atmosphere, attentive staff, and unique experience, which are all qualities that would appeal to a solo traveler seeking a relaxing and authentic stay.',
    sourcesChecked: ['sala lodges website', 'google maps', 'tripadvisor', 'expedia', 'kayak', 'michelin guide'],
  },
  // ==========================================================================
  // INDONESIA
  // ==========================================================================
  {
    name: 'La Cocoteraie Ecolodge',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=La+Cocoteraie+Ecolodge&query_place_id=ChIJ6-CMldzKgbe4ARoML2cvMTJ2dGtybG0w',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'glamping',
    citySlug: 'gili-islands',
    city: 'Gili Islands',
    country: 'Indonesia',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '37',
    googleRating: 4.8,
    reviewCount: 222,
    whySelected: 'This eco-friendly glamping resort offers a unique and peaceful experience for solo travelers. It\'s located in a quiet coconut grove, away from the party scene, providing a safe and serene environment. The resort offers activities like yoga and cycling, and the friendly staff are often highlighted in reviews.',
    highlights: ['Eco-friendly', 'Glamping tents', 'Peaceful location', 'Yoga and cycling tours', 'Friendly staff'],
    considerations: ['A bit further from the main strip, but bikes are provided.'],
    soloFemaleReviews: '"Safe, quiet and comfortable away from party areas. Perfect for female solo travellers." - Tripadvisor review. "good place to stay in Gili Trawangan, especially for an adventure travelers." - Agoda review from a solo traveler.',
    sourcesChecked: ['thegoodobserverblog.co.uk', 'google maps', 'tripadvisor', 'agoda'],
  },
  {
    name: 'The Elysian Boutique Villa Hotel',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=The+Elysian+Boutique+Villa+Hotel%2C+Seminyak%2C+Indonesia',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'seminyak',
    city: 'Seminyak',
    country: 'Indonesia',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '200',
    googleRating: 4.6,
    reviewCount: 1500,
    whySelected: 'The Elysian Boutique Villa Hotel offers a luxurious and secure environment for solo travelers, with private villas ensuring a peaceful and private stay. The property\'s supportive staff and tranquil garden setting provide a comfortable and relaxing atmosphere, which is particularly appealing for those traveling alone.',
    highlights: ['Full-service spa', 'Outdoor pool', 'Restaurant', 'Snack bar/deli', 'Library', 'Garden views'],
    considerations: ['The romantic atmosphere may not be suitable for all solo travelers.'],
    soloFemaleReviews: 'Travelling solo I felt safe and supported. I will come back for sure.',
    sourcesChecked: ['theelysian.com', 'tripadvisor.com', 'booking.com'],
  },
  {
    name: 'Bambu Indah',
    googleMapsUrl: 'https://www.google.com/maps/place/Bambu+Indah/@-8.51203,115.238438,17z/data=!3m1!4b1!4m8!3m7!1s0x2dd241a37cffffff:0x8a248a2157434c6f!5m2!4m1!1i2!8m2!3d-8.51203!4d115.2406267',
    googlePlaceId: '0x2dd241a37cffffff:0x8a248a2157434c6f',
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'ubud',
    city: 'Ubud',
    country: 'Indonesia',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '241442',
    googleRating: 4.7,
    reviewCount: 2038,
    whySelected: 'Bambu Indah offers a unique and immersive experience for solo travelers looking for a connection with nature. The resort\'s stunning bamboo architecture, natural pools, and commitment to sustainability provide a memorable and eco-conscious stay. While it may be a splurge, the unique accommodations and serene environment make it a worthwhile choice for a special solo travelers seeking a distinctive and luxurious retreat-one-of-a-kind retreat in Ubud.',
    highlights: ['Unique bamboo architecture', 'Natural swimming pools', 'Focus on sustainability', 'Locally-sourced food'],
    considerations: ['Price may be high for solo travelers', 'some rooms are open-air and may not be suitable for all preferences.'],
    soloFemaleReviews: 'Bambu Indah is definitely my type of accommodation: boutique, charming, comfortable and one-of-the-kind. For a solo traveler, the price is a little steep. I was lucky to be able to book the smallest house for one person: Kuda house. Before booking, I was not sure...; I highly recommend it. Bambu Indah is a dream whether you\'re a solo traveler, with your friends or your family (both kids and teens would love it).',
    sourcesChecked: ['bambuindah.com', 'booking.com', 'tripadvisor.com', 'kayak.com', 'expedia.com'],
  },
  // ==========================================================================
  // JAPAN
  // ==========================================================================
  {
    name: 'BnA Alter Museum',
    googleMapsUrl: 'https://www.google.com/maps/place/BnA+Alter+Museum/@35.0013889,135.7669444,17z/data=!3m1!4b1!4m8!3m7!1s0x6001088f7a6b4b7b:0x9b0b3b3b3b3b3b3b!5m2!4m1!1i2!8m2!3d35.0013889!4d135.7691333',
    googlePlaceId: '0x6001088f7a6b4b7b:0x9b0b3b3b3b3b3b3b',
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'kyoto',
    city: 'Kyoto',
    country: 'Japan',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '150',
    googleRating: 4.5,
    reviewCount: 144,
    whySelected: 'BnA Alter Museum offers a truly unique and immersive experience for solo travelers by allowing them to stay in a room that is also a work of art. The hotel\'s central location provides easy access to many of Kyoto\'s main attractions, and its business model directly supports the local art scene, making for a memorable and meaningful stay.',
    highlights: ['Each of the 31 rooms is a unique art installation created by a Japanese artist', 'Features a 10-story vertical art gallery', 'Located in the heart of Kyoto, within walking distance of Gion and Kawaramachi', 'A portion of the profits from each stay goes directly to the artist who designed the room.'],
    considerations: ['Some rooms may be considered small by some travelers', 'The unique art in each room is subjective and may not appeal to all tastes.'],
    soloFemaleReviews: 'One solo traveler mentioned that the double bed was a great size for them. Another review from a solo traveler praised the comfortable stay and the hotel\'s convenient location, within walking distance to public transportation. A third solo traveler loved their stay, describing their room as \'very cool and comfortable\' with a nice street view.',
    sourcesChecked: ['erikastravelventures.com', 'bnaaltermuseum.com', 'booking.com', 'tripadvisor.com', 'expedia.com', 'google.com'],
  },
  {
    name: 'Centara Grand Hotel Osaka',
    googleMapsUrl: 'https://www.google.com/maps/place/Centara+Grand+Hotel+Osaka/@34.660291,135.5022983,17z/data=!3m1!4b1!4m9!3m8!1s0x6000e77d49576fcb:0x95a4a56ffb33256c!5m2!4m1!1i2!8m2!3d34.660291!4d135.5022983!16s%2Fg%2F11swz6fcgv?entry=ttu',
    googlePlaceId: '0x6000e77d49576fcb:0x95a4a56ffb33256c',
    type: 'hotel',
    originalType: 'hotel',
    citySlug: 'osaka',
    city: 'Osaka',
    country: 'Japan',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '235',
    googleRating: 4.5,
    reviewCount: 1362,
    whySelected: 'Centara Grand Hotel Osaka is a new, modern hotel with a focus on wellness, featuring a full-service spa with unique Thai treatments. Its location in the lively Namba district provides easy access to attractions and transport, making it a convenient and rejuvenating choice for solo travelers seeking a blend of relaxation and city exploration.',
    highlights: ['Spa Cenvaree with Thai-inspired treatments', 'Rooftop dining with city views', 'Modern and spacious rooms', 'Conveniently located in the vibrant Namba district'],
    considerations: ['Some reviews mention noise from nearby train tracks', 'Slow check-in process at times'],
    soloFemaleReviews: 'A review on Reddit mentioned it as a comfortable stay for a solo traveler. Priceline data indicates a high number of solo traveler guests.',
    sourcesChecked: ['hotel website', 'google maps', 'tripadvisor', 'expedia', 'reddit', 'priceline'],
  },
  {
    name: 'Asakusa Kokono Club Hotel',
    googleMapsUrl: 'https://maps.google.com/?cid=13034265332494688955',
    googlePlaceId: 'cid:13034265332494688955',
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'tokyo',
    city: 'Tokyo',
    country: 'Japan',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '150',
    googleRating: 4.4,
    reviewCount: 11,
    whySelected: 'The Asakusa Kokono Club Hotel is a boutique hotel in the heart of the historic Asakusa district, making it ideal for solo travelers seeking cultural immersion. Its unique feature is an on-site theater, offering a distinctive entertainment experience. The hotel\'s proximity to Senso-ji Temple and other attractions, combined with complimentary bicycle rentals, facilitates easy exploration of the vibrant neighborhood.',
    highlights: ['Boutique hotel with an on-site theater', 'Located in the historic Asakusa district', 'Walking distance to Senso-ji Temple', 'Free bicycle rentals for guests', 'Rooms feature artwork by local artisans'],
    considerations: ['Some standard rooms may be considered small.'],
    soloFemaleReviews: 'A solo traveler from Singapore mentioned the \'perfect location with many eateries around! Walking distance to the train station and attractions :)\'.',
    sourcesChecked: ['michelin guide', 'agoda', 'reddit', 'tripadvisor', 'official website', 'google maps'],
  },
  // ==========================================================================
  // LAOS
  // ==========================================================================
  {
    name: 'The Namkhan',
    googleMapsUrl: 'https://www.google.com/maps?q=NamKhan+Ecolodge&ftid=0x312f29861f3493bf:0xe95a2f14ebf9068a&hl=en-PH&gl=ph&entry=gps&lucs=s2se,a1&shorturl=1',
    googlePlaceId: '0x312f29861f3493bf:0xe95a2f14ebf9068a',
    type: 'hotel',
    originalType: 'glamping',
    citySlug: 'luang-prabang',
    city: 'Luang Prabang',
    country: 'Laos',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '130',
    googleRating: 4.7,
    reviewCount: 211,
    whySelected: 'The Namkhan offers a unique glamping experience in a serene, natural setting, making it an excellent choice for solo travelers seeking both relaxation and adventure. The property\'s focus on wellness, with yoga and meditation, and its location by the Nam Khan River provide a peaceful retreat with opportunities for mindful activities.',
    highlights: ['Glamping tents with river views', 'wellness-focused with yoga and meditation', 'organic farm on-site', 'shuttle to the city.'],
    considerations: ['Located outside the main town, requiring a shuttle', 'some reviews mention the property is aging.'],
    soloFemaleReviews: 'One reviewer on Tripadvisor mentioned, "I stayed in the tents...It was above and beyond what I expected it to be." Another mentioned the "beautiful location to just relax and enjoy the stunning surroundings."',
    sourcesChecked: ['the namkhan website', 'google maps', 'tripadvisor'],
  },
  {
    name: 'Vang Vieng Eco Lodge',
    googleMapsUrl: 'https://maps.app.goo.gl/fwGLWZKzB9oqehxb6',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'eco_lodge',
    citySlug: 'vang-vieng',
    city: 'Vang Vieng',
    country: 'Laos',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '50',
    googleRating: 4.1,
    reviewCount: 70,
    whySelected: 'Vang Vieng Eco Lodge offers a tranquil retreat for nature lovers seeking a unique and sustainable experience. Its location, nestled in the breathtaking landscapes of Vang Vieng, provides a peaceful environment away from the town\'s hustle and bustle, making it ideal for solo travelers seeking relaxation and a connection with nature. The property\'s focus on eco-friendly practices and its offering of rooms with garden or mountain views further enhance its appeal for those looking for a serene and responsible travel option.',
    highlights: ['Secluded and quiet location', 'magnificent views', 'on-site restaurant serving local and international cuisines', 'free WiFi', 'sun terrace and garden', 'tour desk.'],
    considerations: ['The property is located far from downtown Vang Vieng, so transportation is needed to get to the town center', 'The property only accepts cash payments.'],
    soloFemaleReviews: 'No specific solo traveler reviews were found, but the general sentiment from reviews is positive, highlighting the peaceful location and beautiful views.',
    sourcesChecked: ['booking.com', 'tripadvisor.com', 'agoda.com', 'expedia.com', 'google.com/maps'],
  },
  {
    name: 'Lao Poet Hotel',
    googleMapsUrl: 'https://maps.app.goo.gl/DdtRcqc8QybpxxVXA',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'vientiane',
    city: 'Vientiane',
    country: 'Laos',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '78',
    googleRating: 4.5,
    reviewCount: 336,
    whySelected: 'Lao Poet Hotel is a boutique hotel that offers a unique and stylish experience for solo travelers. Its central location, combined with its tranquil atmosphere and rooftop pool, provides a perfect retreat after a day of exploring Vientiane. The hotel\'s design, inspired by 1930s Indochina, adds a touch of elegance and charm.',
    highlights: ['Rooftop pool with city views', 'Stylish and unique design', 'Central location', 'Excellent breakfast'],
    considerations: ['Some reviews mention that the rooms can be dark.'],
    soloFemaleReviews: '"We stayed in the Lao Poet hotel for 2 nights just before New Year\'s and overall had a very nice stay! The hotel is nicely decorated with a Lao feel." - Wunderlust78, Tripadvisor. "Good location, i personally found the rooms quite dark but that could be just my personal preference." - Trip.com Member',
    sourcesChecked: ['laopoethotel.com', 'google maps', 'tripadvisor', 'expedia', 'booking.com'],
  },
  // ==========================================================================
  // MALAYSIA
  // ==========================================================================
  {
    name: 'Gayana Marine Resort',
    googleMapsUrl: 'https://www.google.com/maps/place/Gayana+Marine+Resort/@6.0133431,116.0482836,17z/data=!3m1!4b1!4m9!3m8!1s0x323b6995e6a6aba7:0x8a1bfde374cc13a9!5m2!4m1!1i2!8m2!3d6.0133431!4d116.0482836!16s%2Fg%2F1tgdfhrc?entry=ttu',
    googlePlaceId: '0x323b6995e6a6aba7:0x8a1bfde374cc13a9',
    type: 'hotel',
    originalType: 'eco_lodge',
    citySlug: 'kota-kinabalu',
    city: 'Kota Kinabalu',
    country: 'Malaysia',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '333',
    googleRating: 4.3,
    reviewCount: 433,
    whySelected: 'Gayana Marine Resort is a great option for solo travelers interested in marine conservation and a luxurious overwater villa experience. The on-site Marine Ecology Research Centre offers a unique educational component, and the resort\'s focus on sustainability will appeal to eco-conscious travelers. The tranquil setting and beautiful surroundings provide a perfect escape for relaxation and rejuvenation.',
    highlights: ['Overwater villas', 'Marine Ecology Research Centre', 'Focus on sustainability', 'Spa', 'Multiple dining options.'],
    considerations: ['Some reviews mention that the facilities are a bit dated', 'The sea is not always clean due to proximity to the city.'],
    soloFemaleReviews: 'The resort exceeded my expectations in every way.; The room was spacious and clean with excellent ocean view!; The water is clear the villa on the water is superb.',
    sourcesChecked: ['agoda', 'booking.com', 'tripadvisor', 'google maps.'],
  },
  {
    name: 'The RuMa Hotel and Residences',
    googleMapsUrl: 'https://www.google.com.gh/travel/hotels/entity/ChoIyvnbnvPHkdmPARoNL2cvMTFiNjZnbnlweBAB?utm_campaign=sharing&utm_medium=link&utm_source=htls&ved=0CAAQ5JsGahcKEwjw7PaZqb2SAxUAAAAAHQAAAAAQAw&ts=CAEaIAoCGgASGhIUCgcI6g8QAhgLEgcI6g8QAhgMGAEyAhAAKgkKBToDRVVSGgA',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'hotel',
    citySlug: 'kuala-lumpur',
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '197',
    googleRating: 4.6,
    reviewCount: 2287,
    whySelected: 'The RuMa Hotel and Residences offers a luxurious and tranquil experience in the heart of Kuala Lumpur, making it an excellent choice for solo travelers seeking a sophisticated and comfortable stay. Its design is inspired by Malaysian heritage, providing a unique cultural immersion. The hotel is praised for its attentive service and serene atmosphere, ensuring a relaxing and safe environment for solo guests.',
    highlights: ['Infinity pool with city views', 'UR SPA for wellness treatments', 'ATAS, a modern Malaysian restaurant', 'Central location near KLCC Park and Petronas Twin Towers.'],
    considerations: ['Higher price point compared to other options.'],
    soloFemaleReviews: 'Everything is great at the hotel and their customer service is also excellent. They helped me out with restaurant indications in the city. (TripAdvisor); Verified solo travelers that have stayed at this property have given The RuMa Hotel and Residences an average rating of 9.4. (Agoda)',
    sourcesChecked: ['the gone goat', 'google', 'tripadvisor', 'agoda'],
  },
  {
    name: 'The Smith House',
    googleMapsUrl: 'https://maps.google.com/?cid=8385571329464982920',
    googlePlaceId: 'cid:8385571329464982920',
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'langkawi',
    city: 'Langkawi',
    country: 'Malaysia',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '50',
    googleRating: 4.6,
    reviewCount: 1500,
    whySelected: 'The Smith House is a modern boutique hotel offering excellent value for solo travelers. Its proximity to Langkawi International Airport makes it a convenient choice for arrivals and departures, while positive reviews consistently highlight the friendly staff, clean accommodations, and a pleasant rooftop pool.',
    highlights: ['Close to the airport', 'Modern design', 'Rooftop pool', 'Friendly staff', 'Clean rooms', 'Good value for money'],
    considerations: ['Some reviews mention traffic noise', 'Only one lift serves two blocks.'],
    soloFemaleReviews: 'A solo traveler praised the hotel for its convenient location close to the airport, friendly staff, and clean, comfortable rooms. Another solo traveler highlighted the great value for money, excellent breakfast, and overall positive experience.',
    sourcesChecked: ['the culture trip', 'booking.com', 'tripadvisor', 'google maps'],
  },
  {
    name: 'Rosa Malacca',
    googleMapsUrl: 'https://www.google.com/maps/place/Rosa+Malacca/@2.1886804,102.2585026,17z/data=!4m9!3m8!1s0x31d1ee1eec481707:0x3ee5467be3c058b9!5m2!4m1!1i2!8m2!3d2.1886804!4d102.2585026!16s%2Fg%2F11cmq30q77?entry=ttu',
    googlePlaceId: '0x31d1ee1eec481707:0x3ee5467be3c058b9',
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'malacca',
    city: 'Malacca',
    country: 'Malaysia',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '71',
    googleRating: 4.5,
    reviewCount: 1658,
    whySelected: 'Rosa Malacca is a hip boutique hotel with a unique industrial-chic design, offering a different experience from the many heritage hotels in Malacca. It is a good option for solo travelers looking for a stylish and comfortable stay. The hotel has excellent reviews, with many guests praising the friendly staff and clean rooms.',
    highlights: ['Industrial-chic design', 'Restored redbrick building', 'Friendly staff', 'Clean rooms'],
    considerations: ['The location is slightly outside the main tourist area, but still within walking distance.'],
    soloFemaleReviews: 'Good security for solo female traveller - Good food in the cafe - Nice bed - All the amenities are complete for traveller - Will repeat & recommend;Solo traveller. 9.0/10. Great. Date of stay: Nov 2025. Deluxe King Room. Rosa Malacca is a charming hotel with stylish and original decor. The staff is ...',
    sourcesChecked: ['google maps', 'tripadvisor', 'expedia'],
  },
  {
    name: 'The Blue Mansion (Cheong Fatt Tze Mansion)',
    googleMapsUrl: 'https://www.google.com/maps?daddr=Cheong+Fatt+Tze+-+The+Blue+Mansion,+14,+Lebuh+Leith,+Georgetown,+10200+George+Town,+Penang,+Malaysia',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'penang',
    city: 'Penang',
    country: 'Malaysia',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '175',
    googleRating: 4.4,
    reviewCount: 5415,
    whySelected: 'The Blue Mansion is a beautifully restored 19th-century mansion and a UNESCO award-winning heritage building. It offers a unique and historical experience for solo travelers who appreciate architecture and history. Its central location in George Town provides easy access to explore the city\'s attractions.',
    highlights: ['Restored 19th-century mansion', 'UNESCO award-winning', 'guided tours', 'on-site restaurant and bar', 'central location in George Town.'],
    considerations: ['Higher price point.'],
    soloFemaleReviews: 'We absolutely loved our stay in this boutique small hotel. Room are old (but modernized) with...',
    sourcesChecked: ['official website', 'tripadvisor'],
  },
  // ==========================================================================
  // MOROCCO
  // ==========================================================================
  {
    name: 'Riad Cherifa',
    googleMapsUrl: 'https://maps.google.com/?cid=10303180',
    googlePlaceId: 'cid:10303180',
    type: 'hotel',
    originalType: 'riad',
    citySlug: 'chefchaouen',
    city: 'Chefchaouen',
    country: 'Morocco',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '142',
    googleRating: 4.8,
    reviewCount: 135,
    whySelected: 'Riad Cherifa offers a unique and immersive experience in the heart of Chefchaouen\'s medina. Its \'medina within a medina\' concept, beautiful Andalusian-Moorish architecture, and amenities like a hammam, spa, and pool make it an excellent choice for solo travelers seeking a blend of cultural authenticity and comfort.',
    highlights: ['Medina within a medina concept', 'Rooftop garden terrace with views', 'Hammam and spa', 'Outdoor swimming pool', 'Traditional Moroccan charm with modern comfort'],
    considerations: ['Some rooms may be small', 'a chorus of cats can be heard at night from rooms overlooking the town.'],
    soloFemaleReviews: 'A solo traveler mentioned that the riad is a great place for solo travelers seeking a balance between tradition and comfort. Another review mentioned that the staff were incredibly friendly and helpful, and that the location was perfect, right in the heart of the blue city, close to the main sights yet peaceful at night.',
    sourcesChecked: ['kimkim.com', 'booking.com', 'tripadvisor.com', 'riadcherifahotel.com'],
  },
  {
    name: 'Berber Lodge',
    googleMapsUrl: 'https://www.google.com/maps?hl=en-GB&gl=US&um=1&ie=UTF-8&fb=1&sa=X&geocode=KYf-osoK4a8NMWeHT15Xv6rG&daddr=Berber+Lodge%D8%8C+route+de+barrage%D8%8C+Province+al+Haouz,+Marrakesh+42312,+Morocco',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'marrakech',
    city: 'Marrakech',
    country: 'Morocco',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '250',
    googleRating: 4.8,
    reviewCount: 136,
    whySelected: 'Berber Lodge offers a unique and tranquil escape from the bustling city, making it an ideal choice for solo travelers seeking a peaceful retreat. The property\'s design, inspired by traditional Berber architecture, and its location within an olive grove provide an authentic Moroccan experience. The welcoming atmosphere and communal dining options also offer opportunities for connection with other guests.',
    highlights: ['Authentic Berber-style architecture', 'Tranquil setting in an olive grove', 'Outdoor swimming pool', 'Locally sourced, home-cooked meals', 'Fireplaces in some rooms'],
    considerations: ['Remote location requires a car or taxi for excursions', 'Wi-Fi is primarily available in common areas, encouraging a digital detox.'],
    soloFemaleReviews: 'One solo traveler described it as the \'highlight of my time in Morocco,\' praising the \'wonderful staff, great pool and animals on the property.\' They also noted that while internet is accessible, the limited Wi-Fi in rooms is a \'nice touch to keep your phone off.\'',
    sourcesChecked: ['google', 'tripadvisor'],
  },
  // ==========================================================================
  // MYANMAR
  // ==========================================================================
  {
    name: 'Bagan Lodge',
    googleMapsUrl: 'https://www.google.com/maps/dir//Bagan+Lodge+Hotel,+4VPF%2B5J8,+Myat+Lay+Road,+New+Bagan,+Myanmar+(Burma)/@28.395053,84.127804,7z/data=!4m8!4m7!1m0!1m5!1m1!1s0x30b5e4962a312a35:0xb16a956c056874d1!2m2!1d94.8740793!2d21.1354017?hl=en&entry=ttu&g_ep=EgoyMDI2MDEyOC4wIKXMDSoASAFQAw%3D%3D',
    googlePlaceId: '0x30b5e4962a312a35:0xb16a956c056874d1',
    type: 'hotel',
    originalType: 'glamping',
    citySlug: 'bagan',
    city: 'Bagan',
    country: 'Myanmar',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '222',
    googleRating: 4.4,
    reviewCount: 226,
    whySelected: 'Bagan Lodge offers a unique glamping experience with luxurious tented villas, providing a distinctive and comfortable base for exploring the ancient temples of Bagan. Its on-site e-bike rentals make it convenient for solo travelers to independently explore the vast archaeological zone.',
    highlights: ['Glamping-style tented villas', 'Two swimming pools', 'On-site e-bike rentals', 'Spa with massage and beauty treatments', 'Free Wi-Fi.'],
    considerations: ['Some reviews mention the location is not within walking distance of many attractions, requiring transportation. The on-site restaurant has received mixed reviews.'],
    soloFemaleReviews: 'A solo traveler on Agoda mentioned, \'Loved my stay at Bagan Lodge during low season (when price was cheaper). Ebikes available to rent on site. Would give staff 6 stars if I could: my ebike ran out of battery late at night on a deserted sandy road and they came within 20 minutes to pick me up.\'',
    sourcesChecked: ['glamping.com', 'agoda.com'],
  },
  {
    name: 'Inle Lake View Resort & Spa',
    googleMapsUrl: 'https://www.google.com/maps?hl=en-GB&gl=MX&um=1&ie=UTF-8&fb=1&sa=X&geocode=KWmPxb_fks4wMa-4Bd0vGIwS&daddr=HVXH%2BHM6+Inle+Lake+View+Resort,+Khaungtaing,+Myanmar+(Burma)',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'resort',
    citySlug: 'inle-lake',
    city: 'Inle Lake',
    country: 'Myanmar',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '80',
    googleRating: 4.4,
    reviewCount: 117,
    whySelected: 'Inle Lake View Resort & Spa offers a serene and luxurious experience for solo travelers looking to unwind and connect with nature. The resort\'s eco-friendly practices and stunning lake views provide a unique and memorable stay. With a high rating from past solo travelers, it is a safe and welcoming choice for those exploring Inle Lake alone.',
    highlights: ['Infinity pool with lake views', 'Eco-friendly practices', 'Spa and wellness center', 'On-site restaurant with local and international cuisine'],
    considerations: ['Some reviews mention that the location is a bit far from the main town, requiring a boat or car for transportation.'],
    soloFemaleReviews: 'Past solo travelers that have stayed at this property have given Inle Resort & Spa an average rating of 8.2. You can look up more detailed customer reviews and feedback to help you filtered down your search.',
    sourcesChecked: ['travelfish', 'agoda', 'google'],
  },
  {
    name: 'Vintage Luxury Yacht Hotel',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Vintage+Luxury+Yacht+Hotel&query_place_id=ChIJI-pS-pYowTAR8Gq_f-Q_xG8',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'yangon',
    city: 'Yangon',
    country: 'Myanmar',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '45',
    googleRating: 4.1,
    reviewCount: 967,
    whySelected: 'The Vintage Luxury Yacht Hotel offers a unique and memorable experience for solo travelers. Its 1920s theme and location on the Yangon River provide a distinct alternative to standard hotels. The proximity to local markets and pagodas allows for easy cultural immersion.',
    highlights: ['1920s-themed decor', 'Located on the Yangon River', 'Close to Botahtaung Pagoda', 'Two on-site restaurants', 'On-site spa.'],
    considerations: ['Some reviews mention that the rooms can be small and dark. The decor might be considered \'tacky\' by some.'],
    soloFemaleReviews: 'One reviewer on Booking.com said, \'A wonderful hotel-ship, with excellent staff and a wonderful view of the river. I really liked it. I recommend it to everyone!\' Another on Tripadvisor mentioned, \'This was the most incredible experience. It’s truly a page out of a storybook.\'',
    sourcesChecked: ['televisionofnomads.com', 'google travel', 'tripadvisor', 'booking.com'],
  },
  // ==========================================================================
  // PHILIPPINES
  // ==========================================================================
  {
    name: 'Treehouse de Valentine',
    googleMapsUrl: 'https://www.google.com/maps/place/Treehouse+de+Valentine+Mountain+Resort/@10.5187765,123.7664537,17z/data=!4m9!3m8!1s0x33a9096b4d039db9:0x98712056a5d13a58!5m2!4m1!1i2!8m2!3d10.5187765!4d123.7690286!16s%2Fg%2F11fnyp303m?entry=ttu',
    googlePlaceId: '0x33a9096b4d039db9:0x98712056a5d13a58',
    type: 'hotel',
    originalType: 'treehouse',
    citySlug: 'cebu',
    city: 'Cebu',
    country: 'Philippines',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '152',
    googleRating: 4.9,
    reviewCount: 192,
    whySelected: 'Treehouse de Valentine offers a unique and immersive nature experience, perfect for solo travelers looking to disconnect and relax. The property\'s distinctive treehouse and dome accommodations, coupled with a dedicated staff and curated activities, provide a memorable and comfortable stay away from the city\'s hustle and bustle.',
    highlights: ['Unique treehouse and dome accommodations', 'Peaceful and quiet environment', 'Full-time staff for assistance', 'Offers curated activities and tours.'],
    considerations: ['Located in Balamban, which is a bit far from Cebu City', 'Requires travel time to reach city attractions.'],
    soloFemaleReviews: 'Reviews mention it\'s a great place for a peaceful retreat and to disconnect from the city. The staff is often praised for being helpful and accommodating.',
    sourcesChecked: ['official website', 'google maps', 'booking.com', 'agoda', 'tripadvisor'],
  },
  {
    name: 'Glamping at Karuna El Nido',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Glamping+at+Karuna+El+Nido',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'glamping',
    citySlug: 'el-nido',
    city: 'El Nido',
    country: 'Philippines',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '150',
    googleRating: 4.8,
    reviewCount: 150,
    whySelected: 'Offers a variety of unique, themed glamping pods with stunning views of Bacuit Bay. It provides a luxurious and immersive nature experience, ideal for solo travelers seeking comfort and something different from a standard hotel.',
    highlights: ['Unique themed pods (pyramid, dome, cocoon, etc.)', 'Private bathrooms and air conditioning', 'Ocean views', 'Private outdoor lounge areas.'],
    considerations: ['Some units require a bit of a walk to access.'],
    soloFemaleReviews: 'No specific solo traveler reviews found, but general reviews praise the unique experience and beautiful views.',
    sourcesChecked: ['official website', 'google maps'],
  },
  {
    name: 'Water To Forest Ecolodge',
    googleMapsUrl: 'https://www.google.com/maps/place/Water+to+Forest+Ecolodge/@9.6325061,124.0156863,17z/data=!4m9!3m8!1s0x33aa45aa6b7310ff:0x2373cf8e23745f8!5m2!4m1!1i2!8m2!3d9.6325061!4d124.0156863!16s%2Fg%2F11dy1ncm10?entry=ttu',
    googlePlaceId: '0x33aa45aa6b7310ff:0x2373cf8e23745f8',
    type: 'hotel',
    originalType: 'eco_lodge',
    citySlug: 'bohol',
    city: 'Bohol',
    country: 'Philippines',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: '51',
    googleRating: 4.5,
    reviewCount: 155,
    whySelected: 'This ecolodge offers a unique experience for nature-loving solo travelers. It is located on the Loboc River and provides direct access to water activities like kayaking and stand-up paddleboarding. The property is built with minimal environmental impact, using indigenous techniques for comfort. It\'s a great option for those seeking a quiet, nature-focused retreat.',
    highlights: ['Direct river access', 'Watersports and photography tours', 'Eco-friendly practices', 'On-site cafe', 'Scooter rentals'],
    considerations: ['No air conditioning or water heaters', 'Presence of insects and toads at night'],
    soloFemaleReviews: 'Reviews mention the incredible service, connection to nature, clean facilities, and delicious food. One reviewer noted the dormatory-style accommodation is a large, fabric-separated space with a mattress on the floor and a mosquito net.',
    sourcesChecked: ['official website', 'tripadvisor', 'booking.com', 'google maps'],
  },
  {
    name: 'The Henry Hotel Manila',
    googleMapsUrl: 'https://www.google.com/maps/place/The+Henry+Hotel+Manila/@14.552937,120.9929,17z/data=!3m1!4b1!4m8!3m7!1s0x3397c95d1b561e7b:0x4937e25f8f6b6e2e!5m2!4m1!1i2!8m2!3d14.552937!4d120.9950887',
    googlePlaceId: '0x3397c95d1b561e7b:0x4937e25f8f6b6e2e',
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'manila',
    city: 'Manila',
    country: 'Philippines',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '74',
    googleRating: 4.5,
    reviewCount: 671,
    whySelected: 'The Henry Hotel Manila offers a unique and charming experience for solo travelers looking for something different from the usual city hotels. Its location in a restored 1940s mansion, surrounded by lush gardens, provides a tranquil and safe environment. The individually decorated rooms and personalized service create a welcoming and memorable stay.',
    highlights: ['Restored 1940s mansion', 'Lush gardens', 'Unique, vintage-inspired rooms', 'On-site restaurant', 'Quiet and safe location.'],
    considerations: ['Some rooms may be smaller than expected', 'occasional noise from events held on the property.'],
    soloFemaleReviews: 'Solo travelers praise the hotel\'s charming and unique atmosphere, friendly staff, and the feeling of being in a peaceful oasis within the city. Many appreciate the well-maintained gardens and the on-site restaurant.',
    sourcesChecked: ['tripadvisor', 'expedia', 'agoda', 'google maps'],
  },
  // ==========================================================================
  // PORTUGAL
  // ==========================================================================
  {
    name: 'The Lumiares Hotel & Spa',
    googleMapsUrl: 'https://www.google.com/maps/place/The+Lumiares/@38.7133034,-9.1441699,17z/data=!3m1!4b1!4m8!3m7!1s0xd19347e7a555555:0x300ebde4902cc0!5m2!4m1!1i2!8m2!3d38.7132992!4d-9.1419812',
    googlePlaceId: '0xd19347e7a555555:0x300ebde4902cc0',
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'lisbon',
    city: 'Lisbon',
    country: 'Portugal',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '213',
    googleRating: 4.6,
    reviewCount: 1397,
    whySelected: 'The Lumiares Hotel & Spa is an excellent choice for solo travelers seeking a luxurious and wellness-focused stay in Lisbon. The hotel\'s extensive spa facilities, including a sauna, steam room, and a variety of treatments, provide the perfect opportunity for relaxation and self-care. The apartment-style rooms with kitchenettes offer a degree of independence and flexibility that is often appreciated by solo travelers. The central location in Bairro Alto allows for easy exploration of the city\'s main attractions, while the rooftop bar provides a stunning setting for enjoying a drink and meeting other travelers.',
    highlights: ['5-star boutique hotel with a spa and gym', 'Rooftop bar and restaurant with panoramic city views', 'Apartment-style suites with kitchenettes', 'Located in the vibrant Bairro Alto district', 'Offers a range of wellness treatments, including massages and facials.'],
    considerations: ['Some reviews mention that the hotel can be noisy due to its location in a lively neighborhood', 'The apartment-style rooms may not be ideal for travelers seeking a traditional hotel experience.'],
    soloFemaleReviews: 'Many reviews from solo travelers praise the hotel\'s central location, friendly staff, and comfortable rooms. The spa and wellness facilities are also highlighted as a major plus for those looking to relax and rejuvenate.',
    sourcesChecked: ['the lumiares hotel & spa official website', 'google hotels', 'tripadvisor', 'kayak', 'expedia', 'mr & mrs smith'],
  },
  {
    name: 'Casa do Conto Arts & Residence',
    googleMapsUrl: 'https://www.google.com/travel/hotels/entity/ChoQq-25lcG92rjNARoNL2cvMTFtZG1wcXJ2dhAC',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'porto',
    city: 'Porto',
    country: 'Portugal',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '140',
    googleRating: 9.6,
    reviewCount: 177,
    whySelected: 'This renovated 19th-century building offers a unique and stylish experience for solo travelers. The property features just six suites, ensuring an intimate and personalized stay. Each suite is individually designed with a blend of modern and period furniture, and includes a kitchenette for added convenience. Its location provides easy access to public transportation and is within walking distance of several attractions, making it a great base for exploring Porto.',
    highlights: ['Renovated 19th-century building', '6 unique and stylish suites', 'Kitchenette in each suite', 'Balcony with city views', 'Garden and lounge with fireplace', '24-hour reception.'],
    considerations: ['Limited number of rooms, so booking in advance is recommended.'],
    soloFemaleReviews: 'No specific solo traveler reviews found, but general reviews are overwhelmingly positive, highlighting the beautiful design, comfortable rooms, and helpful staff.',
    sourcesChecked: ['secretplaces.com', 'booking.com', 'tripadvisor.com', 'google.com'],
  },
  // ==========================================================================
  // SINGAPORE
  // ==========================================================================
  {
    name: 'The Warehouse Hotel',
    googleMapsUrl: 'https://maps.google.com/?cid=11680778',
    googlePlaceId: 'cid:11680778',
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'singapore',
    city: 'Singapore',
    country: 'Singapore',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '310',
    googleRating: 4.6,
    reviewCount: 1072,
    whySelected: 'The Warehouse Hotel is a striking example of a heritage property transformed into a modern, design-focused hotel. Its location on the Singapore River in a restored 1895 \'godown\' (warehouse) offers a unique and historical context. The hotel\'s emphasis on local talent and design, combined with its luxurious amenities, makes it a compelling choice for solo travelers seeking an authentic and high-quality Singaporean experience.',
    highlights: ['Restored 1895 warehouse', 'Rooftop infinity pool', 'Onsite restaurant and cocktail bar', 'High-end contemporary design', 'Part of Marriott Bonvoy\'s Design Hotels portfolio.'],
    considerations: ['Can be expensive', 'Some rooms are windowless', 'Not located directly next to an MRT station.'],
    soloFemaleReviews: 'Young, trendy, and chic, this small 37 room boutique hotel is located in the Robertson Quay area of Singapore and is a little bit of a walk away from the nearest MRT station. The hotel is a converted warehouse and has a very industrial-chic vibe. The staff are friendly and helpful, and the rooms are clean and comfortable. The hotel has a rooftop pool with a great view of the city. The hotel is a great option for solo travelers who are looking for a stylish and unique place to stay in Singapore.',
    sourcesChecked: ['mstravelsolo.com', 'thewarehousehotel.com', 'tripadvisor.com', 'kayak.com', 'designhotels.com', 'asinglewanderer.wordpress.com'],
  },
  // ==========================================================================
  // THAILAND
  // ==========================================================================
  {
    name: 'Bangkok Tree House',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Bangkok+Tree+House',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'treehouse',
    citySlug: 'bangkok',
    city: 'Bangkok',
    country: 'Thailand',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '112',
    googleRating: 4,
    reviewCount: 1440,
    whySelected: 'A unique, eco-friendly option for travelers seeking a quiet escape from the city. It offers a chance to experience nature and a different side of Bangkok.',
    highlights: ['Eco-friendly', 'close to nature', 'unique treehouse experience'],
    considerations: ['Located outside of central Bangkok, requires a boat ride to access.'],
    soloFemaleReviews: 'No specific solo traveler reviews found, but general reviews are positive.',
    sourcesChecked: ['official website', 'tripadvisor', 'google maps'],
  },
  {
    name: 'i Lanna House',
    googleMapsUrl: '',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'guesthouse',
    citySlug: 'chiang-mai',
    city: 'Chiang Mai',
    country: 'Thailand',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '45',
    googleRating: 4.5,
    reviewCount: 309,
    whySelected: 'i Lanna House is a family-run guesthouse offering a peaceful and authentic Lanna-style experience within Chiang Mai\'s Old City. Its quiet location, comfortable rooms, and high ratings for staff attentiveness make it a good option for solo travelers seeking a relaxing and culturally immersive stay. The property\'s small size fosters a more intimate and personalized atmosphere.',
    highlights: ['Lanna-style architecture', 'Quiet location in the Old City', 'Outdoor pool', 'Complimentary breakfast', 'Friendly and helpful staff'],
    considerations: ['Small pool', 'Some reviews mention mold in the shower', 'Solo traveler review mentioned the room was small and priced for two people.'],
    soloFemaleReviews: 'A nice clean hotel on the rim of the old town, a close walk to the main street and temples. Really great staff who are willing to help. Also a nice pool at the front of the hotel.; The staff is extremely attentive. But the room was small and had no natural light coming in. It felt very claustrophobic!!! Also as a solo traveler I found that the cost of the room was for two.. No exceptions. That means you cover two breakfasts.',
    sourcesChecked: ['fortheloveofwanderlust.com', 'agoda.com'],
  },
  {
    name: 'Le Palais Hotel',
    googleMapsUrl: 'https://www.google.com/maps/place/Le+Palais+Hotel/@9.6825392,100.0553148,17z/data=!4m9!3m8!1s0x3054fc9435f4549f:0x26cc6e2b295f4aef!5m2!4m1!1i2!8m2!3d9.6825392!4d100.0553148!16s%2Fg%2F11fxhdx2f1?entry=ttu',
    googlePlaceId: '0x3054fc9435f4549f:0x26cc6e2b295f4aef',
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'koh-phangan',
    city: 'Koh Phangan',
    country: 'Thailand',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '100',
    googleRating: 4.3,
    reviewCount: 212,
    whySelected: 'Le Palais Hotel is selected for its unique and memorable design, offering a one-of-a-kind experience for travelers. Its location provides a good balance for solo travelers who want to experience the nightlife of Haad Rin but also have a quiet place to retreat. The positive reviews from other solo travelers and the friendly staff make it a promising option for a safe and enjoyable stay.',
    highlights: ['Unique Angkor Wat-themed architecture', 'Stunning sea views from rooms and the restaurant', 'Friendly and helpful staff', 'Clean and spacious rooms', 'Free shuttle service to the pier'],
    considerations: ['Some reviews mention that the property could use some refurbishment', 'There are many stairs to access the beach (around 220)', 'Breakfast has received mixed reviews', 'The hotel has faced some controversy regarding cultural appropriation of the Angkor Wat design.'],
    soloFemaleReviews: 'A truly unique hotel experience with wonderful personnel.; This hotel is great hotel at koh phangan.; Beautiful décor',
    sourcesChecked: ['agoda', 'google maps', 'various travel blogs'],
  },
  {
    name: 'TreeHouse Villas Koh Yao Noi',
    googleMapsUrl: 'https://www.google.com/maps/@8.176598,98.634552,16z?hl=en-US&entry=ttu',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'treehouse',
    citySlug: 'krabi',
    city: 'Krabi',
    country: 'Thailand',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '750',
    googleRating: 4.8,
    reviewCount: 389,
    whySelected: 'TreeHouse Villas offers a truly unique and luxurious experience for solo travelers seeking a peaceful and nature-immersive retreat. The adults-only policy ensures a quiet atmosphere, and the private pool villas provide a high degree of privacy and comfort. It\'s an excellent choice for those looking to splurge on a memorable, secluded getaway.',
    highlights: ['Adults-only resort', 'Villas with private plunge pools', 'Unique treehouse design amidst lush jungle', 'Strong focus on nature and seclusion', 'High-end amenities and service.'],
    considerations: ['Remote location requires a boat transfer', 'Caters primarily to couples, so solo travelers seeking social interaction might prefer other options', 'Higher price point.'],
    soloFemaleReviews: 'While most reviews are from couples, solo travelers have praised the resort for its tranquility and the opportunity to disconnect. One review mentioned it as a \'perfect place to recharge and be with your own thoughts.\' Another solo guest highlighted the \'feeling of being in a private paradise.\'',
    sourcesChecked: ['official website', 'booking.com', 'tripadvisor', 'google maps'],
  },
  {
    name: 'Reverie Siam',
    googleMapsUrl: 'https://maps.app.goo.gl/5NHT3gGFewu3QqgGA',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'pai',
    city: 'Pai',
    country: 'Thailand',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '206',
    googleRating: 4.8,
    reviewCount: 687,
    whySelected: 'Reverie Siam is a unique boutique hotel with a vintage, colonial-inspired design, offering a luxurious and peaceful retreat for solo travelers. It\'s located by the Pai River, providing a serene environment while still being a short shuttle ride from the town center. The property has two saltwater pools and a highly-rated restaurant, making it a self-contained oasis.',
    highlights: ['Two saltwater swimming pools', 'On-site restaurant and bar with Mediterranean and Thai cuisine', 'Free shuttle service to town', 'Unique, stylish decor.'],
    considerations: ['Higher price point compared to other options in Pai', 'Location is not in the immediate town center, requiring a shuttle or other transport.'],
    soloFemaleReviews: 'A TripAdvisor review from a solo traveler states: \'My favorite place to stay in Thailand\'. Experience Travel Group notes that \'Reverie Siam works particularly well for couples and solo travellers looking for a peaceful base, and for anyone wanting something more polished than the town\'s usual offerings.\'',
    sourcesChecked: ['dth travel', 'tripadvisor', 'google maps', 'reverie siam official website'],
  },
  // ==========================================================================
  // VIETNAM
  // ==========================================================================
  {
    name: 'Crazy House',
    googleMapsUrl: 'https://www.google.com/maps?q=11.9347127,108.4309274',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'guesthouse',
    citySlug: 'da-lat',
    city: 'Da Lat',
    country: 'Vietnam',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '50',
    googleRating: 4.2,
    reviewCount: 14000,
    whySelected: 'Crazy House is a highly unique and imaginative property, offering a one-of-a-kind experience for travelers seeking something beyond the ordinary. Its surreal, Gaudi-esque architecture and themed rooms make it a memorable stay for solo travelers looking for an unconventional and artistic environment. The property\'s central location allows for easy exploration of Da Lat, while the opportunity to explore the attached tourist attraction after hours provides a special perk.',
    highlights: ['Unique architecture', 'Themed rooms', 'Central location', 'After-hours access to the Crazy House attraction.'],
    considerations: ['The guesthouse is a popular tourist attraction, so it can be crowded during the day', 'Rooms lack modern amenities like televisions and air conditioning to encourage a connection with nature.'],
    soloFemaleReviews: 'Many solo travelers enjoy the unique and whimsical experience. Some find it a bit touristy, but most agree it\'s a fun and memorable place to stay.',
    sourcesChecked: ['crazyhouse.vn', 'tripadvisor.com', 'dreambigtravelfarblog.com'],
  },
  {
    name: 'Enosta Space',
    googleMapsUrl: 'https://www.google.com/maps/place/Enosta+Space+-+Coworking+%26+Coliving+Space+-+An+Nhon+3/@16.0692673,108.2313386,17z/data=!3m1!4b1!4m6!3m5!1s0x314219fc541032b1:0x610f7367caf4c58a!8m2!3d16.0692673!4d108.2339135!16s%2Fg%2F11h7k1f9f1?entry=tts',
    googlePlaceId: '0x314219fc541032b1:0x610f7367caf4c58a',
    type: 'hotel',
    originalType: 'coliving',
    citySlug: 'da-nang',
    city: 'Da Nang',
    country: 'Vietnam',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: '8',
    googleRating: 4.8,
    reviewCount: 118,
    whySelected: 'Enosta Space is a co-living and co-working space designed for digital nomads and remote workers. It offers a productive environment with high-speed internet, meeting rooms, and a supportive community, making it an excellent choice for solo travelers looking to connect with like-minded individuals while maintaining a professional workflow.',
    highlights: ['Co-living apartments with weekly/monthly rates', 'Dedicated co-working areas', 'Community events', 'High-speed internet'],
    considerations: ['Can get crowded at peak times.'],
    soloFemaleReviews: 'I highly recommend this building for digital nomads, the internet speed is perfect, the private room is huge and the staff is very very nice and professional! She helped me from the beginning in anything and I really appreciate that!',
    sourcesChecked: ['enostaspace.com', 'thingsnomadsdo.com', 'google maps'],
  },
  {
    name: 'Apricot Hotel',
    googleMapsUrl: 'https://www.google.com/maps/place/Apricot+Hotel/@21.02935,105.8524,17z/data=!3m1!4b1!4m9!3m8!1s0x3135ab9ae9f8c9c3:0x53a779083217d6d5!5m2!4m1!1i2!8m2!3d21.02935!4d105.8524!16s%2Fg%2F11dx_3w1k3?entry=ttu',
    googlePlaceId: '0x3135ab9ae9f8c9c3:0x53a779083217d6d5',
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'hanoi',
    city: 'Hanoi',
    country: 'Vietnam',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '163',
    googleRating: 4.5,
    reviewCount: 1800,
    whySelected: 'The Apricot Hotel is a centrally located, art-themed boutique hotel that offers a luxurious and culturally immersive experience for solo travelers. Its proximity to major attractions and positive reviews from other solo travelers make it a safe and appealing choice.',
    highlights: ['Art-focused boutique hotel', 'Rooftop pool with panoramic city views', 'Central location near Hoan Kiem Lake', 'Excellent service'],
    considerations: ['Some rooms may be small', 'Rooftop bar can be crowded'],
    soloFemaleReviews: 'Agoda reviews mention a solo traveler rating of 8.9. A Reddit user who stayed as a solo traveler \'really enjoyed it - great location.\'',
    sourcesChecked: ['agoda.com', 'reddit.com', 'tripadvisor.com', 'apricothotels.com'],
  },
  {
    name: 'The Common Room Project',
    googleMapsUrl: 'https://maps.google.com/?cid=4242294328463952147',
    googlePlaceId: 'cid:4242294328463952147',
    type: 'hotel',
    originalType: 'coliving',
    citySlug: 'ho-chi-minh-city',
    city: 'Ho Chi Minh City',
    country: 'Vietnam',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '60',
    googleRating: 5,
    reviewCount: 610,
    whySelected: 'The Common Room Project is a modern, stylish coliving space designed for digital nomads and remote workers, fostering a strong sense of community through shared spaces and activities. Its central location in District 1 provides easy access to the city\'s attractions, making it an ideal base for solo travelers looking to connect with others while exploring Ho Chi Minh City.',
    highlights: ['Communal kitchen', 'Rooftop bar', 'Social events', 'Female-only dorms available', 'Modern design'],
    considerations: ['Located on a busy street, which could be noisy at night', 'Some reviews mention that it can be a bit of a party hostel, which might not be suitable for all solo travelers.'],
    soloFemaleReviews: 'I had a wonderful experience staying here. The hostel is clean, cozy, and well-located (D1 HCM). The staff were super friendly and helpful, always ready to give great local tips. The beds are comfortable and the common areas are great for meeting other travelers. (Tripadvisor); Really loved staying at The Common Room Project. The hostel itself is a beautiful design, the beds are very comfy and everything is super clean. The staff is amazing and they organize family dinners every night which is a great way to meet people. (Hostelworld)',
    sourcesChecked: ['google maps', 'tripadvisor', 'hostelworld', 'booking.com', 'agoda'],
  },
  {
    name: 'Rock Villa',
    googleMapsUrl: 'https://maps.google.com/maps?q=15.8825,108.3553',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'villa',
    citySlug: 'hoi-an',
    city: 'Hoi An',
    country: 'Vietnam',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '34',
    googleRating: 4.5,
    reviewCount: 75,
    whySelected: 'Rock Villa offers a tranquil and luxurious retreat for solo travelers seeking a peaceful escape. Its location in the serene Cam Chau neighborhood, combined with its lush gardens and proximity to the Thu Bon River, provides a perfect setting for relaxation and immersion in nature. The exceptional staff, highly praised for their helpfulness and kindness, create a welcoming and safe environment for solo travelers.',
    highlights: ['Private beach', 'Free Wi-Fi', 'Swimming pool', 'Free parking', 'Spa', '24-hour front desk', 'Restaurants', 'Bar'],
    considerations: ['Located 3.7km from the city center, which may require transportation for those wanting to explore the ancient town frequently.'],
    soloFemaleReviews: 'One solo traveler on Agoda mentioned: \'Loved this place! Everything about it. Great pool, great design, great staff, huge breakfast.\'',
    sourcesChecked: ['agoda', 'tripadvisor', 'kayak'],
  },
];
