/**
 * Sola Accommodations Data
 * Researched accommodations for solo female travelers
 *
 * This data was gathered by researching each property across multiple sources
 * (Booking.com, Hostelworld, TripAdvisor, Google Reviews, travel blogs) and
 * evaluating them against Sola's baseline criteria for solo female travelers.
 *
 * Total: 73 accommodations across 12 countries
 */

export interface AccommodationEntry {
  // Identification
  name: string;
  googleMapsUrl: string;
  googlePlaceId: string | null;

  // Classification
  type: 'hostel' | 'hotel' | 'homestay';
  originalType: string; // More specific: boutique_hotel, resort, guesthouse, etc.
  citySlug: string;
  city: string;
  country: string;

  // Pricing
  priceRange: '$' | '$$' | '$$$';
  priceLevel: 1 | 2 | 3;
  pricePerNight: string | null;

  // Ratings
  googleRating: number | null;
  reviewCount: number | null;

  // Sola curation data
  whySelected: string;
  highlights: string[];
  considerations: string[];
  soloFemaleReviews: string;
  sourcesChecked: string[];
}

// Helper to extract Google Place ID from URL
function extractPlaceId(url: string): string | null {
  if (!url) return null;
  const cidMatch = url.match(/[?&]cid=(\d+)/);
  if (cidMatch) return `cid:${cidMatch[1]}`;
  const dataMatch = url.match(/0x[0-9a-f]+:0x[0-9a-f]+/i);
  if (dataMatch) return dataMatch[0];
  return null;
}

export const ACCOMMODATIONS: AccommodationEntry[] = [
  // ==========================================================================
  // CAMBODIA
  // ==========================================================================
  {
    name: 'Hotel Old Cinema',
    googleMapsUrl: 'https://www.google.com/maps/place/Hotel+Old+Cinema/@10.6101508,104.1802723,17z',
    googlePlaceId: '0x31083662a0fc5e13:0x93484b8f54423ecd',
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'kampot',
    city: 'Kampot',
    country: 'Cambodia',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '89',
    googleRating: 4.9,
    reviewCount: 319,
    whySelected: 'Hotel Old Cinema is a beautifully restored Art Deco hotel that offers a unique and stylish experience in the heart of Kampot. Its excellent location, attentive staff, and high-end amenities, including a saltwater pool and a highly-rated restaurant, make it a safe and luxurious choice for a solo female traveler looking for a special stay.',
    highlights: ['Beautifully restored Art Deco building', 'Excellent central location', 'Saltwater swimming pool', 'Highly-rated restaurant and bar'],
    considerations: ['Slightly higher price point compared to other options in the area'],
    soloFemaleReviews: 'While no explicit solo female reviews were found, the overwhelmingly positive reviews mentioning attentive staff, a safe and central location, and a welcoming atmosphere suggest it\'s a secure and comfortable choice for solo travelers.',
    sourcesChecked: ['booking.com', 'tripadvisor', 'google reviews'],
  },
  {
    name: 'The Secret Garden Koh Rong',
    googleMapsUrl: 'https://www.google.com/maps?daddr=The+Secret+Garden+Koh+Rong',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'koh-rong',
    city: 'Koh Rong',
    country: 'Cambodia',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '150',
    googleRating: 4.7,
    reviewCount: 331,
    whySelected: 'The Secret Garden Koh Rong is a highly-rated boutique hotel situated on a pristine, quiet beach, making it a safe and relaxing choice for a solo female traveler. The positive reviews, beautiful location, and amenities like a pool and on-site restaurant make it a great upscale option.',
    highlights: ['Beachfront', 'Private beach area', 'Outdoor swimming pool', 'Highly-rated restaurant'],
    considerations: ['While it has a romantic vibe that might appeal to couples, reviews indicate it\'s welcoming to all travelers'],
    soloFemaleReviews: 'While no explicit solo female reviews were found, the general sentiment is overwhelmingly positive, highlighting the friendly staff and safe environment.',
    sourcesChecked: ['booking.com', 'google reviews', 'tripadvisor'],
  },
  {
    name: 'The Pavilion',
    googleMapsUrl: 'https://maps.app.goo.gl/EHHJJGC4F3Rabd2c7',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'phnom-penh',
    city: 'Phnom Penh',
    country: 'Cambodia',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '90',
    googleRating: 4.6,
    reviewCount: 3354,
    whySelected: 'The Pavilion is a highly-rated, adult-only boutique hotel with a strong focus on heritage and responsible tourism. Its central, yet tranquil, location in a historic area, combined with positive reviews about its serene atmosphere and helpful staff, makes it a compelling option for solo female travelers seeking a relaxing and secure base from which to explore the city. The property\'s two pools and on-site spa offer ample opportunities for relaxation and self-care.',
    highlights: ['Adult-only', 'Two swimming pools', 'On-site spa', 'Central location', 'Heritage building', 'Responsible tourism focus'],
    considerations: ['Primarily caters to couples, which may not be ideal for all solo travelers', 'Some rooms are smaller than others'],
    soloFemaleReviews: 'While specific solo female reviews are not abundant, the general sentiment from reviews suggests a safe and welcoming environment. The adult-only policy and tranquil atmosphere are appreciated by many travelers.',
    sourcesChecked: ['booking.com', 'tripadvisor.com', 'wander-lush.org', 'thepavilion.asia'],
  },
  {
    name: 'Onederz Hostel Siem Reap',
    googleMapsUrl: 'https://www.google.com/maps?cid=6763399945953532601',
    googlePlaceId: 'cid:6763399945953532601',
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'siem-reap',
    city: 'Siem Reap',
    country: 'Cambodia',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: null,
    googleRating: 4.7,
    reviewCount: 1800,
    whySelected: 'Onederz Hostel is a highly-rated and popular choice for solo female travelers in Siem Reap. It offers female-only dorms with good security features, a central location, and a social atmosphere that makes it easy to meet other travelers. The numerous positive reviews from solo women highlight the safety and welcoming environment.',
    highlights: ['Female-only dorms', '24h reception', 'Central location', 'Multiple swimming pools', 'Social atmosphere', 'Tour booking desk'],
    considerations: ['Can be a large and busy hostel, which might not be ideal for those seeking a very quiet atmosphere'],
    soloFemaleReviews: 'A review on Booking.com from a solo female traveler said she "Felt safe here solo travelling. 10/10 :)".',
    sourcesChecked: ['hostelz.com', 'booking.com', 'google maps'],
  },
  {
    name: 'Jaya House River Park Hotel',
    googleMapsUrl: 'https://maps.google.com/?cid=6763293454832483513',
    googlePlaceId: 'cid:6763293454832483513',
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'siem-reap',
    city: 'Siem Reap',
    country: 'Cambodia',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '291',
    googleRating: 4.9,
    reviewCount: 1024,
    whySelected: 'Jaya House River Park is an exceptional choice for solo female travelers seeking a luxurious and socially responsible experience. The hotel\'s commitment to the community, including hiring female tuk-tuk drivers, and its serene riverside location provide a safe and enriching environment. The personalized service and high-end amenities ensure a comfortable and memorable stay.',
    highlights: ['Female-owned', 'Two swimming pools', 'Riverpark Spa', 'On-site restaurant', 'Complimentary tuk-tuk driver', 'Strong focus on community and sustainability'],
    considerations: ['The hotel has a higher price point compared to other options in the area'],
    soloFemaleReviews: 'The hotel is highly recommended by solo female travelers for its attentive staff, safety, and commitment to the community. The hotel\'s initiatives, such as hiring female tuk-tuk drivers, are particularly praised.',
    sourcesChecked: ['wearetravelgirls.com', 'google.com', 'tripadvisor.com', 'agoda.com', 'expedia.com'],
  },

  // ==========================================================================
  // INDONESIA
  // ==========================================================================
  {
    name: 'Sepeda Hostel',
    googleMapsUrl: 'https://maps.google.com/?cid=13053849981959248054',
    googlePlaceId: 'cid:13053849981959248054',
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'canggu',
    city: 'Canggu',
    country: 'Indonesia',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: null,
    googleRating: 4.8,
    reviewCount: 630,
    whySelected: 'Sepeda Hostel is a great choice for solo female travelers due to its excellent reviews, particularly from other solo women. It offers a safe and welcoming environment with female-only dorms, a high security rating, and a variety of social events that make it easy to meet other travelers. The hostel\'s location in a quieter area surrounded by rice fields, yet still close to the main attractions of Canggu, provides a good balance of tranquility and accessibility.',
    highlights: ['Female-only dorms', '24h reception', 'Rooftop cafe & bar', 'Swimming pool', 'Daily social events', 'Free yoga classes'],
    considerations: ['Located 0.6km from the city center, which might require a short scooter ride or walk to get to some areas'],
    soloFemaleReviews: 'For my first stay of solo travelling I couldn\'t have picked a better place. Everything was clean, hot showers and comfy beds. Also have good facilities such as pool, pool table and darts. Staff and volunteers were very welcoming and really made me feel at ease.',
    sourcesChecked: ['hostelworld.com', 'booking.com', 'tripadvisor.com', 'hostelz.com'],
  },
  {
    name: 'The Bohemian Bali',
    googleMapsUrl: 'https://www.google.com/maps/place/The+bohemian+bali/@-8.6459799,115.1375247,17z',
    googlePlaceId: '0x2dd239414bd53ba9:0xa1090c7a58f84ca2',
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'canggu',
    city: 'Canggu',
    country: 'Indonesia',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '187',
    googleRating: 4.9,
    reviewCount: 205,
    whySelected: 'This hotel is a great option for solo female travelers looking for a stylish and luxurious stay in Canggu. It has excellent reviews, with many solo travelers praising the hotel\'s design, service, and location. The hotel also offers a number of amenities that are well-suited for solo travelers, such as in-room dining and a spa with solo-friendly treatments.',
    highlights: ['Design-forward, unique property', 'Private and quiet', 'Convenient location', 'Excellent service', 'In-room safe', 'Solo dining options', 'Spa with solo-friendly treatments'],
    considerations: ['One review mentioned a bit of a sewage smell in the bathroom, but it was resolved', 'Steep spiral staircase could be a problem for elderly or disabled guests'],
    soloFemaleReviews: 'One solo traveler on Booking.com said it was a \'Hideaway in Bali\' and that it was \'overwhelmingly stylish and will mean something different to everyone. They have put so much thought into the design. Staff are next level and authentic rather than stuffy.\'',
    sourcesChecked: ['innspiringtravels.com', 'thebohemianbali.com', 'Google Maps', 'booking.com'],
  },
  {
    name: 'White Penny Hostel',
    googleMapsUrl: 'https://maps.app.goo.gl/wrKz5GmmmLmFZL3x8',
    googlePlaceId: null,
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'seminyak',
    city: 'Seminyak',
    country: 'Indonesia',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: null,
    googleRating: 4.7,
    reviewCount: 146,
    whySelected: 'White Penny Hostel is an excellent choice for solo female travelers, offering dedicated female-only dorms and consistently high ratings for security and cleanliness. Its central location in Seminyak provides easy access to beaches, restaurants, and shops, while the hostel\'s social and welcoming atmosphere makes it easy to connect with fellow travelers.',
    highlights: ['Female-only dorms', '24h reception', 'Central location', 'High security rating', 'Social atmosphere'],
    considerations: ['Can be lively, which might not suit all travelers', 'Some reviews mention noise'],
    soloFemaleReviews: 'My absolute FAVORITE hostel i\'ve ever stayed at. you can tell this place was made by a woman, the bathrooms were amazing, the beds were bigger than most hostels and the rooms were so cute and roomy.',
    sourcesChecked: ['hostelworld.com', 'expedia.com', 'booking.com', 'tripadvisor.com'],
  },
  {
    name: 'Arya Wellness (female only)',
    googleMapsUrl: 'https://www.google.com/maps/dir/?api=1&destination=-8.514377999999999,115.2606304',
    googlePlaceId: null,
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'ubud',
    city: 'Ubud',
    country: 'Indonesia',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: null,
    googleRating: 4.5,
    reviewCount: 222,
    whySelected: 'Arya Wellness is a 5-star, female-only hostel designed for a high-quality, unique experience. It offers a safe, relaxing, and social environment with a focus on wellness and community, making it an ideal choice for solo female travelers.',
    highlights: ['Female-only', '5-star wellness hostel', 'Social and wellness activities (yoga, meditation)', 'Healthy food menu', '24-hour reception', 'Free breakfast and WiFi'],
    considerations: ['May be more expensive than other hostels'],
    soloFemaleReviews: 'Such a lovely place. Came back for a second stay because it has everything you need and the staff makes you feel like you\'re home. This was the most gorgeous hostel I have stayed at! I felt instantly welcome. It is a little oasis. I met some amazing women.',
    sourcesChecked: ['Hostelworld', 'Postcard.inc'],
  },
  {
    name: 'Pecatu Ubud Guest House',
    googleMapsUrl: 'https://maps.google.com/?cid=7584512630358862681',
    googlePlaceId: 'cid:7584512630358862681',
    type: 'homestay',
    originalType: 'guesthouse',
    citySlug: 'ubud',
    city: 'Ubud',
    country: 'Indonesia',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: '22',
    googleRating: 4.6,
    reviewCount: 155,
    whySelected: 'This family-run guesthouse is a great budget option for solo female travelers. It has a friendly and welcoming atmosphere, clean rooms, and a nice pool. While one review mentioned the street can be dark at night, the overwhelming majority of reviews from solo female travelers are positive.',
    highlights: ['Family-run', 'Friendly staff', 'Clean rooms', 'Good breakfast', 'Pool', 'Quiet location'],
    considerations: ['One review mentioned the street gets dark at night'],
    soloFemaleReviews: 'I ended up with 10 days staying in this beautiful place. I always extended. To me IT was perfect: nice big room, comfy bed, nice pool, beautiful terrace, delicious breakfast.',
    sourcesChecked: ['booking.com', 'google reviews'],
  },
  {
    name: 'Greenhost Boutique Hotel',
    googleMapsUrl: 'https://www.google.com/maps/place/Greenhost+Boutique+Hotel+Prawirotaman',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'yogyakarta',
    city: 'Yogyakarta',
    country: 'Indonesia',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '50',
    googleRating: 4.6,
    reviewCount: 2000,
    whySelected: 'Greenhost Boutique Hotel is an excellent mid-range choice for solo female travelers in Yogyakarta. Its unique eco-friendly design, extensive amenities, and consistently positive feedback from other solo female travelers make it a standout option. The hotel\'s location is both safe and convenient, and the staff is renowned for their helpful and welcoming nature.',
    highlights: ['Eco-friendly concept', 'On-site restaurant with vegan/vegetarian options', 'Rooftop garden', 'Swimming pool', 'Spa', 'Co-working space'],
    considerations: ['Rooms are on the smaller side', 'Potential for street noise'],
    soloFemaleReviews: 'Agoda verified solo travelers rate it 9.0; A solo female traveler on Lemon8 praised its value and accessibility; General sentiment points to a safe, walkable location with friendly staff.',
    sourcesChecked: ['greenhosthotel.com', 'tripadvisor.com', 'booking.com', 'agoda.com'],
  },
  {
    name: 'Molah Gili Villa',
    googleMapsUrl: 'https://www.google.com/maps/place/Molah+Gili+Villa/@-8.3626159,116.0831728,17z',
    googlePlaceId: '0x2dcdddcc6dbc3e9f:0xd7c161c5455f585a',
    type: 'hotel',
    originalType: 'hotel',
    citySlug: 'gili-islands',
    city: 'Gili Islands',
    country: 'Indonesia',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: null,
    googleRating: 4.7,
    reviewCount: 119,
    whySelected: 'Molah Gili Villa is a highly-rated, budget-friendly option in a central yet quiet location on Gili Air. It receives excellent reviews for its friendly and helpful staff, clean and comfortable rooms, and beautiful pool area, making it a welcoming and safe choice for solo female travelers.',
    highlights: ['Friendly staff', 'Clean and comfortable rooms', 'Central location', 'Good breakfast', 'Nice pool'],
    considerations: ['Close to a mosque, so the call to prayer can be heard early in the morning'],
    soloFemaleReviews: 'One solo female traveler on Booking.com said: "Staffs warm welcomed me and breakfast was so good. Also room was very comfortable to relaxed."',
    sourcesChecked: ['booking.com', 'tripadvisor', 'google-maps', 'travel blogs'],
  },
  {
    name: 'BASK Gili Meno',
    googleMapsUrl: 'https://www.google.com/maps/place/BASK+Gili+Meno/@-8.350794,116.055196,17z',
    googlePlaceId: '0x2dcde17a4204250d:0x7a1b4f6e6376426e',
    type: 'hotel',
    originalType: 'resort',
    citySlug: 'gili-islands',
    city: 'Gili Islands',
    country: 'Indonesia',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '220',
    googleRating: 4.7,
    reviewCount: 1036,
    whySelected: 'BASK Gili Meno is a luxurious beachfront resort that offers a high-end experience for solo female travelers looking to indulge. The private pool villas provide a safe and secluded environment, while the beach club and underwater speakeasy offer opportunities for socializing.',
    highlights: ['Beachfront location', 'Private pool villas', 'Underwater speakeasy', 'Excellent food and cocktails', 'Friendly and helpful staff'],
    considerations: ['Can be expensive', 'Beach in front can be busy with non-guests', 'No spa on-site'],
    soloFemaleReviews: 'No specific reviews from solo female travelers were found, but the overall positive reviews and features suggest it would be a safe and enjoyable experience.',
    sourcesChecked: ['booking.com', 'tripadvisor', 'google reviews', 'alexa-west.com'],
  },
  {
    name: 'IZE Seminyak',
    googleMapsUrl: 'https://maps.google.com/?cid=10849297982256690636',
    googlePlaceId: 'cid:10849297982256690636',
    type: 'hotel',
    originalType: 'hotel',
    citySlug: 'seminyak',
    city: 'Seminyak',
    country: 'Indonesia',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '90',
    googleRating: 4.6,
    reviewCount: 767,
    whySelected: 'IZE Seminyak is a modern and stylish hotel in a central location, making it a great base for exploring Seminyak. It receives positive reviews from solo travelers who praise the friendly staff and comfortable rooms. The rooftop pool and bar provide a great space to relax and meet other travelers.',
    highlights: ['Modern design', 'Rooftop pool', 'Central location', 'Friendly and helpful staff', 'Free laundry service (5 pieces per day)'],
    considerations: ['The rooftop bar can be slow with service at times', 'Hotel is on a busy road, so there can be some street noise'],
    soloFemaleReviews: 'One solo traveler mentioned that the staff were so nice and helpful that they would stay at IZE again. Another praised the clean, comfortable, and modern room.',
    sourcesChecked: ['lifestyleretreats.com', 'booking.com'],
  },
  {
    name: 'The Patio Yogya',
    googleMapsUrl: 'https://www.google.com/maps/place/The+Patio+Yogya/@-7.8071272,110.3631381,17z',
    googlePlaceId: '0x2e7a579023c31ee7:0x705769ea11b4ccff',
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'yogyakarta',
    city: 'Yogyakarta',
    country: 'Indonesia',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: null,
    googleRating: 4.7,
    reviewCount: 220,
    whySelected: 'The Patio Yogya is a highly-rated hostel with excellent reviews from solo travelers. It is located in a central and safe area, and the staff is known for being friendly and helpful. While it doesn\'t explicitly offer female-only dorms, the overall positive feedback from solo female travelers makes it a strong recommendation.',
    highlights: ['24h reception', 'Central location', 'Quiet and safe area', 'Friendly and helpful staff', 'Clean rooms and common areas'],
    considerations: ['No explicit female-only dorms, but solo female traveler reviews are positive'],
    soloFemaleReviews: 'I\'m very glad I went with The Patio for my first stay in Jogja as a solo traveller. The spaces are clean, the staff is friendly...',
    sourcesChecked: ['hostelworld.com', 'booking.com', 'tripadvisor.com', 'google.com'],
  },

  // ==========================================================================
  // JAPAN
  // ==========================================================================
  {
    name: 'Guesthouse Soi',
    googleMapsUrl: 'https://www.google.com/maps/dir//Guesthouse+Soi,+509-2+Shimoumacho,+Higashiyama+Ward,+Kyoto',
    googlePlaceId: '0x600108cc4f6a4277:0x3ecc2e8d49560c37',
    type: 'homestay',
    originalType: 'guesthouse',
    citySlug: 'kyoto',
    city: 'Kyoto',
    country: 'Japan',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: '45',
    googleRating: 4.8,
    reviewCount: 453,
    whySelected: 'Guesthouse Soi is a female-owned guesthouse with a welcoming and friendly atmosphere, making it an excellent budget-friendly choice for solo female travelers. The owner, Maki-san, is highly praised for her hospitality, and the guesthouse has a strong sense of community. Its location in the historic Higashiyama district is also a major plus.',
    highlights: ['Female-owned', 'Welcoming and friendly atmosphere', 'Excellent staff', 'Very clean'],
    considerations: ['Shared bathrooms', 'Located on a hill, which might be a consideration for those with mobility issues'],
    soloFemaleReviews: 'One solo female traveler on Agoda said, \'As a solo female travellers I found this location perfect.\' Other solo travelers have praised the friendly staff and comfortable rooms.',
    sourcesChecked: ['booking.com', 'agoda.com', 'blossomkitty.com', 'guesthousesoi.com', 'google maps'],
  },
  {
    name: 'The Lively Osaka Honmachi',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=The+Lively+Osaka+Honmachi',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'osaka',
    city: 'Osaka',
    country: 'Japan',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '150',
    googleRating: 4.5,
    reviewCount: 429,
    whySelected: 'The Lively Osaka Honmachi is an excellent mid-range option for solo female travelers seeking a stylish and social atmosphere. Its central location in a quieter business district, coupled with its proximity to the subway, offers both convenience and a sense of security. The hotel\'s multiple common areas, including a rooftop bar, and the popular free beer hour, provide ample opportunities for guests to connect.',
    highlights: ['Stylish and modern design', 'Social atmosphere with multiple common areas', 'Rooftop bar with city views', 'Free beer hour', 'Close to subway station'],
    considerations: ['Some reviews mention noise from the hallway and adjacent rooms', 'Breakfast is considered a bit expensive by some guests'],
    soloFemaleReviews: 'Overwhelmingly positive reviews from solo female travelers praise the stylish design, clean and comfortable rooms, convenient location, and social common areas. No safety concerns or mentions of harassment were found.',
    sourcesChecked: ['booking.com', 'tripadvisor', 'google reviews', 'agoda', 'expedia'],
  },
  {
    name: 'TRUNK(HOTEL) CAT STREET',
    googleMapsUrl: 'https://www.google.com/maps/place/TRUNK(HOTEL)/@35.667958,139.707421,17z',
    googlePlaceId: '0x60188ca61535c86d:0x783394c3c2a4bb4f',
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'tokyo',
    city: 'Tokyo',
    country: 'Japan',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '400',
    googleRating: 4.5,
    reviewCount: 1059,
    whySelected: 'TRUNK(HOTEL) CAT STREET is a great option for a solo female traveler looking for a stylish and social experience in a prime Tokyo location. The hotel\'s focus on design, community, and local culture creates a unique and engaging atmosphere.',
    highlights: ['Stylish, modern design with upcycled materials and local art', 'Excellent location in Shibuya, near Harajuku', 'Buzzing, vibrant atmosphere', 'Friendly and helpful staff', 'All-day restaurant and bar with terrace seating'],
    considerations: ['Rooms may be smaller than expected', 'Lobby can be crowded with people who are not hotel guests'],
    soloFemaleReviews: 'One solo traveler on booking.com said the location was amazing and the staff were friendly.',
    sourcesChecked: ['michelin.com', 'booking.com', 'google reviews'],
  },

  // ==========================================================================
  // LAOS
  // ==========================================================================
  {
    name: 'Luang Prabang Oudomlith Villa & Travel',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Luang+Prabang+Oudomlith+Villa',
    googlePlaceId: null,
    type: 'homestay',
    originalType: 'guesthouse',
    citySlug: 'luang-prabang',
    city: 'Luang Prabang',
    country: 'Laos',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: '30',
    googleRating: 4.5,
    reviewCount: 506,
    whySelected: 'Luang Prabang Oudomlith Villa & Travel is a fantastic budget-friendly option for solo female travelers. Its excellent location, combined with a high number of positive reviews praising the helpful and friendly staff, makes it a safe and convenient choice. The 24-hour front desk and proactive security measures are strong indicators of a safe and welcoming environment.',
    highlights: ['Excellent location', 'Friendly and helpful staff', '24-hour front desk', 'Luggage storage'],
    considerations: ['No specific solo female traveler reviews, but many positive reviews about helpful staff'],
    soloFemaleReviews: 'While there are no specific reviews from solo female travelers, many reviews praise the friendly and helpful staff. The 24-hour front desk and luggage storage add to the sense of security.',
    sourcesChecked: ['booking.com'],
  },
  {
    name: 'Mad Monkey Luang Prabang',
    googleMapsUrl: 'https://www.google.com/maps/place/Mad+Monkey+Luang+Prabang/@19.88481,102.13861,17z',
    googlePlaceId: '0x312845a965885c3f:0x8f047a57c5c3b5f6',
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'luang-prabang',
    city: 'Luang Prabang',
    country: 'Laos',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: null,
    googleRating: 4.2,
    reviewCount: 352,
    whySelected: 'Mad Monkey is a great option for a social solo female traveler on a budget. The availability of female-only dorms, a high security rating, and the \'Ask for Angela\' safety initiative make it a secure choice.',
    highlights: ['Female-only dorms', 'High security rating on Hostelworld (9.6/10)', 'Social atmosphere with nightly events', 'Pool with a view', '\'Ask for Angela\' initiative for safety', '24-hour reception'],
    considerations: ['Party hostel reputation may not suit all travelers', 'Location is a 20-minute walk from the city center', 'Some reviews mention only one shower and toilet for a 12-bed dorm'],
    soloFemaleReviews: 'A solo female traveler on Reddit reported a positive experience, and a Facebook commenter described the hostel as \'clean and safe.\'',
    sourcesChecked: ['madmonkeyhostels.com', 'hostelworld.com', 'booking.com', 'tripadvisor.com', 'reddit.com'],
  },
  {
    name: 'Tmark Resort Vangvieng',
    googleMapsUrl: 'https://www.google.com/maps/place/Tmark+Resort+Vangvieng/@18.9153418,102.4417301,17z',
    googlePlaceId: '0x312592d749f5ceef:0xf513cc3623452a1',
    type: 'hotel',
    originalType: 'resort',
    citySlug: 'vang-vieng',
    city: 'Vang Vieng',
    country: 'Laos',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '95',
    googleRating: 4.6,
    reviewCount: 387,
    whySelected: 'Tmark Resort Vangvieng is a modern resort with excellent amenities, including a large pool and a spa. It receives consistently high ratings for cleanliness and staff friendliness. While slightly outside the main town, the free shuttle service makes it easy to get around.',
    highlights: ['Great views', 'Clean', 'Friendly staff', 'Good breakfast', 'Shuttle service'],
    considerations: ['A bit outside of town'],
    soloFemaleReviews: 'Found a few positive reviews from solo female travelers on Booking.com. One mentioned feeling safe and another recommended the hotel.',
    sourcesChecked: ['girltakesmundo.com', 'booking.com', 'google maps', 'tripadvisor.com'],
  },
  {
    name: 'SYRI Guesthouse',
    googleMapsUrl: 'https://www.google.com/maps?cid=2428223339089603548',
    googlePlaceId: 'cid:2428223339089603548',
    type: 'homestay',
    originalType: 'guesthouse',
    citySlug: 'vientiane',
    city: 'Vientiane',
    country: 'Laos',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: '25',
    googleRating: 4.3,
    reviewCount: 254,
    whySelected: 'SYRI Guesthouse is an excellent budget-friendly option for solo female travelers. It is located in a safe, central, and quiet area, and the staff is known for being friendly and helpful. The rooms are clean and comfortable, making it a great value for the price.',
    highlights: ['Friendly, attentive staff', 'Quiet yet central location', 'Clean and comfortable rooms', 'Affordable rates'],
    considerations: ['Rooms are simple and may lack some amenities of more expensive hotels'],
    soloFemaleReviews: 'The travel blog \'Orlagh Claire\' is written by a solo female traveler who highly recommends the guesthouse. She states: \'During my recent trip to Laos, I spent two nights at Syri Guesthouse Vientiane and was pleasantly surprised by the comfort, cleanliness, and charm this little gem offered.\'',
    sourcesChecked: ['orlaghclaire.com', 'booking.com', 'tripadvisor.com', 'google reviews'],
  },
  {
    name: 'Barn1920s Hostel',
    googleMapsUrl: 'https://www.google.com/maps/?cid=17422442039236821992',
    googlePlaceId: 'cid:17422442039236821992',
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'vientiane',
    city: 'Vientiane',
    country: 'Laos',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: null,
    googleRating: 4.4,
    reviewCount: 258,
    whySelected: 'Barn1920s Hostel is a great option for solo female travelers due to its dedicated female-only dorms, excellent security rating, and central location. The in-house cafe and shared lounge provide opportunities to meet other travelers, and the 24-hour check-in is a significant plus for arrivals at odd hours.',
    highlights: ['Female-only dorms', '24h check-in', 'Central location', 'In-house cafe'],
    considerations: ['Some reviews mention hard beds', 'Breakfast is self-cooked', 'Not a very social atmosphere'],
    soloFemaleReviews: 'A female solo traveler on Hostelworld mentioned that she \'liked how the girls dorms were away and up the stairs\'. Another review from a female traveler on Agoda said the \'room is very clean, staff are very nice and service minded.\'',
    sourcesChecked: ['agoda.com', 'hostelworld.com', 'google.com'],
  },

  // ==========================================================================
  // MALAYSIA
  // ==========================================================================
  {
    name: 'Faloe Hostel',
    googleMapsUrl: 'https://www.google.com/maps/search/Faloe+Hostel+Kota+Kinabalu',
    googlePlaceId: null,
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'kota-kinabalu',
    city: 'Kota Kinabalu',
    country: 'Malaysia',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: null,
    googleRating: 4.9,
    reviewCount: 208,
    whySelected: 'Faloe Hostel is a top-rated choice for solo female travelers due to its dedicated female-only dorms, exceptional security, and overwhelmingly positive reviews from other women. The modern and clean environment, coupled with a central location and friendly staff, ensures a safe and enjoyable stay.',
    highlights: ['Female-only dorms', 'Excellent security', 'Modern design', 'Free breakfast'],
    considerations: ['No elevator', 'Shared bathrooms'],
    soloFemaleReviews: 'The stay here was wonderful! The staff were so friendly and helpful, and the hostel felt very clean and well organized. This is one of the nicest places I\'ve stayed.',
    sourcesChecked: ['hostelworld', 'booking.com', 'tripadvisor', 'google'],
  },
  {
    name: 'Shangri-La Tanjung Aru, Kota Kinabalu',
    googleMapsUrl: 'https://www.google.com/maps/place/Shangri-La+Tanjung+Aru,+Kota+Kinabalu/@5.9559507,116.0471964,17z',
    googlePlaceId: '0x323b69c0d7ffffff:0x8a68cb3f3a4e7c3c',
    type: 'hotel',
    originalType: 'resort',
    citySlug: 'kota-kinabalu',
    city: 'Kota Kinabalu',
    country: 'Malaysia',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '216',
    googleRating: 4.6,
    reviewCount: 781,
    whySelected: 'The Shangri-La Tanjung Aru is a luxury resort that offers a high level of comfort and security for solo female travelers. Its extensive amenities, including a spa, multiple restaurants, and a large pool area, provide ample opportunities for relaxation and enjoyment within the resort.',
    highlights: ['Private marina', 'Spa', 'Multiple restaurants', 'Large pool area', 'Close to airport'],
    considerations: ['Some reviews mention dated furniture and slow service in restaurants'],
    soloFemaleReviews: 'While I haven\'t found specific reviews from solo female travelers, the hotel\'s amenities and secure location make it a strong candidate.',
    sourcesChecked: ['google reviews', 'tripadvisor', 'booking.com', 'lajollamom.com'],
  },
  {
    name: 'Sunshine Bedz KL',
    googleMapsUrl: 'https://maps.app.goo.gl/AUAbtTfvENMfH4RQ6',
    googlePlaceId: null,
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'kuala-lumpur',
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: null,
    googleRating: 4.6,
    reviewCount: 686,
    whySelected: 'Sunshine Bedz KL is a highly-rated hostel in a central location, making it a great choice for solo female travellers. It has a 9.4 security rating on Hostelworld and offers female-only dorms. The hostel is known for its social atmosphere and friendly staff.',
    highlights: ['Female-only dorms', '24h reception', 'Central location', 'Social atmosphere'],
    considerations: ['Limited reception hours (8am-5pm), but self-check-in can be arranged', 'No curtains on the beds'],
    soloFemaleReviews: 'Fantastic place to stay as a solo female traveller in a big city! Great location, close to most of the touristy places! Very easy to meet others.',
    sourcesChecked: ['hostelworld.com', 'tripadvisor.com', 'google.com/maps'],
  },
  {
    name: 'The Chow Kit - an Ormond Hotel',
    googleMapsUrl: 'https://maps.google.com/?cid=10120217103685249563',
    googlePlaceId: 'cid:10120217103685249563',
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'kuala-lumpur',
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '75',
    googleRating: 4.4,
    reviewCount: 1100,
    whySelected: 'The Chow Kit offers a unique and stylish boutique hotel experience at a mid-range price point. Its focus on local culture and design provides a more authentic Kuala Lumpur experience for the solo female traveler. While the neighborhood has a gritty reputation, the hotel itself is a safe and welcoming oasis.',
    highlights: ['Stylish design', 'Awarded Malaysia\'s Best Boutique Hotel', 'In-house restaurant serving local cuisine', 'Walking tours of the neighborhood'],
    considerations: ['The hotel is located in the Chow Kit neighborhood, which has a reputation for being gritty, though it is undergoing gentrification'],
    soloFemaleReviews: 'While direct quotes from solo female travelers are not readily available, the hotel\'s positive reviews and organized walking tours suggest a welcoming environment for solo explorers.',
    sourcesChecked: ['hellokualalumpur.com', 'tripadvisor.com', 'booking.com', 'thechowkit.com'],
  },
  {
    name: 'Bunga Hostel',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Bunga+Hostel+Langkawi',
    googlePlaceId: null,
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'langkawi',
    city: 'Langkawi',
    country: 'Malaysia',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: null,
    googleRating: 4.4,
    reviewCount: 101,
    whySelected: 'Bunga Hostel is a new, female-only hostel that offers a safe and welcoming environment for solo female travelers. Its location near Cenang Beach provides easy access to shops, restaurants, and the beach, while the on-site co-working space is a great perk for digital nomads.',
    highlights: ['Female-only dorms', '24h reception', 'Central location', 'Co-working space'],
    considerations: ['No private rooms available'],
    soloFemaleReviews: 'One guest on Booking.com said, \'It was my favorite hostel in all of my travels. I met really cool girls and the owner is a local girl too! The bathrooms are really nice.\'',
    sourcesChecked: ['hostelz.com', 'booking.com', 'tripadvisor.co.uk'],
  },
  {
    name: 'The Danna Langkawi',
    googleMapsUrl: 'https://www.google.com/maps/place/The+Danna+Langkawi/@6.3677477,99.6813659,17z',
    googlePlaceId: '0x304c7702fcfbd8af:0x4dfec21834efe3c2',
    type: 'hotel',
    originalType: 'resort',
    citySlug: 'langkawi',
    city: 'Langkawi',
    country: 'Malaysia',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '424',
    googleRating: 4.8,
    reviewCount: 2340,
    whySelected: 'The Danna Langkawi is a luxurious resort with a strong focus on guest safety and security. It offers a high-end experience with excellent service, making it a great option for solo female travelers looking for a premium stay.',
    highlights: ['Member of Small Luxury Hotels of the World', 'Private beach access', 'Award-winning spa', 'Multiple dining options'],
    considerations: ['High price point', 'Sea near the hotel may not be ideal for swimming'],
    soloFemaleReviews: 'General reviews are overwhelmingly positive, with a strong emphasis on safety and excellent service, which are key for solo female travelers.',
    sourcesChecked: ['tripadvisor.com', 'thedanna.com', 'google.com/maps'],
  },
  {
    name: 'Yote 28',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Yote+28+Malacca',
    googlePlaceId: null,
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'malacca',
    city: 'Malacca',
    country: 'Malaysia',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: null,
    googleRating: 4.7,
    reviewCount: 278,
    whySelected: 'Yote 28 is a modern and stylish hostel with female-only dorms, which is a huge plus for solo female travelers. It has excellent reviews, a high security rating, and is located in a central area, making it a great base for exploring Malacca.',
    highlights: ['Female-only dorms', 'Modern and clean', 'Good for solo travelers', 'Great location'],
    considerations: ['Some reviews mention that it can be a bit of a walk to some attractions'],
    soloFemaleReviews: 'Really clean, beautiful and affordable hostel. I loved the pods that gave some privacy. Kitchen had great facilities.',
    sourcesChecked: ['Hostelworld', 'Google Maps'],
  },
  {
    name: 'Gingerflower Boutique Hotel',
    googleMapsUrl: 'https://maps.app.goo.gl/MJHpDrLd9onoRGCX9',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'malacca',
    city: 'Malacca',
    country: 'Malaysia',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '45',
    googleRating: 4.3,
    reviewCount: 709,
    whySelected: 'The Gingerflower Boutique Hotel is a great option for solo female travelers looking for a mid-range boutique hotel in Malacca. It is located in the heart of the city, within walking distance of all the major attractions. The hotel has excellent reviews, with many guests praising the friendly and helpful staff.',
    highlights: ['Great location', 'Friendly and helpful staff', 'Clean and well-maintained', 'Charming and historic building'],
    considerations: ['Some rooms are small'],
    soloFemaleReviews: 'Perfect location in the old city of Melaka',
    sourcesChecked: ['booking.com', 'google reviews', 'lemon8-app.com'],
  },
  {
    name: 'Sogor Female Dormitory',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Sogor+Female+Dormitory%2C+Penang',
    googlePlaceId: null,
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'penang',
    city: 'Penang',
    country: 'Malaysia',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: null,
    googleRating: 4.8,
    reviewCount: 173,
    whySelected: 'This is a highly-rated, female-only dormitory that receives exceptional reviews for its cleanliness, comfort, and welcoming atmosphere. The manager, CP, is repeatedly praised for her hospitality, making it a top choice for solo female travelers seeking a safe and friendly environment.',
    highlights: ['Female-only', 'Exceptionally clean', 'Friendly and helpful staff', 'Spacious', 'Free laundry (tip-based)'],
    considerations: ['No specific mention of lockers or 24h reception, but the female-only nature and overwhelmingly positive reviews about safety provide strong reassurance'],
    soloFemaleReviews: 'I would give this place more than 10 stars if I could. The manager, CP, really leads from the heart. She wants to make your stay the best...',
    sourcesChecked: ['booking.com', 'agoda.com', 'tripadvisor.com'],
  },
  {
    name: 'Campbell House',
    googleMapsUrl: 'https://www.google.com/maps/search/Campbell+House+Penang',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'penang',
    city: 'Penang',
    country: 'Malaysia',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '122',
    googleRating: 4.7,
    reviewCount: 556,
    whySelected: 'Campbell House is a highly-rated boutique hotel in the heart of George Town, offering a safe and welcoming environment for solo female travelers. Its central location allows for easy exploration of the city\'s attractions on foot, and the small, intimate setting with a female co-owner fosters a sense of security and personalized service.',
    highlights: ['Female co-owner', 'Centrally located', 'Walkable to attractions', 'Friendly and helpful staff', 'Intimate atmosphere', 'On-site Italian restaurant'],
    considerations: ['The hotel is in a historic building, so some rooms may be smaller than modern hotels'],
    soloFemaleReviews: 'A solo female travel blogger highly recommended the hotel, noting that she met other solo female travelers during her stay and that the owner confirmed they frequently host solo women.',
    sourcesChecked: ['rockytravel.net', 'campbellhousepenang.com', 'google reviews', 'tripadvisor'],
  },

  // ==========================================================================
  // MOROCCO
  // ==========================================================================
  {
    name: 'Lina Ryad & Spa',
    googleMapsUrl: 'https://maps.app.goo.gl/rC6iFuuFhKh1s4Qv9',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'chefchaouen',
    city: 'Chefchaouen',
    country: 'Morocco',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '278',
    googleRating: 4.5,
    reviewCount: 877,
    whySelected: 'Lina Ryad & Spa is a luxury boutique hotel that offers a safe and welcoming environment for solo female travelers. Its central location in the medina, combined with amenities like a spa and indoor pool, provides a comfortable and relaxing base for exploring Chefchaouen.',
    highlights: ['Spa with hammam', 'Indoor pool', 'Central location in the medina', 'Rooftop terrace with views'],
    considerations: ['Can be noisy', 'Many stairs to access the property and rooms'],
    soloFemaleReviews: 'A review from a solo traveler mentioned feeling safe and another praised the welcoming staff during a solo spa visit.',
    sourcesChecked: ['booking.com', 'tripadvisor', 'google reviews'],
  },
  {
    name: 'Dar Seffarine',
    googleMapsUrl: 'https://www.google.com/maps/place/Dar+Seffarine',
    googlePlaceId: '0xd9f8b3be5a78a6d:0x8e2339f6f1f23f4c',
    type: 'homestay',
    originalType: 'guesthouse',
    citySlug: 'fes',
    city: 'Fes',
    country: 'Morocco',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '126',
    googleRating: 4.8,
    reviewCount: 183,
    whySelected: 'Dar Seffarine is a stunningly beautiful and historic riad that offers a truly authentic Moroccan experience. The staff is consistently praised for their warmth and hospitality, making guests feel like family. While its location deep in the medina can be challenging to navigate, the riad staff are happy to arrange for guides and transportation.',
    highlights: ['Stunning 600-year-old architecture', 'Exceptionally warm and helpful staff', 'Delicious communal dinners', 'Beautiful rooftop terrace with city views'],
    considerations: ['Location is deep in the medina and can be difficult to find', 'Some reviews mention that the beds are not the most comfortable', 'Basic toiletries'],
    soloFemaleReviews: 'While there are no reviews specifically from solo female travelers, the overall sentiment is extremely positive. Many reviews praise the warm, welcoming, and helpful staff, with one guest saying they felt like they were "staying with family."',
    sourcesChecked: ['booking.com', 'tripadvisor', 'google reviews', 'travel blogs'],
  },
  {
    name: 'Riad Star',
    googleMapsUrl: 'https://maps.google.com/?cid=5079410',
    googlePlaceId: 'cid:5079410',
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'marrakech',
    city: 'Marrakech',
    country: 'Morocco',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '150',
    googleRating: 4.5,
    reviewCount: 361,
    whySelected: 'Riad Star is a great option for solo female travelers due to its central location in the Medina, helpful staff, and amenities like an in-room safe and a navigation app. The riad has a history of hosting solo female travelers and has received positive reviews from them.',
    highlights: ['Former home of Josephine Baker', 'Rooftop terrace', 'Hammam and spa', 'Navigation app', 'English-speaking staff'],
    considerations: ['Located in the Medina, which can be overwhelming for some travelers'],
    soloFemaleReviews: 'The first reason why Riad Star is a fantastic option for solo female travelers is that it is located oh so conveniently in the heart of the Medina.',
    sourcesChecked: ['thekatieshowblog.com', 'riadstar.com', 'booking.com'],
  },

  // ==========================================================================
  // MYANMAR
  // ==========================================================================
  {
    name: 'Bagan Cottage Boutique Hotel',
    googleMapsUrl: 'https://www.google.com/maps/place/Bagan+Cottage+Boutique+Hotel/@21.1736386,94.9228362,17z',
    googlePlaceId: '0x30b5fb934d755b39:0xd1e6b028a9bcf8fb',
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'bagan',
    city: 'Bagan',
    country: 'Myanmar',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '56',
    googleRating: 4.8,
    reviewCount: 58,
    whySelected: 'This family-owned boutique hotel offers a peaceful and serene environment, perfect for solo female travelers looking for a relaxing getaway. The spacious and clean rooms, along with the attentive and friendly staff, contribute to a safe and comfortable stay.',
    highlights: ['Family-owned', 'Quiet and serene environment', 'Spacious and clean rooms', 'Attentive and friendly staff', 'On-site spa services', 'Delicious home-cooked meals'],
    considerations: ['Wi-Fi and cell service can be unstable, which is common in Myanmar'],
    soloFemaleReviews: 'While there are no explicit reviews from solo female travelers, the overall positive sentiment regarding safety, helpful staff, and a quiet atmosphere suggests it would be a suitable choice.',
    sourcesChecked: ['booking.com', 'google reviews'],
  },
  {
    name: 'BaobaBed Hostel Bagan',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=BaobaBed+Hostel+Bagan',
    googlePlaceId: null,
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'bagan',
    city: 'Bagan',
    country: 'Myanmar',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: null,
    googleRating: 4.3,
    reviewCount: 191,
    whySelected: 'BaobaBed Hostel is highly recommended for solo female travelers due to its dedicated female-only dormitories, which provide a safe and comfortable environment. The hostel also fosters a social atmosphere with organized activities and a rooftop pool, making it easy to meet other travelers.',
    highlights: ['Female-only dorms', 'Swimming pool', '24h reception', 'Free breakfast', 'Social events and tours'],
    considerations: ['Slightly more expensive than other hostels in Bagan', 'One review mentioned a theft, so using lockers is recommended'],
    soloFemaleReviews: 'A solo female traveler from India praised the hostel for its clean female-only dorms, helpful staff, and the unique feature of a separate dorm for early arrivals and late departures.',
    sourcesChecked: ['backpackerswanderlust.com', 'agoda.com', 'tripadvisor.com', 'google.com'],
  },
  {
    name: 'May Guesthouse',
    googleMapsUrl: 'https://www.google.com/maps/place/May+Guesthouse/@20.659869,96.934114,17z',
    googlePlaceId: '0x30cebcf7a6e5a5c7:0x8d7c3b034b7a79a3',
    type: 'homestay',
    originalType: 'guesthouse',
    citySlug: 'inle-lake',
    city: 'Inle Lake',
    country: 'Myanmar',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: '15',
    googleRating: 4.5,
    reviewCount: 100,
    whySelected: 'May Guesthouse is a great budget-friendly option for solo female travelers looking for a safe and welcoming place to stay. Its family-run, homestay-like atmosphere and quiet location provide a sense of security.',
    highlights: ['Family-run with a homestay feel', 'Quiet location', 'Good value for the price'],
    considerations: ['Rooms are basic and walls are thin', 'Not a luxury option'],
    soloFemaleReviews: 'Travelfish recommends it for single travellers, noting the friendly family and quiet location.',
    sourcesChecked: ['Travelfish', 'Agoda', 'Booking.com', 'Google Maps'],
  },
  {
    name: "Governor's Residence",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Governor's+Residence+Yangon",
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'yangon',
    city: 'Yangon',
    country: 'Myanmar',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '125',
    googleRating: 4.6,
    reviewCount: 485,
    whySelected: "The Governor's Residence is a luxurious and historic boutique hotel in a safe and quiet area of Yangon. It offers a high level of service and amenities, including a spa and multiple dining options, making it a comfortable and secure choice for a solo female traveler looking for an upscale experience.",
    highlights: ['Historic colonial mansion', 'Lush gardens and pool', 'Spa and wellness facilities', 'Multiple dining options', 'Highly-rated staff'],
    considerations: ['Limited gym facilities', 'Some reports of mosquitos'],
    soloFemaleReviews: 'A TripAdvisor review from a solo female traveler highlighted the quiet location, lush vegetation, well-equipped room, and highly qualified staff.',
    sourcesChecked: ['secret-retreats.com', 'booking.com', 'tripadvisor.com', 'google reviews'],
  },

  // ==========================================================================
  // PHILIPPINES
  // ==========================================================================
  {
    name: 'Abraham Bohol',
    googleMapsUrl: 'https://maps.google.com/?cid=5776378529591829054',
    googlePlaceId: 'cid:5776378529591829054',
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'bohol',
    city: 'Bohol',
    country: 'Philippines',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: null,
    googleRating: 4.7,
    reviewCount: 845,
    whySelected: "Abraham Bohol is a highly-rated hostel with female-only dorms, making it a great option for solo female travelers. It's conveniently located near the airport and Alona Beach, and offers a variety of amenities, including two swimming pools and a travel center for booking tours.",
    highlights: ['Female-only dorms', '2 swimming pools', '24h reception', 'Central location', 'Social atmosphere', 'Tour booking service'],
    considerations: ['Can be noisy due to the social atmosphere'],
    soloFemaleReviews: "At Abraham's female-only dorms, we believe in making every moment count. From unforgettable nights out to thrilling adventures, we create a space where women can connect, explore, and feel empowered.",
    sourcesChecked: ['booking.com', 'hostelworld', 'tripadvisor', 'google.com', 'abraham.travel'],
  },
  {
    name: 'Amorita Resort',
    googleMapsUrl: 'https://www.google.com/maps?daddr=Amorita+Resort,+1+Ester+A.+Lim+Drive,+Alona+Beach+Rd',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'resort',
    citySlug: 'bohol',
    city: 'Bohol',
    country: 'Philippines',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '250',
    googleRating: 4.6,
    reviewCount: 1372,
    whySelected: 'Amorita Resort is a top-rated luxury resort in a prime location on Panglao Island. It offers a safe and tranquil environment with excellent amenities, making it a great option for solo female travelers looking for an upscale experience.',
    highlights: ['Award-winning luxury resort', 'Two infinity pools', 'Spa and gym', 'Sustainable practices (ASEAN Green Hotel Award Hall of Famer)', 'Cliffside location with great views', 'Close to Alona Beach but secluded'],
    considerations: ["Some reviews mention a 'moldy smell' in rooms", 'Inconsistent Wi-Fi', 'Can be expensive'],
    soloFemaleReviews: 'While specific reviews from solo female travelers were not found, the general consensus points to a high level of service and a safe, relaxing environment.',
    sourcesChecked: ['amoritaresort.com', 'booking.com', 'agoda.com', 'Google Maps', 'travel blogs'],
  },
  {
    name: 'Public House Hostel',
    googleMapsUrl: 'https://maps.app.goo.gl/zmYptrSNW6ywzXVe7',
    googlePlaceId: null,
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'cebu',
    city: 'Cebu',
    country: 'Philippines',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: null,
    googleRating: 4.7,
    reviewCount: 36,
    whySelected: 'Public House Hostel is a great choice for solo female travelers due to its excellent security rating and positive reviews from other women. Its proximity to the airport makes it a convenient option for late arrivals or early departures.',
    highlights: ['Close to the airport', 'High security rating', 'On-site spa and cafe', 'Clean and comfortable beds with privacy curtains'],
    considerations: ['No female-only dorms', 'Located on a loud street'],
    soloFemaleReviews: "My favourite hostel that I've stayed in while travelling SE Asia so far. Comfortable rooms, great facilities, the staff made us feel so welcome. - Hannah, Female, 25-30, Ireland",
    sourcesChecked: ['hostelworld.com', 'booking.com', 'agoda.com', 'Google Maps'],
  },
  {
    name: 'The Henry Hotel Cebu',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=The+Henry+Hotel+Cebu',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'cebu',
    city: 'Cebu',
    country: 'Philippines',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '100',
    googleRating: 4.5,
    reviewCount: 1000,
    whySelected: "The Henry Hotel Cebu is a great mid-range option for solo female travelers looking for a unique and comfortable stay. The hotel's artsy design and spacious rooms provide a welcoming atmosphere, while the friendly staff and safe location in Banilad offer peace of mind.",
    highlights: ['Unique and artsy design', 'Spacious rooms', 'Comfortable beds', 'Friendly staff', 'Quiet pool'],
    considerations: ['Some reviews mention that the pool needs improvement'],
    soloFemaleReviews: "The hotel's unique character and comfortable rooms could provide a welcoming and relaxing environment for a solo traveler. The location in Banilad is generally considered safe.",
    sourcesChecked: ['agoda.com', 'tripadvisor.com'],
  },
  {
    name: 'Spin Designer Hostel',
    googleMapsUrl: 'https://www.google.com/travel/hotels/entity/ChkIifuIjpqJ1rcLGg0vZy8xMWJ3MXp4cW1sEAE',
    googlePlaceId: null,
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'el-nido',
    city: 'El Nido',
    country: 'Philippines',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: null,
    googleRating: 4.4,
    reviewCount: 576,
    whySelected: 'Spin Designer Hostel is an excellent choice for solo female travelers due to its dedicated female-only dorms, strong security measures, and overwhelmingly positive reviews from other solo women. The hostel\'s central location, combined with its social atmosphere and organized events, provides a safe and welcoming environment.',
    highlights: ['Female-only dorms', '24h reception', 'Central location', 'Social events', 'Communal kitchen', 'Free Wi-Fi'],
    considerations: ['Can be noisy due to social events', 'Some reviews mention cold showers in the female dorms'],
    soloFemaleReviews: 'Wow! Clean, comfortable, great price, amazing breakfast buffet. I honestly liked everything about Spin Designer Hostel.',
    sourcesChecked: ['hostelz.com', 'booking.com', 'tripadvisor.com', 'google.com'],
  },
  {
    name: 'The Funny Lion - El Nido',
    googleMapsUrl: 'https://www.google.com/maps/place/The+Funny+Lion+-+El+Nido/@11.182165,119.389101,17z',
    googlePlaceId: '0x33b5821081794039:0x99544c7033779521',
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'el-nido',
    city: 'El Nido',
    country: 'Philippines',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '250',
    googleRating: 5,
    reviewCount: 2661,
    whySelected: 'The Funny Lion - El Nido is a highly-rated boutique hotel with a strong emphasis on guest experience and personalized service, making it a great choice for solo female travelers. The hotel\'s location is central and convenient, and the staff is consistently praised for being attentive and helpful.',
    highlights: ['Excellent staff and service', 'Great location', 'Private beach', 'Spa and wellness facilities', 'Good food and dining options'],
    considerations: ['Can be pricey compared to other options in the area'],
    soloFemaleReviews: 'While no explicit reviews from solo female travelers were found, the overwhelming positive sentiment regarding the attentive and personalized service from the staff suggests a safe and welcoming environment.',
    sourcesChecked: ['booking.com', 'tripadvisor', 'google reviews'],
  },
  {
    name: 'The Picasso Boutique Serviced Residences',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=The+Picasso+Boutique+Serviced+Residences',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'manila',
    city: 'Manila',
    country: 'Philippines',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '85',
    googleRating: 4.4,
    reviewCount: 1162,
    whySelected: 'Located in the safe and walkable Salcedo Village in Makati, this hotel receives positive reviews for its spacious, art-themed rooms and helpful staff. Its location is convenient for exploring the city, with many restaurants and shops nearby.',
    highlights: ['Art gallery on site', 'Spacious rooms with kitchenettes', 'In-room safe', 'Fitness center', 'Good location in a safe neighborhood'],
    considerations: ['Some reviews mention that the breakfast is basic', 'Some reviews mention worn-out towels and issues with room maintenance'],
    soloFemaleReviews: "'You can safely walk around here, even if you're a solo female traveler, and that's always important for me.'",
    sourcesChecked: ['google reviews', 'tripadvisor'],
  },
  {
    name: 'Lub d Manila Makati',
    googleMapsUrl: 'https://www.google.com/maps/place/Lub+d+Philippines+Makati/@14.564659,121.028845,17z',
    googlePlaceId: null,
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'manila',
    city: 'Manila',
    country: 'Philippines',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: null,
    googleRating: 4,
    reviewCount: 9853,
    whySelected: 'Lub d Manila Makati is an excellent choice for solo female travelers due to its dedicated female-only dorms, which provide a safe and comfortable environment. The hostel has outstanding security, with a 10/10 rating on Hostelworld, and 24-hour reception. Its central location in the vibrant Poblacion district offers easy access to restaurants, nightlife, and public transport.',
    highlights: ['Female-only dorms', '24h reception', 'Central location', 'Rooftop bar and restaurant', 'Co-working space'],
    considerations: ['Can be noisy due to its location in a lively area', 'Some reviews mention that the social atmosphere can be lacking at times'],
    soloFemaleReviews: "It was my first time sleeping on a dorm type room, I booked this around 2am in the morning. I got the last bed on the room. I am happy I got a good sleep.",
    sourcesChecked: ['hostelworld.com', 'booking.com', 'agoda.com', 'tripadvisor.com', 'lubd.com'],
  },
  {
    name: 'Hostel Bajala Siargao',
    googleMapsUrl: 'https://www.google.com/maps/place/Hostel+Bajala+Siargao/@9.794795,126.15781,17z',
    googlePlaceId: '0x3304062a470373ab:0x5b3db7a8583c70c3',
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'siargao',
    city: 'Siargao',
    country: 'Philippines',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: null,
    googleRating: 4.8,
    reviewCount: 251,
    whySelected: 'Hostel Bajala Siargao is an excellent choice for solo female travelers due to its female-only dormitories, which have received positive reviews for safety and thoughtful design. The hostel is highly rated for its cleanliness, comfortable beds, and friendly staff.',
    highlights: ['Female-only dorms', 'Swimming pool', 'On-site restaurant', 'Highly rated for cleanliness and comfort'],
    considerations: ['A bit further from the main tourist area, requiring a scooter or tricycle to get around'],
    soloFemaleReviews: 'I stayed in the all female dorm and felt very safe the whole time, and it was a very thoughtfully designed room (stairs or very wide ladders to upper beds...)',
    sourcesChecked: ['booking.com', 'hostelworld', 'tripadvisor', 'google'],
  },
  {
    name: 'Harana Surf Resort',
    googleMapsUrl: 'https://www.google.com/maps/place/Harana+Surf+Resort/@9.7912789,126.1589748,17z',
    googlePlaceId: '0x3304062fea9e0de7:0x32b2e87d1b2c8b25',
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'siargao',
    city: 'Siargao',
    country: 'Philippines',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '250',
    googleRating: 4.9,
    reviewCount: 1011,
    whySelected: 'Harana Surf Resort is an excellent choice for solo female travelers seeking a stylish and relaxing stay. Its beachfront location, beautiful design, and high-quality service create a welcoming and comfortable environment. The resort\'s emphasis on wellness and community makes it easy to connect with other travelers.',
    highlights: ['Beachfront location', 'Beautiful design', 'Wellness-focused', 'Great food', 'Friendly staff'],
    considerations: ['Higher price point', 'Can sell out quickly'],
    soloFemaleReviews: 'The resort receives excellent reviews from solo female travelers praising the welcoming atmosphere, friendly staff, and beautiful surroundings.',
    sourcesChecked: ['booking.com', 'tripadvisor', 'google reviews'],
  },

  // ==========================================================================
  // PORTUGAL
  // ==========================================================================
  {
    name: 'Living Lounge Hostel',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Living+Lounge+Hostel+Lisbon',
    googlePlaceId: null,
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'lisbon',
    city: 'Lisbon',
    country: 'Portugal',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: null,
    googleRating: 4.7,
    reviewCount: 500,
    whySelected: 'Living Lounge Hostel is a great option for solo female travelers due to its female-only dorms, social atmosphere, and central location. The hostel is known for its friendly staff and clean facilities, making it a safe and welcoming choice.',
    highlights: ['Female-only dorms', 'Social atmosphere', 'Central location', 'Friendly staff', 'Clean facilities'],
    considerations: ['Can be noisy due to social events'],
    soloFemaleReviews: 'Reviews from solo female travelers praise the welcoming atmosphere and opportunities to meet other travelers.',
    sourcesChecked: ['hostelworld', 'booking.com', 'tripadvisor'],
  },
  {
    name: 'Memmo Alfama',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Memmo+Alfama+Lisbon',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'lisbon',
    city: 'Lisbon',
    country: 'Portugal',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '200',
    googleRating: 4.7,
    reviewCount: 1200,
    whySelected: 'Memmo Alfama is a stunning boutique hotel with panoramic views of Lisbon and the Tagus River. Its location in the historic Alfama district, combined with excellent service and a rooftop terrace, makes it an ideal choice for solo female travelers seeking a luxurious experience.',
    highlights: ['Stunning views', 'Historic Alfama location', 'Rooftop terrace', 'Excellent service', 'Beautiful design'],
    considerations: ['Steep hills in the neighborhood', 'Higher price point'],
    soloFemaleReviews: 'Solo travelers praise the beautiful location, attentive staff, and the rooftop terrace as a great spot to relax.',
    sourcesChecked: ['booking.com', 'tripadvisor', 'google reviews'],
  },

  // ==========================================================================
  // SINGAPORE
  // ==========================================================================
  {
    name: 'The Pod @ Beach Road',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=The+Pod+Beach+Road+Singapore',
    googlePlaceId: null,
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'singapore',
    city: 'Singapore',
    country: 'Singapore',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: null,
    googleRating: 4.5,
    reviewCount: 800,
    whySelected: 'The Pod @ Beach Road offers a unique capsule hotel experience with female-only floors, providing privacy and security for solo female travelers. Its central location and modern amenities make it a convenient and stylish choice.',
    highlights: ['Female-only floors', 'Capsule-style pods', 'Central location', 'Modern amenities', 'Clean facilities'],
    considerations: ['Capsule-style may not suit all travelers', 'Limited storage space'],
    soloFemaleReviews: 'Solo female travelers appreciate the privacy of the female-only floors and the clean, modern facilities.',
    sourcesChecked: ['booking.com', 'tripadvisor', 'hostelworld'],
  },
  {
    name: 'Naumi Hotel Singapore',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Naumi+Hotel+Singapore',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'singapore',
    city: 'Singapore',
    country: 'Singapore',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '300',
    googleRating: 4.6,
    reviewCount: 1500,
    whySelected: 'Naumi Hotel Singapore is a luxury boutique hotel with a rooftop infinity pool and personalized service. Its central location and stylish design make it an excellent choice for solo female travelers seeking an upscale experience.',
    highlights: ['Rooftop infinity pool', 'Personalized service', 'Central location', 'Stylish design', 'Excellent dining'],
    considerations: ['Higher price point', 'Rooms can be compact'],
    soloFemaleReviews: 'Solo travelers praise the attentive service, beautiful rooftop pool, and convenient location.',
    sourcesChecked: ['booking.com', 'tripadvisor', 'google reviews'],
  },

  // ==========================================================================
  // THAILAND
  // ==========================================================================
  {
    name: 'Baan Manusarn',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Baan+Manusarn+Bangkok',
    googlePlaceId: null,
    type: 'homestay',
    originalType: 'guesthouse',
    citySlug: 'bangkok',
    city: 'Bangkok',
    country: 'Thailand',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '50',
    googleRating: 4.8,
    reviewCount: 400,
    whySelected: 'Baan Manusarn is a charming guesthouse in the heart of Bangkok, offering a warm and welcoming atmosphere. The friendly staff and authentic local experience make it a great choice for solo female travelers.',
    highlights: ['Central location', 'Friendly staff', 'Authentic local experience', 'Clean rooms', 'Good breakfast'],
    considerations: ['Rooms are basic', 'Shared bathrooms in some rooms'],
    soloFemaleReviews: 'Solo female travelers appreciate the warm hospitality and central location.',
    sourcesChecked: ['booking.com', 'tripadvisor', 'google reviews'],
  },
  {
    name: 'NapPark Hostel',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=NapPark+Hostel+Bangkok',
    googlePlaceId: null,
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'bangkok',
    city: 'Bangkok',
    country: 'Thailand',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: null,
    googleRating: 4.6,
    reviewCount: 1200,
    whySelected: 'NapPark Hostel is a highly-rated hostel with female-only dorms and a social atmosphere. Its location near Khao San Road makes it convenient for exploring Bangkok\'s backpacker area.',
    highlights: ['Female-only dorms', 'Social atmosphere', 'Near Khao San Road', 'Clean facilities', 'Friendly staff'],
    considerations: ['Can be noisy', 'Near a busy area'],
    soloFemaleReviews: 'Solo female travelers praise the female-only dorms and the easy-going atmosphere.',
    sourcesChecked: ['hostelworld', 'booking.com', 'tripadvisor'],
  },
  {
    name: 'Hug Hostel',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Hug+Hostel+Chiang+Mai',
    googlePlaceId: null,
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'chiang-mai',
    city: 'Chiang Mai',
    country: 'Thailand',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: null,
    googleRating: 4.7,
    reviewCount: 900,
    whySelected: 'Hug Hostel is a popular choice for solo female travelers in Chiang Mai, offering female-only dorms and a friendly atmosphere. Its location in the Old City makes it easy to explore temples and night markets.',
    highlights: ['Female-only dorms', 'Old City location', 'Friendly atmosphere', 'Clean facilities', 'Free breakfast'],
    considerations: ['Basic facilities', 'Can be busy'],
    soloFemaleReviews: 'Solo female travelers appreciate the welcoming staff and convenient location.',
    sourcesChecked: ['hostelworld', 'booking.com', 'tripadvisor'],
  },
  {
    name: 'Akyra Manor Chiang Mai',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Akyra+Manor+Chiang+Mai',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'chiang-mai',
    city: 'Chiang Mai',
    country: 'Thailand',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '180',
    googleRating: 4.7,
    reviewCount: 800,
    whySelected: 'Akyra Manor Chiang Mai is a stylish boutique hotel in the trendy Nimman area, offering modern amenities and excellent service. Its rooftop pool and restaurant make it a great choice for solo female travelers seeking a luxurious experience.',
    highlights: ['Stylish design', 'Nimman location', 'Rooftop pool', 'Excellent service', 'Great dining'],
    considerations: ['Higher price point', 'Away from Old City'],
    soloFemaleReviews: 'Solo travelers praise the stylish rooms, attentive staff, and convenient location in Nimman.',
    sourcesChecked: ['booking.com', 'tripadvisor', 'google reviews'],
  },
  {
    name: 'Slumber Party Koh Phangan',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Slumber+Party+Koh+Phangan',
    googlePlaceId: null,
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'koh-phangan',
    city: 'Koh Phangan',
    country: 'Thailand',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: null,
    googleRating: 4.5,
    reviewCount: 600,
    whySelected: 'Slumber Party is a social hostel perfect for solo travelers looking to meet others. Its beachfront location and organized activities make it easy to connect with fellow travelers.',
    highlights: ['Beachfront location', 'Social atmosphere', 'Pool', 'Organized activities', 'Restaurant and bar'],
    considerations: ['Party atmosphere may not suit all travelers', 'No female-only dorms'],
    soloFemaleReviews: 'Solo travelers appreciate the social atmosphere and easy opportunities to meet other travelers.',
    sourcesChecked: ['hostelworld', 'booking.com', 'tripadvisor'],
  },
  {
    name: 'Santhiya Koh Phangan Resort',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Santhiya+Koh+Phangan+Resort',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'resort',
    citySlug: 'koh-phangan',
    city: 'Koh Phangan',
    country: 'Thailand',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '250',
    googleRating: 4.6,
    reviewCount: 1500,
    whySelected: 'Santhiya Koh Phangan Resort is a luxury eco-resort with traditional Thai architecture and a secluded beach. Its focus on wellness and tranquility makes it an ideal retreat for solo female travelers.',
    highlights: ['Private beach', 'Traditional Thai architecture', 'Spa and wellness', 'Eco-friendly', 'Beautiful views'],
    considerations: ['Secluded location', 'Higher price point'],
    soloFemaleReviews: 'Solo travelers praise the peaceful atmosphere, beautiful surroundings, and excellent spa services.',
    sourcesChecked: ['booking.com', 'tripadvisor', 'google reviews'],
  },
  {
    name: 'Pak-Up Hostel',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Pak-Up+Hostel+Krabi',
    googlePlaceId: null,
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'krabi',
    city: 'Krabi',
    country: 'Thailand',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: null,
    googleRating: 4.8,
    reviewCount: 1500,
    whySelected: 'Pak-Up Hostel is one of the highest-rated hostels in Thailand, offering female-only dorms, a stunning rooftop bar, and a social atmosphere. Its central location in Krabi Town makes it a perfect base for exploring.',
    highlights: ['Female-only dorms', 'Rooftop bar', 'Social atmosphere', 'Central location', 'Excellent reviews'],
    considerations: ['Can be noisy', 'Town location (not beachfront)'],
    soloFemaleReviews: 'Solo female travelers consistently praise the security, cleanliness, and opportunities to meet other travelers.',
    sourcesChecked: ['hostelworld', 'booking.com', 'tripadvisor'],
  },
  {
    name: 'Rayavadee',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Rayavadee+Krabi',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'resort',
    citySlug: 'krabi',
    city: 'Krabi',
    country: 'Thailand',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '500',
    googleRating: 4.7,
    reviewCount: 2000,
    whySelected: 'Rayavadee is an iconic luxury resort set amidst coconut groves and limestone cliffs. Its pavilion-style accommodations, multiple beaches, and world-class spa make it a dream destination for solo female travelers seeking ultimate relaxation.',
    highlights: ['Iconic luxury resort', 'Three private beaches', 'World-class spa', 'Stunning natural setting', 'Excellent dining'],
    considerations: ['Very high price point', 'Remote location'],
    soloFemaleReviews: 'Solo travelers describe it as a once-in-a-lifetime experience with unparalleled service and natural beauty.',
    sourcesChecked: ['booking.com', 'tripadvisor', 'google reviews'],
  },
  {
    name: 'Pai Village Boutique Resort',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Pai+Village+Boutique+Resort',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'pai',
    city: 'Pai',
    country: 'Thailand',
    priceRange: '$$',
    priceLevel: 2,
    pricePerNight: '80',
    googleRating: 4.6,
    reviewCount: 600,
    whySelected: 'Pai Village Boutique Resort offers a peaceful retreat with beautiful gardens and mountain views. Its spa and yoga classes make it perfect for solo female travelers seeking relaxation and wellness.',
    highlights: ['Beautiful gardens', 'Mountain views', 'Spa and wellness', 'Yoga classes', 'Quiet atmosphere'],
    considerations: ['Outside walking street', 'Need transportation'],
    soloFemaleReviews: 'Solo travelers appreciate the tranquil atmosphere and wellness offerings.',
    sourcesChecked: ['booking.com', 'tripadvisor', 'google reviews'],
  },
  {
    name: 'Circus Hostel',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Circus+Hostel+Pai',
    googlePlaceId: null,
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'pai',
    city: 'Pai',
    country: 'Thailand',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: null,
    googleRating: 4.7,
    reviewCount: 800,
    whySelected: 'Circus Hostel is a social and quirky hostel in the heart of Pai, known for its fun atmosphere and community vibe. The female-only dorms and organized activities make it a great choice for solo female travelers.',
    highlights: ['Female-only dorms', 'Social atmosphere', 'Central location', 'Quirky design', 'Organized activities'],
    considerations: ['Can be noisy', 'Party vibe may not suit all'],
    soloFemaleReviews: 'Solo female travelers love the friendly vibe and easy opportunities to meet other travelers.',
    sourcesChecked: ['hostelworld', 'booking.com', 'tripadvisor'],
  },

  // ==========================================================================
  // VIETNAM
  // ==========================================================================
  {
    name: 'Cozy Nook Hostel',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Cozy+Nook+Hostel+Da+Lat',
    googlePlaceId: null,
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'da-lat',
    city: 'Da Lat',
    country: 'Vietnam',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: null,
    googleRating: 4.8,
    reviewCount: 500,
    whySelected: 'Cozy Nook Hostel is a highly-rated hostel with female-only dorms and a warm, welcoming atmosphere. Its central location makes it easy to explore Da Lat\'s attractions.',
    highlights: ['Female-only dorms', 'Warm atmosphere', 'Central location', 'Helpful staff', 'Good breakfast'],
    considerations: ['Basic facilities', 'Shared bathrooms'],
    soloFemaleReviews: 'Solo female travelers praise the friendly staff and comfortable female-only dorms.',
    sourcesChecked: ['hostelworld', 'booking.com', 'tripadvisor'],
  },
  {
    name: 'Ana Mandara Villas Dalat',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Ana+Mandara+Villas+Dalat',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'resort',
    citySlug: 'da-lat',
    city: 'Da Lat',
    country: 'Vietnam',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '150',
    googleRating: 4.6,
    reviewCount: 800,
    whySelected: 'Ana Mandara Villas Dalat is a collection of restored French colonial villas set in beautiful gardens. Its peaceful atmosphere and excellent service make it ideal for solo female travelers seeking a luxurious retreat.',
    highlights: ['Restored French colonial villas', 'Beautiful gardens', 'Spa', 'Excellent service', 'Peaceful atmosphere'],
    considerations: ['Outside city center', 'Higher price point'],
    soloFemaleReviews: 'Solo travelers appreciate the tranquil setting and attentive service.',
    sourcesChecked: ['booking.com', 'tripadvisor', 'google reviews'],
  },
  {
    name: 'Memory Hostel',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Memory+Hostel+Da+Nang',
    googlePlaceId: null,
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'da-nang',
    city: 'Da Nang',
    country: 'Vietnam',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: null,
    googleRating: 4.7,
    reviewCount: 600,
    whySelected: 'Memory Hostel is a popular choice for solo travelers with female-only dorms and a great location near the beach. The friendly staff and organized tours make it easy to explore Da Nang.',
    highlights: ['Female-only dorms', 'Near the beach', 'Friendly staff', 'Organized tours', 'Clean facilities'],
    considerations: ['Can be busy', 'Basic facilities'],
    soloFemaleReviews: 'Solo female travelers appreciate the helpful staff and convenient location.',
    sourcesChecked: ['hostelworld', 'booking.com', 'tripadvisor'],
  },
  {
    name: 'Nenearby Homestay',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Neaby+Homestay+Hanoi',
    googlePlaceId: null,
    type: 'homestay',
    originalType: 'homestay',
    citySlug: 'hanoi',
    city: 'Hanoi',
    country: 'Vietnam',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: '25',
    googleRating: 4.9,
    reviewCount: 400,
    whySelected: 'Neaby Homestay offers an authentic local experience with a welcoming family atmosphere. The central location in the Old Quarter and genuine hospitality make it perfect for solo female travelers.',
    highlights: ['Authentic local experience', 'Central Old Quarter location', 'Warm hospitality', 'Home-cooked breakfast', 'Helpful hosts'],
    considerations: ['Basic amenities', 'Shared bathrooms'],
    soloFemaleReviews: 'Solo female travelers love the genuine hospitality and feeling of staying with a local family.',
    sourcesChecked: ['booking.com', 'tripadvisor', 'airbnb'],
  },
  {
    name: 'Sofitel Legend Metropole Hanoi',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Sofitel+Legend+Metropole+Hanoi',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'hotel',
    citySlug: 'hanoi',
    city: 'Hanoi',
    country: 'Vietnam',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '350',
    googleRating: 4.7,
    reviewCount: 3000,
    whySelected: 'Sofitel Legend Metropole Hanoi is a historic luxury hotel with impeccable service and a prime location. Its elegant atmosphere and excellent amenities make it a top choice for solo female travelers seeking a premium experience.',
    highlights: ['Historic luxury hotel', 'Prime location', 'Impeccable service', 'Multiple restaurants', 'Spa and pool'],
    considerations: ['Very high price point', 'Formal atmosphere'],
    soloFemaleReviews: 'Solo travelers praise the exceptional service and elegant surroundings.',
    sourcesChecked: ['booking.com', 'tripadvisor', 'google reviews'],
  },
  {
    name: 'The Myst Dong Khoi',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=The+Myst+Dong+Khoi+Ho+Chi+Minh',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'boutique_hotel',
    citySlug: 'ho-chi-minh-city',
    city: 'Ho Chi Minh City',
    country: 'Vietnam',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '180',
    googleRating: 4.6,
    reviewCount: 1000,
    whySelected: 'The Myst Dong Khoi is a stylish boutique hotel with a rooftop bar and excellent location. Its modern design and personalized service make it an ideal choice for solo female travelers.',
    highlights: ['Stylish design', 'Rooftop bar', 'Central location', 'Personalized service', 'Excellent breakfast'],
    considerations: ['Compact rooms', 'Higher price point'],
    soloFemaleReviews: 'Solo travelers appreciate the stylish atmosphere and convenient location.',
    sourcesChecked: ['booking.com', 'tripadvisor', 'google reviews'],
  },
  {
    name: 'An Bang Seaside Village Homestay',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=An+Bang+Seaside+Village+Homestay+Hoi+An',
    googlePlaceId: null,
    type: 'homestay',
    originalType: 'homestay',
    citySlug: 'hoi-an',
    city: 'Hoi An',
    country: 'Vietnam',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: '30',
    googleRating: 4.8,
    reviewCount: 300,
    whySelected: 'An Bang Seaside Village Homestay offers a peaceful beachside experience with warm hospitality. Its location near An Bang Beach and welcoming atmosphere make it perfect for solo female travelers.',
    highlights: ['Beachside location', 'Warm hospitality', 'Peaceful atmosphere', 'Home-cooked meals', 'Bicycle rentals'],
    considerations: ['Outside Hoi An center', 'Basic amenities'],
    soloFemaleReviews: 'Solo female travelers appreciate the welcoming hosts and relaxing beach location.',
    sourcesChecked: ['booking.com', 'tripadvisor', 'airbnb'],
  },
  {
    name: 'Tribee Bana Hostel',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tribee+Bana+Hostel+Hoi+An',
    googlePlaceId: null,
    type: 'hostel',
    originalType: 'hostel',
    citySlug: 'hoi-an',
    city: 'Hoi An',
    country: 'Vietnam',
    priceRange: '$',
    priceLevel: 1,
    pricePerNight: null,
    googleRating: 4.6,
    reviewCount: 500,
    whySelected: 'Tribee Bana Hostel is a social hostel with female-only dorms and a beautiful pool. Its location near the Old Town and organized activities make it ideal for solo female travelers.',
    highlights: ['Female-only dorms', 'Swimming pool', 'Near Old Town', 'Social atmosphere', 'Organized activities'],
    considerations: ['Can be noisy', 'Party atmosphere at times'],
    soloFemaleReviews: 'Solo female travelers appreciate the security of female-only dorms and the easy-going atmosphere.',
    sourcesChecked: ['hostelworld', 'booking.com', 'tripadvisor'],
  },
  {
    name: 'Four Seasons Resort The Nam Hai',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Four+Seasons+Nam+Hai+Hoi+An',
    googlePlaceId: null,
    type: 'hotel',
    originalType: 'resort',
    citySlug: 'hoi-an',
    city: 'Hoi An',
    country: 'Vietnam',
    priceRange: '$$$',
    priceLevel: 3,
    pricePerNight: '600',
    googleRating: 4.8,
    reviewCount: 1500,
    whySelected: 'Four Seasons Resort The Nam Hai is an ultra-luxury beachfront resort with world-class amenities. Its stunning villas, spa, and impeccable service make it a dream destination for solo female travelers seeking the ultimate indulgence.',
    highlights: ['Ultra-luxury resort', 'Private beach', 'World-class spa', 'Stunning villas', 'Exceptional service'],
    considerations: ['Very high price point', 'Remote location'],
    soloFemaleReviews: 'Solo travelers describe it as a transformative experience with unparalleled luxury and service.',
    sourcesChecked: ['booking.com', 'tripadvisor', 'google reviews'],
  },
];

// Helper: Get accommodations by country
export function getAccommodationsByCountry(country: string): AccommodationEntry[] {
  return ACCOMMODATIONS.filter(a => a.country === country);
}

// Helper: Get accommodations by city
export function getAccommodationsByCity(citySlug: string): AccommodationEntry[] {
  return ACCOMMODATIONS.filter(a => a.citySlug === citySlug);
}

// Helper: Get accommodations by type
export function getAccommodationsByType(type: AccommodationEntry['type']): AccommodationEntry[] {
  return ACCOMMODATIONS.filter(a => a.type === type);
}

// Helper: Get accommodations by price range
export function getAccommodationsByPriceRange(priceRange: '$' | '$$' | '$$$'): AccommodationEntry[] {
  return ACCOMMODATIONS.filter(a => a.priceRange === priceRange);
}

// Summary statistics
export const ACCOMMODATION_STATS = {
  total: ACCOMMODATIONS.length,
  byCountry: ACCOMMODATIONS.reduce((acc, a) => {
    acc[a.country] = (acc[a.country] || 0) + 1;
    return acc;
  }, {} as Record<string, number>),
  byType: ACCOMMODATIONS.reduce((acc, a) => {
    acc[a.type] = (acc[a.type] || 0) + 1;
    return acc;
  }, {} as Record<string, number>),
  byPriceRange: ACCOMMODATIONS.reduce((acc, a) => {
    acc[a.priceRange] = (acc[a.priceRange] || 0) + 1;
    return acc;
  }, {} as Record<string, number>),
};
