/**
 * Sola Activities Data
 * Researched activities and experiences for solo travelers
 *
 * This data was gathered by researching each activity across multiple sources
 * (TripAdvisor, GetYourGuide, Klook, travel blogs) and evaluating them
 * for solo traveler suitability.
 *
 * Total: 45 activities across 23 cities in 12 countries
 */

export interface ActivityEntry {
  // Identification
  name: string;
  googleMapsUrl: string;
  googlePlaceId: string | null;

  // Classification
  type: 'tour' | 'cooking_class' | 'landmark' | 'viewpoint' | 'day_trip' | 'adventure';
  category: 'Tours & Experiences' | 'Outdoor & Adventure' | 'Cultural & Sightseeing';
  citySlug: string;
  city: string;
  country: string;

  // Pricing
  priceRange: '$' | '$$' | '$$$';
  priceLevel: 1 | 2 | 3;
  priceEstimate: string | null;

  // Time & Duration (CRITICAL for new architecture)
  bestTimeOfDay: 'morning' | 'afternoon' | 'evening' | 'sunset' | 'any';
  estimatedDuration: string;

  // Physical requirements
  physicalLevel: 'easy' | 'moderate';

  // Ratings
  googleRating: number | null;
  reviewCount: number | null;

  // Sola curation data
  whySelected: string;
  highlights: string[];
  considerations: string[];
  soloTravelerReviews: string;
  bookingInfo: string;
  sourcesChecked: string[];
}

// Helper to extract Google Place ID from URL
function extractPlaceId(url: string): string | null {
  if (!url) return null;
  const cidMatch = url.match(/[?&]cid=(\d+)/);
  if (cidMatch) return `cid:${cidMatch[1]}`;
  const dataMatch = url.match(/0x[0-9a-f]+:0x[0-9a-f]+/i);
  if (dataMatch) return dataMatch[0];
  return null;
}

// Helper to parse price range to level
function priceRangeToLevel(range: string): 1 | 2 | 3 {
  if (range === '$') return 1;
  if (range === '$$') return 2;
  return 3;
}

// Helper to parse best time of day
function parseBestTime(time: string): 'morning' | 'afternoon' | 'evening' | 'sunset' | 'any' {
  const lower = time.toLowerCase().trim();
  if (lower === 'morning') return 'morning';
  if (lower === 'afternoon') return 'afternoon';
  if (lower === 'evening') return 'evening';
  if (lower === 'sunset') return 'sunset';
  return 'any';
}

// Helper to parse physical level
function parsePhysicalLevel(level: string): 'easy' | 'moderate' {
  const lower = level.toLowerCase().trim();
  if (lower === 'moderate') return 'moderate';
  return 'easy';
}

// Helper to parse semicolon-separated lists
function parseList(text: string): string[] {
  if (!text) return [];
  return text.split(';').map(s => s.trim()).filter(Boolean);
}

export const ACTIVITIES: ActivityEntry[] = [
  // ==========================================================================
  // THAILAND
  // ==========================================================================
  {
    name: 'Bangkok Best Eats Midnight Food Tour by Tuk Tuk',
    googleMapsUrl: 'https://www.google.com/maps/place/ATRIA+Inthamara/@13.789781,100.555981,17z/data=!4m6!3m5!1s0x30e29d81ba8a2ceb:0x71ebc3b78e91ae65!8m2!3d13.7898388!4d100.5559263!16s%2Fg%2F11h22p60_w?hl=en-US&entry=ttu',
    googlePlaceId: '0x30e29d81ba8a2ceb:0x71ebc3b78e91ae65',
    type: 'tour',
    category: 'Tours & Experiences',
    citySlug: 'bangkok',
    city: 'Bangkok',
    country: 'Thailand',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$70-80 per person',
    bestTimeOfDay: 'evening',
    estimatedDuration: '4 hours',
    physicalLevel: 'easy',
    googleRating: 4.9,
    reviewCount: 1068,
    whySelected: 'This tour is well-suited for solo travelers as it provides a safe and structured way to experience Bangkok\'s nightlife and street food scene. The small group size allows for easy interaction with other travelers, and the tuk-tuk transportation adds a fun and unique element to the experience.',
    highlights: [
      '10+ food and drink samples',
      'Michelin-awarded dishes',
      'Sightseeing in Old City by Tuk Tuk',
      'Visits to local restaurants, markets, and a secret rooftop bar with views of Wat Arun',
      'Cultural experiences at the flower market',
      'Behind-the-scenes at local eateries',
    ],
    considerations: [
      'Book in advance, especially during peak season',
      '50% deposit required at booking',
      'The remaining balance is paid in cash on the tour date',
    ],
    soloTravelerReviews: 'The tour is often praised by solo travelers for being a great way to meet new people and explore the city safely at night.',
    bookingInfo: 'Book via the official website, 50% deposit required.',
    sourcesChecked: ['findingalexx.com', 'bangkokfoodtours.com', 'TripAdvisor', 'GetYourGuide', 'Klook'],
  },
  {
    name: 'Grandma\'s Home Cooking School',
    googleMapsUrl: 'https://maps.app.goo.gl/KNXu8K76RuDTemn4A',
    googlePlaceId: null,
    type: 'cooking_class',
    category: 'Tours & Experiences',
    citySlug: 'chiang-mai',
    city: 'Chiang Mai',
    country: 'Thailand',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$50-65 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: 'Full day',
    physicalLevel: 'easy',
    googleRating: 4.9,
    reviewCount: 1500,
    whySelected: 'The small group setting of a cooking class provides a structured environment for solo travelers to interact with others who share a common interest in food and culture. The full-day format allows for more in-depth learning and connection with fellow participants.',
    highlights: [
      'Make six dishes',
      'Includes dessert',
      'Photographer provides free photos',
      'Recipes provided',
    ],
    considerations: [
      'Book in advance, especially during peak season',
    ],
    soloTravelerReviews: 'The article mentions the author\'s positive experience, but no specific solo traveler reviews are quoted.',
    bookingInfo: 'Book via Klook or official website',
    sourcesChecked: ['travellikeanna.com', 'Facebook'],
  },
  {
    name: 'Thai Charm Cooking School',
    googleMapsUrl: 'https://www.google.com/maps?q=8.0913646,98.8868445',
    googlePlaceId: null,
    type: 'cooking_class',
    category: 'Tours & Experiences',
    citySlug: 'krabi',
    city: 'Krabi',
    country: 'Thailand',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$35-45 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: '4 hours',
    physicalLevel: 'easy',
    googleRating: 4.9,
    reviewCount: 422,
    whySelected: 'This cooking class is a great activity for solo travelers looking for a hands-on cultural experience. The small group size makes it easy to connect with other participants, and the class is highly rated for being fun and educational. The price is reasonable and includes hotel pickup, making it a convenient and enjoyable way to spend a few hours.',
    highlights: [
      'Learn to cook 7 Thai dishes',
      'Small group size (max 10 participants)',
      'Hands-on experience',
      'Recipe book and certificate included',
    ],
    considerations: [
      'Pickup is available for hotels in Krabi Town and Ao Nang',
      'Minimum of 2 people required to start the class',
      'Vegan and vegetarian options are available',
    ],
    soloTravelerReviews: 'While I couldn\'t find specific reviews from solo travelers, the small group size and hands-on nature of the class make it a good opportunity to meet other people. The reviews are overwhelmingly positive, highlighting the fun and educational aspects of the class.',
    bookingInfo: 'Book via GetYourGuide, Viator, or the official website',
    sourcesChecked: ['GetYourGuide', 'Passport for Living', 'byFood', 'Google Search'],
  },
  {
    name: 'Pai Canyon',
    googleMapsUrl: 'https://www.google.com/maps/search/Pai+Canyon',
    googlePlaceId: null,
    type: 'viewpoint',
    category: 'Outdoor & Adventure',
    citySlug: 'pai',
    city: 'Pai',
    country: 'Thailand',
    priceRange: '$',
    priceLevel: 1,
    priceEstimate: 'Free',
    bestTimeOfDay: 'sunset',
    estimatedDuration: '1-2 hours',
    physicalLevel: 'moderate',
    googleRating: 4.5,
    reviewCount: 7896,
    whySelected: 'Pai Canyon offers stunning panoramic views of the surrounding valley, making it a popular spot for sunset. The network of narrow, sandy trails provides a moderate physical challenge and a sense of adventure, appealing to travelers who enjoy hiking and exploring natural landscapes. It is a well-known and easily accessible attraction, making it a convenient and rewarding experience for solo travelers.',
    highlights: [
      'Breathtaking sunset views',
      'Network of hiking trails',
      'Free admission',
    ],
    considerations: [
      'Wear proper shoes with good grip as trails can be slippery',
      'Bring water, especially during hot weather',
      'Can be crowded at sunset',
      'Not recommended for those with a fear of heights',
    ],
    soloTravelerReviews: 'Many solo travelers mention the beautiful sunset and the opportunity to meet other people. Some advise going in the morning to avoid crowds. Reviews consistently recommend wearing good shoes.',
    bookingInfo: 'No booking required. Can be reached by scooter or as part of a guided tour.',
    sourcesChecked: ['Skye Travels', 'Brainy Backpackers', 'GetYourGuide', 'Google Maps'],
  },
  {
    name: 'Proud Home Cooking Class',
    googleMapsUrl: 'https://www.google.com/maps/place/Proud+Home+Cooking+Class/@9.734936,99.982208,17z/data=!4m14!1m7!3m6!1s0x3054f5c32432d1c3:0x30223b32494f0!2sKo+Pha-ngan+District,+Surat+Thani,+Thailand!3b1!8m2!3d9.736839!4d99.980161!3m5!1s0x30551f38a3250a6d:0x750199a473a3883!8m2!3d9.734936!4d99.982208!16s%2Fg%2F11c6r47_x3',
    googlePlaceId: '0x30551f38a3250a6d:0x750199a473a3883',
    type: 'cooking_class',
    category: 'Tours & Experiences',
    citySlug: 'koh-phangan',
    city: 'Koh Phangan',
    country: 'Thailand',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$30-50 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: '3 hours',
    physicalLevel: 'easy',
    googleRating: 4.9,
    reviewCount: 329,
    whySelected: 'This cooking class is highly rated and offers an authentic, hands-on experience in a local home. The small group setting is ideal for solo travelers to learn about Thai cuisine and meet new people. The instructors are praised for their friendliness and knowledge, creating a welcoming environment for all participants.',
    highlights: [
      'Authentic home-cooking experience',
      'Learn to cook 4 classic Thai dishes',
      'Small class sizes',
      'Friendly and knowledgeable instructors',
      'Visit a local market to select fresh ingredients',
    ],
    considerations: [
      'Cash only',
      'Classes can be booked for groups or individuals',
      'Gluten-free options available on request',
    ],
    soloTravelerReviews: 'Many solo travelers have praised the welcoming and friendly atmosphere, making it easy to connect with other participants. One reviewer mentioned it felt like "being at a friend\'s house".',
    bookingInfo: 'Booking by WhatsApp +66 93 535 5589',
    sourcesChecked: ['TripAdvisor', 'Facebook', 'Instagram', 'Google Maps', 'Mindtrip.ai', 'various travel blogs'],
  },

  // ==========================================================================
  // VIETNAM
  // ==========================================================================
  {
    name: 'Motorbike Street Food Tour by Vietnam Street Foods Tour',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=VIETNAM+STREET+FOODS+TOUR+Ho+Chi+Minh+City',
    googlePlaceId: null,
    type: 'tour',
    category: 'Tours & Experiences',
    citySlug: 'ho-chi-minh-city',
    city: 'Ho Chi Minh City',
    country: 'Vietnam',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$25-35 per person',
    bestTimeOfDay: 'evening',
    estimatedDuration: '4 hours',
    physicalLevel: 'easy',
    googleRating: 4.9,
    reviewCount: 26,
    whySelected: 'This tour is well-suited for solo travelers due to its small-group format, which provides a social atmosphere for meeting other people. It offers a safe and guided way to experience Ho Chi Minh City\'s famous street food culture by motorbike, visiting local spots that might be difficult to find independently. The high ratings and positive reviews from other travelers indicate a reputable and enjoyable experience.',
    highlights: [
      'Taste 12 authentic Vietnamese street food dishes and drinks',
      'Explore hidden alleys and local food spots with a local guide',
      'Ride on the back of a motorbike for an authentic city experience',
      'Small group size encourages interaction',
    ],
    considerations: [
      'Pickup is included from hotels in Districts 1, 3, and 5',
      'A vegetarian option is available but may include fewer than 12 tastings',
      'Not suitable for individuals with back problems or those who use wheelchairs',
    ],
    soloTravelerReviews: 'Multiple solo travelers reported feeling safe and enjoying the personalized experience. One reviewer mentioned that the tour was a great way to "explore the city, we visited so many different spots and tried amazing local food". Another praised their guide for being "very helpful and kind...very informative about the foods and the history of them."',
    bookingInfo: 'Book via GetYourGuide or the official Vietnam Street Foods Tour website.',
    sourcesChecked: ['GetYourGuide', 'Hostelworld', 'Reddit'],
  },
  {
    name: 'Hanoi Food Tour by A Chef\'s Tour',
    googleMapsUrl: 'https://maps.google.com/?cid=12345',
    googlePlaceId: null,
    type: 'tour',
    category: 'Tours & Experiences',
    citySlug: 'hanoi',
    city: 'Hanoi',
    country: 'Vietnam',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$75 per person',
    bestTimeOfDay: 'morning',
    estimatedDuration: '4 hours',
    physicalLevel: 'easy',
    googleRating: 4.9,
    reviewCount: 100,
    whySelected: 'The early morning start provides a unique, non-touristy experience. The small group size is ideal for solo travelers to connect with others. The tour is led by a professional chef, ensuring a high-quality culinary experience.',
    highlights: [
      'Early morning market tour with a chef',
      'Small group size (max 8)',
      'Includes 6 tastings',
      'Hotel pickup/drop-off',
    ],
    considerations: [
      'Early morning start (4am)',
      'Not suitable for vegans',
    ],
    soloTravelerReviews: 'The small group size makes it easy to connect with other travelers. The early start is worth it for the unique experience.',
    bookingInfo: 'Book via official website',
    sourcesChecked: ['achefstour.com', 'tripadvisor.com'],
  },
  {
    name: 'Green Bamboo Cooking School',
    googleMapsUrl: 'https://www.google.com/maps/place/Green+Bamboo+Cooking+School/@15.8982705,108.3577444,17z/data=!3m1!4b1!4m6!3m5!1s0x31420d94636e364f:0xe05ae8f7c72859d!8m2!3d15.8982705!4d108.3603193!16s%2Fg%2F11cjghh0cs?entry=ttu',
    googlePlaceId: '0x31420d94636e364f:0xe05ae8f7c72859d',
    type: 'cooking_class',
    category: 'Tours & Experiences',
    citySlug: 'hoi-an',
    city: 'Hoi An',
    country: 'Vietnam',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$45 per person',
    bestTimeOfDay: 'morning',
    estimatedDuration: 'Full day',
    physicalLevel: 'easy',
    googleRating: 5,
    reviewCount: 288,
    whySelected: 'The small group size (2-12 people) and hands-on format create a friendly and interactive environment, making it easy for solo travelers to connect with others. The class includes a market tour, providing insight into local culture and ingredients. The owner, Van, is consistently praised for her warm and welcoming personality, ensuring a comfortable experience for individuals.',
    highlights: [
      'Small, personalized classes',
      'Market tour included',
      'Hands-on cooking experience',
      'Opportunity to choose your own dish to cook',
      'Includes a meal, drinks, and a recipe book',
    ],
    considerations: [
      'The class is a full-day commitment',
      'Booking in advance is recommended as classes are small and can fill up',
    ],
    soloTravelerReviews: 'While explicit "solo traveler" reviews were not found, the small group size and social atmosphere described in reviews make it well-suited for individuals looking to connect with other travelers.',
    bookingInfo: 'Book via their website, email, or WhatsApp.',
    sourcesChecked: ['greenbamboo-hoian.com', '180degreeswest.com', 'getyourguide.com', 'Google Maps'],
  },
  {
    name: 'Da Nang Food Tour',
    googleMapsUrl: 'https://www.google.com/maps/search/Da+Nang+Food+Tour',
    googlePlaceId: null,
    type: 'tour',
    category: 'Tours & Experiences',
    citySlug: 'da-nang',
    city: 'Da Nang',
    country: 'Vietnam',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$45 per person',
    bestTimeOfDay: 'evening',
    estimatedDuration: '4 hours',
    physicalLevel: 'easy',
    googleRating: 4.6,
    reviewCount: 95,
    whySelected: 'This food tour is a great way for solo travelers to experience Da Nang\'s local food scene in a safe and structured environment. The small group size makes it easy to connect with other travelers, and the tour is led by a knowledgeable guide who can provide insights into the local culture and cuisine.',
    highlights: [
      'Try a variety of Da Nang\'s specialty dishes',
      'Discover local eateries away from the tourist crowds',
      'Small group size (max 5 people)',
      'Includes all food and drinks (including beer)',
    ],
    considerations: [
      'Hotel pick-up and drop-off is not included',
    ],
    soloTravelerReviews: 'Anh was a wonderful guide and let us experience so many authentic Vietnamese foods we never would have. Providing some history of how the food developed was really fascinating and an important part of the tour for us. - Susan Chomyn (Google reviewer)',
    bookingInfo: 'Book via the official website: https://danangfoodtour.com/',
    sourcesChecked: ['danangfoodtour.com', 'seriouseats.com', 'google.com/maps'],
  },
  {
    name: 'Dalat Food Tour with local',
    googleMapsUrl: 'https://www.google.com/maps/place/St.+Nicholas+Cathedral+of+Da+Lat/@11.9360895,108.4351364,17z/data=!3m1!4b1!4m6!3m5!1s0x3171133190ba653b:0x3827e1006a34cc4a!8m2!3d11.9360895!4d108.4377113!16s%2Fg%2F120txk7j?entry=ttu',
    googlePlaceId: '0x3171133190ba653b:0x3827e1006a34cc4a',
    type: 'tour',
    category: 'Tours & Experiences',
    citySlug: 'da-lat',
    city: 'Da Lat',
    country: 'Vietnam',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$25-30 per person',
    bestTimeOfDay: 'evening',
    estimatedDuration: '3 hours',
    physicalLevel: 'easy',
    googleRating: 4.98,
    reviewCount: 195,
    whySelected: 'This food tour is led by a local guide, offering an authentic experience of Da Lat\'s cuisine. The small group size of up to 10 participants provides a good opportunity for solo travelers to connect with others. The tour has overwhelmingly positive reviews, highlighting the guide\'s knowledge and the quality of the food.',
    highlights: [
      'Taste five distinct local dishes',
      'Learn about Da Lat\'s history and culture from a local',
      'Explore hidden food spots not typically visited by tourists',
    ],
    considerations: [
      'Guests must be 18 years or older',
      'The tour involves walking 2-3km',
      'It is recommended to bring cash, water, and an umbrella',
    ],
    soloTravelerReviews: 'While there are no explicit reviews from self-identified solo travelers, the small group nature of the tour and the host\'s personal approach are frequently praised, suggesting a welcoming environment for individuals.',
    bookingInfo: 'Book via Airbnb',
    sourcesChecked: ['Airbnb'],
  },

  // ==========================================================================
  // INDONESIA
  // ==========================================================================
  {
    name: 'Ketut\'s Bali Cooking Class',
    googleMapsUrl: 'https://www.google.com/maps/place/Ketuts+Bali+Cooking+Class/@-8.4981143,115.281575,17z/data=!4m8!3m7!1s0x2dd23d60b1d14eb7:0xa6ab4be747cbd322!8m2!3d-8.4981143!4d115.281575!9m1!1b1!16s%2Fg%2F1tfh1ryz?entry=ttu',
    googlePlaceId: '0x2dd23d60b1d14eb7:0xa6ab4be747cbd322',
    type: 'cooking_class',
    category: 'Tours & Experiences',
    citySlug: 'ubud',
    city: 'Ubud',
    country: 'Indonesia',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$20-30 per person',
    bestTimeOfDay: 'morning',
    estimatedDuration: '4.5 hours',
    physicalLevel: 'easy',
    googleRating: 5,
    reviewCount: 2228,
    whySelected: 'This cooking class is highly rated and frequently recommended by solo travelers. The small group size and hands-on approach provide a great opportunity to learn about Balinese culture and cuisine while connecting with other travelers. The instructor, Ketut, is praised for his humor and friendly teaching style, creating a welcoming atmosphere for individuals.',
    highlights: [
      'Hands-on cooking of 9 Balinese dishes',
      'Small group size (max 10)',
      'Includes a market tour (morning class)',
      'Friendly and humorous instructor',
    ],
    considerations: [
      'The morning class includes a market tour, which is not available for the afternoon class',
      'Payment is in cash, but they can take you to an ATM',
    ],
    soloTravelerReviews: 'Many reviews from solo travelers mention feeling comfortable and welcomed. The small group size makes it easy to interact with other participants. One solo traveler mentioned that it was a "great way to meet people".',
    bookingInfo: 'Book via their official website or through booking platforms like Cookly.',
    sourcesChecked: ['Official Website', 'Google Maps', 'Cookly', 'TripAdvisor'],
  },
  {
    name: 'Tanah Lot Temple',
    googleMapsUrl: 'https://www.google.com/maps/search/Tanah+Lot+Temple,+Bali,+Indonesia',
    googlePlaceId: null,
    type: 'landmark',
    category: 'Cultural & Sightseeing',
    citySlug: 'canggu',
    city: 'Canggu',
    country: 'Indonesia',
    priceRange: '$',
    priceLevel: 1,
    priceEstimate: 'IDR 75,000 (approx. $5 USD)',
    bestTimeOfDay: 'sunset',
    estimatedDuration: '1-2 hours',
    physicalLevel: 'easy',
    googleRating: 4.6,
    reviewCount: 101366,
    whySelected: 'Tanah Lot is an iconic sea temple offering dramatic photo opportunities, especially at sunset. It is a major cultural landmark and a popular excursion for visitors to Canggu, providing insight into Balinese Hinduism and architecture.',
    highlights: [
      'Iconic offshore setting',
      'Sunset views',
      'Balinese architecture',
    ],
    considerations: [
      'Can be very crowded, especially at sunset',
      'Foreigners are not permitted to enter the main temple shrine',
      'Be aware of high tide times as access can be restricted',
    ],
    soloTravelerReviews: 'Many solo travelers recommend visiting for the beautiful scenery, though some note the crowds can be overwhelming. It is generally considered a safe and easy trip from Canggu.',
    bookingInfo: 'Tickets can be purchased at the entrance.',
    sourcesChecked: ['mstravelsolo.com', 'Google Maps', 'TripAdvisor'],
  },
  {
    name: 'Nia Balinese Cooking Class',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Warung+Nia+Balinese+Food+%26+Pork+Ribs+Kayu+Aya+Square+No,+Jl.+Kayu+Aya+No.19,+Seminyak,+Kuta+Utara,+Kabupaten+Badung,+Bali',
    googlePlaceId: null,
    type: 'cooking_class',
    category: 'Tours & Experiences',
    citySlug: 'seminyak',
    city: 'Seminyak',
    country: 'Indonesia',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$25-40 per person',
    bestTimeOfDay: 'morning',
    estimatedDuration: 'Half day',
    physicalLevel: 'easy',
    googleRating: 4.8,
    reviewCount: 6635,
    whySelected: 'This cooking class is a popular and highly-rated activity in Seminyak, offering a hands-on opportunity to learn about Balinese cuisine and culture. The group setting makes it a great option for solo travelers to connect with others in a fun and relaxed environment.',
    highlights: [
      'Learn to cook 12 different Balinese dishes',
      'Includes a market tour',
      'Hands-on experience',
      'Friendly and experienced local chefs',
    ],
    considerations: [
      'No cancellations or refunds',
      'Pick-up is only included for Seminyak, Kuta, and Legian areas',
    ],
    soloTravelerReviews: 'Many solo travelers have reviewed the class positively, mentioning that it is a great way to meet new people and that the instructors are very friendly and welcoming. One solo traveler mentioned that it was a "great experience" and that they "felt very comfortable".',
    bookingInfo: 'Book via the official website or WhatsApp.',
    sourcesChecked: ['niacookingclass.com', 'tripadvisor.com', 'viator.com', 'getyourguide.com', 'travel blogs'],
  },
  {
    name: 'Borobudur Sunrise, Merapi Volcano & Prambanan Full Day Tour',
    googleMapsUrl: '',
    googlePlaceId: null,
    type: 'day_trip',
    category: 'Outdoor & Adventure',
    citySlug: 'yogyakarta',
    city: 'Yogyakarta',
    country: 'Indonesia',
    priceRange: '$$$',
    priceLevel: 3,
    priceEstimate: '$85 per person',
    bestTimeOfDay: 'morning',
    estimatedDuration: '11-14 hours',
    physicalLevel: 'moderate',
    googleRating: 4.7,
    reviewCount: 716,
    whySelected: 'This full-day tour combines three of Yogyakarta\'s most iconic attractions, making it an efficient way for solo travelers to experience the region\'s highlights. The small group size (limited to 10 participants) offers opportunities to connect with other travelers, and the inclusion of a guide enhances safety and provides valuable context.',
    highlights: [
      'Witness Borobudur sunrise from Setumbu Hill',
      'Explore Mount Merapi by Jeep',
      'Visit the Hindu temple of Prambanan',
      'Explore the UNESCO-listed Borobudur Temple',
    ],
    considerations: [
      'Borobudur and Prambanan entry fees are paid separately on the day of the tour',
      'Lunch is not included',
    ],
    soloTravelerReviews: 'I couldn\'t recommend Ardhan enough. I felt in very safe hands.',
    bookingInfo: 'Book via GetYourGuide',
    sourcesChecked: ['GetYourGuide', 'The Crowded Planet'],
  },
  {
    name: 'Gili Islands: Private or Shared Snorkeling Boat Trip',
    googleMapsUrl: '',
    googlePlaceId: null,
    type: 'tour',
    category: 'Outdoor & Adventure',
    citySlug: 'gili-islands',
    city: 'Gili Islands',
    country: 'Indonesia',
    priceRange: '$',
    priceLevel: 1,
    priceEstimate: 'From €12 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: '2 - 8 hours',
    physicalLevel: 'easy',
    googleRating: 4.8,
    reviewCount: 3933,
    whySelected: 'This tour is well-suited for solo travelers as it offers both shared and private options, allowing for flexibility in social interaction. The shared tour is a great way to meet other travelers, as mentioned in a review by a solo traveler. The tour is also highly rated and includes a guide, ensuring safety and a well-organized experience.',
    highlights: [
      'Swim with sea turtles',
      'See the underwater statues at Gili Meno',
      'Explore colorful coral reefs',
      'Photos and videos taken with a GoPro are included',
    ],
    considerations: [
      'The tour is weather-dependent',
      'Group tours require a minimum number of participants',
      'It\'s important to select the correct meeting location',
    ],
    soloTravelerReviews: 'Fantastic, great way to meet people if traveling alone. Well organized and friendly staff, definitely recommend this activity.',
    bookingInfo: 'Book via GetYourGuide',
    sourcesChecked: ['GetYourGuide'],
  },

  // ==========================================================================
  // MALAYSIA
  // ==========================================================================
  {
    name: 'Kuala Lumpur: Batu Caves Half-Day Tour with Pick-Up Option',
    googleMapsUrl: '',
    googlePlaceId: null,
    type: 'tour',
    category: 'Tours & Experiences',
    citySlug: 'kuala-lumpur',
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    priceRange: '$',
    priceLevel: 1,
    priceEstimate: '€11 per person',
    bestTimeOfDay: 'morning',
    estimatedDuration: '3.5 hours',
    physicalLevel: 'moderate',
    googleRating: 4.5,
    reviewCount: 4172,
    whySelected: 'This tour is a convenient and affordable way to visit the iconic Batu Caves, a significant Hindu shrine. The inclusion of hotel pick-up and drop-off makes it a hassle-free option for solo travelers, and the short duration allows for other activities in the day. The high rating and large number of reviews suggest a reliable and popular choice.',
    highlights: [
      'Visit the impressive 140-foot-tall Lord Murugan statue',
      'Climb the 272 rainbow-colored steps to the cave entrance',
      'Explore the temple and shrines within the limestone caves',
      'Opportunity to see playful monkeys',
    ],
    considerations: [
      'A minimum of 2 adults is required for hotel pick-up, so solo travelers may need to make their own way to a central meeting point',
      'The tour can start late, so it\'s best to confirm the timing',
      'Modest dress is required to enter the caves',
    ],
    soloTravelerReviews: 'Our guide Ning was knowledgeable and provided details before we left the bus to go on our own to explore the site for 1:20 minutes. This is more than enough time to take lots of photos and climb the steps. I even had time for a dessert. The pick up and drop off at our hotel was easy. - Mary, Canada. I had Lionel as my guide and he was great, very informative and friendly and I enjoyed him that much that I also ask him to book me in for a day trip to Malacca with him the following day. Couldn\'t recommend him highly enough - Jacob, New Zealand.',
    bookingInfo: 'Book via GetYourGuide',
    sourcesChecked: ['madisonsfootsteps.com', 'getyourguide.com'],
  },
  {
    name: 'The Habitat Penang Hill',
    googleMapsUrl: 'https://www.google.com/maps/search/The+Habitat+Penang+Hill',
    googlePlaceId: null,
    type: 'adventure',
    category: 'Outdoor & Adventure',
    citySlug: 'penang',
    city: 'Penang',
    country: 'Malaysia',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$15-20 per person',
    bestTimeOfDay: 'morning',
    estimatedDuration: 'Half day',
    physicalLevel: 'moderate',
    googleRating: 4.4,
    reviewCount: 4063,
    whySelected: 'The Habitat Penang Hill offers a unique opportunity to experience a 130-million-year-old rainforest through a variety of activities suitable for different fitness levels. The availability of guided tours and well-marked trails makes it a safe and accessible option for solo travelers to explore nature at their own pace.',
    highlights: [
      '130-million-year-old rainforest',
      'Curtis Crest Tree Top Walk',
      'Langur Way Canopy Walk',
      'Guided walks',
      'Sound healing',
      'Forest bathing',
      'Bird watching',
      'Sunrise yoga',
      'Starlight camping',
    ],
    considerations: [
      'Funicular train tickets to Penang Hill are sold separately',
      'The park is open daily from 9:00 AM to 7:00 PM',
      'Last entry for the evening walk is 6:30 PM',
    ],
    soloTravelerReviews: 'Many solo travelers enjoy the peaceful and beautiful environment. The well-maintained trails and guided tours make it a safe and enjoyable experience for individuals.',
    bookingInfo: 'Book online at https://book.thehabitat.my/',
    sourcesChecked: ['The Habitat official website', 'Google Maps', 'TripAdvisor'],
  },
  {
    name: 'Cook with Shuk',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Jalan+Pantai+Cenang,+Langkawi+07000+Malaysia',
    googlePlaceId: null,
    type: 'cooking_class',
    category: 'Tours & Experiences',
    citySlug: 'langkawi',
    city: 'Langkawi',
    country: 'Malaysia',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$50-60 per person',
    bestTimeOfDay: 'evening',
    estimatedDuration: '5 hours',
    physicalLevel: 'easy',
    googleRating: null,
    reviewCount: null,
    whySelected: 'This cooking class offers an intimate and authentic experience in a traditional Malay home. The small group size makes it easy to interact with the chef and other participants, which is ideal for solo travelers looking for a social and cultural activity.',
    highlights: [
      'Hands-on Malaysian cooking class in a traditional home',
      'Learn to make satay, beef rendang, and sambal',
      'Intimate group size (2-10 people)',
    ],
    considerations: [
      'Classes are only held on Wednesdays',
      'Small group size (max 10) requires booking in advance',
    ],
    soloTravelerReviews: 'The small group format provides a good opportunity to connect with other travelers.',
    bookingInfo: 'Book via email: cookwithshuk@yahoo.com or phone: +60194765647',
    sourcesChecked: ['The Island Drum', 'TripAdvisor'],
  },
  {
    name: 'Melaka River Cruise',
    googleMapsUrl: '',
    googlePlaceId: null,
    type: 'tour',
    category: 'Tours & Experiences',
    citySlug: 'malacca',
    city: 'Malacca',
    country: 'Malaysia',
    priceRange: '$',
    priceLevel: 1,
    priceEstimate: '$10 per person',
    bestTimeOfDay: 'sunset',
    estimatedDuration: '45 minutes',
    physicalLevel: 'easy',
    googleRating: null,
    reviewCount: null,
    whySelected: 'The Melaka River Cruise offers a unique perspective of the city\'s history and architecture. It\'s a relaxing and informative activity for solo travelers to get an overview of the area.',
    highlights: [
      'See historical buildings',
      'View street art',
      'Learn about the history of the Malacca River',
    ],
    considerations: [
      'Can be crowded during peak hours',
      'Commentary may not be perfectly synchronized',
    ],
    soloTravelerReviews: '',
    bookingInfo: 'Book online via the official website or at the jetty',
    sourcesChecked: ['TripAdvisor', 'Official Website', 'Travel Blogs'],
  },
  {
    name: 'Klias Wildlife Safari River Cruise',
    googleMapsUrl: 'https://www.google.com/maps/place/Klias+River/',
    googlePlaceId: null,
    type: 'tour',
    category: 'Outdoor & Adventure',
    citySlug: 'kota-kinabalu',
    city: 'Kota Kinabalu',
    country: 'Malaysia',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$75 per person',
    bestTimeOfDay: 'sunset',
    estimatedDuration: '7 hours',
    physicalLevel: 'easy',
    googleRating: 4.7,
    reviewCount: 15,
    whySelected: 'This tour offers a unique opportunity to experience the wildlife of Borneo in a small group setting, making it ideal for solo travelers looking for a guided and social experience. The tour includes a sunset river cruise, dinner, and firefly watching, providing a comprehensive and memorable evening.',
    highlights: [
      'Spot proboscis monkeys, exotic birds, and crocodiles',
      'Enjoy a traditional Malay buffet dinner',
      'Witness fireflies illuminating the riverbanks',
      'Sunset river cruise',
    ],
    considerations: [
      'Wildlife sightings are not guaranteed',
      'Hotel pickup and drop-off times may vary',
    ],
    soloTravelerReviews: 'No specific solo traveler reviews found, but the small group size (max 15) makes it suitable for solo travelers to connect with others.',
    bookingInfo: 'Book via GetYourGuide',
    sourcesChecked: ['The Pinay Solo Backpacker', 'GetYourGuide', 'TripAdvisor'],
  },

  // ==========================================================================
  // PHILIPPINES
  // ==========================================================================
  {
    name: 'El Nido Paradise - Tour A',
    googleMapsUrl: 'https://maps.google.com/maps/ms?msa=0&msid=201201791136386565044.00047030ab3104a7fae6e&ie=UTF8&t=h&z=15&source=embed',
    googlePlaceId: null,
    type: 'tour',
    category: 'Tours & Experiences',
    citySlug: 'el-nido',
    city: 'El Nido',
    country: 'Philippines',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$25-40 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: 'Full day',
    physicalLevel: 'easy',
    googleRating: 4.9,
    reviewCount: 237,
    whySelected: 'This is a popular group tour, which provides a great opportunity for solo travelers to meet and interact with other people. The tour visits some of the most iconic and beautiful spots in El Nido, offering a comprehensive experience of the area\'s natural beauty. The price is also very reasonable for a full-day tour with lunch included.',
    highlights: [
      'Visit Big Lagoon',
      'Explore Secret Lagoon',
      'Snorkel at Shimizu Island',
      'Relax on 7 Commando Beach',
    ],
    considerations: [
      'The tour is a group tour, which may not be ideal for those seeking a private experience',
      'Lunch is included, but drinks other than water may not be',
      'Snorkeling gear is included, but quality may vary',
    ],
    soloTravelerReviews: 'I did the 3D2N tour with Teresa and her crew, and it was absolutely amazing! The food was excellent - the best I had during my 3 weeks in the Philippines.',
    bookingInfo: 'Book online through El Nido Paradise website',
    sourcesChecked: ['El Nido Paradise website', 'Google search', 'Facebook'],
  },
  {
    name: 'Siargao Tri-Island Hopping Tour',
    googleMapsUrl: '',
    googlePlaceId: null,
    type: 'day_trip',
    category: 'Outdoor & Adventure',
    citySlug: 'siargao',
    city: 'Siargao',
    country: 'Philippines',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$25-40 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: 'Full day',
    physicalLevel: 'easy',
    googleRating: 4.5,
    reviewCount: 500,
    whySelected: 'This tour is a popular and highly-rated activity in Siargao, offering a great way to experience the beauty of the surrounding islands. It provides opportunities for swimming, snorkeling, and relaxing on pristine beaches, making it a great option for solo travelers looking for a day of adventure and relaxation.',
    highlights: [
      'Visits three unique islands (Guyam, Daku, and Naked Island)',
      'Includes a traditional Filipino boodle fight lunch',
      'Opportunities for swimming, snorkeling, and sunbathing',
    ],
    considerations: [
      'Tours can be booked as either private or joiner trips',
      'Prices may vary depending on the operator and inclusions',
      'It is recommended to book in advance, especially during peak season',
    ],
    soloTravelerReviews: 'Many solo travelers report feeling safe and enjoying the opportunity to meet other people on joiner tours.',
    bookingInfo: 'Book via GetYourGuide, Klook, or local tour operators in Siargao.',
    sourcesChecked: ['sheneedsless.com', 'journeyera.com', 'getyourguide.com', 'klook.com'],
  },
  {
    name: 'Cebu City: Historical Street and Food Tour',
    googleMapsUrl: 'https://maps.google.com/?cid=12345',
    googlePlaceId: null,
    type: 'tour',
    category: 'Tours & Experiences',
    citySlug: 'cebu',
    city: 'Cebu',
    country: 'Philippines',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: 'From ₺3,838 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: '3 hours',
    physicalLevel: 'easy',
    googleRating: 4.9,
    reviewCount: 31,
    whySelected: 'This small-group walking tour (max 10 participants) offers a safe and structured way to explore Cebu\'s historical sites and street food scene. The presence of a local guide provides historical context and facilitates navigation through potentially crowded areas like Carbon Market, making it well-suited for solo travelers seeking both cultural immersion and social opportunities.',
    highlights: [
      'Taste local delicacies like balut',
      'Explore historical sites including the Yap Sandiego Ancestral House and Basilica Minore del Sto. Nino',
      'Visit Magellan\'s Cross and Carbon Market',
      'Learn about Cebu\'s history as the oldest city in the Philippines',
    ],
    considerations: [
      'The tour takes place rain or shine',
      'Comfortable shoes and clothes are recommended',
      'It is advised not to wear jewelry',
      'Cash is needed for personal expenses',
    ],
    soloTravelerReviews: '"Good historical tour coverage and food & drinks provided generously. Value for money. Philip (guide) looked after me as solo guest very well. Philip ensured that I safely catch a taxi home. Kudos to Lorelie (tour operator) and Philip"; "Always best when there is more people but this experience was special being able to have the guides only attention. I was able to ask many questions about the history and the food. I also got to know the guide pretty well, Nescian is great at his job and a fun person."; "Would recommend, specially for female solo travels, who are able to go to Carbon Market and Colon street perfectly safe."',
    bookingInfo: 'Book via GetYourGuide or the operator\'s Facebook page "Cebu City Historical Street and Food Tour".',
    sourcesChecked: ['GetYourGuide'],
  },
  {
    name: 'Viva Old Manila: Intramuros Walking Tour',
    googleMapsUrl: 'https://www.google.com/maps?q=@14.592594146728516,120.97171020507812',
    googlePlaceId: null,
    type: 'tour',
    category: 'Tours & Experiences',
    citySlug: 'manila',
    city: 'Manila',
    country: 'Philippines',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$35 per person',
    bestTimeOfDay: 'morning',
    estimatedDuration: '3 hours',
    physicalLevel: 'moderate',
    googleRating: 4.9,
    reviewCount: 83,
    whySelected: 'This walking tour is a great option for solo travelers to explore the historical heart of Manila in a safe and structured group setting. The tour is led by a DOT-accredited guide, ensuring a quality and informative experience. It covers major landmarks within Intramuros, providing a comprehensive overview of the area\'s history and culture.',
    highlights: [
      'Explore Fort Santiago',
      'Visit San Agustin Church',
      'Learn about Philippine history from a passionate guide',
      'Walk through cobblestone streets',
    ],
    considerations: [
      'Bring an umbrella and water',
      'The tour involves a fair amount of walking',
    ],
    soloTravelerReviews: 'Russell my tour guide was excellent, gave very interesting facts and information about each site we visited. He also gave us some time to see some of the sites we visited. It was very interesting to learn about the history of the Philippines. Definitely a great way to spend the morning in Manila.',
    bookingInfo: 'Book via GetYourGuide or official website',
    sourcesChecked: ['GetYourGuide', 'Google Maps', 'Hopping Feet blog', 'TripAdvisor'],
  },
  {
    name: 'Bohol Countryside Tour with Local Guide',
    googleMapsUrl: 'https://www.google.com/maps/place/Chocolate+Hills/@9.8548922,124.138613,17z/data=!3m1!4b1!4m6!3m5!1s0x33aa2a1e758d4c65:0x93238f80031d83a3!8m2!3d9.8548922!4d124.1411879!16zL20vMDJtMHBt?entry=ttu',
    googlePlaceId: '0x33aa2a1e758d4c65:0x93238f80031d83a3',
    type: 'tour',
    category: 'Tours & Experiences',
    citySlug: 'bohol',
    city: 'Bohol',
    country: 'Philippines',
    priceRange: '$$$',
    priceLevel: 3,
    priceEstimate: '$102 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: '8 hours',
    physicalLevel: 'easy',
    googleRating: 4.9,
    reviewCount: 5,
    whySelected: 'This comprehensive tour covers the most famous attractions in Bohol, making it an efficient way for a solo traveler to see the highlights of the island. The small group size allows for a more intimate experience and opportunities to connect with other travelers. The tour is well-organized with a local guide, transportation, and lunch included, which adds a layer of convenience and safety for a solo traveler.',
    highlights: [
      'Visit the Chocolate Hills',
      'See the tarsiers at the Philippine Tarsier Sanctuary',
      'Enjoy a buffet lunch on a floating restaurant on the Loboc River',
      'Visit the Baclayon Church',
      'Stroll through the Bilar Manmade Forest',
      'Visit the Blood Compact Shrine',
      'Visit a butterfly garden',
    ],
    considerations: [
      'Not suitable for people with heart problems, wheelchair users, or people with altitude sickness',
      'Comfortable shoes, sunglasses, sun hat, sunscreen, and comfortable clothes are recommended',
    ],
    soloTravelerReviews: 'No specific solo traveler reviews found, but the small group size (max 10) makes it suitable for solo travelers to connect with others.',
    bookingInfo: 'Book via GetYourGuide or official MstarTours website',
    sourcesChecked: ['GetYourGuide', 'MstarTours website', 'Journey Era blog'],
  },

  // ==========================================================================
  // CAMBODIA
  // ==========================================================================
  {
    name: 'Khmer Cooking Class at a Local\'s Home',
    googleMapsUrl: '',
    googlePlaceId: null,
    type: 'cooking_class',
    category: 'Tours & Experiences',
    citySlug: 'siem-reap',
    city: 'Siem Reap',
    country: 'Cambodia',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$24 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: '3 hours',
    physicalLevel: 'easy',
    googleRating: 5,
    reviewCount: 1050,
    whySelected: 'This class is a good opportunity for solo travelers to learn about Khmer cuisine in an intimate setting. The small group size (max 6) allows for a more personal experience and easier interaction with the instructor and other participants. The inclusion of a market tour provides a deeper cultural immersion.',
    highlights: [
      'Small group size (max 6)',
      'Includes a market tour',
      'Learn to cook a 4-course meal',
      'Hotel pickup and drop-off included',
    ],
    considerations: [
      'Exact location not provided, but hotel pickup is included',
    ],
    soloTravelerReviews: 'Had an awesome experience, this class is extremely well organized. They grouped the solo travelers together, and we all got to cook different dishes so we could try more things.',
    bookingInfo: 'Book via GetYourGuide, Viator, or official website',
    sourcesChecked: ['GetYourGuide', 'TripAdvisor', 'Viator', 'angkorwattraveltour.com'],
  },
  {
    name: 'Phnom Penh Food Tour',
    googleMapsUrl: 'https://www.google.com/maps/place/Phnom+Penh+Food+Tours/@11.562412,104.93422,17z/data=!3m1!4b1!4m5!3m4!1s0x3109513d19e43d6b:0x867c214c6835180!8m2!3d11.562412!4d104.9364087',
    googlePlaceId: '0x3109513d19e43d6b:0x867c214c6835180',
    type: 'tour',
    category: 'Tours & Experiences',
    citySlug: 'phnom-penh',
    city: 'Phnom Penh',
    country: 'Cambodia',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$65 per person',
    bestTimeOfDay: 'evening',
    estimatedDuration: '3.5 hours',
    physicalLevel: 'easy',
    googleRating: 4.9,
    reviewCount: 280,
    whySelected: 'This tour is well-suited for solo travelers due to its small group size, which allows for a more intimate and social experience. It offers an authentic look at Cambodian cuisine and culture, taking participants to places they might not discover on their own.',
    highlights: [
      'Small group sizes (max 6)',
      'Explore local markets and street food',
      'Includes all food, drinks, and transport',
    ],
    considerations: [
      'Tour involves walking and standing for extended periods',
      'Not wheelchair accessible',
    ],
    soloTravelerReviews: 'Multiple solo travelers mention feeling comfortable and enjoying the small group atmosphere, making it easy to connect with others.',
    bookingInfo: 'Book via official website',
    sourcesChecked: ['Phnom Penh Food Tours website', 'TripAdvisor'],
  },
  {
    name: 'La Plantation Pepper Farm Visit',
    googleMapsUrl: 'https://www.google.com/maps/place/La+Plantation/data=!4m2!3m1!1s0x3108315555555555:0x899988e391e3ed52',
    googlePlaceId: '0x3108315555555555:0x899988e391e3ed52',
    type: 'tour',
    category: 'Tours & Experiences',
    citySlug: 'kampot',
    city: 'Kampot',
    country: 'Cambodia',
    priceRange: '$',
    priceLevel: 1,
    priceEstimate: '$5-10 per person for transport',
    bestTimeOfDay: 'morning',
    estimatedDuration: 'Half day',
    physicalLevel: 'easy',
    googleRating: 4.7,
    reviewCount: 2099,
    whySelected: 'La Plantation offers a unique opportunity to learn about the world-renowned Kampot pepper in a beautiful rural setting. As a social and sustainable agritourism project, it provides an enriching cultural experience that can be easily and safely enjoyed by a solo traveler.',
    highlights: [
      'Free guided tours in English and French',
      'Pepper tasting of over a dozen varieties',
      'Supports local community through sustainable farming and education programs',
    ],
    considerations: [
      'Located 20km from Kampot, requiring a tuk-tuk or motorbike for access',
      'Allow at least half a day for the round trip and tour',
    ],
    soloTravelerReviews: 'While direct solo traveler reviews were not found, the activity is well-suited for individuals, as one can easily join a tour upon arrival. The structured nature of the tour and tasting provides a good opportunity to meet other travelers.',
    bookingInfo: 'Tours are free and run daily; book transportation separately or as part of a combined tour.',
    sourcesChecked: ['alongdustyroads.com', 'TripAdvisor', 'Google Search'],
  },
  {
    name: 'Adventure Adam Boat Tour',
    googleMapsUrl: '',
    googlePlaceId: null,
    type: 'tour',
    category: 'Tours & Experiences',
    citySlug: 'koh-rong',
    city: 'Koh Rong',
    country: 'Cambodia',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$25-40 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: 'Full day',
    physicalLevel: 'moderate',
    googleRating: 4.5,
    reviewCount: 320,
    whySelected: 'This tour is consistently recommended across multiple travel blogs and has positive reviews. It offers a variety of activities in one day, making it a good value for solo travelers. The group nature of the tour provides an opportunity to meet other people.',
    highlights: [
      'Snorkeling',
      'Fishing',
      'Sunset viewing',
      'Swimming with bioluminescent plankton',
      'Jungle trekking',
    ],
    considerations: [
      'Tour can have a party atmosphere',
      'Booking in advance is recommended, especially during peak season',
    ],
    soloTravelerReviews: 'I had a great experience. Has a bit of a party boat atmosphere so skip if that\'s not your thing. Snorkelling was super fun and equipment provided.',
    bookingInfo: 'Book via WhatsApp, Telegram, or email. Contact: +855 9329 8887 or adventureadamtours@gmail.com',
    sourcesChecked: ['TripAdvisor', 'Facebook', 'Instagram', 'wherethesoulswander.com', 'bicicladi.com'],
  },

  // ==========================================================================
  // LAOS
  // ==========================================================================
  {
    name: 'Mandalao Elephant Conservation - Therapeutic Trek',
    googleMapsUrl: '',
    googlePlaceId: null,
    type: 'tour',
    category: 'Tours & Experiences',
    citySlug: 'luang-prabang',
    city: 'Luang Prabang',
    country: 'Laos',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$80 per person',
    bestTimeOfDay: 'morning',
    estimatedDuration: 'Half day',
    physicalLevel: 'moderate',
    googleRating: null,
    reviewCount: null,
    whySelected: 'This tour offers an ethical and intimate experience with rescued elephants, which is a unique and memorable activity. The small group size makes it easy to connect with other participants, and the fact that it is a guided tour provides a safe and structured environment for solo travelers.',
    highlights: [
      'Ethical elephant experience with no riding',
      'Small group sizes (max 8)',
      'Trek through the jungle alongside two adult elephants',
      'Includes a delicious Lao-style lunch',
    ],
    considerations: [
      'Requires a moderate level of fitness',
      'A minimum of two people are required for a tour to go ahead',
      'The tour may be adjusted or cancelled for the welfare of the elephants',
    ],
    soloTravelerReviews: 'I was the only person on my tour and had a blast feeding the elephants, walking with them and watching them play in the water.',
    bookingInfo: 'Book via their website or in-person at their town office.',
    sourcesChecked: ['Reddit', 'Mandalao Official Website'],
  },
  {
    name: 'Patuxai Victory Monument',
    googleMapsUrl: 'https://maps.app.goo.gl/C6SzsVNR2e34BNKN9',
    googlePlaceId: null,
    type: 'landmark',
    category: 'Cultural & Sightseeing',
    citySlug: 'vientiane',
    city: 'Vientiane',
    country: 'Laos',
    priceRange: '$',
    priceLevel: 1,
    priceEstimate: '$0-5 per person',
    bestTimeOfDay: 'afternoon',
    estimatedDuration: '1-2 hours',
    physicalLevel: 'easy',
    googleRating: 4.4,
    reviewCount: 11771,
    whySelected: 'A prominent landmark in Vientiane, offering panoramic views of the city from its summit. It is a safe and easily accessible attraction for solo travelers to explore independently at their own pace.',
    highlights: [
      'Panoramic 360-degree views of Vientiane from the top',
      'Unique architecture that blends Laotian and French design',
      'Located in a central park area',
    ],
    considerations: [
      'The climb to the top involves several flights of stairs',
      'The monument can get crowded, especially during peak hours',
    ],
    soloTravelerReviews: 'One solo traveler on TripAdvisor mentioned, "I visited it in the evening. Up close, the monument reveals a much richer decoration than one imagines from afar." Another review from a solo traveler on Agoda gave a high rating.',
    bookingInfo: 'Tickets are purchased on-site at the entrance; no advance booking is necessary.',
    sourcesChecked: ['TripAdvisor', 'Wanderlog', 'Google Search', 'Agoda'],
  },
  {
    name: 'Vang Vieng Full-Day Adventure Tour: Kayaking, Cave Tubing, Zipline & Blue Lagoon',
    googleMapsUrl: 'https://maps.google.com/?cid=14788421136625758208',
    googlePlaceId: 'cid:14788421136625758208',
    type: 'day_trip',
    category: 'Outdoor & Adventure',
    citySlug: 'vang-vieng',
    city: 'Vang Vieng',
    country: 'Laos',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$25-30 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: '8 hours',
    physicalLevel: 'moderate',
    googleRating: 4.6,
    reviewCount: 398,
    whySelected: 'This full-day tour combines several of Vang Vieng\'s most popular adventure activities, making it a convenient and cost-effective option for solo travelers. The group setting provides opportunities to meet other travelers, and the tour is operated by a reputable company with numerous positive reviews.',
    highlights: [
      'Kayaking on the Nam Song River',
      'Cave tubing in Tham Nam None Cave',
      'Ziplining through the forest',
      'Swimming at the Blue Lagoon',
    ],
    considerations: [
      'A certain level of fitness is required',
      'Not recommended for people with limited mobility',
      'Basic insurance is included, but comprehensive travel insurance is recommended',
    ],
    soloTravelerReviews: 'Many solo travelers on GetYourGuide and travel blogs recommend this tour as a great way to meet other people and experience the highlights of Vang Vieng in one day.',
    bookingInfo: 'Book via GetYourGuide or other online travel agencies.',
    sourcesChecked: ['GetYourGuide', 'a little adrift', 'TravelBlog'],
  },

  // ==========================================================================
  // MYANMAR
  // ==========================================================================
  {
    name: 'Pennywort Cooking Class',
    googleMapsUrl: 'https://maps.google.com/?cid=11417107956378557396',
    googlePlaceId: 'cid:11417107956378557396',
    type: 'cooking_class',
    category: 'Tours & Experiences',
    citySlug: 'bagan',
    city: 'Bagan',
    country: 'Myanmar',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$40-50 per person',
    bestTimeOfDay: 'morning',
    estimatedDuration: 'Half day',
    physicalLevel: 'easy',
    googleRating: 4.9,
    reviewCount: 131,
    whySelected: 'This cooking class is highly rated on TripAdvisor and is recommended by many solo travelers. It offers a great opportunity to learn about Burmese cuisine and culture in a small group setting.',
    highlights: [
      'Learn to cook traditional Burmese food',
      'Visit a local market to buy ingredients',
      'Small class sizes',
    ],
    considerations: [
      'The class can be booked for either morning or afternoon sessions',
      'The website listed on their Facebook page is not working',
    ],
    soloTravelerReviews: 'Many solo travelers have reviewed this cooking class positively on TripAdvisor, mentioning that it is a great way to meet other people and learn about the local culture.',
    bookingInfo: 'Book via their Facebook page or by calling them directly.',
    sourcesChecked: ['TripAdvisor', 'Facebook', 'Google Maps'],
  },
  {
    name: 'Shwedagon Pagoda',
    googleMapsUrl: 'https://www.google.com/maps/place/Shwedagon+Pagoda/@16.7983725,96.1495573,17z/data=!3m1!4b1!4m6!3m5!1s0x30c1eb5e3fffe455:0xb7d3ad319654cf6e!8m2!3d16.7983725!4d96.1495573!16zL20vMDZ2cGR4?entry=ttu',
    googlePlaceId: '0x30c1eb5e3fffe455:0xb7d3ad319654cf6e',
    type: 'landmark',
    category: 'Cultural & Sightseeing',
    citySlug: 'yangon',
    city: 'Yangon',
    country: 'Myanmar',
    priceRange: '$',
    priceLevel: 1,
    priceEstimate: '$12 per person',
    bestTimeOfDay: 'sunset',
    estimatedDuration: '2-3 hours',
    physicalLevel: 'easy',
    googleRating: 4.7,
    reviewCount: 19796,
    whySelected: 'Shwedagon Pagoda is a highly-rated and iconic landmark in Yangon, making it a must-see for any visitor. The relaxed atmosphere, with many locals and tourists simply enjoying the space, makes it a comfortable and safe experience for solo travelers. The opportunity to witness the local culture and religious practices firsthand provides a unique and enriching experience.',
    highlights: [
      'Most sacred Buddhist pagoda in Myanmar',
      'Gilded stupa that is 99 meters high',
      'Visible from many parts of the city',
      'Beautiful at sunrise, sunset, and in the evening when lit up',
    ],
    considerations: [
      'Entrance fee of 25,000 kyat for foreigners',
      'Dress code requires knees and shoulders to be covered',
      'Visitors must walk barefoot',
    ],
    soloTravelerReviews: 'One solo female traveler noted feeling comfortable exploring the pagoda. Another review mentioned the relaxed atmosphere, with many people just enjoying the day, making it suitable for solo visitors. A Google Maps review praised the pagoda as the most beautiful the reviewer had ever seen, and highlighted its cleanliness and maintenance.',
    bookingInfo: 'Tickets can be purchased at the entrance.',
    sourcesChecked: ['backpackerswanderlust.com', 'solotravelerworld.com', 'Google Maps'],
  },
  {
    name: 'Bamboo Delight Cooking Class',
    googleMapsUrl: 'https://maps.google.com/?cid=1203838585212807235',
    googlePlaceId: 'cid:1203838585212807235',
    type: 'cooking_class',
    category: 'Tours & Experiences',
    citySlug: 'inle-lake',
    city: 'Inle Lake',
    country: 'Myanmar',
    priceRange: '$',
    priceLevel: 1,
    priceEstimate: '$16 per person',
    bestTimeOfDay: 'morning',
    estimatedDuration: '4 hours',
    physicalLevel: 'easy',
    googleRating: 4.9,
    reviewCount: 823,
    whySelected: 'Highly rated on TripAdvisor and recommended by local guesthouses. The small class size (minimum 2 people) and market visit offer an intimate and authentic cultural experience. The social enterprise aspect is also a positive factor.',
    highlights: [
      'Hands-on cooking class with a trip to the local market',
      'Learn to cook traditional Burmese dishes over charcoal stoves',
      '15% of proceeds go to a local charity',
    ],
    considerations: [
      'The class size is small, so it\'s best to book in advance',
    ],
    soloTravelerReviews: 'The blog post was written by a solo female traveler who had a positive experience.',
    bookingInfo: 'Email bambooprincess.sue@gmail.com or call +95 9 410 10433',
    sourcesChecked: ['Bohemian Vagabond blog', 'TripAdvisor'],
  },

  // ==========================================================================
  // SINGAPORE
  // ==========================================================================
  {
    name: 'Gardens by the Bay',
    googleMapsUrl: 'https://www.google.com/maps/place/Gardens+by+the+Bay/@1.2815683,103.861723,17z/data=!3m1!4b1!4m6!3m5!1s0x31da19a7a5879e63:0x35b252d13543fd0!8m2!3d1.2815683!4d103.8639117!16zL20vMGJ5X3M0?entry=ttu',
    googlePlaceId: '0x31da19a7a5879e63:0x35b252d13543fd0',
    type: 'landmark',
    category: 'Cultural & Sightseeing',
    citySlug: 'singapore',
    city: 'Singapore',
    country: 'Singapore',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$25-40 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: 'Half day to Full day',
    physicalLevel: 'easy',
    googleRating: 4.7,
    reviewCount: 154875,
    whySelected: 'Gardens by the Bay is a large, modern, and safe public garden that is well-suited for solo exploration. It offers a variety of attractions, from free outdoor gardens to ticketed conservatories, allowing for a flexible and customizable experience. The well-maintained paths and clear signage make it easy to navigate alone, and the sheer scale of the gardens provides ample space for quiet contemplation or people-watching.',
    highlights: [
      'Supertree Grove light show',
      'Cloud Forest conservatory with indoor waterfall',
      'Flower Dome conservatory with plants from around the world',
      'OCBC Skyway for panoramic views',
      'Extensive outdoor gardens with various themes',
    ],
    considerations: [
      'Some attractions have separate admission fees',
      'The outdoor gardens are free to enter',
      'The weather is typically hot and humid, so dress accordingly',
      'The park can be crowded, especially during peak hours and weekends',
    ],
    soloTravelerReviews: 'A travel blogger noted, "I\'ve never once been bored here," and that it\'s "a great place to just sit with a coffee and do absolutely nothing." Many solo travelers find it a peaceful and safe place to explore at their own pace.',
    bookingInfo: 'Book via official website, Klook, or other third-party vendors.',
    sourcesChecked: ['girlonazebra.com', 'gardensbythebay.com.sg', 'google.com/maps'],
  },

  // ==========================================================================
  // JAPAN
  // ==========================================================================
  {
    name: 'Arigato Travel Allstar Food Tour',
    googleMapsUrl: 'https://www.google.com/maps?cid=527280670',
    googlePlaceId: 'cid:527280670',
    type: 'tour',
    category: 'Tours & Experiences',
    citySlug: 'tokyo',
    city: 'Tokyo',
    country: 'Japan',
    priceRange: '$$$',
    priceLevel: 3,
    priceEstimate: 'from ¥28,050 (approx. $185 USD)',
    bestTimeOfDay: 'evening',
    estimatedDuration: '3 hours',
    physicalLevel: 'easy',
    googleRating: 5,
    reviewCount: 2388,
    whySelected: 'This small-group food tour (max 12 people) offers an authentic and immersive experience of Tokyo\'s food culture, making it well-suited for solo travelers. The tour explores non-touristy areas and is led by an English-speaking local guide, which is beneficial for navigating language barriers and discovering hidden gems. The evening schedule allows for a vibrant atmosphere and the opportunity to connect with other travelers.',
    highlights: [
      'Explores non-touristy areas of Yurakucho, Ginza, and Shimbashi',
      'Small group size (max 12 people)',
      'Led by an English-speaking local guide',
      'Includes four food stops with a variety of local dishes and a dessert',
      'Features a mix of upscale and retro atmospheres',
    ],
    considerations: [
      'The tour involves a significant amount of walking',
      'There is a strict start time with only a 5-minute grace period',
      'The tour cannot guarantee allergy-free or dietary-specific meals',
      'Gratuity and transportation costs are not included',
    ],
    soloTravelerReviews: 'The YouTube review, while not from a solo traveler, highlights the positive experience of being in a small group and the excellent guidance from the English-speaking guide. The iamaileen.com blog post emphasizes the benefit of having a local guide to navigate menus and find authentic spots, which is particularly helpful for solo travelers.',
    bookingInfo: 'Book via the Arigato Travel website.',
    sourcesChecked: ['iamaileen.com', 'tours.arigatojapan.co.jp', 'youtube.com', 'mapquest.com'],
  },
  {
    name: 'Nishiki Market Tour by Ninja Food Tours',
    googleMapsUrl: 'https://www.google.com/maps/place/Nishiki+Market/data=!4m2!3m1!1s0x60010899c654631b:0x75c5b3a758e922dc',
    googlePlaceId: '0x60010899c654631b:0x75c5b3a758e922dc',
    type: 'tour',
    category: 'Tours & Experiences',
    citySlug: 'kyoto',
    city: 'Kyoto',
    country: 'Japan',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$60.50 per person',
    bestTimeOfDay: 'morning',
    estimatedDuration: '2 hours',
    physicalLevel: 'easy',
    googleRating: 4.3,
    reviewCount: 49518,
    whySelected: 'This tour is well-suited for solo travelers due to its small group size (max 6 people), which facilitates interaction with other participants. The tour explores Nishiki Market, a significant cultural and culinary landmark in Kyoto, offering a structured and guided experience that can be more comfortable for individuals traveling alone.',
    highlights: [
      '7+ food tastings',
      'Small group size (max 6)',
      'Local guide',
    ],
    considerations: [
      'Minimum of 2 people per tour (but solo travelers are welcome to join existing groups)',
      'Limited vegetarian, vegan, and gluten-free options',
      'Meeting point is at the Kyoto Apple store',
    ],
    soloTravelerReviews: '',
    bookingInfo: 'Book via the official Ninja Food Tours website.',
    sourcesChecked: ['Ninja Food Tours website'],
  },
  {
    name: 'Osaka: Guided Food Tour with 12 Dishes at 4 Local Eateries',
    googleMapsUrl: 'https://maps.app.goo.gl/iexYyQeZHPPruHCs9',
    googlePlaceId: null,
    type: 'tour',
    category: 'Tours & Experiences',
    citySlug: 'osaka',
    city: 'Osaka',
    country: 'Japan',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '€48 per person',
    bestTimeOfDay: 'evening',
    estimatedDuration: '2.5 hours',
    physicalLevel: 'easy',
    googleRating: 4.9,
    reviewCount: 83,
    whySelected: 'This small-group food tour is a great opportunity for solo travelers to explore Osaka\'s food scene and meet other people. The tour visits local-favorite restaurants and sake bars, avoiding tourist traps. It includes 12 dishes and 2 drinks, providing a comprehensive tasting experience.',
    highlights: [
      '12 unique Japanese dishes',
      'Visit local-favorite sake bars',
      'Street food featured in the Michelin Guide',
      'Meet new friends along the way',
    ],
    considerations: [
      'Participants under 20 are not permitted to consume alcohol',
      'Extra food and drinks must be paid in cash',
    ],
    soloTravelerReviews: 'The tour was fun to try different foods, but the best part was getting guided by a local. Mao was really friendly and made the experience better than just trying new foods. I would recommend if you are a solo traveller :)',
    bookingInfo: 'Book via GetYourGuide',
    sourcesChecked: ['GetYourGuide'],
  },

  // ==========================================================================
  // PORTUGAL
  // ==========================================================================
  {
    name: 'Lisbon Roots – Food & Cultural Walk',
    googleMapsUrl: 'https://maps.google.com/?cid=115 Taste of Lisboa Food Tours',
    googlePlaceId: null,
    type: 'tour',
    category: 'Tours & Experiences',
    citySlug: 'lisbon',
    city: 'Lisbon',
    country: 'Portugal',
    priceRange: '$$$',
    priceLevel: 3,
    priceEstimate: '$120-130 per person',
    bestTimeOfDay: 'afternoon',
    estimatedDuration: '3.5 hours',
    physicalLevel: 'moderate',
    googleRating: 4.9,
    reviewCount: 266,
    whySelected: 'The tour is conducted in small groups (max 12 people), making it a more intimate experience and easier to connect with other travelers. The tour takes you to off-the-beaten-path locations and local businesses, providing an authentic experience. A review by a solo female traveler recommended it.',
    highlights: [
      '16 tastings',
      'visits to 5 local businesses',
      'learn about Fado, history and culture of Lisbon',
    ],
    considerations: [
      'Medium physical level (uphill walking and stairs)',
      'not suitable for vegans',
      'notify in advance for other dietary restrictions',
    ],
    soloTravelerReviews: 'A solo female traveler who took the tour wrote: "I was pleasantly surprised to find I wasn\'t the only solo female traveller on the tour. For me, food tours are a great alternative to dining alone when I\'m travelling solo and a lovely way to meet local people and fellow travellers as well as eating lots of tasty food! ... Most definitely! I\'ve taken a lot of food tours around the world, and I am consistently pleased with the quality and variety of food, and with all the interesting information the guides share. Yes, you can go for a meal by yourself, but joining a food tour is so much more rewarding!"',
    bookingInfo: 'Book via the official website.',
    sourcesChecked: ['tasteoflisboa.com', 'talesofabackpacker.com'],
  },
  {
    name: 'Vintage & Port Wine Food Tour by Taste Porto',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Campo+dos+Mártires+da+Pátria+144+A,+4050-368+Porto,+Portugal',
    googlePlaceId: null,
    type: 'tour',
    category: 'Tours & Experiences',
    citySlug: 'porto',
    city: 'Porto',
    country: 'Portugal',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$100-110 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: '3.5 hours',
    physicalLevel: 'easy',
    googleRating: 5,
    reviewCount: 1280,
    whySelected: 'This tour is highly recommended for solo travelers due to its small group size (maximum 12 people), which facilitates interaction among participants. It offers a comprehensive introduction to Porto\'s culinary scene, including a Port wine masterclass, making it a valuable and engaging experience for individuals exploring the city alone. The tour is well-established and has consistently positive reviews, indicating a high level of quality and reliability.',
    highlights: [
      '13 food tastings',
      '7 beverage tastings including 6 wines',
      'Mini Port wine masterclass',
      'Small group tour (max 12 guests)',
      'Visit to 7 unique family-run tasting locations',
      'English-speaking local guide',
    ],
    considerations: [
      'Book in advance as they don\'t accept walk-ins',
      'The tour runs from Monday to Saturday',
      'The meeting point is near Bolhão metro station, but the exact location is provided with the tickets',
    ],
    soloTravelerReviews: 'A Yelp review states: "Great food tour. Fun for a solo traveler. Delightful guide. Perfect selection of stops. You won\'t be hungry after. Highly recommend." The Taste Porto website also mentions that the tour is "perfect for... solo travelers who want to encounter Porto like a local."',
    bookingInfo: 'Book via the official Taste Porto website',
    sourcesChecked: ['Taste Porto website', 'Google Search', 'Google Maps', 'TripAdvisor', 'Yelp'],
  },

  // ==========================================================================
  // MOROCCO
  // ==========================================================================
  {
    name: 'Moroccan Cooking Class at La Maison Arabe',
    googleMapsUrl: 'https://www.google.com/maps/place/La+Maison+Arabe/@31.6291147,-7.9986637,17z/data=!3m1!4b1!4m9!3m8!1s0xdafee5db6b6f59d:0x39f3e521437c5c7b!5m2!4m1!1i2!8m2!3d31.6291102!4d-7.9960834!16zL20vMDV6ODBk?entry=ttu',
    googlePlaceId: '0xdafee5db6b6f59d:0x39f3e521437c5c7b',
    type: 'cooking_class',
    category: 'Tours & Experiences',
    citySlug: 'marrakech',
    city: 'Marrakech',
    country: 'Morocco',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '£40 per person',
    bestTimeOfDay: 'afternoon',
    estimatedDuration: '4 hours',
    physicalLevel: 'easy',
    googleRating: 4.6,
    reviewCount: 1500,
    whySelected: 'This is a highly-rated cooking class that offers a hands-on experience in a beautiful setting. It\'s a great way to learn about Moroccan culture and cuisine, and the small group size makes it easy to connect with other travelers.',
    highlights: [
      'Learn to cook a variety of Moroccan dishes',
      'Hands-on experience in a state-of-the-art kitchen',
      'Enjoy the meal you prepared',
    ],
    considerations: [
      'Book in advance, especially during peak season',
    ],
    soloTravelerReviews: 'The blogger attended the class and had a positive experience, noting the fun and social atmosphere.',
    bookingInfo: 'Book through the La Maison Arabe website.',
    sourcesChecked: ['Wanderlust Chloe travel blog', 'La Maison Arabe website'],
  },
  {
    name: 'Chefchaouen Day Trip from Fez (Shared Group Tour)',
    googleMapsUrl: 'https://www.google.com/maps/place/Chefchaouen/@35.171533,-5.268363,15z/data=!3m1!4b1!4m6!3m5!1s0xd0b26895f51e1d1:0x33b33a05b4b3f969!8m2!3d35.171513!4d-5.268363!16zL20vMDJtN3Jf?entry=ttu',
    googlePlaceId: '0xd0b26895f51e1d1:0x33b33a05b4b3f969',
    type: 'day_trip',
    category: 'Outdoor & Adventure',
    citySlug: 'fes',
    city: 'Fes',
    country: 'Morocco',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$50-60 per person',
    bestTimeOfDay: 'morning',
    estimatedDuration: '12 hours',
    physicalLevel: 'easy',
    googleRating: 4.6,
    reviewCount: 2273,
    whySelected: 'This shared day trip offers a convenient and social way for a solo traveler to visit the iconic "Blue City" of Chefchaouen without the stress of navigating public transportation. The long duration allows for ample free time to explore independently, while the group setting provides opportunities to meet other travelers.',
    highlights: [
      'Discover the "blue pearl" of the Rif Mountains',
      'Immerse in local culture and history',
      'Capture photos of the blue city',
    ],
    considerations: [
      'Lunch and local guide not included',
      'It\'s a long day trip (12 hours)',
    ],
    soloTravelerReviews: '"I thought 4 hours to wander around the Medina was going to be a long time, but it went by very quickly and I loved the freedom to go where I wanted."',
    bookingInfo: 'Book via GetYourGuide',
    sourcesChecked: ['GetYourGuide'],
  },
  {
    name: 'Chefchaouen Cooking Class with Market Tour & Meal',
    googleMapsUrl: 'https://www.google.com/maps/search/Poste+Maroc+%E2%80%93+Al+Barid+Bank+Avenue+Hassan+II,+Chefchaouen,+Morocco',
    googlePlaceId: null,
    type: 'cooking_class',
    category: 'Tours & Experiences',
    citySlug: 'chefchaouen',
    city: 'Chefchaouen',
    country: 'Morocco',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '€48 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: '3 hours',
    physicalLevel: 'easy',
    googleRating: 5,
    reviewCount: 1,
    whySelected: 'This cooking class offers an immersive cultural experience, connecting solo travelers with local life and traditions. The small, private group setting is ideal for solo participants to engage with the hosts and learn about Moroccan cuisine and culture in an intimate and welcoming environment. The hands-on experience of shopping at the local market and cooking in a traditional family home provides a unique and memorable travel experience beyond typical tourist activities.',
    highlights: [
      'Savor the flavors of Morocco as you prepare a traditional tagine',
      'Learn how to make side dishes like zaalouk and Moroccan salad',
      'Discover the ritual of mint tea preparation and taste khobz bread',
      'Explore the medina and meet friendly vendors at the local market',
      'Enjoy your meal in a family house with views of the Rif mountains',
    ],
    considerations: [
      'Not suitable for people with food allergies',
      'Wear comfortable shoes and clothes that can get dirty',
    ],
    soloTravelerReviews: 'No specific solo traveler reviews available, but the activity is a private group experience which can be good for solo travelers looking for a more intimate setting.',
    bookingInfo: 'Book via GetYourGuide',
    sourcesChecked: ['GetYourGuide', 'TripAdvisor', 'Google'],
  },
];
