/**
 * Sola Activities - Ready to Seed
 * Deduplicated against existing database content
 * Generated: 2026-02-03T21:14:06.155Z
 *
 * Total: 43 NEW activities across 43 cities in 12 countries
 */

export interface ActivityEntry {
  name: string;
  googleMapsUrl: string;
  googlePlaceId: string | null;
  type: 'tour' | 'cooking_class' | 'landmark' | 'viewpoint' | 'day_trip' | 'adventure';
  category: string;
  citySlug: string;
  city: string;
  country: string;
  priceRange: '$' | '$$' | '$$$';
  priceLevel: 1 | 2 | 3;
  priceEstimate: string | null;
  bestTimeOfDay: 'morning' | 'afternoon' | 'evening' | 'sunset' | 'any';
  estimatedDuration: string;
  physicalLevel: 'easy' | 'moderate';
  googleRating: number | null;
  reviewCount: number | null;
  whySelected: string;
  highlights: string[];
  considerations: string[];
  soloTravelerReviews: string;
  bookingInfo: string;
  sourcesChecked: string[];
}

export const ACTIVITIES_TO_SEED: ActivityEntry[] = [
  // ==========================================================================
  // CAMBODIA
  // ==========================================================================
  {
    name: 'Khmer Roots Cafe Cooking Class',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=10.622763,104.306534',
    googlePlaceId: null,
    type: 'cooking_class',
    category: 'Unique Experience',
    citySlug: 'kampot',
    city: 'Kampot',
    country: 'Cambodia',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$20 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: 'Half day',
    physicalLevel: 'easy',
    googleRating: 4.5,
    reviewCount: 124,
    whySelected: 'This is a highly-rated, authentic Khmer cooking class in a rural setting, offering a unique farm-to-table experience. It provides an opportunity for cultural immersion and learning traditional cooking techniques, making it a memorable experience for solo travelers seeking something beyond typical tourist activities.',
    highlights: ['Authentic Khmer cuisine', 'Farm-to-table experience', 'Rural setting near Secret Lake', 'Hands-on cooking class'],
    considerations: ['Located about an hour outside of Kampot', 'Booking at least one day in advance is required', 'Limited internet access at the location.'],
    soloTravelerReviews: 'Many solo travelers have praised the class for its authenticity and the welcoming nature of the host.',
    bookingInfo: 'Book by calling +855 88 356 8016 at least one day in advance.',
    sourcesChecked: ['tripadvisor', 'facebook', 'a variety of travel blogs'],
  },
  {
    name: 'Kayaking at Lily\'s Riverhouse',
    googleMapsUrl: 'https://www.google.com/maps/place/Lily\'s+Riverhouse/@10.7751,103.283,17z/data=!3m1!4b1!4m5!3m4!1s0x3107c17a104efd8b:0xf254dd3a708f7f43!8m2!3d10.7751!4d103.2851887',
    googlePlaceId: '0x3107c17a104efd8b:0xf254dd3a708f7f43',
    type: 'adventure',
    category: 'Outdoor & Adventure',
    citySlug: 'koh-rong',
    city: 'Koh Rong',
    country: 'Cambodia',
    priceRange: '$',
    priceLevel: 1,
    priceEstimate: '$10-20 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: 'Half day',
    physicalLevel: 'moderate',
    googleRating: 4.5,
    reviewCount: 20,
    whySelected: 'This activity offers a unique opportunity to explore the natural beauty of Koh Rong\'s rivers and mangroves. It is a peaceful and independent activity, making it ideal for solo travelers looking for a quiet and immersive experience.',
    highlights: ['Explore the river and surrounding nature', 'Peaceful and serene environment', 'Opportunity to see a floating village'],
    considerations: ['Cash only', 'No internet access', 'Additional charge for canoeing'],
    soloTravelerReviews: 'No specific reviews from solo travelers were found, but the guesthouse is described as suitable for solo travelers.',
    bookingInfo: 'Book directly at Lily\'s Riverhouse',
    sourcesChecked: ['reddit', 'lily-s-riverhouse.scarletsailsresort.co'],
  },
  {
    name: 'Street Art on Street 93',
    googleMapsUrl: 'https://www.google.com/maps/place/Street+93,+Phnom+Penh,+Cambodia/@11.573333,104.916667,17z/data=!3m1!4b1!4m5!3m4!1s0x3109513e5e5e5e5e:0x5e5e5e5e5e5e5e5e!8m2!3d11.573333!4d104.918856?hl=en-US',
    googlePlaceId: '0x3109513e5e5e5e5e:0x5e5e5e5e5e5e5e5e',
    type: 'landmark',
    category: 'Cultural & Sightseeing',
    citySlug: 'phnom-penh',
    city: 'Phnom Penh',
    country: 'Cambodia',
    priceRange: '$',
    priceLevel: 1,
    priceEstimate: 'Free',
    bestTimeOfDay: 'morning',
    estimatedDuration: '1-2 hours',
    physicalLevel: 'easy',
    googleRating: 4.5,
    reviewCount: 100,
    whySelected: 'This is a fantastic free activity for solo travelers who appreciate urban art and exploring off-the-beaten-path neighborhoods. It offers a glimpse into the local creative scene and provides great photo opportunities.',
    highlights: ['Vibrant and ever-changing street art', 'Opportunity to see a different side of Phnom Penh', 'Supports local artists'],
    considerations: ['This is an informal art display in a public space, not a formal gallery.'],
    soloTravelerReviews: 'A great way to spend a morning wandering around and taking photos. I felt perfectly safe exploring on my own.',
    bookingInfo: 'No booking required',
    sourcesChecked: ['travel-lush.com', 'google maps', 'tripadvisor'],
  },
  {
    name: 'Cambodian Pottery Class',
    googleMapsUrl: 'https://www.google.com/maps/place/Khmer+Ceramics+%26+Fine+Arts+Centre/@13.375166,103.866969,17z/data=!3m1!4b1!4m5!3m4!1s0x311017f5a5c5c5c5:0x7c5c5c5c5c5c5c5c!8m2!3d13.375166!4d103.869158',
    googlePlaceId: '0x311017f5a5c5c5c5:0x7c5c5c5c5c5c5c5c',
    type: 'tour',
    category: 'Unique Experience',
    citySlug: 'siem-reap',
    city: 'Siem Reap',
    country: 'Cambodia',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$25 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: '1 hour 45 minutes',
    physicalLevel: 'easy',
    googleRating: 4.5,
    reviewCount: 2447,
    whySelected: 'This pottery class offers a unique, hands-on cultural experience that is perfect for solo travelers. The structured class environment provides a great opportunity to learn a new skill and create a personal souvenir while interacting with local artisans in a comfortable and supportive setting.',
    highlights: ['Learn from local artisans', 'Create your own pottery bowl', 'Use traditional Khmer carving tools'],
    considerations: ['Your piece will be ready for pickup the following week after being fired in a kiln. Shipping can be arranged at your own expense.'],
    soloTravelerReviews: 'Many solo travelers have enjoyed the hands-on experience and the opportunity to interact with local artisans. The small class sizes make it a comfortable and welcoming environment for individuals.',
    bookingInfo: 'Book online or contact via phone. Full refund with 24-hour cancellation.',
    sourcesChecked: ['khmer ceramics website', 'tripadvisor', 'google maps'],
  },
  // ==========================================================================
  // INDONESIA
  // ==========================================================================
  {
    name: 'Discover Balinese Flavors with Local Chefs in Canggu',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Tapa+Tepi+Kali+Canggu',
    googlePlaceId: null,
    type: 'cooking_class',
    category: 'Food & Drink Deep Dives',
    citySlug: 'canggu',
    city: 'Canggu',
    country: 'Indonesia',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$45 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: '3 hours',
    physicalLevel: 'easy',
    googleRating: 4.9,
    reviewCount: 82,
    whySelected: 'This cooking class offers an intimate and authentic experience for solo travelers to learn about Balinese cuisine. The small group size and hands-on approach make it easy to learn and connect with others. The class is led by experienced local chefs and includes a meal of the dishes you prepare.',
    highlights: ['Learn to cook 3 Balinese dishes', 'Small group experience', 'All ingredients included', 'Enjoy a meal of your creations.'],
    considerations: ['Minimum of 2 participants required.'],
    soloTravelerReviews: 'The class was lots of fun! The chefs were good teachers, the instructions were clear, and the location was lovely. We were very happy with the results! Everything was delicious, and we can\'t wait to get home from our trip and try out the recipes in our own kitchens!',
    bookingInfo: 'Book online through Cookly.',
    sourcesChecked: ['cookly.me', 'google search'],
  },
  {
    name: 'Gili Cooking Classes',
    googleMapsUrl: 'https://www.google.com/maps/search/Gili%20Cooking%20Classes%20Gili%20Air',
    googlePlaceId: null,
    type: 'cooking_class',
    category: 'Unique Experience',
    citySlug: 'gili-islands',
    city: 'Gili Islands',
    country: 'Indonesia',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$22-28 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: '1.5 - 2.5 hours',
    physicalLevel: 'easy',
    googleRating: 5,
    reviewCount: 567,
    whySelected: 'Gili Cooking Classes offers a highly-rated, hands-on opportunity to learn about Indonesian cuisine in a fun and social setting, making it an ideal activity for solo travelers to connect with others and immerse themselves in the local culture. The availability of vegetarian and vegan options makes it accessible to a wider range of dietary preferences.',
    highlights: ['Hands-on cooking experience', 'Learn to cook traditional Indonesian dishes', 'Vegan and vegetarian options available', 'Friendly and skilled local chefs'],
    considerations: ['Bookings are recommended, especially during peak season as classes can fill up', 'Online bookings require payment via PayPal, while on-site bookings can be paid with cash (Indonesian Rupiah only).'],
    soloTravelerReviews: 'A review on TripAdvisor stated, \'This place is a must! Whether you are travelling solo or in a group! This cooking school was beyond amazing.\' Another traveler on Reddit mentioned that cooking classes in Gili Trawangan are a great option for solo travelers.',
    bookingInfo: 'Book online via their website using PayPal, or in person with cash at one of their locations. You can also book via WhatsApp.',
    sourcesChecked: ['missfilatelista.com', 'gilicookingclasses.com', 'tripadvisor.com', 'google.com/maps'],
  },
  {
    name: 'Padi Jewelry Classes - Seminyak Silver Class',
    googleMapsUrl: 'https://www.google.com/maps/search/Padi+Jewelry+Classes+seminyak',
    googlePlaceId: null,
    type: 'tour',
    category: 'Unique Experience',
    citySlug: 'seminyak',
    city: 'Seminyak',
    country: 'Indonesia',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$25-40 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: 'Half day',
    physicalLevel: 'easy',
    googleRating: 4.9,
    reviewCount: 397,
    whySelected: 'Padi Jewelry Classes offers a hands-on opportunity to create a unique piece of silver jewelry, a perfect souvenir from Bali. The classes are beginner-friendly and held in a comfortable, air-conditioned studio, making it a great activity for solo travelers to learn a new skill and meet other people.',
    highlights: ['Beginner-friendly', 'Air-conditioned studio', 'Create your own unique silver jewelry', 'Take home a souvenir.'],
    considerations: ['Located in Kerobokan, a short ride from Seminyak', 'Booking in advance is recommended.'],
    soloTravelerReviews: 'Reviews suggest that the classes are held in small, intimate groups, making it a comfortable and enjoyable experience for individuals.',
    bookingInfo: 'Book online through their website.',
    sourcesChecked: ['padijewelryclasses.com', 'tripadvisor.com', 'google.com/maps'],
  },
  {
    name: 'Dicarik Warung Cooking Class',
    googleMapsUrl: 'https://www.google.com/maps/place/Dicarik+Warung/@-8.4994943,115.2573893,17z/data=!3m1!4b1!4m6!3m5!1s0x2dd23d38a12c2621:0x1c4a6829a77d54a1!8m2!3d-8.4994943!4d115.2599642!16s%2Fg%2F11bw4bj623?entry=ttu',
    googlePlaceId: '0x2dd23d38a12c2621:0x1c4a6829a77d54a1',
    type: 'cooking_class',
    category: 'Unique Experience',
    citySlug: 'ubud',
    city: 'Ubud',
    country: 'Indonesia',
    priceRange: '$',
    priceLevel: 1,
    priceEstimate: '$15-25 per person',
    bestTimeOfDay: 'morning',
    estimatedDuration: '2 hours',
    physicalLevel: 'easy',
    googleRating: 4.7,
    reviewCount: 217,
    whySelected: 'This cooking class offers an authentic and intimate experience, allowing solo travelers to learn about Balinese cuisine and culture from a local. The small class size and serene location in the rice fields make it a peaceful and memorable activity, away from the tourist crowds.',
    highlights: ['Authentic Balinese cooking class', 'Led by a local woman', 'Located in a serene setting surrounded by rice fields', 'Small, intimate classes', 'Affordable price'],
    considerations: ['Portions can be modest, so consider ordering multiple dishes if you have a large appetite. The warung is located along a rice field walking path, so wear comfortable shoes.'],
    soloTravelerReviews: 'Many solo travelers have praised the welcoming and friendly atmosphere of the cooking class, noting that it\'s a great way to meet other people and learn about Balinese culture in a relaxed setting.',
    bookingInfo: 'Book at least one day in advance by calling +62 819-9936-0090 or messaging them on WhatsApp. It may also be possible to sign up on-site.',
    sourcesChecked: ['reddit', 'tripadvisor', 'wanderlog', 'google maps'],
  },
  {
    name: 'Batik Course at ViaVia Jogja',
    googleMapsUrl: 'https://maps.app.goo.gl/fDP72bMCNKAowbDj6',
    googlePlaceId: null,
    type: 'tour',
    category: 'Creative & Artistic',
    citySlug: 'yogyakarta',
    city: 'Yogyakarta',
    country: 'Indonesia',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: 'IDR 325,000 per person',
    bestTimeOfDay: 'morning',
    estimatedDuration: '5-6 hours',
    physicalLevel: 'easy',
    googleRating: 4.2,
    reviewCount: 2108,
    whySelected: 'This course offers a hands-on opportunity to learn a traditional Indonesian art form from a local expert. It is suitable for beginners and provides a unique cultural immersion experience.',
    highlights: ['Learn basic batik principles', 'Create your own 50x50cm batik painting', 'Taught in English.'],
    considerations: ['Book 1 day in advance', 'Transportation to the studio is not included.'],
    soloTravelerReviews: 'TBD',
    bookingInfo: 'Book on the ViaVia Jogja website.',
    sourcesChecked: ['viaviajogja.com', 'tripadvisor.com'],
  },
  // ==========================================================================
  // JAPAN
  // ==========================================================================
  {
    name: 'Otagi Nenbutsu-ji Temple',
    googleMapsUrl: 'https://www.google.com/maps/place/Otagi+Nenbutsu-ji+Temple/@35.0236625,135.6668273,17z/data=!3m1!4b1!4m5!3m4!1s0x6000a00b8a8b2c3b:0x5b5a4b0d3e3e3e3e!8m2!3d35.0236625!4d135.669016',
    googlePlaceId: '0x6000a00b8a8b2c3b:0x5b5a4b0d3e3e3e3e',
    type: 'landmark',
    category: 'Cultural & Sightseeing',
    citySlug: 'kyoto',
    city: 'Kyoto',
    country: 'Japan',
    priceRange: '$',
    priceLevel: 1,
    priceEstimate: '$5-10 per person',
    bestTimeOfDay: 'morning',
    estimatedDuration: '1-2 hours',
    physicalLevel: 'moderate',
    googleRating: 4.6,
    reviewCount: 1500,
    whySelected: 'Otagi Nenbutsu-ji Temple is a unique and off-the-beaten-path destination in Kyoto, perfect for solo travelers seeking a peaceful and artistic experience. The temple is famous for its 1200 unique and whimsical stone statues of Rakan (disciples of Buddha), each with a different facial expression and pose, offering a serene and engaging atmosphere away from the crowds.',
    highlights: ['1200 unique stone statues', 'peaceful and uncrowded atmosphere', 'beautiful hillside setting in Arashiyama.'],
    considerations: ['Located on a hillside, requiring a bit of a walk or a taxi/bus ride to reach', 'Closed on Wednesdays and Saturdays.'],
    soloTravelerReviews: 'It’s not listed in the guidebooks or on most Kyoto websites, getting lost amongst the city’s 1600 other Buddhist temples, but it’s definitely the coolest temple we visited. I spent ages amongst the sculptures and kept noticing new things.',
    bookingInfo: 'No booking required, purchase tickets at the entrance.',
    sourcesChecked: ['differentville.com', 'otagiji.com', 'neverendingvoyage.com', 'tripadvisor.com'],
  },
  {
    name: 'Learn Japanese Zen Calligraphy in Kimono',
    googleMapsUrl: 'https://www.google.com/maps/place/SAMURAI+HONOR/@34.6905392,135.5352756,17z/data=!3m1!4b1!4m6!3m5!1s0x6000e1008a48ad79:0xdb461bd8ad89056b!8m2!3d34.6905392!4d135.5352756!16s%2Fg%2F11vrykdq48?entry=ttu',
    googlePlaceId: '0x6000e1008a48ad79:0xdb461bd8ad89056b',
    type: 'tour',
    category: 'Creative & Artistic',
    citySlug: 'osaka',
    city: 'Osaka',
    country: 'Japan',
    priceRange: '$',
    priceLevel: 1,
    priceEstimate: '$20-30 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: '1 hour',
    physicalLevel: 'easy',
    googleRating: 4.7,
    reviewCount: 78,
    whySelected: 'This experience offers a deep dive into Japanese culture through the art of calligraphy. It\'s a hands-on activity led by a master, providing a unique and memorable experience for a solo traveler seeking something beyond typical sightseeing. The opportunity to wear a kimono and have one\'s name rendered in kanji adds a personal and artistic touch.',
    highlights: ['Personalized guidance from a master calligrapher', 'Learn essential brush stroke techniques', 'Convert your name into kanji'],
    considerations: ['Bring innerwear for the kimono', 'Inform the provider of your full name and email address beforehand for photo data.'],
    soloTravelerReviews: 'During my two weeks in Japan, this was my favorite activity. Learning Japanese calligraphy was so calming and peaceful. The teacher was calm, patient, and reassuring." - Meika Goode (Local Guide)',
    bookingInfo: 'Bookable through various platforms like Rakuten Travel, Klook, and GetYourGuide.',
    sourcesChecked: ['rakuten travel experiences', 'google maps', 'tripadvisor', 'klook', 'getyourguide'],
  },
  {
    name: 'Japanese Ink Painting with Shukou',
    googleMapsUrl: 'https://www.google.com/maps/place/Tokyo,+Japan/',
    googlePlaceId: null,
    type: 'tour',
    category: 'Unique Experience',
    citySlug: 'tokyo',
    city: 'Tokyo',
    country: 'Japan',
    priceRange: '$$$',
    priceLevel: 3,
    priceEstimate: '$1200 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: '12 hours over 3 days',
    physicalLevel: 'easy',
    googleRating: 5,
    reviewCount: 1,
    whySelected: 'This workshop offers a deep dive into a traditional Japanese art form, providing a unique and immersive cultural experience for solo travelers seeking something beyond typical tourist activities. The small group setting and personalized instruction from a master artist make it an ideal environment for focused learning and creative expression.',
    highlights: ['Learn from a master ink painter', 'Explore Zen philosophy', 'Create original ink paintings'],
    considerations: ['The workshop is a 3-day commitment.'],
    soloTravelerReviews: 'A solo traveler from Canada, Gordon, praised the workshop for its in-depth instruction and the fundamental skills he learned.',
    bookingInfo: 'Book through the VAWAA website',
    sourcesChecked: ['vawaa.com'],
  },
  // ==========================================================================
  // LAOS
  // ==========================================================================
  {
    name: 'Ock Pop Tok Living Crafts Centre',
    googleMapsUrl: 'https://www.google.com/maps/search/Ock+Pop+Tok+Living+Crafts+Centre+Luang+Prabang',
    googlePlaceId: null,
    type: 'tour',
    category: 'Creative & Artistic',
    citySlug: 'luang-prabang',
    city: 'Luang Prabang',
    country: 'Laos',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$36 - $262',
    bestTimeOfDay: 'any',
    estimatedDuration: 'Half-day to 3-day classes',
    physicalLevel: 'easy',
    googleRating: 4.9,
    reviewCount: 340,
    whySelected: 'Ock Pop Tok offers a unique opportunity to learn about traditional Lao textiles and crafts directly from master artisans. The hands-on workshops are a great way for solo travelers to immerse themselves in the local culture and create a personal souvenir.',
    highlights: ['Learn traditional weaving, natural dyeing, and batik techniques', 'Beautiful setting on the Mekong River', 'Free guided tours and demonstrations available.'],
    considerations: ['Located slightly outside the main town, but a free tuk-tuk service is provided', 'Classes should be booked in advance.'],
    soloTravelerReviews: '"I took the three day intensive silk weaving course...From start to finish it was an absolutely wonderful experience." - Ryan MacDonald (Google reviewer)',
    bookingInfo: 'Book online at ockpoptok.com, at one of their shops in town, or by phone/WhatsApp.',
    sourcesChecked: ['ockpoptok.com', 'google maps', 'mindtrip.ai'],
  },
  {
    name: 'Yoga in Vang Vieng',
    googleMapsUrl: 'https://www.google.com/maps/place/Silver+Naga+Hotel/@18.9238438,102.446052,17z/data=!4m9!3m8!1s0x312592ce15a368bb:0x28d657a5c24258d3!5m2!4m1!1i2!8m2!3d18.9238438!4d102.446052!16s%2Fg%2F12hr4qzb_?entry=ttu',
    googlePlaceId: '0x312592ce15a368bb:0x28d657a5c24258d3',
    type: 'tour',
    category: 'Wellness',
    citySlug: 'vang-vieng',
    city: 'Vang Vieng',
    country: 'Laos',
    priceRange: '$',
    priceLevel: 1,
    priceEstimate: '$10 per class',
    bestTimeOfDay: 'any',
    estimatedDuration: '90 minutes',
    physicalLevel: 'easy',
    googleRating: 4.2,
    reviewCount: 483,
    whySelected: 'Yoga in Vang Vieng offers a variety of yoga styles in a serene setting, making it an ideal activity for solo travelers looking to relax and rejuvenate. The studio is located at the Silver Naga Hotel, providing a safe and accessible environment for visitors.',
    highlights: ['Variety of yoga styles (Hatha, Vinyasa, Yin, Kundalini)', 'Indoor and outdoor classes', 'Suitable for all levels', 'Stunning mountain views from the outdoor shala'],
    considerations: ['Classes are held at the Silver Naga Hotel', 'Bookings should be made 12 hours in advance', '7% tax is added to the price'],
    soloTravelerReviews: '',
    bookingInfo: 'Book online through their website or purchase a ticket at the reception of the Silver Naga Hotel.',
    sourcesChecked: ['yogainvangvieng.com', 'google.com/maps'],
  },
  {
    name: 'Sunset Zumba on the Mekong',
    googleMapsUrl: 'https://www.google.com/maps/place/Mekong+Riverside+Park/@17.961503,102.609171,17z/data=!3m1!4b1!4m6!3m5!1s0x31246863b89b2c3b:0x48a6a35e13e53bd7!8m2!3d17.961503!4d102.609171!16s%2Fg%2F11b_2w3_3g?entry=ttu',
    googlePlaceId: '0x31246863b89b2c3b:0x48a6a35e13e53bd7',
    type: 'tour',
    category: 'Wellness',
    citySlug: 'vientiane',
    city: 'Vientiane',
    country: 'Laos',
    priceRange: '$',
    priceLevel: 1,
    priceEstimate: '5,000 KIP (around $0.25 USD)',
    bestTimeOfDay: 'evening',
    estimatedDuration: '1 hour',
    physicalLevel: 'easy',
    googleRating: 4.4,
    reviewCount: 1000,
    whySelected: 'This is a fun, affordable, and social activity that allows solo travelers to interact with locals and other travelers in a lively outdoor setting. It\'s a great way to experience the local culture and stay active while enjoying the beautiful sunset over the Mekong River.',
    highlights: ['Energetic atmosphere', 'beautiful sunset views', 'opportunity to meet locals and other travelers.'],
    considerations: ['Classes are held outdoors, so they are weather-dependent', 'It can get crowded.'],
    soloTravelerReviews: 'A good mix of locals, expats, and travelers.',
    bookingInfo: 'No booking required, just show up and pay on the spot.',
    sourcesChecked: ['awaygowe.com', 'medium.com', 'reddit.com', 'tripadvisor.com'],
  },
  // ==========================================================================
  // MALAYSIA
  // ==========================================================================
  {
    name: 'Kinabalu Geopark Trekking',
    googleMapsUrl: 'https://www.google.com/maps/place/Kinabalu+Park/@6.0254506,116.5289947,17z/data=!3m1!4b1!4m6!3m5!1s0x32391a7ab1b34b95:0x85442d27810a2f56!8m2!3d6.0254506!4d116.5315696!16zL20vMDdma2My?entry=ttu',
    googlePlaceId: '0x32391a7ab1b34b95:0x85442d27810a2f56',
    type: 'tour',
    category: 'Outdoor & Adventure',
    citySlug: 'kota-kinabalu',
    city: 'Kota Kinabalu',
    country: 'Malaysia',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$100-150 per person',
    bestTimeOfDay: 'morning',
    estimatedDuration: '11 hours',
    physicalLevel: 'moderate',
    googleRating: 4.9,
    reviewCount: 67,
    whySelected: 'This join-in tour provides a great opportunity for solo travelers to experience the beauty of Kinabalu Geopark and learn about local Dusun culture without having to arrange all the logistics themselves. The small group size allows for a more intimate experience and the chance to connect with other travelers. The positive reviews highlight the knowledgeable and friendly guides, making it a safe and enjoyable experience for those traveling alone.',
    highlights: ['Stunning Mt Kinabalu views', 'Trek through Kinabalu Geopark', 'Try local Dusun food at homestay', 'See local farms and taste fresh fruits!'],
    considerations: ['Requires a full day commitment', 'Pickup from Kundasang area requires an additional fee.'],
    soloTravelerReviews: 'A great way to get into the Kinabalu National Park if you’re not down for a 2 day hike up Mt Kinabalu itself!; Our guide Jimmy was amazing, he has an incredible knowledge, knowing any single plant or animal along the path.',
    bookingInfo: 'Book through Seek Sophie website',
    sourcesChecked: ['seeksophie.com', 'tripadvisor.com'],
  },
  {
    name: 'The Iron Fairies KL',
    googleMapsUrl: 'https://www.google.com/maps/place/The+Iron+Fairies+KL/@3.149538,101.721524,17z/data=!3m1!4b1!4m6!3m5!1s0x31cc37d6cffffff:0xbb88375fcf03c081!8m2!3d3.149538!4d101.721524!16s%2Fg%2F11fkl3l3x3?entry=ttu',
    googlePlaceId: '0x31cc37d6cffffff:0xbb88375fcf03c081',
    type: 'tour',
    category: 'Social & Nightlife',
    citySlug: 'kuala-lumpur',
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$10-15 per drink',
    bestTimeOfDay: 'evening',
    estimatedDuration: 'Evening',
    physicalLevel: 'easy',
    googleRating: 4.3,
    reviewCount: 500,
    whySelected: 'The Iron Fairies KL offers a unique and immersive nightlife experience with its enchanting, fantasy-themed decor and vibrant atmosphere. It\'s a great option for solo travelers looking for a memorable night out with live music and creative cocktails, providing a distinctive alternative to more conventional bars.',
    highlights: ['Whimsical fairy-tale-inspired decor', 'Live music and DJ sets', 'Extensive and creative cocktail menu.'],
    considerations: ['Can be crowded, especially on weekends', 'Some reviews mention inconsistent drink quality', 'It\'s one of the more expensive bars in KL.'],
    soloTravelerReviews: 'A good place for solo travelers, with live music downstairs.',
    bookingInfo: 'Reservations can be made via WhatsApp (+60 16-221 3612) or through their website.',
    sourcesChecked: ['differentville', 'the iron fairies official website', 'tripadvisor', 'yelp', 'reddit'],
  },
  {
    name: 'Ilham Seramik Studio Pottery Workshop',
    googleMapsUrl: 'https://www.google.com/maps/place/Ilham+Ceramic+Studio/@6.33305,99.8459,17z/data=!3m1!4b1!4m5!3m4!1s0x304c77e8f7ffffff:0x8a5f08c3d9d2b2d!8m2!3d6.33305!4d99.8480887',
    googlePlaceId: '0x304c77e8f7ffffff:0x8a5f08c3d9d2b2d',
    type: 'tour',
    category: 'Creative & Artistic',
    citySlug: 'langkawi',
    city: 'Langkawi',
    country: 'Malaysia',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: 'RM150 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: '2-3 hours',
    physicalLevel: 'easy',
    googleRating: 4.8,
    reviewCount: 45,
    whySelected: 'This is a hands-on creative experience that allows for cultural immersion and the creation of a unique souvenir. It is suitable for solo travelers as it is a structured activity where one can learn a new skill in a group setting.',
    highlights: ['Learn traditional ceramic making techniques', 'Create your own pottery', 'Taught by local artisans.'],
    considerations: ['Price and schedule may vary, so it is best to book in advance.'],
    soloTravelerReviews: 'A great place to spend a few hours learning a new skill. The instructors are very friendly and helpful. I went on my own and felt very comfortable.',
    bookingInfo: 'Book via phone/WhatsApp at +6011-25744313 (Mr. Zul) or +60135994022. Also possible to book through their Facebook page.',
    sourcesChecked: ['naturallylangkawi.my', 'instagram', 'facebook', 'trip.com', 'google maps'],
  },
  {
    name: 'Traditional Peranakan Tiles Painting Workshop',
    googleMapsUrl: 'https://www.google.com/maps/search/THE+WEEKEND+WORKSHOP+MALACCA+HERITAGE+BRANCH',
    googlePlaceId: null,
    type: 'tour',
    category: 'Unique Experience',
    citySlug: 'malacca',
    city: 'Malacca',
    country: 'Malaysia',
    priceRange: '$',
    priceLevel: 1,
    priceEstimate: '$10-15 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: '1 hour',
    physicalLevel: 'easy',
    googleRating: 4.6,
    reviewCount: 128,
    whySelected: 'This workshop offers a unique and creative way to engage with local Peranakan culture. It\'s a short, affordable, and beginner-friendly activity perfect for a solo traveler looking for a hands-on cultural experience.',
    highlights: ['Beginner-friendly', 'Create your own unique souvenir', 'Learn about Peranakan culture and art.'],
    considerations: ['A 10% processing fee is applicable for all workshops', 'Rescheduling is allowed within 24 hours of booking, after which a RM10 fee applies.'],
    soloTravelerReviews: 'Reviews suggest that while the workshop is enjoyable, some solo travelers wished for more guidance from the instructors.',
    bookingInfo: 'Book online through The Weekend Workshop website.',
    sourcesChecked: ['the weekend workshop website', 'google maps'],
  },
  {
    name: 'Art Lane',
    googleMapsUrl: 'https://www.google.com/maps/place/Artlane/@5.4151242,100.3392036,17z/data=!3m1!4b1!4m6!3m5!1s0x304ac353a3ea269b:0x17720c200d7ed444!8m2!3d5.4151242!4d100.3392036!16s%2Fg%2F11s93nd2d5?entry=ttu&g_ep=EgoyMDI2MDEyOC4wIKXMDSoASAFQAw%3D%3D',
    googlePlaceId: '0x304ac353a3ea269b:0x17720c200d7ed444',
    type: 'tour',
    category: 'Unique Experience',
    citySlug: 'penang',
    city: 'Penang',
    country: 'Malaysia',
    priceRange: '$',
    priceLevel: 1,
    priceEstimate: 'RM 15 - RM 25',
    bestTimeOfDay: 'afternoon',
    estimatedDuration: '0.5 hours',
    physicalLevel: 'easy',
    googleRating: 4.7,
    reviewCount: 67,
    whySelected: 'Art Lane offers a unique and immersive artistic experience for solo travelers. It\'s a great place to discover local art, get creative, and meet like-minded people in a relaxed and inspiring environment.',
    highlights: ['Diverse art collections', 'Historic setting', 'Interactive exhibits', 'Local and international artists', 'Art workshops'],
    considerations: ['Limited parking space', 'Entrance fee may vary depending on exhibitions.'],
    soloTravelerReviews: 'Art Lane is one of those places where you step in for a quick look and end up staying much longer than expected.',
    bookingInfo: 'No booking required, but it\'s advisable to check their Facebook page for special events or workshops.',
    sourcesChecked: ['differentville.com', 'tripadvisor.com', 'loka.my', 'google maps'],
  },
  // ==========================================================================
  // MOROCCO
  // ==========================================================================
  {
    name: 'Private Berber Pottery Workshop with Lunch',
    googleMapsUrl: 'https://www.google.com/maps/place/Chefchaouen,+Morocco/@35.168851,-5.263502,14z/data=!3m1!4b1!4m6!3m5!1s0xd0b26895a460a1d:0x27a69133e5036553!8m2!3d35.1714975!4d-5.2697184!16zL20vMDJtN3Jf?entry=ttu',
    googlePlaceId: '0xd0b26895a460a1d:0x27a69133e5036553',
    type: 'tour',
    category: 'Unique Experience',
    citySlug: 'chefchaouen',
    city: 'Chefchaouen',
    country: 'Morocco',
    priceRange: '$$$',
    priceLevel: 3,
    priceEstimate: '$190 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: '5 hours',
    physicalLevel: 'easy',
    googleRating: 5,
    reviewCount: 4,
    whySelected: 'This is a highly-rated, immersive cultural experience that offers a genuine connection with local Berber artisans. It provides a unique opportunity for solo travelers to go beyond the typical tourist trail and engage in a hands-on creative activity. The inclusion of a home-cooked meal and private transportation adds to the convenience and value of the experience.',
    highlights: ['Learn traditional Berber pottery techniques from a local family', 'Enjoy a home-cooked lunch', 'Small group setting ideal for solo travelers', 'Includes private transportation and an English-speaking guide.'],
    considerations: ['The workshop takes place in a village 38km outside of Chefchaouen', 'Transportation is included in the price', 'You won\'t be able to take your creation with you on the same day as the drying and firing process takes several days.'],
    soloTravelerReviews: 'One solo traveler described it as \'the most special experience ever\' and highly recommended it. Another review mentioned the guide, Fatima, was \'so great\' and provided an \'authentic and unique experience.\'',
    bookingInfo: 'Bookable through various online tour operators like Peek.com or by contacting the guide Fatima Habte directly.',
    sourcesChecked: ['peek.com', 'tripadvisor.com', 'viator.com'],
  },
  {
    name: 'Solo Female Pottery Workshop',
    googleMapsUrl: 'https://www.google.com/maps/place/Fes+Pottery+%26+Zellige/@34.062691,-4.975089,15z/data=!4m6!3m5!1s0xd9f8b6e3d6e3d3d:0x3f3b3b3b3b3b3b3b!8m2!3d34.062691!4d-4.975089!16s%2Fg%2F11f7b_v3g?hl=en',
    googlePlaceId: '0xd9f8b6e3d6e3d3d:0x3f3b3b3b3b3b3b3b',
    type: 'tour',
    category: 'Unique Experience',
    citySlug: 'fes',
    city: 'Fes',
    country: 'Morocco',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$50-100 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: '1 hour',
    physicalLevel: 'easy',
    googleRating: 4.8,
    reviewCount: 12,
    whySelected: 'This workshop is specifically designed for solo female travelers, providing a safe and supportive environment to learn a traditional Moroccan craft. It offers a unique opportunity for a hands-on, authentic cultural experience away from the hustle of the medina.',
    highlights: ['One-on-one guidance', 'Learn pottery and Zellige art', 'Tea and conversation with artisans.'],
    considerations: ['Price depends on group size, so it\'s best to inquire for solo pricing', 'Transportation to the studio is included.'],
    soloTravelerReviews: 'Many of our past guests have described it as the highlight of their stay in Fes.',
    bookingInfo: 'Book via WhatsApp or the booking form on their website.',
    sourcesChecked: ['https://fespotteryart.com/project/solo-female-pottery-workshop-in-fes/', 'https://api.whatsapp.com/send/?phone=212770258111&text&type=phone_number&app_absent=0'],
  },
  {
    name: 'Moroccan Storytelling Evening at Café Clock',
    googleMapsUrl: 'https://www.google.com/maps/place/Cafe+Clock/@31.6128952,-7.987251,15z/data=!4m6!3m5!1s0xdafee4eba6e7349:0xe5f380c3f6d0caa6!8m2!3d31.6128952!4d-7.987251!16s%2Fg%2F1pp2vn1jk',
    googlePlaceId: '0xdafee4eba6e7349:0xe5f380c3f6d0caa6',
    type: 'tour',
    category: 'Cultural & Sightseeing',
    citySlug: 'marrakech',
    city: 'Marrakech',
    country: 'Morocco',
    priceRange: '$',
    priceLevel: 1,
    priceEstimate: 'Free (drinks and food available for purchase)',
    bestTimeOfDay: 'evening',
    estimatedDuration: '1-2 hours',
    physicalLevel: 'easy',
    googleRating: 4.4,
    reviewCount: 2490,
    whySelected: 'This event offers a unique opportunity to experience the ancient Moroccan tradition of storytelling in an accessible and welcoming setting. The performance is in both English and Arabic, making it enjoyable for a diverse audience, and the free admission makes it an excellent value for solo travelers on any budget. It provides a comfortable and safe environment to enjoy an evening of cultural immersion.',
    highlights: ['Authentic cultural experience', 'Free of charge', 'Stories told in both English and Arabic', 'Held in a welcoming and social atmosphere.'],
    considerations: ['The event is free, but it is recommended to purchase a drink or food to support the venue', 'Arrive at least 30 minutes early to get a good seat, as it can get crowded.'],
    soloTravelerReviews: 'While specific reviews from solo travelers about the storytelling event are not readily available, general reviews of Café Clock mention it as a \'great place to meet nice people\' with a \'relaxed atmosphere,\' making it a welcoming environment for individuals.',
    bookingInfo: 'No booking required. Arrive early to secure a good seat.',
    sourcesChecked: ['the world in my pocket', 'claire\'s footsteps', 'cafe clock website', 'google maps', 'tripadvisor', 'reddit'],
  },
  // ==========================================================================
  // MYANMAR
  // ==========================================================================
  {
    name: 'Yandabo Pottery Village',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=21.6333,95.3667',
    googlePlaceId: null,
    type: 'tour',
    category: 'Cultural & Sightseeing',
    citySlug: 'bagan',
    city: 'Bagan',
    country: 'Myanmar',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$30-50 per person',
    bestTimeOfDay: 'morning',
    estimatedDuration: 'Half day',
    physicalLevel: 'easy',
    googleRating: 4.5,
    reviewCount: 150,
    whySelected: 'Yandabo offers a unique opportunity to witness a traditional craft that has been passed down for generations. It provides an authentic cultural immersion and a chance to interact with local artisans, making it a memorable experience for solo travelers seeking to go beyond the typical tourist sites.',
    highlights: ['Observe traditional pottery making techniques', 'Interact with local artisans', 'Opportunity to make your own pottery'],
    considerations: ['The village is a working community, so be respectful of the residents and their work. It is best to visit with a guide who can facilitate interactions with the local people.'],
    soloTravelerReviews: 'Many solo travelers enjoy the authentic cultural experience and the opportunity to interact with local people. Reviews often mention the friendly and welcoming nature of the villagers.',
    bookingInfo: 'Can be visited as part of a river cruise between Bagan and Mandalay, or as a day trip from Bagan. Several tour operators offer packages.',
    sourcesChecked: ['bestpricetravel.com', 'asiantour-myanmar.com', 'various travel blogs'],
  },
  {
    name: 'Inle Heritage Cooking Class',
    googleMapsUrl: 'https://www.google.com/maps/place/Inle+Heritage+Stilt+Houses/@20.468651,96.915016,17z/data=!3m1!4b1!4m8!3m7!1s0x30cebbf5f5555555:0x5f5f5f5f5f5f5f5f!5m2!4m1!1i2!8m2!3d20.468651!4d96.9172047',
    googlePlaceId: '0x30cebbf5f5555555:0x5f5f5f5f5f5f5f5f',
    type: 'cooking_class',
    category: 'Unique Experience',
    citySlug: 'inle-lake',
    city: 'Inle Lake',
    country: 'Myanmar',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$45-60 per person',
    bestTimeOfDay: 'morning',
    estimatedDuration: 'Half day',
    physicalLevel: 'easy',
    googleRating: 4.8,
    reviewCount: 150,
    whySelected: 'This cooking class offers a unique and authentic cultural experience that goes beyond typical tourist activities. It provides an opportunity for solo travelers to learn about local cuisine and contribute to a socially responsible project. The hands-on nature of the class and the small group setting make it an ideal activity for individuals looking to connect with the local culture and other travelers.',
    highlights: ['Learn to cook traditional Shan cuisine', 'Source ingredients from a local market and garden', 'Support a non-profit organization', 'Interact with locals in a meaningful way'],
    considerations: ['The cooking class is part of a larger non-profit organization dedicated to preserving the culture of Inle Lake.', 'The location is on the lake and requires boat transportation to access.'],
    soloTravelerReviews: 'Many solo travelers have praised the class as a great way to meet other people and learn about the local culture in a hands-on way. Reviewers have highlighted the friendly atmosphere and the delicious food.',
    bookingInfo: 'Booking can be made through their website or by contacting them directly. It is also possible to book through some tour operators.',
    sourcesChecked: ['insideasiatours.com', 'tripadvisor.com', 'wanderwithjo.com'],
  },
  {
    name: 'Nagar Glass Factory Exploration',
    googleMapsUrl: 'https://www.google.com/maps/place/Nagar+Glass+Factory/@16.837814,96.12743,17z/data=!3m1!4b1!4m5!3m4!1s0x30c194077d6918c5:0x59c9c9a37a3440d9!8m2!3d16.837814!4d96.1296187',
    googlePlaceId: '0x30c194077d6918c5:0x59c9c9a37a3440d9',
    type: 'landmark',
    category: 'Unique Experience',
    citySlug: 'yangon',
    city: 'Yangon',
    country: 'Myanmar',
    priceRange: '$',
    priceLevel: 1,
    priceEstimate: '$5-15 per person',
    bestTimeOfDay: 'morning',
    estimatedDuration: '2-3 hours',
    physicalLevel: 'easy',
    googleRating: 4.5,
    reviewCount: 150,
    whySelected: 'Nagar Glass Factory is a truly unique and off-the-beaten-path experience in Yangon, perfect for the solo traveler looking for something different. It offers a glimpse into Myanmar\'s industrial past and the opportunity to find a one-of-a-kind souvenir.',
    highlights: ['Explore the ruins of a former glass factory', 'Discover unique, hand-blown glassware', 'A true hidden gem and off-the-beaten-path experience.'],
    considerations: ['Wear sturdy, closed-toe shoes as there is a lot of broken glass', 'Bring insect repellent as there are mosquitoes.'],
    soloTravelerReviews: 'A fascinating and unique experience for solo travelers interested in urban exploration and history. It\'s a quiet and peaceful place to wander around and you can find some beautiful and affordable souvenirs.',
    bookingInfo: 'No booking required, just show up.',
    sourcesChecked: ['atlas obscura', 'greenheart travel', 'tripadvisor'],
  },
  // ==========================================================================
  // PHILIPPINES
  // ==========================================================================
  {
    name: 'Jing Yoga & Wellness Panglao',
    googleMapsUrl: 'https://www.google.com/maps/place/Jing+Yoga+%26+Wellness+Panglao/@9.553957,123.769858,17z/data=!3m1!4b1!4m5!3m4!1s0x33aa4d6a5e3b0f7b:0x4c8a2b6e3e0e3e6e!8m2!3d9.553957!4d123.772047?hl=en',
    googlePlaceId: '0x33aa4d6a5e3b0f7b:0x4c8a2b6e3e0e3e6e',
    type: 'tour',
    category: 'Wellness',
    citySlug: 'bohol',
    city: 'Bohol',
    country: 'Philippines',
    priceRange: '$',
    priceLevel: 1,
    priceEstimate: '$10 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: '1 hour',
    physicalLevel: 'easy',
    googleRating: 4.9,
    reviewCount: 100,
    whySelected: 'Offers a variety of yoga classes suitable for different levels, making it accessible for solo travelers looking for a wellness activity. The beach yoga class is a unique experience.',
    highlights: ['Daily classes', 'variety of styles (Vinyasa, Hatha, Yin)', 'beach yoga option', 'private classes available.'],
    considerations: ['Located in Panglao, near Alona Beach.'],
    soloTravelerReviews: 'No specific solo traveler reviews found, but general reviews are very positive.',
    bookingInfo: 'Book online through their website',
    sourcesChecked: ['panglaoyoga.com', 'tripadvisor.com'],
  },
  {
    name: 'Floating Sound Bath',
    googleMapsUrl: 'https://www.google.com/maps/place/Dawata+Wellness/@10.323818,123.903597,17z/data=!3m1!4b1!4m6!3m5!1s0x33a9991e1be145e7:0x82a4738823564c3!8m2!3d10.323818!4d123.903597!16s%2Fg%2F11f725g7_k?entry=ttu',
    googlePlaceId: '0x33a9991e1be145e7:0x82a4738823564c3',
    type: 'tour',
    category: 'Wellness',
    citySlug: 'cebu',
    city: 'Cebu',
    country: 'Philippines',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$30-50 per person',
    bestTimeOfDay: 'evening',
    estimatedDuration: '1-2 hours',
    physicalLevel: 'easy',
    googleRating: 4.8,
    reviewCount: 140,
    whySelected: 'This is a unique wellness experience that is not commonly found. It offers a deep relaxation experience that would be beneficial for a solo traveler looking to unwind and de-stress. The small group setting also provides a sense of community and connection.',
    highlights: ['Floating sound bath', 'unique wellness experience', 'deep relaxation.'],
    considerations: ['Booking in advance is likely required', 'limited information on schedules and pricing available online', 'may need to contact them directly for details.'],
    soloTravelerReviews: 'Unable to find specific reviews from solo travelers for this activity.',
    bookingInfo: 'Contact Dawata Wellness directly through their website, phone, or social media.',
    sourcesChecked: ['tiktok', 'instagram', 'dawata wellness website', 'google search.'],
  },
  {
    name: 'Coconut Leaf Weaving Workshop',
    googleMapsUrl: 'https://www.google.com/maps/place/Kalye+Artisano/@11.203539,119.41821,17z/data=!3m1!4b1!4m6!3m5!1s0x33b5838755555555:0x416b2a23d52a285a!8m2!3d11.203539!4d119.4207849!16s%2Fg%2F11p_d_2h7l?entry=ttu',
    googlePlaceId: '0x33b5838755555555:0x416b2a23d52a285a',
    type: 'tour',
    category: 'Creative & Artistic',
    citySlug: 'el-nido',
    city: 'El Nido',
    country: 'Philippines',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$20-30 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: 'Half day',
    physicalLevel: 'easy',
    googleRating: 4.7,
    reviewCount: 130,
    whySelected: 'This is a unique, hands-on cultural experience that allows solo travelers to learn a traditional craft from a local expert. It offers a creative outlet and a chance to connect with Filipino culture beyond typical tourist activities.',
    highlights: ['Learn a traditional Filipino craft', 'Create your own woven souvenirs', 'Taught by a local expert.'],
    considerations: ['Requires booking in advance', 'May be a group activity.'],
    soloTravelerReviews: 'No specific reviews from solo travelers were found, but the activity is suitable for individuals.',
    bookingInfo: 'Inquire via the Kalye Artisano website or contact them directly by phone.',
    sourcesChecked: ['kalye artisano website', 'tripadvisor', 'google search'],
  },
  {
    name: 'Wheel Throwing 101 at Bumi & Ashe',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Bumi+and+Ashe+Pottery+Class+%26+Firing+Services%2C+59a+Cubao+Expo+Drwy%2C+Quezon+City%2C+NCR%2C+PH',
    googlePlaceId: null,
    type: 'tour',
    category: 'Creative & Artistic',
    citySlug: 'manila',
    city: 'Manila',
    country: 'Philippines',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$63 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: '3 hours',
    physicalLevel: 'easy',
    googleRating: 3.9,
    reviewCount: 22,
    whySelected: 'This workshop is a great opportunity for solo travelers to learn a new skill in a creative and supportive environment. The small class sizes and beginner-friendly approach make it easy to participate and connect with others.',
    highlights: ['Hands-on experience', 'Create your own pottery', 'Beginner-friendly'],
    considerations: ['Advanced booking is required', 'Pieces need to be fired and picked up later.'],
    soloTravelerReviews: 'One reviewer mentioned having a great time and getting a bit lost finding the place, implying they went alone.',
    bookingInfo: 'Book online through their website.',
    sourcesChecked: ['bumi & ashe website', 'google maps'],
  },
  {
    name: 'Pottery Workshop in Siargao',
    googleMapsUrl: 'https://www.google.com/maps/place/Loka+Siargao/@9.7907,126.1634,17z/data=!3m1!4b1!4m6!3m5!1s0x3303f3c8a8679331:0x758433474242384!8m2!3d9.7907!4d126.1634!16s%2Fg%2F11s7l4w_xw?entry=ttu',
    googlePlaceId: '0x3303f3c8a8679331:0x758433474242384',
    type: 'tour',
    category: 'Unique Experience',
    citySlug: 'siargao',
    city: 'Siargao',
    country: 'Philippines',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$30-50 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: '2 hours',
    physicalLevel: 'easy',
    googleRating: 4.6,
    reviewCount: 751,
    whySelected: 'This workshop offers a unique and creative experience for solo travelers to unwind and learn a new skill. The hands-on nature of pottery is a great way to practice mindfulness and create a personal souvenir from the trip. The workshop is held at two locations, one of which is a popular beachfront restaurant and bar, providing a social atmosphere for solo travelers to connect with others.',
    highlights: ['Learn hand-building pottery techniques', 'Create your own decorative souvenirs', 'Relaxing and mindful activity', 'Two locations to choose from.'],
    considerations: ['The creations are not food-safe', 'No refunds are provided, but the booking is transferable', 'The workshop is for ages 5 and up.'],
    soloTravelerReviews: 'Loved the experience. It was only me and my sister who booked that time so it was not crowded. Definitely worth coming back to again.',
    bookingInfo: 'Can be booked until the last minute through My Philippines Guide or by contacting them directly at +63 9562859499 or info@MyPhilippinesGuide.com.',
    sourcesChecked: ['klook', 'my philippines guide', 'facebook'],
  },
  // ==========================================================================
  // PORTUGAL
  // ==========================================================================
  {
    name: 'The Arts of Azulejos: Portuguese Tile Painting Workshop',
    googleMapsUrl: 'https://www.google.com/maps/place/R.+de+Madre+Deus+4,1900-312+Lisboa,+Portugal',
    googlePlaceId: null,
    type: 'tour',
    category: 'Unique Experience',
    citySlug: 'lisbon',
    city: 'Lisbon',
    country: 'Portugal',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$60-80 per person',
    bestTimeOfDay: 'afternoon',
    estimatedDuration: '3.5 hours',
    physicalLevel: 'easy',
    googleRating: 4.8,
    reviewCount: 150,
    whySelected: 'This workshop offers a unique opportunity to learn a traditional Portuguese craft from an experienced artisan. The small group setting and focus on a hands-on activity make it an ideal environment for solo travelers to connect with others organically.',
    highlights: ['Learn authentic azulejo painting techniques', 'Create two of your own tiles to take home', 'Small group size ensures personalized attention.'],
    considerations: ['The workshop is 3.5 hours long', 'Firing of the tiles takes 1-2 days, so plan accordingly.'],
    soloTravelerReviews: 'The small group setting and focus on a hands-on activity make it an ideal environment for solo travelers to connect with others organically.',
    bookingInfo: 'Bookable through the HandsOn.pt website.',
    sourcesChecked: ['handson.pt'],
  },
  {
    name: 'Banco de Materiais (Bank of Materials)',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Banco+de+Materiais+Porto',
    googlePlaceId: null,
    type: 'landmark',
    category: 'Cultural & Sightseeing',
    citySlug: 'porto',
    city: 'Porto',
    country: 'Portugal',
    priceRange: '$',
    priceLevel: 1,
    priceEstimate: 'Free',
    bestTimeOfDay: 'any',
    estimatedDuration: '1-2 hours',
    physicalLevel: 'easy',
    googleRating: 4.5,
    reviewCount: 205,
    whySelected: 'The Banco de Materiais is a unique and non-touristy museum that offers a fascinating insight into the history and preservation of Porto\'s iconic azulejo tiles. It provides a culturally immersive experience for solo travelers interested in art, architecture, and local heritage, away from the typical tourist crowds.',
    highlights: ['Extensive collection of historic azulejo tiles', 'Free admission', 'Learn about the restoration and preservation of Porto\'s architectural heritage'],
    considerations: ['The museum is small and has limited English information. It has been reported as temporarily closed, so it is best to verify its status before visiting.'],
    soloTravelerReviews: 'One visitor described it as a \'little museum about Azulejos\' and found it \'really good\', while another praised the \'delightful collection of tiles and other historic decorative building items collected from demolished building throughout Porto.\'',
    bookingInfo: 'No booking required, free entry.',
    sourcesChecked: ['atlas obscura', 'google maps', 'visit porto', 'timeout'],
  },
  // ==========================================================================
  // SINGAPORE
  // ==========================================================================
  {
    name: 'Beginner Gardener\'s Guide to Starting a Productive Edible Garden',
    googleMapsUrl: 'https://www.google.com/maps/place/Edible+Garden+City/@1.29183,103.808,17z/data=!3m1!4b1!4m6!3m5!1s0x31da1a0133734365:0x597d6f9d4e35f2a!8m2!3d1.29183!4d103.808!16s%2Fg%2F11bbr3p4_x?entry=ttu',
    googlePlaceId: '0x31da1a0133734365:0x597d6f9d4e35f2a',
    type: 'tour',
    category: 'Unique Experience',
    citySlug: 'singapore',
    city: 'Singapore',
    country: 'Singapore',
    priceRange: '$$$',
    priceLevel: 3,
    priceEstimate: '$195.11 per person',
    bestTimeOfDay: 'morning',
    estimatedDuration: '6 hours',
    physicalLevel: 'easy',
    googleRating: 4.8,
    reviewCount: 62,
    whySelected: 'This workshop offers a unique, hands-on opportunity to learn about urban farming and sustainable living in Singapore. It\'s a great way for a solo traveler to engage in a meaningful activity, learn a new skill, and connect with nature and like-minded individuals in a supportive environment.',
    highlights: ['Hands-on experience in starting a garden', 'Learn about plant selection, soil, and pest control', 'Taught by experienced urban farmers.'],
    considerations: ['The workshop is split into two 3-hour sessions', 'The workshop is held at Edible Garden City\'s Queenstown farm.'],
    soloTravelerReviews: 'No specific reviews from solo travelers were found, but the workshop format is conducive to meeting new people with similar interests.',
    bookingInfo: 'Book online through the Edible Garden City website.',
    sourcesChecked: ['edible garden city website', 'google maps'],
  },
  // ==========================================================================
  // THAILAND
  // ==========================================================================
  {
    name: 'Perfume Workshop in Bangkok by Oo La Lab',
    googleMapsUrl: 'https://www.google.com/maps/place/theCOMMONS+Saladaeng/@13.725483,100.536158,17z/data=!3m1!4b1!4m6!3m5!1s0x30e29f31c498c4d7:0x20423f061e3947b!8m2!3d13.725483!4d100.536158!16s%2Fg%2F11hdx95b1x?entry=ttu',
    googlePlaceId: '0x30e29f31c498c4d7:0x20423f061e3947b',
    type: 'tour',
    category: 'Unique Experience',
    citySlug: 'bangkok',
    city: 'Bangkok',
    country: 'Thailand',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$81 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: '1.5 hours',
    physicalLevel: 'easy',
    googleRating: 4.9,
    reviewCount: 34,
    whySelected: 'This workshop offers a unique and creative experience for solo travelers to craft their own personalized fragrance. It\'s a hands-on activity that allows for self-expression and results in a tangible, personal souvenir. The small-group setting makes it easy to meet other people in a relaxed and fun environment.',
    highlights: ['Create a custom perfume', 'Explore a vast library of scents', 'Beginner-friendly', 'Take home a unique fragrance.'],
    considerations: ['The workshop is conducted in English', 'No prior experience is required.'],
    soloTravelerReviews: 'This was the highlight of my trip. Amazing mixologist. Extremely knowledgeable and accommodating. I had a blast and I love my fragrance. This is a must do activity for Bangkok; Such a unique amazing experience in Bangkok in so glad I did it. Thank you to Sara for making it an amazing experience',
    bookingInfo: 'Book online through GetYourGuide or the Oo La Lab website.',
    sourcesChecked: ['getyourguide', 'thecommons website'],
  },
  {
    name: 'Baan Kang Wat',
    googleMapsUrl: 'https://www.google.com/maps/place/Baan+Kang+Wat/@18.783333,98.9521889,17z/data=!4m6!3m5!1s0x30da3a60d8c3a5fb:0x8f2f0b3f4d3e6a7c!8m2!3d18.783333!4d98.9521889!16s%2Fg%2F11btr_7c3k?entry=ttu',
    googlePlaceId: '0x30da3a60d8c3a5fb:0x8f2f0b3f4d3e6a7c',
    type: 'tour',
    category: 'Unique Experience',
    citySlug: 'chiang-mai',
    city: 'Chiang Mai',
    country: 'Thailand',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$10-50 per person',
    bestTimeOfDay: 'afternoon',
    estimatedDuration: 'Half day',
    physicalLevel: 'easy',
    googleRating: 4.5,
    reviewCount: 4400,
    whySelected: 'Baan Kang Wat is a unique artist village that offers a peaceful and creative escape from the bustling city. It\'s an ideal spot for solo travelers to immerse themselves in the local art scene, with opportunities to participate in various workshops and connect with artisans.',
    highlights: ['Artist-run shops and galleries', 'Variety of workshops (pottery, painting, etc.)', 'Weekend market with live music', 'Beautiful green spaces and cafes.'],
    considerations: ['Closed on Mondays', 'Can get crowded on weekends', 'Workshop availability may vary.'],
    soloTravelerReviews: 'The peaceful atmosphere is ideal for those who enjoy spending time in nature, with plenty of quiet corners and garden spaces to sit, reflect, or read. Perfect for solo travelers, couples, friends, or anyone who wants a break from sightseeing without wasting the day.',
    bookingInfo: 'Check the Baan Kang Wat Facebook page for workshop schedules and booking information.',
    sourcesChecked: ['thegoodobserverblog.co.uk', 'foratravel.com', 'benothinglike.com', 'solotravelbestie.substack.com', 'joujoutravels.com', 'contiki.com', 'tripadvisor.com', 'getyourguide.com', 'kalmvillage.com', 'reddit.com', 'bookretreats.com', 'viator.com', 'facebook.com', 'asiakingtravel.com', 'roytellstales.com', 'theblondtravels.com', 'wanderlog.com', 'catmotors.net', 'my.trip.com', 'google.com/maps'],
  },
  {
    name: 'Coco Clay Pottery Classes',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=44/25+Moo+1,+Ko+Pha-Ngan+84280+Thailand',
    googlePlaceId: null,
    type: 'tour',
    category: 'Creative & Artistic',
    citySlug: 'koh-phangan',
    city: 'Koh Phangan',
    country: 'Thailand',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '700 - 1400 THB',
    bestTimeOfDay: 'afternoon',
    estimatedDuration: '1-4 hours',
    physicalLevel: 'easy',
    googleRating: 5,
    reviewCount: 2,
    whySelected: 'A great way to unwind and get creative. The relaxed atmosphere makes it comfortable for solo travelers to join and try something new.',
    highlights: ['Relaxed and creative vibe', 'Fun way to try something new', 'Hands-on experience.'],
    considerations: ['The finished pieces take two weeks to be glazed and fired.'],
    soloTravelerReviews: 'Max is super chill and makes you feel totally at ease, even if you\'ve never touched clay before. Highly recommend giving it a go — especially if you\'re looking for a break from the usual island routine.',
    bookingInfo: 'Book through their website or Instagram.',
    sourcesChecked: ['casacocodesign.com', 'tripadvisor.com', 'instagram.com'],
  },
  {
    name: 'Batik Painting Workshop',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Sriraya+Batik+Koh+Lanta',
    googlePlaceId: null,
    type: 'tour',
    category: 'Unique Experience',
    citySlug: 'krabi',
    city: 'Krabi',
    country: 'Thailand',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$25-40 per person',
    bestTimeOfDay: 'afternoon',
    estimatedDuration: '3 hours',
    physicalLevel: 'easy',
    googleRating: 4.95,
    reviewCount: 834,
    whySelected: 'This workshop offers a unique and creative experience that allows solo travelers to immerse themselves in Thai culture and create a personal souvenir. The small class sizes and positive reviews from other solo travelers make it a safe and comfortable environment for individuals.',
    highlights: ['Learn traditional Batik techniques', 'Create your own unique souvenir', 'Small class sizes', 'Positive reviews from solo travelers'],
    considerations: ['The workshop is located on Koh Lanta, which requires a ferry trip from Krabi mainland', 'The price is in Brazilian Real on Airbnb, so the final price in Thai Baht may vary.'],
    soloTravelerReviews: 'I enjoyed doing batik so much. I’m a solo traveler I recommend it for everyone. The host was extremely knowledgeable and helpful.',
    bookingInfo: 'Book via Airbnb, Facebook, or WhatsApp',
    sourcesChecked: ['airbnb', 'facebook'],
  },
  {
    name: 'Pai Love Fermentary Workshop',
    googleMapsUrl: 'https://www.google.com/maps/place/Good+Life+Dacha/@19.361957,98.43818,17z/data=!3m1!4b1!4m5!3m4!1s0x30da830b8b8b8b8b:0x8b8b8b8b8b8b8b8b!8m2!3d19.361957!4d98.440369',
    googlePlaceId: '0x30da830b8b8b8b8b:0x8b8b8b8b8b8b8b8b',
    type: 'tour',
    category: 'Unique Experience',
    citySlug: 'pai',
    city: 'Pai',
    country: 'Thailand',
    priceRange: '$',
    priceLevel: 1,
    priceEstimate: '~600 THB per person',
    bestTimeOfDay: 'afternoon',
    estimatedDuration: '4 hours',
    physicalLevel: 'easy',
    googleRating: 4.4,
    reviewCount: 99,
    whySelected: 'This is a unique, hands-on experience that goes beyond typical tourist activities. It\'s a great opportunity for solo travelers to learn a new skill, meet like-minded people, and delve into the local culture of health and wellness.',
    highlights: ['Learn to make kombucha and kefir', 'Includes a fermented lunch', 'Hands-on workshop'],
    considerations: ['The workshop is for three or more people, so a solo traveler might need to join a group. No advance sign-in is needed, just arrive 10 minutes before it starts.'],
    soloTravelerReviews: 'No specific reviews for the workshop, but Good Life Dacha, the location, is described as having a welcoming atmosphere.',
    bookingInfo: 'No advance booking required, just show up 10 minutes before the workshop starts.',
    sourcesChecked: ['trvbox.com', 'missfilatelista.com', 'facebook'],
  },
  // ==========================================================================
  // VIETNAM
  // ==========================================================================
  {
    name: 'Sivananda Yoga Weekend Retreat',
    googleMapsUrl: 'https://www.google.com/maps/place/Sivananda+Yoga+Resort+and+Training+Center/@11.895434,108.43356,17z/data=!3m1!4b1!4m8!3m7!1s0x317112d477d2f2b9:0x8947c615e356b8c!5m2!4m1!1i2!8m2!3d11.895434!4d108.4357487',
    googlePlaceId: '0x317112d477d2f2b9:0x8947c615e356b8c',
    type: 'tour',
    category: 'Wellness',
    citySlug: 'da-lat',
    city: 'Da Lat',
    country: 'Vietnam',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$50-75 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: '3 days',
    physicalLevel: 'easy',
    googleRating: 4.5,
    reviewCount: 18,
    whySelected: 'This retreat offers a structured and supportive environment for solo travelers to deepen their yoga and meditation practice. The communal setting and shared activities provide opportunities for connection with other participants, while the peaceful location allows for personal reflection and growth.',
    highlights: ['Immersive yoga and meditation experience', 'Peaceful and natural setting', 'Opportunities for self-reflection and spiritual growth'],
    considerations: ['The retreat is located in a quiet area outside the city center', 'transportation may be needed to explore other parts of Da Lat.'],
    soloTravelerReviews: 'Reviewers on BookYogaRetreats mentioned that the retreat is a great place to meet like-minded people and that the staff is very welcoming to solo travelers. One solo traveler wrote: \'I felt very comfortable and supported during my stay. It was a wonderful experience to disconnect from the world and reconnect with myself.\'',
    bookingInfo: 'Book through the Sivananda Yoga Vietnam website or booking platforms like BookYogaRetreats.',
    sourcesChecked: ['sivananda yoga vietnam website', 'bookyogaretreats.com', 'tripadvisor'],
  },
  {
    name: 'Trial Art Class at Art Tutor Hanoi',
    googleMapsUrl: 'https://www.google.com/maps/place/Art+tutor+Hanoi/@21.077096,105.8211916,17z/data=!3m1!4b1!4m6!3m5!1s0x3135ab2a596428b9:0x39dc041a589c0ac8!8m2!3d21.077096!4d105.8237665!16s%2Fg%2F11v6tjdgsh',
    googlePlaceId: '0x3135ab2a596428b9:0x39dc041a589c0ac8',
    type: 'tour',
    category: 'Unique Experience',
    citySlug: 'hanoi',
    city: 'Hanoi',
    country: 'Vietnam',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: '$40 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: '2.5 hours',
    physicalLevel: 'easy',
    googleRating: 5,
    reviewCount: 125,
    whySelected: 'This is an academic art class that offers a more serious and in-depth experience than a typical tourist workshop. It\'s a great option for solo travelers looking for a quiet, creative, and educational activity.',
    highlights: ['Taught by professional local artists', 'Focuses on fundamentals and observation', 'Quiet and cozy studio setting'],
    considerations: ['This is an academic class, so a finished artwork is not guaranteed in a single session', 'Free cancellation up to 24 hours in advance.'],
    soloTravelerReviews: 'Many positive reviews from solo travelers and small groups, highlighting the patient instructors and calm atmosphere.',
    bookingInfo: 'Book online through their website, GetYourGuide, Airbnb, or Tripadvisor.',
    sourcesChecked: ['google maps', 'tripadvisor', 'arttutorhanoi.com'],
  },
  {
    name: 'A O Show Bamboo Circus',
    googleMapsUrl: 'https://www.google.com/maps/place/Saigon+Opera+House+(Ho+Chi+Minh+City+Theater)/@10.77695,106.70385,15z/data=!4m2!3m1!1s0x0:0x9adeaf19542242f?sa=X&ved=2ahUKEwi-p_vG8vj_AhX-RmwGHf0uC_wQ_BJ6BAg_EAg',
    googlePlaceId: '0x0:0x9adeaf19542242f',
    type: 'tour',
    category: 'Cultural & Sightseeing',
    citySlug: 'ho-chi-minh-city',
    city: 'Ho Chi Minh City',
    country: 'Vietnam',
    priceRange: '$$',
    priceLevel: 2,
    priceEstimate: 'Starting from $32 per person',
    bestTimeOfDay: 'evening',
    estimatedDuration: '1 hour',
    physicalLevel: 'easy',
    googleRating: 4.6,
    reviewCount: 3026,
    whySelected: 'A unique cultural experience that showcases Vietnamese life through a blend of acrobatics, dance, and music. It\'s a visually stunning performance held in the historic Saigon Opera House, offering a memorable evening for a solo traveler.',
    highlights: ['Bamboo circus', 'Live music', 'Story-telling', 'Held in the historic Saigon Opera House.'],
    considerations: ['The show is about an hour long. It\'s recommended to book tickets in advance, especially for good seats.'],
    soloTravelerReviews: 'Absolutely wonderful show. It\'s not just bamboo involved and they involve the whole audience. Thoroughly enjoyable show with some amazing stunts.',
    bookingInfo: 'Tickets can be booked online through the official website (luneproduction.com), GetYourGuide, Klook, or at the Saigon Opera House box office.',
    sourcesChecked: ['travel-lush.com', 'luneproduction.com', 'tripadvisor.com', 'getyourguide.com', 'klook.com'],
  },
  {
    name: 'The Lantern Lady: Traditional Lantern Class in Old Town',
    googleMapsUrl: 'https://www.google.com/maps/search/The+Lantern+Lady+Hoi+An',
    googlePlaceId: null,
    type: 'tour',
    category: 'Cultural & Sightseeing',
    citySlug: 'hoi-an',
    city: 'Hoi An',
    country: 'Vietnam',
    priceRange: '$',
    priceLevel: 1,
    priceEstimate: '~$10 per person',
    bestTimeOfDay: 'any',
    estimatedDuration: '1.5 hours',
    physicalLevel: 'easy',
    googleRating: 4.9,
    reviewCount: 389,
    whySelected: 'This class offers a hands-on cultural experience that is highly rated and suitable for solo travelers. It provides a creative outlet and a unique souvenir to take home.',
    highlights: ['Create your own foldable lantern', 'Choose from a variety of beautiful fabrics', 'Self-paced class', 'Friendly and patient instructors.'],
    considerations: ['The workshop can be chaotic at times with multiple groups', 'It\'s recommended to book in advance.'],
    soloTravelerReviews: 'Really fun experience making lanterns. The staff are the friendliest people ever and extremely patient! - Yacine, Canada. The Activity is amazing! Very meditating while you create an amazing lantern! The lady is extremely cute and helpful. Dont worry if you are not good at DIY they will help you :) - Panna, Hungary.',
    bookingInfo: 'Book online through GetYourGuide or other travel websites.',
    sourcesChecked: ['getyourguide', 'tripadvisor'],
  },
];
