import { did, upsertBatch } from '../seed-utils';

export async function seedCities() {
  const cities = [
    // Thailand (5 cities)
    {
      id: did('city-bkk'),
      country_id: did('country-th'),
      slug: 'bangkok',
      name: 'Bangkok',
      timezone: 'Asia/Bangkok',
      center_lat: 13.7563,
      center_lng: 100.5018,
      is_active: true,
      order_index: 1,
      hero_image_url: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800',
    },
    {
      id: did('city-cnx'),
      country_id: did('country-th'),
      slug: 'chiang-mai',
      name: 'Chiang Mai',
      timezone: 'Asia/Bangkok',
      center_lat: 18.7883,
      center_lng: 98.9853,
      is_active: true,
      order_index: 2,
      hero_image_url: 'https://images.unsplash.com/photo-1598524548734-3a0b9e0d7e53?w=800',
    },
    {
      id: did('city-krabi'),
      country_id: did('country-th'),
      slug: 'krabi',
      name: 'Krabi',
      timezone: 'Asia/Bangkok',
      center_lat: 8.0863,
      center_lng: 98.9063,
      is_active: true,
      order_index: 3,
      hero_image_url: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800',
    },
    {
      id: did('city-pai'),
      country_id: did('country-th'),
      slug: 'pai',
      name: 'Pai',
      timezone: 'Asia/Bangkok',
      center_lat: 19.3582,
      center_lng: 98.4407,
      is_active: true,
      order_index: 4,
      hero_image_url: 'https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800',
    },
    {
      id: did('city-kpg'),
      country_id: did('country-th'),
      slug: 'koh-phangan',
      name: 'Koh Phangan',
      timezone: 'Asia/Bangkok',
      center_lat: 9.7379,
      center_lng: 100.0261,
      is_active: true,
      order_index: 5,
      hero_image_url: 'https://images.unsplash.com/photo-1583947581924-860bda6a26df?w=800',
    },

    // Vietnam (5 cities)
    {
      id: did('city-sgn'),
      country_id: did('country-vn'),
      slug: 'ho-chi-minh-city',
      name: 'Ho Chi Minh City',
      timezone: 'Asia/Ho_Chi_Minh',
      center_lat: 10.8231,
      center_lng: 106.6297,
      is_active: true,
      order_index: 1,
      hero_image_url: 'https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800',
    },
    {
      id: did('city-han'),
      country_id: did('country-vn'),
      slug: 'hanoi',
      name: 'Hanoi',
      timezone: 'Asia/Ho_Chi_Minh',
      center_lat: 21.0285,
      center_lng: 105.8542,
      is_active: true,
      order_index: 2,
      hero_image_url: 'https://images.unsplash.com/photo-1509318308647-e8c2e2c8e1c4?w=800',
    },
    {
      id: did('city-hoi'),
      country_id: did('country-vn'),
      slug: 'hoi-an',
      name: 'Hoi An',
      timezone: 'Asia/Ho_Chi_Minh',
      center_lat: 15.8801,
      center_lng: 108.3380,
      is_active: true,
      order_index: 3,
      hero_image_url: 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800',
    },
    {
      id: did('city-dad'),
      country_id: did('country-vn'),
      slug: 'da-nang',
      name: 'Da Nang',
      timezone: 'Asia/Ho_Chi_Minh',
      center_lat: 16.0544,
      center_lng: 108.2022,
      is_active: true,
      order_index: 4,
      hero_image_url: 'https://images.unsplash.com/photo-1583931654613-8664e7e4ea50?w=800',
    },
    {
      id: did('city-dlat'),
      country_id: did('country-vn'),
      slug: 'da-lat',
      name: 'Da Lat',
      timezone: 'Asia/Ho_Chi_Minh',
      center_lat: 11.9404,
      center_lng: 108.4583,
      is_active: true,
      order_index: 5,
      hero_image_url: 'https://images.unsplash.com/photo-1632244124088-cc48d0f4cc12?w=800',
    },

    // Indonesia (5 cities)
    {
      id: did('city-ubud'),
      country_id: did('country-id'),
      slug: 'ubud',
      name: 'Ubud',
      timezone: 'Asia/Makassar',
      center_lat: -8.5069,
      center_lng: 115.2625,
      is_active: true,
      order_index: 1,
      hero_image_url: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800',
    },
    {
      id: did('city-canggu'),
      country_id: did('country-id'),
      slug: 'canggu',
      name: 'Canggu',
      timezone: 'Asia/Makassar',
      center_lat: -8.6480,
      center_lng: 115.1385,
      is_active: true,
      order_index: 2,
      hero_image_url: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
    },
    {
      id: did('city-seminyak'),
      country_id: did('country-id'),
      slug: 'seminyak',
      name: 'Seminyak',
      timezone: 'Asia/Makassar',
      center_lat: -8.6917,
      center_lng: 115.1673,
      is_active: true,
      order_index: 3,
      hero_image_url: 'https://images.unsplash.com/photo-1537953773345-d172ccf13cf1?w=800',
    },
    {
      id: did('city-yogya'),
      country_id: did('country-id'),
      slug: 'yogyakarta',
      name: 'Yogyakarta',
      timezone: 'Asia/Jakarta',
      center_lat: -7.7956,
      center_lng: 110.3695,
      is_active: true,
      order_index: 4,
      hero_image_url: 'https://images.unsplash.com/photo-1551918120-9739cb430c6d?w=800',
    },
    {
      id: did('city-gili'),
      country_id: did('country-id'),
      slug: 'gili-islands',
      name: 'Gili Islands',
      timezone: 'Asia/Makassar',
      center_lat: -8.3484,
      center_lng: 116.0419,
      is_active: true,
      order_index: 5,
      hero_image_url: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
    },

    // Philippines (5 cities)
    {
      id: did('city-elnido'),
      country_id: did('country-ph'),
      slug: 'el-nido',
      name: 'El Nido',
      timezone: 'Asia/Manila',
      center_lat: 11.1946,
      center_lng: 119.4012,
      is_active: true,
      order_index: 1,
      hero_image_url: 'https://images.unsplash.com/photo-1583940049070-5e3a6f0f3b6f?w=800',
    },
    {
      id: did('city-siargao'),
      country_id: did('country-ph'),
      slug: 'siargao',
      name: 'Siargao',
      timezone: 'Asia/Manila',
      center_lat: 9.8609,
      center_lng: 126.0465,
      is_active: true,
      order_index: 2,
      hero_image_url: 'https://images.unsplash.com/photo-1565177226165-6cfc7db83e59?w=800',
    },
    {
      id: did('city-cebu'),
      country_id: did('country-ph'),
      slug: 'cebu',
      name: 'Cebu',
      timezone: 'Asia/Manila',
      center_lat: 10.3157,
      center_lng: 123.8854,
      is_active: true,
      order_index: 3,
      hero_image_url: 'https://images.unsplash.com/photo-1582623210671-52ed1f1c2cec?w=800',
    },
    {
      id: did('city-manila'),
      country_id: did('country-ph'),
      slug: 'manila',
      name: 'Manila',
      timezone: 'Asia/Manila',
      center_lat: 14.5995,
      center_lng: 120.9842,
      is_active: true,
      order_index: 4,
      hero_image_url: 'https://images.unsplash.com/photo-1578664182210-97018a265f56?w=800',
    },
    {
      id: did('city-bohol'),
      country_id: did('country-ph'),
      slug: 'bohol',
      name: 'Bohol',
      timezone: 'Asia/Manila',
      center_lat: 9.8500,
      center_lng: 124.1435,
      is_active: true,
      order_index: 5,
      hero_image_url: 'https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=800',
    },

    // Malaysia (5 cities)
    {
      id: did('city-kl'),
      country_id: did('country-my'),
      slug: 'kuala-lumpur',
      name: 'Kuala Lumpur',
      timezone: 'Asia/Kuala_Lumpur',
      center_lat: 3.1390,
      center_lng: 101.6869,
      is_active: true,
      order_index: 1,
      hero_image_url: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800',
    },
    {
      id: did('city-penang'),
      country_id: did('country-my'),
      slug: 'penang',
      name: 'Penang',
      timezone: 'Asia/Kuala_Lumpur',
      center_lat: 5.4141,
      center_lng: 100.3288,
      is_active: true,
      order_index: 2,
      hero_image_url: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
    },
    {
      id: did('city-langkawi'),
      country_id: did('country-my'),
      slug: 'langkawi',
      name: 'Langkawi',
      timezone: 'Asia/Kuala_Lumpur',
      center_lat: 6.3500,
      center_lng: 99.8000,
      is_active: true,
      order_index: 3,
      hero_image_url: 'https://images.unsplash.com/photo-1528127269322-539801943592?w=800',
    },
    {
      id: did('city-malacca'),
      country_id: did('country-my'),
      slug: 'malacca',
      name: 'Malacca',
      timezone: 'Asia/Kuala_Lumpur',
      center_lat: 2.1896,
      center_lng: 102.2501,
      is_active: true,
      order_index: 4,
      hero_image_url: 'https://images.unsplash.com/photo-1591768793355-74d04bb6608f?w=800',
    },
    {
      id: did('city-kk'),
      country_id: did('country-my'),
      slug: 'kota-kinabalu',
      name: 'Kota Kinabalu',
      timezone: 'Asia/Kuching',
      center_lat: 5.9804,
      center_lng: 116.0735,
      is_active: true,
      order_index: 5,
      hero_image_url: 'https://images.unsplash.com/photo-1551244072-5d12893278ab?w=800',
    },

    // Singapore (1 city)
    {
      id: did('city-sg'),
      country_id: did('country-sg'),
      slug: 'singapore',
      name: 'Singapore',
      timezone: 'Asia/Singapore',
      center_lat: 1.3521,
      center_lng: 103.8198,
      is_active: true,
      order_index: 1,
      hero_image_url: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800',
    },

    // Cambodia (4 cities)
    {
      id: did('city-siemreap'),
      country_id: did('country-kh'),
      slug: 'siem-reap',
      name: 'Siem Reap',
      timezone: 'Asia/Phnom_Penh',
      center_lat: 13.3671,
      center_lng: 103.8448,
      is_active: true,
      order_index: 1,
      hero_image_url: 'https://images.unsplash.com/photo-1545582990-4dec0e1e470e?w=800',
    },
    {
      id: did('city-phnompenh'),
      country_id: did('country-kh'),
      slug: 'phnom-penh',
      name: 'Phnom Penh',
      timezone: 'Asia/Phnom_Penh',
      center_lat: 11.5564,
      center_lng: 104.9282,
      is_active: true,
      order_index: 2,
      hero_image_url: 'https://images.unsplash.com/photo-1557499305-7059a49a5e5f?w=800',
    },
    {
      id: did('city-kampot'),
      country_id: did('country-kh'),
      slug: 'kampot',
      name: 'Kampot',
      timezone: 'Asia/Phnom_Penh',
      center_lat: 10.6167,
      center_lng: 104.1833,
      is_active: true,
      order_index: 3,
      hero_image_url: 'https://images.unsplash.com/photo-1581333100349-6d67b40e2a8c?w=800',
    },
    {
      id: did('city-kohrong'),
      country_id: did('country-kh'),
      slug: 'koh-rong',
      name: 'Koh Rong',
      timezone: 'Asia/Phnom_Penh',
      center_lat: 10.6906,
      center_lng: 103.3078,
      is_active: true,
      order_index: 4,
      hero_image_url: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
    },

    // Laos (3 cities)
    {
      id: did('city-luangprabang'),
      country_id: did('country-la'),
      slug: 'luang-prabang',
      name: 'Luang Prabang',
      timezone: 'Asia/Vientiane',
      center_lat: 19.8845,
      center_lng: 102.1350,
      is_active: true,
      order_index: 1,
      hero_image_url: 'https://images.unsplash.com/photo-1540611025311-01df3cef54b5?w=800',
    },
    {
      id: did('city-vientiane'),
      country_id: did('country-la'),
      slug: 'vientiane',
      name: 'Vientiane',
      timezone: 'Asia/Vientiane',
      center_lat: 17.9757,
      center_lng: 102.6331,
      is_active: true,
      order_index: 2,
      hero_image_url: 'https://images.unsplash.com/photo-1569513970113-68f8e4dfa826?w=800',
    },
    {
      id: did('city-vangvieng'),
      country_id: did('country-la'),
      slug: 'vang-vieng',
      name: 'Vang Vieng',
      timezone: 'Asia/Vientiane',
      center_lat: 18.9333,
      center_lng: 102.4500,
      is_active: true,
      order_index: 3,
      hero_image_url: 'https://images.unsplash.com/photo-1564657608396-c3a0d2e72e8a?w=800',
    },

    // Myanmar (3 cities)
    {
      id: did('city-bagan'),
      country_id: did('country-mm'),
      slug: 'bagan',
      name: 'Bagan',
      timezone: 'Asia/Yangon',
      center_lat: 21.1717,
      center_lng: 94.8586,
      is_active: true,
      order_index: 1,
      hero_image_url: 'https://images.unsplash.com/photo-1589803283328-e29d35af9df9?w=800',
    },
    {
      id: did('city-yangon'),
      country_id: did('country-mm'),
      slug: 'yangon',
      name: 'Yangon',
      timezone: 'Asia/Yangon',
      center_lat: 16.8661,
      center_lng: 96.1951,
      is_active: true,
      order_index: 2,
      hero_image_url: 'https://images.unsplash.com/photo-1548389429-6451526f3faa?w=800',
    },
    {
      id: did('city-inlelake'),
      country_id: did('country-mm'),
      slug: 'inle-lake',
      name: 'Inle Lake',
      timezone: 'Asia/Yangon',
      center_lat: 20.5792,
      center_lng: 96.8977,
      is_active: true,
      order_index: 3,
      hero_image_url: 'https://images.unsplash.com/photo-1562602833-0f4ab2fc46e3?w=800',
    },

    // Japan (3 cities)
    {
      id: did('city-tokyo'),
      country_id: did('country-jp'),
      slug: 'tokyo',
      name: 'Tokyo',
      timezone: 'Asia/Tokyo',
      center_lat: 35.6762,
      center_lng: 139.6503,
      is_active: true,
      order_index: 1,
      hero_image_url: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800',
    },
    {
      id: did('city-kyoto'),
      country_id: did('country-jp'),
      slug: 'kyoto',
      name: 'Kyoto',
      timezone: 'Asia/Tokyo',
      center_lat: 35.0116,
      center_lng: 135.7681,
      is_active: true,
      order_index: 2,
      hero_image_url: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800',
    },
    {
      id: did('city-osaka'),
      country_id: did('country-jp'),
      slug: 'osaka',
      name: 'Osaka',
      timezone: 'Asia/Tokyo',
      center_lat: 34.6937,
      center_lng: 135.5023,
      is_active: true,
      order_index: 3,
      hero_image_url: 'https://images.unsplash.com/photo-1555217851-6141535bd771?w=800',
    },

    // Portugal (2 cities)
    {
      id: did('city-lisbon'),
      country_id: did('country-pt'),
      slug: 'lisbon',
      name: 'Lisbon',
      timezone: 'Europe/Lisbon',
      center_lat: 38.7223,
      center_lng: -9.1393,
      is_active: true,
      order_index: 1,
      hero_image_url: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800',
    },
    {
      id: did('city-porto'),
      country_id: did('country-pt'),
      slug: 'porto',
      name: 'Porto',
      timezone: 'Europe/Lisbon',
      center_lat: 41.1579,
      center_lng: -8.6291,
      is_active: true,
      order_index: 2,
      hero_image_url: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800',
    },

    // Morocco (3 cities)
    {
      id: did('city-marrakech'),
      country_id: did('country-ma'),
      slug: 'marrakech',
      name: 'Marrakech',
      timezone: 'Africa/Casablanca',
      center_lat: 31.6295,
      center_lng: -7.9811,
      is_active: true,
      order_index: 1,
      hero_image_url: 'https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?w=800',
    },
    {
      id: did('city-fes'),
      country_id: did('country-ma'),
      slug: 'fes',
      name: 'Fes',
      timezone: 'Africa/Casablanca',
      center_lat: 34.0181,
      center_lng: -5.0078,
      is_active: true,
      order_index: 2,
      hero_image_url: 'https://images.unsplash.com/photo-1566438480900-0609be27a4be?w=800',
    },
    {
      id: did('city-chefchaouen'),
      country_id: did('country-ma'),
      slug: 'chefchaouen',
      name: 'Chefchaouen',
      timezone: 'Africa/Casablanca',
      center_lat: 35.1688,
      center_lng: -5.2636,
      is_active: true,
      order_index: 3,
      hero_image_url: 'https://images.unsplash.com/photo-1570708635852-d4bb70d8b8e9?w=800',
    },
  ];

  await upsertBatch('cities', cities, 'id');
}
