import { did, upsertBatch } from '../seed-utils';

export async function seedCityAreas() {
  const areas = [
    // Thailand - Bangkok
    {
      id: did('area-bkk-silom'),
      city_id: did('city-bkk'),
      slug: 'silom',
      name: 'Silom',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-bkk-sukhumvit'),
      city_id: did('city-bkk'),
      slug: 'sukhumvit',
      name: 'Sukhumvit',
      area_kind: 'district',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },
    {
      id: did('area-bkk-rattanakosin'),
      city_id: did('city-bkk'),
      slug: 'rattanakosin',
      name: 'Rattanakosin',
      area_kind: 'district',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },
    {
      id: did('area-bkk-khaosan'),
      city_id: did('city-bkk'),
      slug: 'khaosan',
      name: 'Khao San',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 4,
    },

    // Thailand - Chiang Mai
    {
      id: did('area-cnx-oldcity'),
      city_id: did('city-cnx'),
      slug: 'oldcity',
      name: 'Old City',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-cnx-nimman'),
      city_id: did('city-cnx'),
      slug: 'nimman',
      name: 'Nimman',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },
    {
      id: did('area-cnx-nightbazaar'),
      city_id: did('city-cnx'),
      slug: 'nightbazaar',
      name: 'Night Bazaar',
      area_kind: 'district',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },

    // Thailand - Krabi
    {
      id: did('area-krabi-aonang'),
      city_id: did('city-krabi'),
      slug: 'aonang',
      name: 'Ao Nang',
      area_kind: 'beach',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-krabi-railay'),
      city_id: did('city-krabi'),
      slug: 'railay',
      name: 'Railay',
      area_kind: 'beach',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },

    // Thailand - Pai
    {
      id: did('area-pai-walkingstreet'),
      city_id: did('city-pai'),
      slug: 'walkingstreet',
      name: 'Walking Street',
      area_kind: 'neighborhood',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-pai-paicanyon'),
      city_id: did('city-pai'),
      slug: 'paicanyon',
      name: 'Pai Canyon Area',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },

    // Thailand - Koh Phangan
    {
      id: did('area-kpg-haadrin'),
      city_id: did('city-kpg'),
      slug: 'haadrin',
      name: 'Haad Rin',
      area_kind: 'beach',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-kpg-thongsala'),
      city_id: did('city-kpg'),
      slug: 'thongsala',
      name: 'Thong Sala',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },
    {
      id: did('area-kpg-srithanu'),
      city_id: did('city-kpg'),
      slug: 'srithanu',
      name: 'Srithanu',
      area_kind: 'beach',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },

    // Vietnam - HCMC
    {
      id: did('area-sgn-district1'),
      city_id: did('city-sgn'),
      slug: 'district1',
      name: 'District 1',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-sgn-district3'),
      city_id: did('city-sgn'),
      slug: 'district3',
      name: 'District 3',
      area_kind: 'district',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },
    {
      id: did('area-sgn-buivien'),
      city_id: did('city-sgn'),
      slug: 'buivien',
      name: 'Bui Vien',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },

    // Vietnam - Hanoi
    {
      id: did('area-han-oldquarter'),
      city_id: did('city-han'),
      slug: 'oldquarter',
      name: 'Old Quarter',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-han-westlake'),
      city_id: did('city-han'),
      slug: 'westlake',
      name: 'West Lake',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },
    {
      id: did('area-han-frenchquarter'),
      city_id: did('city-han'),
      slug: 'frenchquarter',
      name: 'French Quarter',
      area_kind: 'district',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },

    // Vietnam - Hoi An
    {
      id: did('area-hoi-ancienttown'),
      city_id: did('city-hoi'),
      slug: 'ancienttown',
      name: 'Ancient Town',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-hoi-anbangbeach'),
      city_id: did('city-hoi'),
      slug: 'anbangbeach',
      name: 'An Bang Beach',
      area_kind: 'beach',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },
    {
      id: did('area-hoi-camthanh'),
      city_id: did('city-hoi'),
      slug: 'camthanh',
      name: 'Cam Thanh',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },

    // Vietnam - Da Nang
    {
      id: did('area-dad-mykhebeach'),
      city_id: did('city-dad'),
      slug: 'mykhebeach',
      name: 'My Khe Beach',
      area_kind: 'beach',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-dad-hanriver'),
      city_id: did('city-dad'),
      slug: 'hanriver',
      name: 'Han River',
      area_kind: 'district',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },
    {
      id: did('area-dad-sontra'),
      city_id: did('city-dad'),
      slug: 'sontra',
      name: 'Son Tra',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },

    // Vietnam - Da Lat
    {
      id: did('area-dlat-citycenter'),
      city_id: did('city-dlat'),
      slug: 'dlat-citycenter',
      name: 'City Center',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-dlat-tuyenlamlake'),
      city_id: did('city-dlat'),
      slug: 'tuyenlamlake',
      name: 'Tuyen Lam Lake',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },

    // Indonesia - Ubud
    {
      id: did('area-ubud-centralubud'),
      city_id: did('city-ubud'),
      slug: 'centralubud',
      name: 'Central Ubud',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-ubud-tegallalang'),
      city_id: did('city-ubud'),
      slug: 'tegallalang',
      name: 'Tegallalang',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },
    {
      id: did('area-ubud-campuhan'),
      city_id: did('city-ubud'),
      slug: 'campuhan',
      name: 'Campuhan',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },

    // Indonesia - Canggu
    {
      id: did('area-canggu-batubolong'),
      city_id: did('city-canggu'),
      slug: 'batubolong',
      name: 'Batu Bolong',
      area_kind: 'beach',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-canggu-berawa'),
      city_id: did('city-canggu'),
      slug: 'berawa',
      name: 'Berawa',
      area_kind: 'beach',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },
    {
      id: did('area-canggu-echobeach'),
      city_id: did('city-canggu'),
      slug: 'echobeach',
      name: 'Echo Beach',
      area_kind: 'beach',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },

    // Indonesia - Seminyak
    {
      id: did('area-seminyak-petitenget'),
      city_id: did('city-seminyak'),
      slug: 'petitenget',
      name: 'Petitenget',
      area_kind: 'neighborhood',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-seminyak-oberoi'),
      city_id: did('city-seminyak'),
      slug: 'oberoi',
      name: 'Oberoi',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },
    {
      id: did('area-seminyak-doublesix'),
      city_id: did('city-seminyak'),
      slug: 'doublesix',
      name: 'Double Six',
      area_kind: 'beach',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },

    // Indonesia - Yogyakarta
    {
      id: did('area-yogya-malioboro'),
      city_id: did('city-yogya'),
      slug: 'malioboro',
      name: 'Malioboro',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-yogya-prawirotaman'),
      city_id: did('city-yogya'),
      slug: 'prawirotaman',
      name: 'Prawirotaman',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },

    // Indonesia - Gili Islands
    {
      id: did('area-gili-gilitrawangan'),
      city_id: did('city-gili'),
      slug: 'gilitrawangan',
      name: 'Gili Trawangan',
      area_kind: 'island',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-gili-giliair'),
      city_id: did('city-gili'),
      slug: 'giliair',
      name: 'Gili Air',
      area_kind: 'island',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },

    // Philippines - El Nido
    {
      id: did('area-elnido-townproper'),
      city_id: did('city-elnido'),
      slug: 'townproper',
      name: 'Town Proper',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-elnido-corongcorong'),
      city_id: did('city-elnido'),
      slug: 'corongcorong',
      name: 'Corong-Corong',
      area_kind: 'beach',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },
    {
      id: did('area-elnido-nacpan'),
      city_id: did('city-elnido'),
      slug: 'nacpan',
      name: 'Nacpan',
      area_kind: 'beach',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },

    // Philippines - Siargao
    {
      id: did('area-siargao-generalluna'),
      city_id: did('city-siargao'),
      slug: 'generalluna',
      name: 'General Luna',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-siargao-cloud9'),
      city_id: did('city-siargao'),
      slug: 'cloud9',
      name: 'Cloud 9',
      area_kind: 'beach',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },
    {
      id: did('area-siargao-dapa'),
      city_id: did('city-siargao'),
      slug: 'dapa',
      name: 'Dapa',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },

    // Philippines - Cebu
    {
      id: did('area-cebu-cebucity'),
      city_id: did('city-cebu'),
      slug: 'cebucity',
      name: 'Cebu City',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-cebu-mactan'),
      city_id: did('city-cebu'),
      slug: 'mactan',
      name: 'Mactan',
      area_kind: 'island',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },
    {
      id: did('area-cebu-oslob'),
      city_id: did('city-cebu'),
      slug: 'oslob',
      name: 'Oslob',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },

    // Philippines - Manila
    {
      id: did('area-manila-makati'),
      city_id: did('city-manila'),
      slug: 'makati',
      name: 'Makati',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-manila-bgc'),
      city_id: did('city-manila'),
      slug: 'bgc',
      name: 'BGC',
      area_kind: 'district',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },
    {
      id: did('area-manila-intramuros'),
      city_id: did('city-manila'),
      slug: 'intramuros',
      name: 'Intramuros',
      area_kind: 'district',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },
    {
      id: did('area-manila-poblacion'),
      city_id: did('city-manila'),
      slug: 'poblacion',
      name: 'Poblacion',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 4,
    },

    // Philippines - Bohol
    {
      id: did('area-bohol-panglao'),
      city_id: did('city-bohol'),
      slug: 'panglao',
      name: 'Panglao',
      area_kind: 'island',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-bohol-tagbilaran'),
      city_id: did('city-bohol'),
      slug: 'tagbilaran',
      name: 'Tagbilaran',
      area_kind: 'district',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },

    // Malaysia - KL
    {
      id: did('area-kl-bukitbintang'),
      city_id: did('city-kl'),
      slug: 'bukitbintang',
      name: 'Bukit Bintang',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-kl-klcc'),
      city_id: did('city-kl'),
      slug: 'klcc',
      name: 'KLCC',
      area_kind: 'district',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },
    {
      id: did('area-kl-chinatown'),
      city_id: did('city-kl'),
      slug: 'kl-chinatown',
      name: 'Chinatown',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },

    // Malaysia - Penang
    {
      id: did('area-penang-georgetown'),
      city_id: did('city-penang'),
      slug: 'georgetown',
      name: 'George Town',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-penang-batuferringhi'),
      city_id: did('city-penang'),
      slug: 'batuferringhi',
      name: 'Batu Ferringhi',
      area_kind: 'beach',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },

    // Malaysia - Langkawi
    {
      id: did('area-langkawi-pantaicenang'),
      city_id: did('city-langkawi'),
      slug: 'pantaicenang',
      name: 'Pantai Cenang',
      area_kind: 'beach',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-langkawi-kuah'),
      city_id: did('city-langkawi'),
      slug: 'kuah',
      name: 'Kuah',
      area_kind: 'district',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },

    // Malaysia - Malacca
    {
      id: did('area-malacca-jonkerstreet'),
      city_id: did('city-malacca'),
      slug: 'jonkerstreet',
      name: 'Jonker Street',
      area_kind: 'neighborhood',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-malacca-dutchsquare'),
      city_id: did('city-malacca'),
      slug: 'dutchsquare',
      name: 'Dutch Square',
      area_kind: 'district',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },

    // Malaysia - Kota Kinabalu
    {
      id: did('area-kk-citycenter'),
      city_id: did('city-kk'),
      slug: 'kk-citycenter',
      name: 'City Center',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-kk-gayastreet'),
      city_id: did('city-kk'),
      slug: 'gayastreet',
      name: 'Gaya Street',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },

    // Singapore
    {
      id: did('area-sg-chinatown'),
      city_id: did('city-sg'),
      slug: 'sg-chinatown',
      name: 'Chinatown',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-sg-kampongglam'),
      city_id: did('city-sg'),
      slug: 'kampongglam',
      name: 'Kampong Glam',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },
    {
      id: did('area-sg-marinabay'),
      city_id: did('city-sg'),
      slug: 'marinabay',
      name: 'Marina Bay',
      area_kind: 'district',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },
    {
      id: did('area-sg-tiongbahru'),
      city_id: did('city-sg'),
      slug: 'tiongbahru',
      name: 'Tiong Bahru',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 4,
    },

    // Cambodia - Siem Reap
    {
      id: did('area-siemreap-oldmarket'),
      city_id: did('city-siemreap'),
      slug: 'oldmarket',
      name: 'Old Market',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-siemreap-pubstreet'),
      city_id: did('city-siemreap'),
      slug: 'pubstreet',
      name: 'Pub Street',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },
    {
      id: did('area-siemreap-angkorarea'),
      city_id: did('city-siemreap'),
      slug: 'angkorarea',
      name: 'Angkor Area',
      area_kind: 'district',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },

    // Cambodia - Phnom Penh
    {
      id: did('area-phnompenh-riverside'),
      city_id: did('city-phnompenh'),
      slug: 'riverside',
      name: 'Riverside',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-phnompenh-bkk1'),
      city_id: did('city-phnompenh'),
      slug: 'bkk1',
      name: 'BKK1',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },
    {
      id: did('area-phnompenh-russianmarket'),
      city_id: did('city-phnompenh'),
      slug: 'russianmarket',
      name: 'Russian Market',
      area_kind: 'district',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },

    // Cambodia - Kampot
    {
      id: did('area-kampot-oldtown'),
      city_id: did('city-kampot'),
      slug: 'kampot-oldtown',
      name: 'Old Town',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-kampot-riverfront'),
      city_id: did('city-kampot'),
      slug: 'riverfront',
      name: 'Riverfront',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },

    // Cambodia - Koh Rong
    {
      id: did('area-kohrong-kohtouch'),
      city_id: did('city-kohrong'),
      slug: 'kohtouch',
      name: 'Koh Touch',
      area_kind: 'beach',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-kohrong-longsetbeach'),
      city_id: did('city-kohrong'),
      slug: 'longsetbeach',
      name: 'Long Set Beach',
      area_kind: 'beach',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },

    // Laos - Luang Prabang
    {
      id: did('area-luangprabang-oldtown'),
      city_id: did('city-luangprabang'),
      slug: 'luangprabang-oldtown',
      name: 'Old Town',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-luangprabang-nightmarket'),
      city_id: did('city-luangprabang'),
      slug: 'nightmarket',
      name: 'Night Market',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },
    {
      id: did('area-luangprabang-mekongriverside'),
      city_id: did('city-luangprabang'),
      slug: 'mekongriverside',
      name: 'Mekong Riverside',
      area_kind: 'district',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },

    // Laos - Vientiane
    {
      id: did('area-vientiane-mekongriverfront'),
      city_id: did('city-vientiane'),
      slug: 'mekongriverfront',
      name: 'Mekong Riverfront',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-vientiane-thatluangarea'),
      city_id: did('city-vientiane'),
      slug: 'thatluangarea',
      name: 'That Luang Area',
      area_kind: 'district',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },

    // Laos - Vang Vieng
    {
      id: did('area-vangvieng-towncenter'),
      city_id: did('city-vangvieng'),
      slug: 'towncenter',
      name: 'Town Center',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-vangvieng-bluelagoonarea'),
      city_id: did('city-vangvieng'),
      slug: 'bluelagoonarea',
      name: 'Blue Lagoon Area',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },

    // Myanmar - Bagan
    {
      id: did('area-bagan-oldbagan'),
      city_id: did('city-bagan'),
      slug: 'oldbagan',
      name: 'Old Bagan',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-bagan-nyaungu'),
      city_id: did('city-bagan'),
      slug: 'nyaungu',
      name: 'Nyaung-U',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },
    {
      id: did('area-bagan-newbagan'),
      city_id: did('city-bagan'),
      slug: 'newbagan',
      name: 'New Bagan',
      area_kind: 'district',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },

    // Myanmar - Yangon
    {
      id: did('area-yangon-downtown'),
      city_id: did('city-yangon'),
      slug: 'downtown',
      name: 'Downtown',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-yangon-shwedagonarea'),
      city_id: did('city-yangon'),
      slug: 'shwedagonarea',
      name: 'Shwedagon Area',
      area_kind: 'district',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },
    {
      id: did('area-yangon-chinatown'),
      city_id: did('city-yangon'),
      slug: 'yangon-chinatown',
      name: 'Chinatown',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },

    // Myanmar - Inle Lake
    {
      id: did('area-inlelake-nyaungshwe'),
      city_id: did('city-inlelake'),
      slug: 'nyaungshwe',
      name: 'Nyaung Shwe',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-inlelake-lakearea'),
      city_id: did('city-inlelake'),
      slug: 'lakearea',
      name: 'Lake Area',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },

    // Japan - Tokyo
    {
      id: did('area-tokyo-shibuya'),
      city_id: did('city-tokyo'),
      slug: 'shibuya',
      name: 'Shibuya',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-tokyo-shinjuku'),
      city_id: did('city-tokyo'),
      slug: 'shinjuku',
      name: 'Shinjuku',
      area_kind: 'district',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },
    {
      id: did('area-tokyo-asakusa'),
      city_id: did('city-tokyo'),
      slug: 'asakusa',
      name: 'Asakusa',
      area_kind: 'district',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },

    // Japan - Kyoto
    {
      id: did('area-kyoto-gion'),
      city_id: did('city-kyoto'),
      slug: 'gion',
      name: 'Gion',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-kyoto-higashiyama'),
      city_id: did('city-kyoto'),
      slug: 'higashiyama',
      name: 'Higashiyama',
      area_kind: 'district',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },
    {
      id: did('area-kyoto-arashiyama'),
      city_id: did('city-kyoto'),
      slug: 'arashiyama',
      name: 'Arashiyama',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },

    // Japan - Osaka
    {
      id: did('area-osaka-namba'),
      city_id: did('city-osaka'),
      slug: 'namba',
      name: 'Namba',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-osaka-dotonbori'),
      city_id: did('city-osaka'),
      slug: 'dotonbori',
      name: 'Dotonbori',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },
    {
      id: did('area-osaka-shinsekai'),
      city_id: did('city-osaka'),
      slug: 'shinsekai',
      name: 'Shinsekai',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },

    // Portugal - Lisbon
    {
      id: did('area-lisbon-alfama'),
      city_id: did('city-lisbon'),
      slug: 'alfama',
      name: 'Alfama',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-lisbon-bairroalto'),
      city_id: did('city-lisbon'),
      slug: 'bairroalto',
      name: 'Bairro Alto',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },
    {
      id: did('area-lisbon-baixa'),
      city_id: did('city-lisbon'),
      slug: 'baixa',
      name: 'Baixa',
      area_kind: 'district',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },
    {
      id: did('area-lisbon-belem'),
      city_id: did('city-lisbon'),
      slug: 'belem',
      name: 'Belem',
      area_kind: 'district',
      is_primary: false,
      is_active: true,
      order_index: 4,
    },

    // Portugal - Porto
    {
      id: did('area-porto-ribeira'),
      city_id: did('city-porto'),
      slug: 'ribeira',
      name: 'Ribeira',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-porto-cedofeita'),
      city_id: did('city-porto'),
      slug: 'cedofeita',
      name: 'Cedofeita',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },

    // Morocco - Marrakech
    {
      id: did('area-marrakech-medina'),
      city_id: did('city-marrakech'),
      slug: 'marrakech-medina',
      name: 'Medina',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-marrakech-gueliz'),
      city_id: did('city-marrakech'),
      slug: 'gueliz',
      name: 'Gueliz',
      area_kind: 'district',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },
    {
      id: did('area-marrakech-kasbah'),
      city_id: did('city-marrakech'),
      slug: 'kasbah',
      name: 'Kasbah',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },

    // Morocco - Fes
    {
      id: did('area-fes-feselbali'),
      city_id: did('city-fes'),
      slug: 'feselbali',
      name: 'Fes el-Bali',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-fes-villenouvelle'),
      city_id: did('city-fes'),
      slug: 'villenouvelle',
      name: 'Ville Nouvelle',
      area_kind: 'district',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },

    // Morocco - Chefchaouen
    {
      id: did('area-chefchaouen-medina'),
      city_id: did('city-chefchaouen'),
      slug: 'chefchaouen-medina',
      name: 'Medina',
      area_kind: 'district',
      is_primary: true,
      is_active: true,
      order_index: 1,
    },
    {
      id: did('area-chefchaouen-plazautaelhammam'),
      city_id: did('city-chefchaouen'),
      slug: 'plazautaelhammam',
      name: 'Plaza Uta el-Hammam',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 2,
    },

    // Missing area entries
    {
      id: did('area-bkk-oldtown'),
      city_id: did('city-bkk'),
      slug: 'bkk-oldtown',
      name: 'Old Town (Rattanakosin)',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 5,
    },
    {
      id: did('area-cebu-city'),
      city_id: did('city-cebu'),
      slug: 'cebu-city-center',
      name: 'Cebu City Center',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 4,
    },
    {
      id: did('area-chefchaouen-plaza'),
      city_id: did('city-chefchaouen'),
      slug: 'chefchaouen-plaza',
      name: 'Plaza Area',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },
    {
      id: did('area-dad-mykhe'),
      city_id: did('city-dad'),
      slug: 'mykhe',
      name: 'My Khe Beach',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 4,
    },
    {
      id: did('area-dlat-center'),
      city_id: did('city-dlat'),
      slug: 'dlat-center',
      name: 'City Center',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },
    {
      id: did('area-dlat-tuyenlam'),
      city_id: did('city-dlat'),
      slug: 'tuyenlam',
      name: 'Tuyen Lam Lake',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 4,
    },
    {
      id: did('area-elnido-corong'),
      city_id: did('city-elnido'),
      slug: 'corong-corong',
      name: 'Corong-Corong',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 4,
    },
    {
      id: did('area-elnido-town'),
      city_id: did('city-elnido'),
      slug: 'elnido-town',
      name: 'El Nido Town',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 5,
    },
    {
      id: did('area-fes-fesbali'),
      city_id: did('city-fes'),
      slug: 'fes-el-bali',
      name: 'Fes el-Bali',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },
    {
      id: did('area-fes-villenovelle'),
      city_id: did('city-fes'),
      slug: 'ville-nouvelle',
      name: 'Ville Nouvelle',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 4,
    },
    {
      id: did('area-gili-air'),
      city_id: did('city-gili'),
      slug: 'gili-air',
      name: 'Gili Air',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },
    {
      id: did('area-gili-trawangan'),
      city_id: did('city-gili'),
      slug: 'gili-trawangan',
      name: 'Gili Trawangan',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 4,
    },
    {
      id: did('area-hoi-anbang'),
      city_id: did('city-hoi'),
      slug: 'an-bang',
      name: 'An Bang Beach',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 4,
    },
    {
      id: did('area-hoi-ancient'),
      city_id: did('city-hoi'),
      slug: 'ancient-town',
      name: 'Ancient Town',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 5,
    },
    {
      id: did('area-inlelake-lake'),
      city_id: did('city-inlelake'),
      slug: 'inle-lake',
      name: 'Inle Lake',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },
    {
      id: did('area-kk-gayast'),
      city_id: did('city-kk'),
      slug: 'gaya-street',
      name: 'Gaya Street',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },
    {
      id: did('area-kohrong-longset'),
      city_id: did('city-kohrong'),
      slug: 'long-set',
      name: 'Long Set Beach',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },
    {
      id: did('area-malacca-jonkerst'),
      city_id: did('city-malacca'),
      slug: 'jonker-street',
      name: 'Jonker Street',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },
    {
      id: did('area-pai-canyon'),
      city_id: did('city-pai'),
      slug: 'pai-canyon',
      name: 'Pai Canyon Area',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },
    {
      id: did('area-pai-walkingst'),
      city_id: did('city-pai'),
      slug: 'walking-street',
      name: 'Walking Street',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 4,
    },
    {
      id: did('area-siemreap-angkor'),
      city_id: did('city-siemreap'),
      slug: 'angkor',
      name: 'Angkor Archaeological Park',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 4,
    },
    {
      id: did('area-siemreap-pubst'),
      city_id: did('city-siemreap'),
      slug: 'pub-street',
      name: 'Pub Street Area',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 5,
    },
    {
      id: did('area-ubud-central'),
      city_id: did('city-ubud'),
      slug: 'ubud-central',
      name: 'Central Ubud',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 4,
    },
    {
      id: did('area-vangvieng-bluelagoon'),
      city_id: did('city-vangvieng'),
      slug: 'blue-lagoon',
      name: 'Blue Lagoon Area',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },
    {
      id: did('area-vangvieng-center'),
      city_id: did('city-vangvieng'),
      slug: 'vangvieng-center',
      name: 'Town Center',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 4,
    },
    {
      id: did('area-vientiane-mekong'),
      city_id: did('city-vientiane'),
      slug: 'mekong-riverside',
      name: 'Mekong Riverside',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 3,
    },
    {
      id: did('area-vientiane-thatluang'),
      city_id: did('city-vientiane'),
      slug: 'that-luang',
      name: 'That Luang Area',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 4,
    },
    {
      id: did('area-yangon-shwedagon'),
      city_id: did('city-yangon'),
      slug: 'shwedagon',
      name: 'Shwedagon Area',
      area_kind: 'neighborhood',
      is_primary: false,
      is_active: true,
      order_index: 4,
    },
  ];

  await upsertBatch('city_areas', areas, 'id');
}
