import { did, upsertBatch } from '../seed-utils';

export async function seedTags() {
  const tags = [
    // Vibe (tg-vibe, filter_group='vibe')
    {
      id: did('tag-chill'),
      tag_group_id: did('tg-vibe'),
      slug: 'chill',
      label: 'Chill',
      filter_group: 'vibe',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 1,
      is_active: true,
    },
    {
      id: did('tag-lively'),
      tag_group_id: did('tg-vibe'),
      slug: 'lively',
      label: 'Lively',
      filter_group: 'vibe',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 2,
      is_active: true,
    },
    {
      id: did('tag-quiet'),
      tag_group_id: did('tg-vibe'),
      slug: 'quiet',
      label: 'Quiet',
      filter_group: 'vibe',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 3,
      is_active: true,
    },
    {
      id: did('tag-aesthetic'),
      tag_group_id: did('tg-vibe'),
      slug: 'aesthetic',
      label: 'Aesthetic',
      filter_group: 'vibe',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 4,
      is_active: true,
    },
    {
      id: did('tag-local-feel'),
      tag_group_id: did('tg-vibe'),
      slug: 'local-feel',
      label: 'Local Feel',
      filter_group: 'vibe',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 5,
      is_active: true,
    },
    {
      id: did('tag-cozy'),
      tag_group_id: did('tg-vibe'),
      slug: 'cozy',
      label: 'Cozy',
      filter_group: 'vibe',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 6,
      is_active: true,
    },
    {
      id: did('tag-trendy'),
      tag_group_id: did('tg-vibe'),
      slug: 'trendy',
      label: 'Trendy',
      filter_group: 'vibe',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 7,
      is_active: true,
    },
    {
      id: did('tag-scenic'),
      tag_group_id: did('tg-vibe'),
      slug: 'scenic',
      label: 'Scenic',
      filter_group: 'vibe',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 8,
      is_active: true,
    },
    {
      id: did('tag-beachfront'),
      tag_group_id: did('tg-vibe'),
      slug: 'beachfront',
      label: 'Beachfront',
      filter_group: 'vibe',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 9,
      is_active: true,
    },
    {
      id: did('tag-nature'),
      tag_group_id: did('tg-vibe'),
      slug: 'nature',
      label: 'Nature',
      filter_group: 'vibe',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 10,
      is_active: true,
    },
    {
      id: did('tag-city'),
      tag_group_id: did('tg-vibe'),
      slug: 'city',
      label: 'City',
      filter_group: 'vibe',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 11,
      is_active: true,
    },

    // Good for (tg-goodfor, filter_group='good_for')
    {
      id: did('tag-solo-friendly'),
      tag_group_id: did('tg-goodfor'),
      slug: 'solo-friendly',
      label: 'Solo Friendly',
      filter_group: 'good_for',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 1,
      is_active: true,
    },
    {
      id: did('tag-work-friendly'),
      tag_group_id: did('tg-goodfor'),
      slug: 'work-friendly',
      label: 'Work Friendly',
      filter_group: 'good_for',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 2,
      is_active: true,
    },
    {
      id: did('tag-meeting-people'),
      tag_group_id: did('tg-goodfor'),
      slug: 'meeting-people',
      label: 'Meeting People',
      filter_group: 'good_for',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 3,
      is_active: true,
    },
    {
      id: did('tag-date-night'),
      tag_group_id: did('tg-goodfor'),
      slug: 'date-night',
      label: 'Date Night',
      filter_group: 'good_for',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 4,
      is_active: true,
    },
    {
      id: did('tag-solo-dining'),
      tag_group_id: did('tg-goodfor'),
      slug: 'solo-dining',
      label: 'Solo Dining',
      filter_group: 'good_for',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 5,
      is_active: true,
    },
    {
      id: did('tag-recovery'),
      tag_group_id: did('tg-goodfor'),
      slug: 'recovery',
      label: 'Recovery',
      filter_group: 'good_for',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 6,
      is_active: true,
    },
    {
      id: did('tag-self-care-day'),
      tag_group_id: did('tg-goodfor'),
      slug: 'self-care-day',
      label: 'Self Care Day',
      filter_group: 'good_for',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 7,
      is_active: true,
    },
    {
      id: did('tag-stress-relief'),
      tag_group_id: did('tg-goodfor'),
      slug: 'stress-relief',
      label: 'Stress Relief',
      filter_group: 'good_for',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 8,
      is_active: true,
    },
    {
      id: did('tag-learning-culture'),
      tag_group_id: did('tg-goodfor'),
      slug: 'learning-culture',
      label: 'Learning Culture',
      filter_group: 'good_for',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 9,
      is_active: true,
    },
    {
      id: did('tag-relax-chill'),
      tag_group_id: did('tg-goodfor'),
      slug: 'relax-chill',
      label: 'Relax & Chill',
      filter_group: 'good_for',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 10,
      is_active: true,
    },
    {
      id: did('tag-active-day'),
      tag_group_id: did('tg-goodfor'),
      slug: 'active-day',
      label: 'Active Day',
      filter_group: 'good_for',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 11,
      is_active: true,
    },
    {
      id: did('tag-dancing'),
      tag_group_id: did('tg-goodfor'),
      slug: 'dancing',
      label: 'Dancing',
      filter_group: 'good_for',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 12,
      is_active: true,
    },
    {
      id: did('tag-drinks-conversation'),
      tag_group_id: did('tg-goodfor'),
      slug: 'drinks-conversation',
      label: 'Drinks & Conversation',
      filter_group: 'good_for',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 13,
      is_active: true,
    },
    {
      id: did('tag-sunset-views'),
      tag_group_id: did('tg-goodfor'),
      slug: 'sunset-views',
      label: 'Sunset Views',
      filter_group: 'good_for',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 14,
      is_active: true,
    },

    // Safety & Comfort (tg-safety, filter_group='safety')
    {
      id: did('tag-women-only-option'),
      tag_group_id: did('tg-safety'),
      slug: 'women-only-option',
      label: 'Women Only Option',
      filter_group: 'safety',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 1,
      is_active: true,
    },
    {
      id: did('tag-well-lit-at-night'),
      tag_group_id: did('tg-safety'),
      slug: 'well-lit-at-night',
      label: 'Well Lit at Night',
      filter_group: 'safety',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 2,
      is_active: true,
    },
    {
      id: did('tag-helpful-staff'),
      tag_group_id: did('tg-safety'),
      slug: 'helpful-staff',
      label: 'Helpful Staff',
      filter_group: 'safety',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 3,
      is_active: true,
    },
    {
      id: did('tag-lockers-available'),
      tag_group_id: did('tg-safety'),
      slug: 'lockers-available',
      label: 'Lockers Available',
      filter_group: 'safety',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 4,
      is_active: true,
    },
    {
      id: did('tag-female-friendly-crowd'),
      tag_group_id: did('tg-safety'),
      slug: 'female-friendly-crowd',
      label: 'Female Friendly Crowd',
      filter_group: 'safety',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 5,
      is_active: true,
    },
    {
      id: did('tag-secure-entrance'),
      tag_group_id: did('tg-safety'),
      slug: 'secure-entrance',
      label: 'Secure Entrance',
      filter_group: 'safety',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 6,
      is_active: true,
    },
    {
      id: did('tag-staff-presence'),
      tag_group_id: did('tg-safety'),
      slug: 'staff-presence',
      label: 'Staff Presence',
      filter_group: 'safety',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 7,
      is_active: true,
    },
    {
      id: did('tag-24-7'),
      tag_group_id: did('tg-safety'),
      slug: '24-7',
      label: '24/7',
      filter_group: 'safety',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 8,
      is_active: true,
    },
    {
      id: did('tag-english-speaking-staff'),
      tag_group_id: did('tg-safety'),
      slug: 'english-speaking-staff',
      label: 'English Speaking Staff',
      filter_group: 'safety',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 9,
      is_active: true,
    },

    // Amenities (tg-amenity, filter_group='amenity')
    {
      id: did('tag-fast-wifi'),
      tag_group_id: did('tg-amenity'),
      slug: 'fast-wifi',
      label: 'Fast WiFi',
      filter_group: 'amenity',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 1,
      is_active: true,
    },
    {
      id: did('tag-ac'),
      tag_group_id: did('tg-amenity'),
      slug: 'ac',
      label: 'AC',
      filter_group: 'amenity',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 2,
      is_active: true,
    },
    {
      id: did('tag-pool'),
      tag_group_id: did('tg-amenity'),
      slug: 'pool',
      label: 'Pool',
      filter_group: 'amenity',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 3,
      is_active: true,
    },
    {
      id: did('tag-power-outlets'),
      tag_group_id: did('tg-amenity'),
      slug: 'power-outlets',
      label: 'Power Outlets',
      filter_group: 'amenity',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 4,
      is_active: true,
    },
    {
      id: did('tag-breakfast-included'),
      tag_group_id: did('tg-amenity'),
      slug: 'breakfast-included',
      label: 'Breakfast Included',
      filter_group: 'amenity',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 5,
      is_active: true,
    },
    {
      id: did('tag-private-bathroom'),
      tag_group_id: did('tg-amenity'),
      slug: 'private-bathroom',
      label: 'Private Bathroom',
      filter_group: 'amenity',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 6,
      is_active: true,
    },
    {
      id: did('tag-kitchen'),
      tag_group_id: did('tg-amenity'),
      slug: 'kitchen',
      label: 'Kitchen',
      filter_group: 'amenity',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 7,
      is_active: true,
    },
    {
      id: did('tag-common-space'),
      tag_group_id: did('tg-amenity'),
      slug: 'common-space',
      label: 'Common Space',
      filter_group: 'amenity',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 8,
      is_active: true,
    },
    {
      id: did('tag-dance-floor'),
      tag_group_id: did('tg-amenity'),
      slug: 'dance-floor',
      label: 'Dance Floor',
      filter_group: 'amenity',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 9,
      is_active: true,
    },
    {
      id: did('tag-outdoor-area'),
      tag_group_id: did('tg-amenity'),
      slug: 'outdoor-area',
      label: 'Outdoor Area',
      filter_group: 'amenity',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 10,
      is_active: true,
    },
    {
      id: did('tag-smoking-area'),
      tag_group_id: did('tg-amenity'),
      slug: 'smoking-area',
      label: 'Smoking Area',
      filter_group: 'amenity',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 11,
      is_active: true,
    },
    {
      id: did('tag-bed-curtains'),
      tag_group_id: did('tg-amenity'),
      slug: 'bed-curtains',
      label: 'Bed Curtains',
      filter_group: 'amenity',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 12,
      is_active: true,
    },
    {
      id: did('tag-rooftop-amenity'),
      tag_group_id: did('tg-amenity'),
      slug: 'rooftop-amenity',
      label: 'Rooftop',
      filter_group: 'amenity',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 13,
      is_active: true,
    },

    // Cuisine & Diet (tg-cuisine, filter_group='cuisine')
    {
      id: did('tag-local-cuisine'),
      tag_group_id: did('tg-cuisine'),
      slug: 'local-cuisine',
      label: 'Local Cuisine',
      filter_group: 'cuisine',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 1,
      is_active: true,
    },
    {
      id: did('tag-international'),
      tag_group_id: did('tg-cuisine'),
      slug: 'international',
      label: 'International',
      filter_group: 'cuisine',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 2,
      is_active: true,
    },
    {
      id: did('tag-breakfast-brunch'),
      tag_group_id: did('tg-cuisine'),
      slug: 'breakfast-brunch',
      label: 'Breakfast & Brunch',
      filter_group: 'cuisine',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 3,
      is_active: true,
    },
    {
      id: did('tag-vegetarian-friendly'),
      tag_group_id: did('tg-cuisine'),
      slug: 'vegetarian-friendly',
      label: 'Vegetarian Friendly',
      filter_group: 'cuisine',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 4,
      is_active: true,
    },
    {
      id: did('tag-vegan-option'),
      tag_group_id: did('tg-cuisine'),
      slug: 'vegan-option',
      label: 'Vegan Option',
      filter_group: 'cuisine',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 5,
      is_active: true,
    },
    {
      id: did('tag-gluten-free'),
      tag_group_id: did('tg-cuisine'),
      slug: 'gluten-free',
      label: 'Gluten Free',
      filter_group: 'cuisine',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 6,
      is_active: true,
    },

    // Music (tg-music, filter_group='music')
    {
      id: did('tag-dj-electronic'),
      tag_group_id: did('tg-music'),
      slug: 'dj-electronic',
      label: 'DJ / Electronic',
      filter_group: 'music',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 1,
      is_active: true,
    },
    {
      id: did('tag-live-music'),
      tag_group_id: did('tg-music'),
      slug: 'live-music',
      label: 'Live Music',
      filter_group: 'music',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 2,
      is_active: true,
    },
    {
      id: did('tag-pop-commercial'),
      tag_group_id: did('tg-music'),
      slug: 'pop-commercial',
      label: 'Pop / Commercial',
      filter_group: 'music',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 3,
      is_active: true,
    },
    {
      id: did('tag-hiphop-rnb'),
      tag_group_id: did('tg-music'),
      slug: 'hiphop-rnb',
      label: 'Hip Hop / R&B',
      filter_group: 'music',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 4,
      is_active: true,
    },

    // Physical Level (tg-physical, filter_group='physical_level')
    {
      id: did('tag-easy'),
      tag_group_id: did('tg-physical'),
      slug: 'easy',
      label: 'Easy',
      filter_group: 'physical_level',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 1,
      is_active: true,
    },
    {
      id: did('tag-moderate'),
      tag_group_id: did('tg-physical'),
      slug: 'moderate',
      label: 'Moderate',
      filter_group: 'physical_level',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 2,
      is_active: true,
    },
    {
      id: did('tag-challenging'),
      tag_group_id: did('tg-physical'),
      slug: 'challenging',
      label: 'Challenging',
      filter_group: 'physical_level',
      scope: 'global',
      tag_type: 'place',
      icon: null,
      order_index: 3,
      is_active: true,
    },
  ];

  await upsertBatch('tags', tags, 'id');
  console.log(`✓ Seeded ${tags.length} tags`);
}
