// Geo data helper module
// Imports JSON files generated by scripts/generateGeoData.mjs

import countriesData from './countries.json';

export interface Country {
  name: string;
  iso2: string;
  iso3: string | null;
  phonecode: string | null;
  currency: string | null;
  flag: string | null;
  latitude: string | null;
  longitude: string | null;
}

export interface City {
  name: string;
  countryIso2: string;
  region: string | null;
  latitude: string | null;
  longitude: string | null;
}

// Export countries array
export const countries: Country[] = countriesData as Country[];

// TODO: fetch from API
export const cities: City[] = [];

// TODO: fetch from API
export const citiesTop: City[] = [];

// Helper functions
export function getCountryByIso2(iso2: string): Country | undefined {
  return countries.find((c) => c.iso2 === iso2);
}

export function getCitiesByCountry(iso2: string, useTop = true): City[] {
  const dataset = useTop ? citiesTop : cities;
  return dataset.filter((city) => city.countryIso2 === iso2);
}

export function searchCities(query: string, useTop = true): City[] {
  const dataset = useTop ? citiesTop : cities;
  const lowerQuery = query.toLowerCase();
  return dataset.filter(
    (city) =>
      city.name.toLowerCase().includes(lowerQuery) ||
      city.countryIso2.toLowerCase().includes(lowerQuery)
  );
}
