import { ArticleRow } from './db.js';

interface ScoredArticle extends ArticleRow {
  solaInsight?: string;
}

export async function generateDigestWithLLM(articles: ScoredArticle[], period: 'daily' | 'weekly'): Promise<string> {
  const anthropicKey = process.env.ANTHROPIC_API_KEY;
  const openaiKey = process.env.OPENAI_API_KEY;

  if (anthropicKey) {
    return await summarizeWithClaude(articles, period, anthropicKey);
  }
  if (openaiKey) {
    return await summarizeWithOpenAI(articles, period, openaiKey);
  }

  return generateDigestText(articles, period);
}

async function summarizeWithClaude(articles: ScoredArticle[], period: string, apiKey: string): Promise<string> {
  const { default: Anthropic } = await import('@anthropic-ai/sdk');
  const client = new Anthropic({ apiKey });

  const articleList = articles.map((a, i) =>
    `${i + 1}. "${a.title}" (${a.publisher}, ${a.publishedAt})\n   ${a.summary}\n   URL: ${a.url}`
  ).join('\n\n');

  const msg = await client.messages.create({
    model: 'claude-haiku-4-5-20251001',
    max_tokens: 1500,
    messages: [{
      role: 'user',
      content: `You are the intelligence analyst for Sola, a women-first solo travel app. Generate a ${period} digest from these articles.

FORMAT (keep it concise — must be readable on email/WhatsApp):

TOP HEADLINES

1. [Title] — [Publisher]
[1-2 sentence summary]
→ Why this matters for Sola: [1 sentence]

(repeat for top 5)

OPPORTUNITIES (3 bullets)
[Product or marketing ideas inspired by the news]

RISKS & WATCHOUTS (2-3 bullets)
[Things to monitor or prepare for]

ONE EXPERIMENT TO RUN THIS WEEK
[Specific, actionable idea]

ARTICLES:
${articleList}`,
    }],
  });

  const content = msg.content[0];
  return content.type === 'text' ? content.text : generateDigestText(articles, period);
}

async function summarizeWithOpenAI(articles: ScoredArticle[], period: string, apiKey: string): Promise<string> {
  const { default: OpenAI } = await import('openai');
  const client = new OpenAI({ apiKey });

  const articleList = articles.map((a, i) =>
    `${i + 1}. "${a.title}" (${a.publisher}, ${a.publishedAt})\n   ${a.summary}\n   URL: ${a.url}`
  ).join('\n\n');

  const response = await client.chat.completions.create({
    model: 'gpt-4o-mini',
    max_tokens: 1500,
    messages: [{
      role: 'user',
      content: `You are the intelligence analyst for Sola, a women-first solo travel app. Generate a ${period} digest from these articles.

FORMAT (keep it concise — must be readable on email/WhatsApp):

TOP HEADLINES

1. [Title] — [Publisher]
[1-2 sentence summary]
→ Why this matters for Sola: [1 sentence]

(repeat for top 5)

OPPORTUNITIES (3 bullets)
[Product or marketing ideas inspired by the news]

RISKS & WATCHOUTS (2-3 bullets)
[Things to monitor or prepare for]

ONE EXPERIMENT TO RUN THIS WEEK
[Specific, actionable idea]

ARTICLES:
${articleList}`,
    }],
  });

  return response.choices[0]?.message?.content || generateDigestText(articles, period);
}

export function generateDigestText(articles: ScoredArticle[], period: 'daily' | 'weekly'): string {
  const top = articles.slice(0, period === 'weekly' ? 7 : 5);
  const date = new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' });
  const label = period === 'weekly' ? 'Weekly Intelligence Brief' : 'Daily Digest';

  let text = `SOLA ${label.toUpperCase()} — ${date}\n\n`;
  text += `TOP HEADLINES\n\n`;

  top.forEach((a, i) => {
    text += `${i + 1}. ${a.title} — ${a.publisher}\n`;
    text += `   ${a.summary}\n`;
    text += `   ${a.url}\n`;
    text += `   → Relevance score: ${(a.relevanceScore * 100).toFixed(0)}%\n\n`;
  });

  text += `OPPORTUNITIES\n`;
  text += `• Review top-scoring articles for feature inspiration\n`;
  text += `• Check competitor mentions in travel tech coverage\n`;
  text += `• Monitor women-safety developments for content opportunities\n\n`;

  text += `RISKS & WATCHOUTS\n`;
  text += `• Watch for regulatory changes affecting travel apps\n`;
  text += `• Monitor safety incidents in key Sola destinations\n\n`;

  text += `ONE EXPERIMENT TO RUN THIS WEEK\n`;
  text += `• Test engagement with the top-trending topic from this digest in Sola's community feed\n\n`;

  text += `---\nGenerated by Sola Intel Agent • ${top.length} articles scored from ${new Date().toISOString().split('T')[0]}`;

  return text;
}

export function formatForEmail(digestText: string, period: 'daily' | 'weekly'): string {
  const label = period === 'weekly' ? 'Weekly Intelligence Brief' : 'Daily Digest';
  const escapedText = digestText
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\n/g, '<br>');

  const withLinks = escapedText.replace(
    /(https?:\/\/[^\s<]+)/g,
    '<a href="$1" style="color:#E5653A;">$1</a>'
  );

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width"></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:600px;margin:0 auto;padding:24px;color:#1a1a1a;line-height:1.6;">
  <div style="border-bottom:3px solid #E5653A;padding-bottom:16px;margin-bottom:24px;">
    <h1 style="font-size:20px;margin:0;color:#E5653A;">Sola</h1>
    <p style="font-size:14px;margin:4px 0 0;color:#666;">${label}</p>
  </div>
  <div style="font-size:14px;white-space:pre-line;">
    ${withLinks}
  </div>
</body>
</html>`;
}
